/**
 * Offline check of the portal's Support section as a three-area workspace: the
 * real PortalSupport, the real Support rail in a real v2 SidebarProvider, the real
 * inbox hook and the real shared workspace, over a scripted in-memory messaging
 * API. No account, database, email or model provider is contacted.
 *
 * What it proves: the ticket list is in the sidebar's slot (no fourth column), the
 * centre is the human conversation and the right is Details | TRAX Summary for the
 * SAME ticket; the message TRAX wrote is an event, not a bubble; a ticket with no
 * TRAX conversation says so; switching tickets never shows the last one's content
 * while the next loads; each area scrolls inside itself with the composer on
 * screen; a failed send keeps the draft; attachments; filters; New ticket from the
 * rail; a collapsed sidebar hands the list back to the page; a narrower screen gets
 * Details as a drawer; and a phone takes the list and the conversation in turns.
 */
import { build } from 'esbuild';
import { chromium } from 'playwright';
import postcss from 'postcss';
import tailwind from 'tailwindcss';
import loadConfig from 'tailwindcss/loadConfig.js';
import { readFile, writeFile, mkdtemp, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createServer } from 'node:http';
import { tmpdir } from 'node:os';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const manual=process.argv.includes('--manual');
const temp=await mkdtemp(resolve(tmpdir(),'drive247-support-'));
const screenshots=resolve(root,'artifacts/trax-support-ui');await mkdir(screenshots,{recursive:true});

/* The fixture API. It answers the same actions as trax-messaging with the same shapes,
   in memory, so the component under test is the real one and nothing is stubbed inside it. */
const fixture=`
import React from 'react';
const now=Date.now();
const iso=(minutes)=>new Date(now-minutes*60000).toISOString();
const long='This vehicle was returned on Tuesday afternoon and the customer confirmed the handover in person, but the rental still shows as active in the dashboard and the deposit has not been released, so the same car cannot be booked again for the weekend. Reference RENT-2026-000148-EXTENDED-CONTRACT-ADDENDUM.';
/* A handoff exactly as support-store.ts writes one for an escalated TRAX issue. */
const handoff={conversationId:'c1',
  issue:{id:'i1',topic:'bookings',summary:'Which rentals are active',state:'submitted'},
  reportedByUser:[{content:'which rentals are active',at:iso(62)}],
  verifiedChecks:[{key:'k1',tool:'list_account_bookings',status:'verified',observedAt:iso(61),findings:['10 recorded active rentals; showing 10.','Each booking is separate from its vehicle.'],limitations:[]}],
  recordReferences:[{kind:'rental',id:'DEMO-104'}],paymentReferences:[],
  unknowns:['Out on hire uses the recorded-state rule, not proof of physical possession.'],
  escalationHistory:[{key:'h1',reason:'human_requested',at:iso(60)}],
  excerpt:[{role:'user',content:'which rentals are active',at:iso(62)},{role:'assistant',content:'There are 10 rentals recorded as active right now.',at:iso(61)},{role:'user',content:'Some of those were returned. I need a person to check.',at:iso(60)}],
  disclosure:'User reports and historical system observations are separate.'};
const summaryBody='TRAX troubleshooting summary — generated by TRAX for this issue. It is not a message written by a support agent, and the requester has not added their own message yet.\\n\\nQuestion: which rentals are active';
const tickets=[
  {id:'t0',reference:'TRX-2A1A14C65E19',summary:'which rentals are active',status:'open',tenant_name:'Northwind Rentals',requester:'Offline operator',updated_at:iso(2),created_at:iso(60),unread:true,conversation_id:'c1',traxLinked:true,handoff,
   preview:'TRAX shared its troubleshooting summary.',
   messages:[
     {seq:1,author_kind:'tenant',body:summaryBody,created_at:iso(60),source:'trax_handoff'},
     {seq:2,author_kind:'support',body:'Thanks — we are checking the ten active rentals against the returns log.',created_at:iso(20)},
     {seq:3,author_kind:'tenant',body:'The TRAX summary said 10, but two were returned yesterday.',created_at:iso(2)},
   ]},
  {id:'t1',reference:'TRX-11AA22BB33CC',summary:'Returned vehicle still shows as out on rent, and the deposit has not been released to the customer',status:'open',tenant_name:'Northwind Rentals',requester:'Offline operator',updated_at:iso(3),created_at:iso(1500),unread:true,conversation_id:null,traxLinked:false,
   handoff:{disclosure:'Reported directly by the requester. No TRAX checks were performed.'},
   messages:[
     {seq:1,author_kind:'tenant',body:'The customer returned the keys on Tuesday but the rental is still open.',created_at:iso(1500)},
     {seq:2,author_kind:'support',body:'Thanks — we can see the rental is still open on our side too. Could you confirm which branch received the keys?',created_at:iso(1440)},
     {seq:3,author_kind:'tenant',body:'Manchester.',created_at:iso(1438)},
     {seq:4,author_kind:'tenant',body:long,created_at:iso(1437)},
     {seq:5,author_kind:'support',body:'Understood. We have asked the operations team to review the handover record.',created_at:iso(5)},
     {seq:6,author_kind:'support',body:'One more thing: please do not close the rental manually while this is open.',created_at:iso(4)},
   ]},
  {id:'t2',reference:'TRX-44DD55EE66FF',summary:'Invoice email did not reach the customer',status:'in_progress',tenant_name:'Northwind Rentals',requester:'Offline operator',updated_at:iso(2880),created_at:iso(4300),unread:false,conversation_id:null,traxLinked:false,
   handoff:{disclosure:'Reported directly by the requester. No TRAX checks were performed.'},
   messages:[{seq:1,author_kind:'tenant',body:'The invoice email bounced.',created_at:iso(4300)},{seq:2,author_kind:'support',body:'We resent it this morning.',created_at:iso(2880)}]},
  {id:'t3',reference:'TRX-77GG88HH99II',summary:'Website booking widget showed the wrong price',status:'closed',closed_at:iso(20000),tenant_name:'Northwind Rentals',requester:'Offline operator',updated_at:iso(20000),created_at:iso(21000),unread:false,conversation_id:null,traxLinked:false,
   handoff:{disclosure:'Reported directly by the requester. No TRAX checks were performed.'},
   messages:[{seq:1,author_kind:'tenant',body:'The widget showed £39 instead of £59.',created_at:iso(21000)},{seq:2,author_kind:'support',body:'Fixed in the pricing rule.',created_at:iso(20000)}]},
];
/* Long history for the scrolling checks. */
for(let i=0;i<24;i++)tickets[1].messages.splice(1,0,{seq:0,author_kind:i%2?'support':'tenant',body:'Earlier update '+(i+1)+' about the return and the deposit.',created_at:iso(3000-i*20)});
tickets[1].messages.forEach((m,i)=>{m.seq=i+1;});
window.failNextSend=false;window.failNextAttach=false;window.slowDetail=null;
const reserved=[],uploads=new Map();
const claim=(ticket,nonce,seq)=>{for(const file of reserved)if(file.nonce===nonce&&!file.seq){file.seq=seq;file.ticketId=ticket.id;}};
const call=async(action,data={})=>{
  await new Promise(r=>setTimeout(r,10));
  if(action==='count')return {unread:tickets.filter(t=>t.unread).length};
  if(action==='list'){
    const q=String(data.search??'').toLowerCase();
    const found=tickets.filter(t=>(!data.status||t.status===data.status)&&(!q||(t.summary+' '+t.reference).toLowerCase().includes(q)));
    return {tickets:found.map(({messages,handoff,conversation_id,traxLinked,closed_at,...rest})=>rest),nextOffset:null,unread:tickets.filter(t=>t.unread).length};
  }
  if(action==='detail'){
    /* A slow ticket, so a switch can be caught while the next one loads. */
    if(window.slowDetail===data.id)await new Promise(r=>setTimeout(r,1500));
    const t=tickets.find(x=>x.id===data.id);if(!t)throw Error('Ticket not found.');
    const {messages,preview,...ticket}=t;
    const files=reserved.filter(f=>f.ticketId===t.id&&f.seq).map(f=>({id:f.id,seq:f.seq,name:f.name,mime:f.mime,size:f.size,authorKind:'tenant',url:uploads.get(f.path)}));
    return {ticket,messages,hasOlder:false,latestSeq:messages.length,attachments:files};
  }
  if(action==='read'){const t=tickets.find(x=>x.id===data.id);if(t)t.unread=false;return {readThrough:data.through};}
  if(action==='attach'){
    if(window.failNextAttach){window.failNextAttach=false;throw Error('The attachment could not be reserved. Your message has not been sent.');}
    const path='fixture/'+(data.id??'new')+'/'+String(reserved.length+1);
    reserved.push({id:'a'+(reserved.length+1),path,ticketId:data.id??null,nonce:data.nonce,name:data.name,mime:data.mime,size:data.size});
    return {attachment:{id:'a'+reserved.length,path,name:data.name,mime:data.mime,size:data.size},upload:{url:'fixture://'+path,token:'token'}};
  }
  if(action==='send'){
    if(window.failNextSend){window.failNextSend=false;throw Error('Fixture connection interrupted. Your draft is preserved for retry.');}
    const t=tickets.find(x=>x.id===data.id);t.messages.push({seq:t.messages.length+1,author_kind:'tenant',body:data.body,created_at:new Date().toISOString()});t.updated_at=new Date().toISOString();
    claim(t,data.nonce,t.messages.length);
    return {seq:t.messages.length};
  }
  if(action==='create'){
    const t={id:'t'+(tickets.length+1),reference:'TRX-NEWFIXTURE000',summary:data.subject,status:'open',tenant_name:'Northwind Rentals',requester:'Offline operator',updated_at:new Date().toISOString(),created_at:new Date().toISOString(),unread:false,conversation_id:null,traxLinked:false,
      handoff:{disclosure:'Reported directly by the requester. No TRAX checks were performed.'},
      messages:[{seq:1,author_kind:'tenant',body:data.body,created_at:new Date().toISOString()}]};
    tickets.unshift(t);claim(t,data.nonce,1);return {id:t.id,reference:t.reference};
  }
  throw Error('Unsupported fixture action: '+action);
};
const uploadAttachment=async(upload,file)=>{
  const bytes=await file.arrayBuffer();
  const base64=btoa(String.fromCharCode(...new Uint8Array(bytes)));
  uploads.set(upload.path,'data:'+file.type+';base64,'+base64);
};
export const useSupportMessaging=()=>({call,scope:'offline-fixture',uploadAttachment,count:1,allowed:true,checking:false,errorCode:null,retry:()=>{}});
export const useTraxSupportOptional=()=>null;
export const useTenant=()=>({tenant:{id:'tenant-fixture',company_name:'Northwind Rentals'}});
export const UserMenuV2=({variant})=>React.createElement('div',{className:'flex h-10 items-center gap-2 px-2 text-[13px]'},variant==='row'?'Offline operator · owner@fixture.invalid':'OO');
export const usePathname=()=>'/support';
export const useSearchParams=()=>new URLSearchParams();
export const useRouter=()=>({push:()=>{}});
export default function Link({children,href,...props}){return React.createElement('a',{href,...props},children);}
`;
const config=loadConfig(resolve(root,'apps/portal/tailwind.config.ts'));
config.content=[resolve(root,'apps/portal/src/components/**/*.{ts,tsx}'),resolve(root,'shared/trax-support/**/*.{ts,tsx}')];
const css=(await postcss([tailwind(config)]).process((await readFile(resolve(root,'apps/portal/src/global.css'),'utf8'))+'\n'+(await readFile(resolve(root,'apps/portal/src/styles/v2-theme.css'),'utf8')),{from:undefined})).css;
await writeFile(resolve(temp,'style.css'),css);
const mocks=new Set(['@/hooks/use-support-messaging','@/components/trax/support/trax-support-context','@/contexts/TenantContext','@/components/shared/layout/user-menu-v2','next/navigation','next/link']);
/* `@/x` as the portal resolves it: a .ts, a .tsx or a folder index. */
const portalPath=(request)=>{const base=resolve(root,'apps/portal/src',request.slice(2));for(const candidate of [base+'.ts',base+'.tsx',resolve(base,'index.ts'),resolve(base,'index.tsx'),base])if(existsSync(candidate))return candidate;return base+'.ts';};
await build({stdin:{contents:`import React from 'react';import {createRoot} from 'react-dom/client';
import {PortalSupport} from './apps/portal/src/components/support/portal-support';
import {SupportRail} from './apps/portal/src/components/support/support-rail';
import {SidebarProvider,SidebarInset} from './apps/portal/src/components/ui-v2/sidebar';
import {TooltipProvider} from './apps/portal/src/components/ui-v2/tooltip';
import {SupportRailProvider} from './shared/trax-support/support-rail';
/* The dashboard layout on /support, reduced to what shapes this route: the v2
   sidebar provider at the Support rail's 19rem, the rail in the sidebar's slot, and
   a bounded-height inset with a top bar above main. */
createRoot(document.getElementById('root')).render(
  React.createElement(TooltipProvider,null,
  React.createElement(SidebarProvider,{className:'h-svh overflow-hidden bg-background bg-app-gradient',style:{'--sidebar-width':'19rem'}},
    React.createElement(SupportRailProvider,null,
      React.createElement(SupportRail,null),
      React.createElement(SidebarInset,{className:'min-w-0 bg-transparent'},
        React.createElement('header',{className:'flex h-16 shrink-0 items-center px-4 text-sm font-semibold','data-testid':'top-bar'},'Portal top bar'),
        React.createElement('main',{className:'flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden p-0'},
          React.createElement('div',{className:'flex min-h-0 min-w-0 flex-1 flex-col p-3 sm:p-4'},
            React.createElement(PortalSupport,null))))))));`,
  resolveDir:root,loader:'tsx'},outfile:resolve(temp,'app.js'),bundle:true,format:'iife',platform:'browser',jsx:'automatic',
  define:{'process.env.NODE_ENV':'"test"'},
  plugins:[{name:'offline-fixtures',setup(b){
    b.onResolve({filter:/.*/},(args)=>{
      if(mocks.has(args.path))return {path:args.path,namespace:'fixture'};
      if(args.path==='react'||args.path==='react-dom'||args.path==='react-dom/client'||args.path.startsWith('react/'))return {path:resolve(root,'node_modules',args.path==='react'?'react/index.js':args.path==='react-dom'?'react-dom/index.js':args.path==='react-dom/client'?'react-dom/client.js':args.path+'.js')};
      if(args.path.startsWith('@/'))return {path:portalPath(args.path)};
    });
    b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:fixture,loader:'jsx',resolveDir:root}));
  }}],logLevel:'silent'});
const server=createServer(async(req,res)=>{
  const file=req.url==='/app.js'?'app.js':req.url==='/style.css'?'style.css':null;
  res.setHeader('Content-Type',file?.endsWith('.js')?'text/javascript':file?'text/css':'text/html');
  res.end(file?await readFile(resolve(temp,file)):'<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"></head><body class="v2-theme"><div id="root"></div><script src="/app.js"></script></body></html>');
});
await new Promise((done)=>server.listen(0,'127.0.0.1',done));

let browser;
try{
  const executablePath=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(existsSync);
  browser=await chromium.launch({headless:!manual,...(executablePath?{executablePath}:{})});
  const W=1440,H=900;
  const page=await browser.newPage({viewport:{width:W,height:H},reducedMotion:'reduce'});
  page.setDefaultTimeout(12_000);
  const errors=[];page.on('pageerror',(e)=>errors.push(e.message));
  await page.route('**/*',(route)=>route.request().url().startsWith('http://127.0.0.1:')?route.continue():route.abort());
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  await page.getByTestId('support-inbox').waitFor();

  if(manual){
    console.log('Support fixture is open in an isolated browser. Close it or press Ctrl+C to finish.');
    await new Promise((done)=>{const stop=()=>{void browser.close();};browser.once('disconnected',done);process.once('SIGINT',stop);browser.once('disconnected',()=>process.removeListener('SIGINT',stop));});
  }else{
  const list=page.getByTestId('support-ticket-list');
  const conversation=page.getByLabel('Support conversation');
  const info=page.getByTestId('ticket-info');
  const thread=page.getByLabel('Message thread');
  const rows=list.locator('ul > li');
  const box=async(locator)=>{const b=await locator.boundingBox();assert.ok(b,'not on screen');return b;};

  // 1 — three areas, and the list is in the sidebar's slot, not a fourth column.
  await rows.first().waitFor(); // The list is debounced; wait for the first load.
  assert.equal(await list.count(),1,'the list is rendered twice');
  const rail=page.locator('[data-slot="sidebar-container"]');
  assert.equal(await rail.locator('[data-testid="support-ticket-list"]').count(),1,'the ticket list is not in the sidebar slot');
  const railBox=await box(rail);
  assert.ok(railBox.x===0&&railBox.width>=280&&railBox.width<=320,`the rail is ${Math.round(railBox.width)}px at x=${railBox.x}`);
  assert.ok(Math.round(railBox.height)===H,'the rail does not run the full height');
  assert.equal(await page.getByRole('link',{name:'Back to portal'}).count(),1,'no way back to the portal');
  await rail.getByText('Northwind Rentals',{exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'Support',exact:true}).count(),1,'one Support heading');
  await rail.getByRole('button',{name:'New ticket',exact:true}).waitFor();
  assert.equal(await rows.count(),4);
  // No leading dot, avatar or bullet on a row: unread is the subject's weight.
  assert.equal(await rows.first().locator('span.size-2, [data-slot="avatar"]').count(),0);
  const subjectClass=async(n)=>await rows.nth(n).locator('span.line-clamp-2').getAttribute('class');
  assert.ok((await subjectClass(0)).includes('font-semibold'),'an unread subject is not emphasised');
  assert.ok(!(await subjectClass(2)).includes('font-semibold'),'a read subject is emphasised anyway');
  assert.ok((await rows.first().innerText()).includes('TRAX shared its troubleshooting summary.'),'the row preview is missing');
  const page1=await page.evaluate(()=>({doc:document.documentElement.scrollHeight,view:window.innerHeight,overflowX:document.documentElement.scrollWidth>window.innerWidth}));
  assert.ok(page1.doc<=page1.view+1,`the page scrolls (${page1.doc} > ${page1.view})`);
  assert.equal(page1.overflowX,false,'horizontal overflow');
  await page.screenshot({path:resolve(screenshots,'workspace-empty.png'),animations:'disabled'});

  // 2 — the TRAX-escalated ticket: centre is people, right is Details | TRAX Summary.
  await rows.first().getByRole('button').click();
  await conversation.getByRole('heading',{name:'which rentals are active'}).waitFor();
  const convBox=await box(conversation),infoBox=await box(info);
  assert.ok(infoBox.width>=300&&infoBox.width<=340,`details panel is ${Math.round(infoBox.width)}px`);
  assert.ok(convBox.x>=railBox.width&&convBox.x+convBox.width<=infoBox.x,'the conversation is not between the rail and the panel');
  assert.ok(convBox.width>=infoBox.width*1.6,`the conversation is only ${Math.round(convBox.width)}px wide`);
  const event=thread.locator('[data-slot="system-event"]');
  await event.waitFor();
  assert.ok((await event.innerText()).includes('TRAX created this ticket'),'the TRAX event is not labelled');
  assert.equal(await thread.locator('[data-slot="bubble"]').filter({hasText:'generated by TRAX for this issue'}).count(),0,'the generated summary is still drawn as a message');
  // A person's message that mentions TRAX is still that person's message.
  await thread.locator('[data-slot="bubble"]').filter({hasText:'The TRAX summary said 10'}).waitFor();
  assert.equal(await conversation.getByText('TRAX troubleshooting context',{exact:false}).count(),0,'the context strip is back in the conversation');
  assert.equal(await conversation.getByRole('button',{name:'Issue details'}).count(),0,'a duplicate Issue details button');
  const headerText=(await conversation.locator('header').innerText()).replace(/\s+/g,' ');
  assert.ok(headerText.includes('TRX-2A1A14C65E19')&&headerText.includes('Open'),'the header lost its reference or status');
  assert.ok(!/Created|Last updated/i.test(headerText),'the created/updated strip is back');
  // Details, by default.
  assert.equal(await info.getByRole('tab',{name:'Details'}).getAttribute('aria-selected'),'true');
  for(const expected of ['TRX-2A1A14C65E19','Northwind Rentals','Offline operator','TRAX escalation','Bookings','Created','Last activity','DEMO-104'])
    await info.getByText(expected,{exact:false}).first().waitFor();
  assert.equal(await info.locator('select').count(),0,'a tenant was given a status control');
  assert.equal(await info.getByRole('link',{name:'DEMO-104'}).getAttribute('href'),'/rentals/DEMO-104');
  await page.screenshot({path:resolve(screenshots,'workspace-details.png'),animations:'disabled'});
  // TRAX Summary, from the event's own link.
  await event.getByRole('button',{name:'View TRAX Summary'}).click();
  assert.equal(await info.getByRole('tab',{name:'TRAX Summary'}).getAttribute('aria-selected'),'true');
  for(const expected of ['Troubleshooting summary','Generated by TRAX','List account bookings','10 recorded active rentals','The tenant asked for a person','Out on hire uses the recorded-state rule','TRAX conversation'])
    await info.getByText(expected,{exact:false}).first().waitFor();
  const turns=info.locator('[data-slot="trax-turn"]');
  assert.equal(await turns.count(),3);
  assert.deepEqual(await turns.evaluateAll((els)=>els.map((el)=>el.dataset.role)),['user','assistant','user']);
  assert.ok((await turns.nth(1).innerText()).startsWith('TRAX'),'the TRAX turn is not labelled');
  assert.ok((await turns.nth(0).innerText()).startsWith('Tenant'),'the tenant turn is not labelled');
  assert.equal(await turns.nth(1).locator('time').count(),1,'a TRAX turn has no timestamp');
  assert.equal(await info.locator('textarea, input').count(),0,'the TRAX Summary tab has a composer');
  assert.equal(/score/i.test(await info.innerText()),false,'the escalation score leaked');
  await page.screenshot({path:resolve(screenshots,'workspace-trax-summary.png'),animations:'disabled'});

  // 3 — switching tickets changes all three together, and never shows the last one while loading.
  await page.evaluate(()=>{window.slowDetail='t2';});
  await rows.nth(2).getByRole('button').click();
  await info.getByText('Loading ticket details…',{exact:true}).waitFor();
  await conversation.getByText('Loading conversation…',{exact:true}).waitFor();
  assert.equal(await info.getByText('TRX-2A1A14C65E19',{exact:false}).count(),0,'the previous ticket stayed in the panel while the next loaded');
  assert.equal(await conversation.getByRole('heading',{name:'which rentals are active'}).count(),0,'the previous conversation stayed on screen');
  await conversation.getByRole('heading',{name:'Invoice email did not reach the customer'}).waitFor();
  await info.getByText('No TRAX conversation is linked to this ticket.',{exact:true}).waitFor();
  assert.equal(await info.getByRole('tab',{name:'TRAX Summary'}).getAttribute('aria-selected'),'true','the chosen tab was not kept');
  await info.getByRole('tab',{name:'Details'}).click();
  await info.getByText('TRX-44DD55EE66FF',{exact:true}).waitFor();
  await info.getByText('Support section',{exact:true}).waitFor();
  await page.screenshot({path:resolve(screenshots,'workspace-no-trax.png'),animations:'disabled'});
  await page.evaluate(()=>{window.slowDetail=null;});

  // 4 — a long conversation: bubbles sized to content, and the composer never moves.
  await rows.nth(1).getByRole('button').click();
  await conversation.getByRole('heading',{name:/Returned vehicle still shows/}).waitFor();
  await thread.getByText('Manchester.',{exact:true}).waitFor();
  const threadBox=await box(thread);
  const shortBubble=await box(thread.locator('[data-slot="bubble"]').filter({hasText:'Manchester.'}));
  assert.ok(shortBubble.width<threadBox.width*0.5,`a one-word reply is ${Math.round(shortBubble.width)}px wide`);
  const longBubble=await box(thread.locator('[data-slot="bubble"]').filter({hasText:'RENT-2026-000148'}));
  assert.ok(longBubble.width<=threadBox.width*0.9&&longBubble.height>shortBubble.height,'a long message is not content-sized');
  const supportBubble=await box(thread.locator('[data-slot="bubble"]').filter({hasText:'Could you confirm which branch'}));
  assert.ok(shortBubble.x+shortBubble.width/2>threadBox.x+threadBox.width/2,'tenant messages are not on the right');
  assert.ok(supportBubble.x+supportBubble.width/2<threadBox.x+threadBox.width/2,'support messages are not on the left');
  assert.equal(await thread.evaluate((el)=>el.scrollWidth>el.clientWidth+1),false,'the conversation scrolls sideways');
  assert.ok(await thread.evaluate((el)=>el.scrollHeight>el.clientHeight),'the fixture history is not long enough to scroll');
  const composerBefore=await box(page.getByPlaceholder('Reply to support…'));
  const infoBefore=await box(info);
  await thread.evaluate((el)=>{el.scrollTop=0;});
  await page.waitForTimeout(200);
  const composerAfter=await box(page.getByPlaceholder('Reply to support…'));
  assert.equal(Math.round(composerBefore.y),Math.round(composerAfter.y),'the composer moved when the history scrolled');
  assert.ok(composerAfter.y+composerAfter.height<=H,'the composer is below the fold');
  assert.equal(Math.round((await box(info)).y),Math.round(infoBefore.y),'the details panel moved with the history');
  assert.equal(await conversation.getByRole('heading',{name:/Returned vehicle still shows/}).isVisible(),true,'the conversation header scrolled away');
  const scrollTop=await thread.evaluate((el)=>el.scrollTop);
  await page.waitForTimeout(6000);
  assert.equal(await thread.evaluate((el)=>el.scrollTop),scrollTop,'the thread jumped to the bottom while reading older messages');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight<=window.innerHeight+1),true,'the page itself scrolls');
  await page.screenshot({path:resolve(screenshots,'workspace-long-conversation.png'),animations:'disabled'});

  // 5 — a failed send keeps the draft and offers Retry; the retry succeeds.
  await page.evaluate(()=>{window.failNextSend=true;});
  await page.getByPlaceholder('Reply to support…').fill('We have not heard anything since Tuesday.');
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Fixture connection interrupted'}).waitFor();
  assert.equal(await page.getByPlaceholder('Reply to support…').inputValue(),'We have not heard anything since Tuesday.','the draft was lost on a failed send');
  await page.getByRole('button',{name:'Retry send',exact:true}).click();
  await thread.getByText('We have not heard anything since Tuesday.',{exact:true}).waitFor();
  assert.equal(await page.getByPlaceholder('Reply to support…').inputValue(),'','the draft survived a confirmed send');

  // 5b — a screenshot goes with the message, and comes back in the conversation.
  const pngBytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==','base64');
  await page.locator('input[type="file"]').setInputFiles({name:'return-handover.png',mimeType:'image/png',buffer:pngBytes});
  await page.getByText('return-handover.png',{exact:false}).waitFor();
  await page.getByPlaceholder('Reply to support…').fill('Here is the screenshot of the handover screen.');
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await thread.getByText('Here is the screenshot of the handover screen.',{exact:true}).waitFor();
  await thread.locator('img[alt="return-handover.png"]').waitFor();
  // 5c — a file the conversation does not accept is refused before any upload.
  await page.locator('input[type="file"]').setInputFiles({name:'notes.txt',mimeType:'text/plain',buffer:Buffer.from('plain text')});
  await page.getByText('Attach a PNG, JPEG, WebP, GIF or PDF.',{exact:false}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Send',exact:true}).isDisabled(),true,'an unsupported file did not block sending');
  await page.getByRole('button',{name:'Remove notes.txt',exact:true}).click();

  // 6 — filters and their empty result, in the rail.
  await list.getByLabel('Filter ticket status').selectOption('closed');
  await page.waitForFunction(()=>document.querySelectorAll('[data-testid="support-ticket-list"] ul > li').length===1);
  await list.getByPlaceholder('Search your tickets…').fill('nothing matches this');
  await list.getByText('No tickets match these filters.',{exact:true}).waitFor();
  await list.getByPlaceholder('Search your tickets…').fill('');
  await list.getByLabel('Filter ticket status').selectOption('');
  await page.waitForFunction(()=>document.querySelectorAll('[data-testid="support-ticket-list"] ul > li').length===4);

  // 7 — New ticket from the rail, created only by the first Send.
  await rail.getByRole('button',{name:'New ticket',exact:true}).click();
  await conversation.getByRole('heading',{name:'New ticket',exact:true}).waitFor();
  await info.getByText('Details appear here once the ticket is sent.',{exact:true}).waitFor();
  await page.getByLabel('Subject',{exact:true}).fill('Deposit release is still pending');
  await page.getByLabel('Your message',{exact:true}).fill('The deposit has not been released three days after the return.');
  assert.equal(await rows.count(),4,'a ticket was created before Send');
  await page.getByRole('button',{name:'Send',exact:true}).click();
  await conversation.getByRole('heading',{name:'Deposit release is still pending'}).waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('[data-testid="support-ticket-list"] ul > li').length===5);

  // 8 — collapsing the sidebar hands the list back to the page, and back again.
  await page.keyboard.press('Control+b');
  await page.getByRole('button',{name:'Show tickets'}).waitFor();
  await page.waitForTimeout(400);
  assert.equal(await list.count(),1,'the list is duplicated after collapsing');
  assert.equal(await rail.locator('[data-testid="support-ticket-list"]').count(),0,'the collapsed rail still holds the list');
  const pageListBox=await box(list);
  assert.ok(pageListBox.x>60,'the page did not take the list back');
  await page.screenshot({path:resolve(screenshots,'workspace-rail-collapsed.png'),animations:'disabled'});
  await page.getByRole('button',{name:'Show tickets'}).click();
  await rail.locator('[data-testid="support-ticket-list"]').waitFor();

  // 9 — narrower than the three columns: Details is a drawer, and Escape closes it.
  await page.setViewportSize({width:1100,height:820});
  await rows.first().getByRole('button').click();
  await conversation.getByRole('heading',{name:'Deposit release is still pending'}).waitFor();
  await rows.filter({hasText:'which rentals are active'}).getByRole('button').click();
  await conversation.getByRole('heading',{name:'which rentals are active'}).waitFor();
  assert.equal(await info.isVisible(),false,'three desktop columns were squeezed into 1100px');
  await conversation.getByRole('button',{name:'Details',exact:true}).click();
  const drawer=page.getByRole('dialog',{name:'Ticket details'});
  await drawer.waitFor();
  await drawer.getByText('TRX-2A1A14C65E19',{exact:false}).first().waitFor();
  await drawer.getByRole('tab',{name:'TRAX Summary'}).click();
  await drawer.locator('[data-slot="trax-turn"]').first().waitFor();
  await page.screenshot({path:resolve(screenshots,'workspace-drawer.png'),animations:'disabled'});
  await page.keyboard.press('Escape');
  await drawer.waitFor({state:'detached'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'horizontal overflow at 1100px');

  // 10 — a phone: the list and the conversation take turns, with Back.
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(400);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,'horizontal overflow on a phone');
  assert.equal(await list.isVisible(),false,'the list is squeezed beside the conversation on a phone');
  const phoneComposer=await box(page.getByPlaceholder('Reply to support…'));
  assert.ok(phoneComposer.y+phoneComposer.height<=844,'the composer is below the fold on a phone');
  await thread.locator('[data-slot="system-event"]').waitFor();
  await page.screenshot({path:resolve(screenshots,'workspace-mobile-conversation.png'),animations:'disabled'});
  await conversation.getByRole('button',{name:'Details',exact:true}).click();
  await page.getByRole('dialog',{name:'Ticket details'}).waitFor();
  const phoneDrawer=await box(page.getByRole('dialog',{name:'Ticket details'}));
  assert.ok(phoneDrawer.width<=390,'the drawer is wider than the phone');
  await page.getByRole('button',{name:'Close ticket details'}).click();
  await page.getByRole('button',{name:'Back to tickets',exact:true}).click();
  await list.waitFor();
  assert.equal(await conversation.isVisible(),false,'the conversation stayed on screen behind the list');
  await page.screenshot({path:resolve(screenshots,'workspace-mobile-list.png'),animations:'disabled'});

  assert.deepEqual(errors,[],'page errors: '+errors.join(' || '));
  console.log(JSON.stringify({status:'passed',mode:'support-three-column-workspace',checks:['ticket-list-in-sidebar-slot','back-to-portal-and-tenant-identity','no-row-markers','row-preview','no-outer-page-scroll','centre-between-rail-and-details','trax-message-is-an-event-not-a-bubble','trax-mention-stays-a-message','no-context-strip-or-issue-details-button','details-tab-fields-and-record-link','tenant-status-read-only','trax-summary-and-labelled-conversation','no-score-no-composer','switch-clears-stale-content','no-trax-conversation-empty-state','content-sized-bubbles','composer-and-panel-fixed-while-scrolling','no-jump-while-reading','failed-send-keeps-draft','attachment-sent-and-shown','unsupported-file-refused','filters-and-empty-result','new-ticket-from-rail','collapsed-rail-returns-list-to-page','details-drawer-below-xl','phone-list-conversation-and-drawer','no-page-errors'],screenshots}));
  }
}finally{
  await browser?.close();
  server.close();
}
