-- Rollback for stage 0a (function grants).
--
-- This RESTORES a privilege-escalation path: with these grants, the published
-- anon key can execute SECURITY DEFINER functions, including exec_sql, which runs
-- arbitrary SQL as the owner. It exists so stage 0a can be exercised in isolated
-- testing and reverted there.
--
-- It is NOT the operational recovery plan. If stage 0a breaks something in
-- production, the recovery is to re-grant the ONE function that broke, named in
-- the incident, not to run this file. See db-isolation-remediation.md §5.

begin;

grant execute on function public.admin_revoke_user_sessions(p_user_ids text[]) to anon;
grant execute on function public.app_login(p_username text, p_password text) to anon;
grant execute on function public.apply_payment(payment_id uuid) to public;
grant execute on function public.apply_payment(payment_id uuid) to anon;
grant execute on function public.apply_payment_fully(p_payment_id uuid) to public;
grant execute on function public.apply_payment_fully(p_payment_id uuid) to anon;
grant execute on function public.approve_booking_payment(p_payment_id uuid, p_approved_by uuid) to public;
grant execute on function public.approve_booking_payment(p_payment_id uuid, p_approved_by uuid) to anon;
grant execute on function public.approve_payment(p_payment_id uuid, p_approved_by uuid) to public;
grant execute on function public.approve_payment(p_payment_id uuid, p_approved_by uuid) to anon;
grant execute on function public.auto_resolve_credits_test_requests() to public;
grant execute on function public.auto_resolve_credits_test_requests() to anon;
grant execute on function public.auto_resolve_go_live_requests() to public;
grant execute on function public.auto_resolve_go_live_requests() to anon;
grant execute on function public.backfill_payment_rental_ids() to public;
grant execute on function public.backfill_payment_rental_ids() to anon;
grant execute on function public.block_customer(p_customer_id uuid, p_reason text, p_blocked_by uuid) to public;
grant execute on function public.calculate_vehicle_book_cost(p_vehicle_id uuid) to public;
grant execute on function public.calculate_vehicle_book_cost(p_vehicle_id uuid) to anon;
grant execute on function public.cancel_installment_plan(p_plan_id uuid, p_reason text) to public;
grant execute on function public.cancel_installment_plan(p_plan_id uuid, p_reason text) to anon;
grant execute on function public.check_and_update_global_blacklist(p_email text) to public;
grant execute on function public.check_and_update_global_blacklist(p_email text) to anon;
grant execute on function public.check_policy_overlap(p_customer_id uuid, p_vehicle_id uuid, p_start_date date, p_expiry_date date, p_policy_id uuid) to public;
grant execute on function public.check_policy_overlap(p_customer_id uuid, p_vehicle_id uuid, p_start_date date, p_expiry_date date, p_policy_id uuid) to anon;
grant execute on function public.classify_audit_log_activity_source() to public;
grant execute on function public.classify_audit_log_activity_source() to anon;
grant execute on function public.create_chat_channel_for_customer() to public;
grant execute on function public.create_chat_channel_for_customer() to anon;
grant execute on function public.create_installment_plan(p_rental_id uuid, p_tenant_id uuid, p_customer_id uuid, p_plan_type text, p_total_installable_amount numeric, p_upfront_amount numeric, p_number_of_installments integer, p_start_date date, p_stripe_customer_id text, p_stripe_payment_method_id text) to public;
grant execute on function public.create_installment_plan(p_rental_id uuid, p_tenant_id uuid, p_customer_id uuid, p_plan_type text, p_total_installable_amount numeric, p_upfront_amount numeric, p_number_of_installments integer, p_start_date date, p_stripe_customer_id text, p_stripe_payment_method_id text) to anon;
grant execute on function public.create_installment_plan(p_rental_id uuid, p_tenant_id uuid, p_customer_id uuid, p_plan_type text, p_total_installable_amount numeric, p_number_of_installments integer, p_upfront_amount numeric, p_stripe_customer_id text, p_start_date date) to public;
grant execute on function public.create_installment_plan(p_rental_id uuid, p_tenant_id uuid, p_customer_id uuid, p_plan_type text, p_total_installable_amount numeric, p_number_of_installments integer, p_upfront_amount numeric, p_stripe_customer_id text, p_start_date date) to anon;
grant execute on function public.create_rental_charges() to public;
grant execute on function public.create_rental_charges() to anon;
grant execute on function public.create_vehicle_pl() to public;
grant execute on function public.create_vehicle_pl() to anon;
grant execute on function public.dispose_vehicle(p_vehicle_id uuid, p_disposal_date date, p_sale_proceeds numeric, p_buyer text, p_notes text) to public;
grant execute on function public.dispose_vehicle(p_vehicle_id uuid, p_disposal_date date, p_sale_proceeds numeric, p_buyer text, p_notes text) to anon;
grant execute on function public.enforce_payment_target_categories() to anon;
grant execute on function public.enqueue_financial_event(p_tenant_id uuid, p_event_type financial_event_type, p_amount_cents integer, p_currency text, p_rental_id uuid, p_customer_id uuid, p_vehicle_id uuid, p_tax_cents integer, p_occurred_at timestamp with time zone, p_source_table text, p_source_id uuid, p_description text, p_metadata jsonb) to public;
grant execute on function public.enqueue_financial_event(p_tenant_id uuid, p_event_type financial_event_type, p_amount_cents integer, p_currency text, p_rental_id uuid, p_customer_id uuid, p_vehicle_id uuid, p_tax_cents integer, p_occurred_at timestamp with time zone, p_source_table text, p_source_id uuid, p_description text, p_metadata jsonb) to anon;
grant execute on function public.enqueue_financial_event_for_ledger_entry() to public;
grant execute on function public.enqueue_financial_event_for_ledger_entry() to anon;
grant execute on function public.ensure_lead_conversation() to public;
grant execute on function public.ensure_lead_conversation() to anon;
grant execute on function public.evaluate_tenant_health(p_trigger text, p_force boolean, p_evaluated_at timestamp with time zone) to anon;
grant execute on function public.exec_sql(query text) to anon;
grant execute on function public.expire_subscription_link_session() to public;
grant execute on function public.expire_subscription_link_session() to anon;
grant execute on function public.finalize_rental_extension(p_extension_id uuid, p_payment_id uuid) to public;
grant execute on function public.finalize_rental_extension(p_extension_id uuid, p_payment_id uuid) to anon;
grant execute on function public.fine_void_charge(f_id uuid) to public;
grant execute on function public.fine_void_charge(f_id uuid) to anon;
grant execute on function public.generate_daily_reminders() to public;
grant execute on function public.generate_daily_reminders() to anon;
grant execute on function public.generate_monthly_charges(rental_id uuid) to public;
grant execute on function public.generate_monthly_charges(rental_id uuid) to anon;
grant execute on function public.generate_next_invoice_number() to public;
grant execute on function public.generate_next_invoice_number() to anon;
grant execute on function public.get_chat_history(p_tenant_id uuid, p_conversation_id uuid, p_limit integer) to public;
grant execute on function public.get_chat_history(p_tenant_id uuid, p_conversation_id uuid, p_limit integer) to anon;
grant execute on function public.get_current_user_role() to public;
grant execute on function public.get_current_user_role() to anon;
grant execute on function public.get_customer_balance_with_status(customer_id_param uuid) to public;
grant execute on function public.get_customer_balance_with_status(customer_id_param uuid) to anon;
grant execute on function public.get_customer_credit(customer_id_param uuid) to public;
grant execute on function public.get_customer_credit(customer_id_param uuid) to anon;
grant execute on function public.get_customer_net_position(customer_id_param uuid) to public;
grant execute on function public.get_customer_net_position(customer_id_param uuid) to anon;
grant execute on function public.get_customer_rag_context(p_tenant_id uuid, p_customer_id uuid) to public;
grant execute on function public.get_customer_rag_context(p_tenant_id uuid, p_customer_id uuid) to anon;
grant execute on function public.get_customer_rag_context(p_customer_id uuid) to public;
grant execute on function public.get_customer_rag_context(p_customer_id uuid) to anon;
grant execute on function public.get_customer_statement(p_customer_id uuid, p_from_date date, p_to_date date) to public;
grant execute on function public.get_customer_statement(p_customer_id uuid, p_from_date date, p_to_date date) to anon;
grant execute on function public.get_due_installments(p_process_date date) to public;
grant execute on function public.get_due_installments(p_process_date date) to anon;
grant execute on function public.get_effective_tenant_id() to public;
grant execute on function public.get_effective_tenant_id() to anon;
grant execute on function public.get_expiring_bookings() to public;
grant execute on function public.get_expiring_bookings() to anon;
grant execute on function public.get_health_score_dashboard(p_history_days integer) to anon;
grant execute on function public.get_installment_plan_summary(p_rental_id uuid) to public;
grant execute on function public.get_installment_plan_summary(p_rental_id uuid) to anon;
grant execute on function public.get_installments_for_reminder() to public;
grant execute on function public.get_installments_for_reminder() to anon;
grant execute on function public.get_installments_for_retry(p_process_date date) to public;
grant execute on function public.get_installments_for_retry(p_process_date date) to anon;
grant execute on function public.get_payment_remaining(payment_id_param uuid) to public;
grant execute on function public.get_payment_remaining(payment_id_param uuid) to anon;
grant execute on function public.get_pending_bookings_count() to public;
grant execute on function public.get_pending_bookings_count() to anon;
grant execute on function public.get_pending_charges_for_reminders() to public;
grant execute on function public.get_pending_charges_for_reminders() to anon;
grant execute on function public.get_pending_payments_count() to public;
grant execute on function public.get_pending_payments_count() to anon;
grant execute on function public.get_pending_rental_requests(p_tenant_id uuid) to public;
grant execute on function public.get_pending_rental_requests(p_tenant_id uuid) to anon;
grant execute on function public.get_rag_metrics(p_tenant_id uuid) to public;
grant execute on function public.get_rag_metrics(p_tenant_id uuid) to anon;
grant execute on function public.get_refunds_due_today() to public;
grant execute on function public.get_refunds_due_today() to anon;
grant execute on function public.get_rental_credit(rental_id_param uuid) to public;
grant execute on function public.get_rental_credit(rental_id_param uuid) to anon;
grant execute on function public.get_rental_insurance_documents(p_rental_id uuid) to public;
grant execute on function public.get_rental_insurance_documents(p_rental_id uuid) to anon;
grant execute on function public.get_tenant_health_activity(p_tenant_id uuid, p_period_days integer, p_anchor timestamp with time zone) to anon;
grant execute on function public.get_user_role(user_id uuid) to public;
grant execute on function public.get_user_role(user_id uuid) to anon;
grant execute on function public.get_user_tenant_id() to public;
grant execute on function public.get_user_tenant_id() to anon;
grant execute on function public.guard_custom_site_toggle() to public;
grant execute on function public.guard_custom_site_toggle() to anon;
grant execute on function public.handle_vehicle_expense_pnl() to public;
grant execute on function public.handle_vehicle_expense_pnl() to anon;
grant execute on function public.handover_stamp_vehicle() to public;
grant execute on function public.handover_stamp_vehicle() to anon;
grant execute on function public.handover_to_odometer_reading() to public;
grant execute on function public.handover_to_odometer_reading() to anon;
grant execute on function public.has_any_role(_user_id uuid, _roles text[]) to public;
grant execute on function public.has_any_role(_user_id uuid, _roles text[]) to anon;
grant execute on function public.has_role(_user_id uuid, _role text) to public;
grant execute on function public.has_role(_user_id uuid, _role text) to anon;
grant execute on function public.hash_password(password text) to public;
grant execute on function public.hash_password(password text) to anon;
grant execute on function public.increment_payg_reminder_count(p_rental_id uuid, p_last_sent_at timestamp with time zone) to public;
grant execute on function public.increment_payg_reminder_count(p_rental_id uuid, p_last_sent_at timestamp with time zone) to anon;
grant execute on function public.initialize_tenant_wallet() to public;
grant execute on function public.initialize_tenant_wallet() to anon;
grant execute on function public.installment_settle_invoice(p_payment_id uuid, p_installment_id uuid) to anon;
grant execute on function public.is_bonzah_partner() to public;
grant execute on function public.is_bonzah_partner() to anon;
grant execute on function public.is_current_user_admin() to public;
grant execute on function public.is_current_user_admin() to anon;
grant execute on function public.is_global_master_admin() to public;
grant execute on function public.is_global_master_admin() to anon;
grant execute on function public.is_globally_blacklisted(p_email text) to public;
grant execute on function public.is_globally_blacklisted(p_email text) to anon;
grant execute on function public.is_identity_blocked(p_identity_number text) to public;
grant execute on function public.is_identity_blocked(p_identity_number text) to anon;
grant execute on function public.is_identity_blocked_for_tenant(p_tenant_id uuid, p_identity_number text) to public;
grant execute on function public.is_identity_blocked_for_tenant(p_tenant_id uuid, p_identity_number text) to anon;
grant execute on function public.is_portal_staff() to public;
grant execute on function public.is_portal_staff() to anon;
grant execute on function public.is_portal_user() to public;
grant execute on function public.is_portal_user() to anon;
grant execute on function public.is_primary_super_admin() to public;
grant execute on function public.is_primary_super_admin() to anon;
grant execute on function public.is_sales_agent() to public;
grant execute on function public.is_sales_agent() to anon;
grant execute on function public.is_super_admin() to public;
grant execute on function public.is_super_admin() to anon;
grant execute on function public.knowledge_articles_rag_sync() to public;
grant execute on function public.knowledge_articles_rag_sync() to anon;
grant execute on function public.landing_pricing_enabled() to anon;
grant execute on function public.log_service_record_event() to public;
grant execute on function public.log_service_record_event() to anon;
grant execute on function public.mark_installment_failed(p_installment_id uuid, p_failure_reason text, p_stripe_payment_intent_id text) to public;
grant execute on function public.mark_installment_failed(p_installment_id uuid, p_failure_reason text, p_stripe_payment_intent_id text) to anon;
grant execute on function public.mark_installment_paid(p_installment_id uuid, p_payment_id uuid, p_ledger_entry_id uuid, p_stripe_payment_intent_id text, p_stripe_charge_id text) to public;
grant execute on function public.mark_installment_paid(p_installment_id uuid, p_payment_id uuid, p_ledger_entry_id uuid, p_stripe_payment_intent_id text, p_stripe_charge_id text) to anon;
grant execute on function public.mark_overdue_installments() to public;
grant execute on function public.mark_overdue_installments() to anon;
grant execute on function public.match_documents(p_tenant_id uuid, query_embedding vector, match_threshold double precision, match_count integer, filter_tables text[]) to public;
grant execute on function public.match_documents(p_tenant_id uuid, query_embedding vector, match_threshold double precision, match_count integer, filter_tables text[]) to anon;
grant execute on function public.notify_automation_event(p_event_type text, p_tenant_id uuid, p_entity_type text, p_entity_id uuid, p_payload jsonb) to public;
grant execute on function public.notify_automation_event(p_event_type text, p_tenant_id uuid, p_entity_type text, p_entity_id uuid, p_payload jsonb) to anon;
grant execute on function public.notify_customer_rental_status_change() to public;
grant execute on function public.notify_customer_rental_status_change() to anon;
grant execute on function public.notify_fine_new() to public;
grant execute on function public.notify_fine_new() to anon;
grant execute on function public.notify_identity_verified() to public;
grant execute on function public.notify_identity_verified() to anon;
grant execute on function public.notify_new_chat_message() to public;
grant execute on function public.notify_new_chat_message() to anon;
grant execute on function public.notify_new_rental() to public;
grant execute on function public.notify_new_rental() to anon;
grant execute on function public.notify_operator_email_dispatch() to public;
grant execute on function public.notify_operator_email_dispatch() to anon;
grant execute on function public.notify_payment_received() to public;
grant execute on function public.notify_payment_received() to anon;
grant execute on function public.notify_platform_activity() to public;
grant execute on function public.notify_platform_activity() to anon;
grant execute on function public.notify_refund_processed() to public;
grant execute on function public.notify_refund_processed() to anon;
grant execute on function public.notify_signing_completed() to public;
grant execute on function public.notify_signing_completed() to anon;
grant execute on function public.notify_subscription_of_invoice_change() to public;
grant execute on function public.notify_subscription_of_invoice_change() to anon;
grant execute on function public.payg_settle_invoice(p_payment_id uuid, p_accrual_id uuid) to public;
grant execute on function public.payg_settle_invoice(p_payment_id uuid, p_accrual_id uuid) to anon;
grant execute on function public.preview_tenant_health_settings(p_period_days integer, p_threshold_percent integer, p_minimum_baseline_events integer, p_new_tenant_grace_days integer, p_include_test_tenants boolean, p_evaluated_at timestamp with time zone) to anon;
grant execute on function public.process_payment_transaction(p_payment_id uuid, p_customer_id uuid, p_rental_id uuid, p_vehicle_id uuid, p_amount numeric, p_payment_type text, p_payment_date date) to public;
grant execute on function public.process_payment_transaction(p_payment_id uuid, p_customer_id uuid, p_rental_id uuid, p_vehicle_id uuid, p_amount numeric, p_payment_type text, p_payment_date date) to anon;
grant execute on function public.queue_for_rag() to public;
grant execute on function public.queue_for_rag() to anon;
grant execute on function public.recalculate_insurance_status() to public;
grant execute on function public.recalculate_insurance_status() to anon;
grant execute on function public.recalculate_vehicle_pl(p_vehicle_id uuid) to public;
grant execute on function public.recalculate_vehicle_pl(p_vehicle_id uuid) to anon;
grant execute on function public.reclassify_expense_pnl(p_tenant_id uuid, p_category text, p_bucket text) to public;
grant execute on function public.reclassify_expense_pnl(p_tenant_id uuid, p_category text, p_bucket text) to anon;
grant execute on function public.record_installment_notification(p_installment_id uuid, p_notification_type text, p_sent_at timestamp with time zone) to public;
grant execute on function public.record_installment_notification(p_installment_id uuid, p_notification_type text, p_sent_at timestamp with time zone) to anon;
grant execute on function public.reject_booking_payment(p_payment_id uuid, p_rejected_by uuid, p_reason text) to public;
grant execute on function public.reject_booking_payment(p_payment_id uuid, p_rejected_by uuid, p_reason text) to anon;
grant execute on function public.reject_payment(p_payment_id uuid, p_rejected_by uuid, p_reason text) to public;
grant execute on function public.reject_payment(p_payment_id uuid, p_rejected_by uuid, p_reason text) to anon;
grant execute on function public.release_rental_sync_lock(p_tenant_id uuid, p_rental_id uuid, p_provider text, p_worker_id text) to public;
grant execute on function public.release_rental_sync_lock(p_tenant_id uuid, p_rental_id uuid, p_provider text, p_worker_id text) to anon;
grant execute on function public.reset_lockbox_sent_on_reschedule() to public;
grant execute on function public.reset_lockbox_sent_on_reschedule() to anon;
grant execute on function public.seed_cms_pages_for_tenant() to public;
grant execute on function public.seed_cms_pages_for_tenant() to anon;
grant execute on function public.seed_default_lead_templates(p_tenant_id uuid) to public;
grant execute on function public.seed_default_lead_templates(p_tenant_id uuid) to anon;
grant execute on function public.session_is_active(p_session_id text, p_user_id text) to anon;
grant execute on function public.swap_rental_vehicle(p_rental_id uuid, p_new_vehicle_id uuid, p_reason text, p_block_old_start date, p_block_old_end date) to public;
grant execute on function public.swap_rental_vehicle(p_rental_id uuid, p_new_vehicle_id uuid, p_reason text, p_block_old_start date, p_block_old_end date) to anon;
grant execute on function public.sync_verified_name_to_customer() to public;
grant execute on function public.sync_verified_name_to_customer() to anon;
grant execute on function public.touch_feedback_prompted_at() to anon;
grant execute on function public.trax_price_suggest(p_vehicle_id uuid, p_tier text, p_make text, p_model text, p_year integer) to anon;
grant execute on function public.trigger_apply_fifo_on_payment_completed() to public;
grant execute on function public.trigger_apply_fifo_on_payment_completed() to anon;
grant execute on function public.trigger_apply_fifo_on_payment_insert() to public;
grant execute on function public.trigger_apply_fifo_on_payment_insert() to anon;
grant execute on function public.trigger_auto_allocate_payments() to public;
grant execute on function public.trigger_auto_allocate_payments() to anon;
grant execute on function public.trigger_create_fine_charge() to public;
grant execute on function public.trigger_create_fine_charge() to anon;
grant execute on function public.trigger_generate_rental_charges() to public;
grant execute on function public.trigger_generate_rental_charges() to anon;
grant execute on function public.trigger_payg_settle_on_ledger_drain() to public;
grant execute on function public.trigger_payg_settle_on_ledger_drain() to anon;
grant execute on function public.trigger_post_acquisition() to public;
grant execute on function public.trigger_post_acquisition() to anon;
grant execute on function public.trigger_settle_ghost_paid_payg_accruals() to public;
grant execute on function public.trigger_settle_ghost_paid_payg_accruals() to anon;
grant execute on function public.trigger_update_plate_pnl() to public;
grant execute on function public.trigger_update_plate_pnl() to anon;
grant execute on function public.trigger_update_vehicle_last_service() to public;
grant execute on function public.trigger_update_vehicle_last_service() to anon;
grant execute on function public.try_acquire_rental_sync_lock(p_tenant_id uuid, p_rental_id uuid, p_provider text, p_worker_id text, p_ttl_seconds integer) to public;
grant execute on function public.try_acquire_rental_sync_lock(p_tenant_id uuid, p_rental_id uuid, p_provider text, p_worker_id text, p_ttl_seconds integer) to anon;
grant execute on function public.turo_blocked_dates_delete_guard() to public;
grant execute on function public.turo_blocked_dates_delete_guard() to anon;
grant execute on function public.turo_bridge_presence_guard() to public;
grant execute on function public.turo_bridge_presence_guard() to anon;
grant execute on function public.turo_bridge_reservations_guard() to public;
grant execute on function public.turo_bridge_reservations_guard() to anon;
grant execute on function public.turo_sync_jobs_guard() to public;
grant execute on function public.turo_sync_jobs_guard() to anon;
grant execute on function public.unblock_customer(p_customer_id uuid) to public;
grant execute on function public.undo_vehicle_disposal(p_vehicle_id uuid) to public;
grant execute on function public.undo_vehicle_disposal(p_vehicle_id uuid) to anon;
grant execute on function public.update_customer_balance(customer_id uuid) to public;
grant execute on function public.update_customer_balance(customer_id uuid) to anon;
grant execute on function public.update_health_score_config(p_expected_version integer, p_enabled boolean, p_period_days integer, p_threshold_percent integer, p_minimum_baseline_events integer, p_new_tenant_grace_days integer, p_repeat_alert_after_days integer, p_recovery_notifications_enabled boolean, p_include_test_tenants boolean, p_recipient_emails text[]) to anon;
grant execute on function public.update_insurance_docs_count() to public;
grant execute on function public.update_insurance_docs_count() to anon;
grant execute on function public.update_refund_status(p_payment_id uuid, p_new_status text, p_stripe_refund_id text, p_error_message text) to public;
grant execute on function public.update_refund_status(p_payment_id uuid, p_new_status text, p_stripe_refund_id text, p_error_message text) to anon;
grant execute on function public.update_vehicle_last_service(p_vehicle_id uuid) to public;
grant execute on function public.update_vehicle_last_service(p_vehicle_id uuid) to anon;
grant execute on function public.upsert_plate_pnl_entry(p_plate_id uuid, p_cost numeric, p_order_date date, p_vehicle_id uuid, p_created_at timestamp with time zone) to public;
grant execute on function public.upsert_plate_pnl_entry(p_plate_id uuid, p_cost numeric, p_order_date date, p_vehicle_id uuid, p_created_at timestamp with time zone) to anon;
grant execute on function public.upsert_service_pnl_entry(p_service_record_id uuid, p_cost numeric, p_service_date date, p_vehicle_id uuid) to public;
grant execute on function public.upsert_service_pnl_entry(p_service_record_id uuid, p_cost numeric, p_service_date date, p_vehicle_id uuid) to anon;
grant execute on function public.user_can_access_rental(p_rental_id uuid) to public;
grant execute on function public.user_can_access_rental(p_rental_id uuid) to anon;
grant execute on function public.vehicle_odometer_apply() to public;
grant execute on function public.vehicle_odometer_apply() to anon;
grant execute on function public.verify_global_master_password(p_email text, p_password text) to public;
grant execute on function public.verify_global_master_password(p_email text, p_password text) to anon;
grant execute on function public.verify_password(stored_hash text, provided_password text) to public;
grant execute on function public.verify_password(stored_hash text, provided_password text) to anon;

commit;
