/**
 * The Vehicles tab tour — three stops on the list, then eight inside one car,
 * and a shorter half for the operator whose fleet is still empty.
 *
 * THE SHAPE, and why it is this shape. The brief for these tours is explicit
 * that stopping at the "Add Vehicle" button would teach the easy half: what a
 * first-time operator cannot guess is not where the button is, it is that a
 * price sheet has three hire-length switches that quietly delist the car, that
 * weekend pricing exists at all, or that there is nothing here to publish. All
 * of that lives INSIDE the record, so the tour goes in — `routeFor` builds
 * `/vehicles/<uuid>?section=…` from an id read off the list the operator is
 * already looking at (`readSampleIds` in `./index`).
 *
 * Eleven steps, inside the ten-to-twelve the brief allows. Each one names a
 * thing and says in one sentence what it means; none of them explains how to
 * fill a form in. Pointing at doors, not walking through them.
 *
 * ---------------------------------------------------------------------------
 * TWO TOURS IN ONE LIST, because an empty fleet is the normal first day
 *
 * All eleven of those steps assume there is a car to open. A brand-new
 * operator has none — that is what new means — and they are the whole audience
 * for an onboarding tour. So the list below is really two lists: every step
 * that points at a row or lives inside a record carries `requires.record`, and
 * three steps written for the empty fleet carry `requires.noRecord`.
 * `stepAllowed` keeps exactly one half, from ids `launch()` reads off the DOM.
 *
 *   EMPTY fleet   5 steps — the counters, why one real car comes first, what a
 *                 record holds, the Add button, and the teaching card's own CTA
 *                 with a pause on it so the operator goes and does the thing.
 *   WITH a car   11 steps — the list, then eight stops inside one vehicle.
 *
 * The `record` guard is NOT redundant with `routeFor` already returning null on
 * an empty fleet. It says the dependency out loud, it puts the decision in one
 * place, and it is the only thing that saves `vehicles.row` — that step has a
 * perfectly valid route and no way to know its anchor is never coming, so
 * without it the operator watches the full `ANCHOR_WAIT_MS` at a table that has
 * been replaced by an empty state, and then watches it skip.
 *
 * The empty half is the most action-oriented of the three tab tours on purpose.
 * Nothing can be rented until a vehicle exists, and adding one is the one thing
 * a first-day operator can do here without waiting on Stripe, on a customer, or
 * on anybody else. So it ends by pushing at the button rather than summarising.
 *
 * ---------------------------------------------------------------------------
 * THIS TAB SPANS TWO DESIGN GENERATIONS, and every anchor below depends on it
 *
 * The LIST (`/vehicles`) is the shared v1 page that all 57 tenants load —
 * shadcn Cards, a real `<table>`, the gradient stat tiles in
 * `components/vehicles/fleet-summary-cards.tsx`. The RECORD (`/vehicles/<id>`)
 * is v2 and canary-only: `components/vehicles-v2/`, nine sections rendered one
 * at a time from `?section=`, with the app sidebar replaced by that record's
 * own rail. So the list steps — the empty-fleet ones included, since the
 * teaching card that replaces the table is rendered by that same v1 page — are
 * written against v1 markup and the last eight against the v2 tree, and the two
 * share no conventions.
 *
 * ---------------------------------------------------------------------------
 * THE ANCHORS, and the fallback that makes the back half safe
 *
 * Every record step falls back to its own row in the vehicle rail —
 * `[data-sidebar="sidebar"] a[href*="section=rates"]` and friends. Those links
 * are generated by `sectionHref()` from `components/vehicles-v2/sections.ts`,
 * so they cannot be absent while a vehicle is open, they are drawn on first
 * paint rather than after a query, and they are small. That matters more than
 * it looks: once ONE step on a route times out waiting for an anchor, every
 * later step on that same route gets a 1.5s budget instead of 6s, and this
 * tour is eight steps on a single pathname. A fallback that resolves instantly
 * keeps one slow panel from starving the rest of the run.
 *
 * It is also correct by identity rather than merely present: each step falls
 * back to the rail row for ITS OWN section, so a step that resolves before the
 * panel has repainted still points at the right door. That is worth stating,
 * because it is the common case — a step changing only `?section=` polls for
 * its anchor the moment the push is issued, which is usually a beat before the
 * new panel renders.
 *
 * The EMPTY half anchors inside the teaching card
 * (`VehiclesTeachingEmptyState` in `components/empty-states/lean-empty-states`),
 * which REPLACES the table when the fleet is empty — the same moment those
 * steps run, and canary-only, which is also the only tenant the launch button
 * renders for. Two attributes reach it: `[data-tour="vehicles-empty-points"]`
 * on the payoff list and `[data-tour="vehicles-empty"]` on the card, which the
 * steps only ever use as a scope for its heading or its CTA. Never the card
 * itself — it runs the full content width at around 450px tall, which is past
 * the point where the spotlight degrades to a centred wash. Each of those steps
 * still falls through to `LIST_HEADING`, so losing the attribute costs nothing.
 *
 * The `?section=` values are a contract with `sections.ts` in two places at
 * once — the route AND the href fallback of the same step. Renaming a
 * `SectionId` breaks both together; there is no half-working state to notice.
 *
 * No step anchors a whole `<Panel>` or a whole `<Section>` card. The spotlight
 * degrades to a centred wash past roughly two thirds of the viewport, which
 * looks like it worked while teaching nothing — so the section anchors land on
 * the section's HEADING ROW (see the `tourId` prop on `Section` in
 * `components/vehicles-v2/kit.tsx`) and the rates step lands on the three
 * switches rather than the price grid above them.
 *
 * ---------------------------------------------------------------------------
 * WHAT IS DELIBERATELY LEFT OUT
 *
 *  - Mileage, Extras, Keys & documents, Money. Mileage and documents ride as
 *    one-line notes on the steps next to them; Extras and Money are readouts an
 *    operator finds on their own once they know the rail exists. Eleven steps
 *    is the budget, and depth here would cost the record steps that earn it.
 *  - The right-hand overview rail (`overview-rail.tsx`). It is `xl:flex`, so it
 *    is `display: none` below 1280px and `isVisible()` rejects it — a step
 *    anchored there would silently skip on a 13" laptop, and `requires.desktop`
 *    only excludes phones.
 *  - Owner, Health and INSHUR columns. Hidden for the canary by
 *    `lib/lean-areas.ts`, so copy naming them would be wrong on the very tenant
 *    this is built for.
 *  - The deposit field, which is fleet-wide and read-only when the tenant is on
 *    `deposit_mode = 'global'` — a sentence promising it can be set per car is
 *    false for some tenants.
 */

import type { TourStep } from '@/lib/first-rental-tour';
import { recordRoute, type TabTour } from './index';

/** The vehicle rail row for a section — the fallback under every record step. */
const rail = (section: string) => `[data-sidebar="sidebar"] a[href*="section=${section}"]`;

/**
 * The list page's own heading. Unconditional on `/vehicles`, and the last
 * resort under every step that lives there.
 *
 * Two selectors because the two chromes disagree: `data-slot="sidebar-inset"`
 * exists only on the v2 sidebar, while `main h1` resolves under either.
 */
const LIST_HEADING = ['[data-slot="sidebar-inset"] h1', 'main h1'] as const;

const STEPS: readonly TourStep[] = [
  {
    id: 'vehicles.fleet',
    label: 'Your fleet',
    title: 'Your fleet, counted',
    body: 'Available means bookable right now. Unavailable means every hire length is switched off. Paused means you took the car off the road.',
    route: '/vehicles',
    anchors: ['[data-tour="fleet-stat-available"]', '[data-tour="fleet-stat-unavailable"]', ...LIST_HEADING],
    side: 'bottom',
    showOutline: true,
  },
  // ── The empty fleet's own three steps ───────────────────────────────────
  // They sit interleaved with the shared ones rather than in a block, because
  // `buildTour` keeps the array's order and the empty run has to READ in order:
  // the counters, why a car comes first, what a record holds, the button, then
  // the card's own CTA. Grouping them at the end would put "add your first car"
  // before "here is what a car record even is".
  {
    id: 'vehicles.empty.first',
    label: 'The first car',
    title: 'Start with one real car',
    body: 'Use the car you actually mean to put on the road, not a test one. What you put on it is what customers see and pay on your booking site.',
    route: '/vehicles',
    anchors: ['[data-tour="vehicles-empty"] h3', ...LIST_HEADING],
    side: 'bottom',
    requires: { noRecord: 'vehicleId' },
  },
  {
    id: 'vehicles.empty.holds',
    label: 'One record',
    title: 'One car, everything about it',
    body: 'Photos, three prices, the dates it cannot be booked, its papers and what it earns. A few fields create it; the rest you fill in on the record.',
    route: '/vehicles',
    anchors: ['[data-tour="vehicles-empty-points"]', ...LIST_HEADING],
    side: 'bottom',
    requires: { noRecord: 'vehicleId' },
  },
  {
    id: 'vehicles.add',
    label: 'Add a vehicle',
    title: 'Add the car you really rent',
    body: 'Plate, make, model — and at least one photo, which it will insist on. Everything else can be filled in on the record afterwards.',
    route: '/vehicles',
    anchors: ['[data-tour="add-vehicle"]', '[data-add-vehicle-trigger]'],
    side: 'bottom',
    requires: { tab: 'vehicles', edit: true },
    // Clicking this opens the dialog. Stand aside rather than sitting on top
    // of it.
    pauseOnAnchorClick: true,
  },
  {
    id: 'vehicles.empty.start',
    label: 'Add your first',
    title: 'Add your first car now',
    body: 'Same form as the button above. Add one car and the rest of this tour unlocks: the launch button becomes See what is inside, and it goes in with you.',
    route: '/vehicles',
    // The teaching card's own CTA — the biggest thing on an empty page — then
    // the header button, then the heading. The middle one is what this step
    // lands on for anyone whose fleet is empty without that card being drawn.
    anchors: ['[data-tour="vehicles-empty"] button', '[data-tour="add-vehicle"]', ...LIST_HEADING],
    side: 'top',
    // `edit` for the same reason `vehicles.add` carries it: never spotlight a
    // mutation control for someone who is not allowed to use it. A view-only
    // manager on an empty fleet keeps the three steps above this one.
    requires: { noRecord: 'vehicleId', tab: 'vehicles', edit: true },
    pauseOnAnchorClick: true,
    // The unexplained failure a first-timer actually hits: the dialog's own
    // submit handler refuses with a toast when no photo has been attached
    // (`add-vehicle-dialog.tsx`), and no field on the form says so.
    notes: [{ text: 'The form will not save until at least one photo of the car is attached.' }],
  },
  {
    id: 'vehicles.row',
    label: 'A vehicle',
    title: 'Every row is a door',
    body: 'Open a car and you get its own screen — photos, prices, papers, and what it has earned. Everything about one vehicle in one place.',
    route: '/vehicles',
    // All three are absent on an empty fleet — the table itself is replaced by
    // the teaching card — so the guard below is the one that matters most in
    // this file. Without it the route is valid, the step has no way to know its
    // anchor is never coming, and the operator watches a six-second pause at a
    // page that has nothing to point at.
    anchors: ['[data-tour="vehicle-row"]', 'table tbody tr', 'table thead'],
    side: 'bottom',
    requires: { record: 'vehicleId' },
  },
  {
    id: 'vehicles.record',
    label: 'The record',
    title: 'Nine places, one car',
    body: 'While a car is open, this rail is its contents page. There is no Save button anywhere on it — what you type applies as you type it.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles'),
    anchors: ['[data-sidebar="sidebar"] [data-sidebar="content"]', '[data-sidebar="sidebar"]'],
    side: 'right',
    // The rail is an off-canvas Sheet on a phone; there is nothing to point at
    // until it is opened. And there is no rail at all without a car to open.
    requires: { desktop: true, record: 'vehicleId' },
  },
  {
    id: 'vehicles.photos',
    label: 'Photos',
    title: 'The first photo is the cover',
    body: 'It is what customers see on your booking site, and how you will pick this car out everywhere in here. Any other photo can take its place.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=vehicle'),
    anchors: ['[data-tour="vehicle-photos"]', rail('vehicle')],
    side: 'bottom',
    requires: { record: 'vehicleId' },
  },
  {
    id: 'vehicles.rates',
    label: 'Rates',
    title: 'Three prices, three hire lengths',
    body: 'A day, a week, a month. The switches under them decide which a customer may ask for — turn all three off and the car leaves your booking site.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=rates'),
    anchors: ['[data-tour="vehicle-hire-lengths"]', rail('rates')],
    side: 'top',
    requires: { record: 'vehicleId' },
    // Mileage sits in the same section and does not need a step of its own,
    // but an empty box meaning "unlimited" is the opposite of what every other
    // form in the product means, so it is worth the line.
    notes: [{ text: 'An empty mileage box below means unlimited, not zero.' }],
  },
  {
    id: 'vehicles.weekends',
    label: 'Weekend pricing',
    title: 'Weekends can cost more',
    body: 'Your fleet sets one weekend rule in Settings. This car only decides whether it takes part, or names its own number. Holidays work the same way.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=addons'),
    anchors: ['[data-tour="vehicle-weekends"]', rail('addons')],
    side: 'bottom',
    requires: { record: 'vehicleId' },
  },
  {
    id: 'vehicles.availability',
    label: 'Availability',
    title: 'Why a car cannot be booked',
    body: 'Every reason is listed here with the lever that clears it. Pausing takes the car off your site; blocked periods take out dates and leave the rest.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=availability'),
    anchors: ['[data-tour="vehicle-blockers"]', rail('availability')],
    side: 'bottom',
    requires: { record: 'vehicleId' },
  },
  {
    id: 'vehicles.lockbox',
    label: 'Handover',
    title: 'Keys without meeting anyone',
    body: 'Set a code and where the box is hidden, and the customer is sent both at pickup. Leave it off and the keys change hands in person.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=pickup'),
    anchors: ['[data-tour="vehicle-lockbox"]', rail('pickup')],
    side: 'top',
    requires: { record: 'vehicleId' },
    // The silent failure worth one line: with the fleet-wide switch off,
    // nothing is ever sent no matter what is typed on the car.
    notes: [{ text: 'Lockbox handover is switched on for the whole fleet in Settings, under Rentals.' }],
  },
  {
    id: 'vehicles.upkeep',
    label: 'Upkeep',
    title: 'Papers, and the odometer',
    body: 'An expired inspection takes the car off your site on its own. An expired warranty only costs you money. Both are dated here.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=upkeep'),
    anchors: ['[data-tour="vehicle-certificates"]', rail('upkeep')],
    side: 'bottom',
    requires: { record: 'vehicleId' },
    // Documents get covered without spending a step. Anchored, so a rail that
    // no longer carries the row drops the line instead of lying about it.
    notes: [
      {
        text: 'The PDFs themselves are filed next door, under Keys and documents.',
        anchors: [rail('keys')],
      },
    ],
  },
  {
    id: 'vehicles.listing',
    label: 'Listing',
    title: 'There is nothing to publish',
    body: 'Your booking site reads this record as it stands, so a price you change is a price a customer sees. This page is exactly what they get.',
    route: '/vehicles',
    routeFor: (ctx) => recordRoute(ctx.sampleIds?.vehicleId, '/vehicles', 'section=listing'),
    anchors: ['[data-tour="vehicle-listing"]', rail('listing')],
    side: 'top',
    requires: { record: 'vehicleId' },
  },
];

export const VEHICLES_TAB_TOUR: TabTour = {
  id: 'vehicles',
  label: 'Vehicles',
  homeRoute: '/vehicles',
  // Said when fewer than `MIN_TOUR_STOPS` anchored steps survive.
  //
  // An empty fleet is NO LONGER that case, which is the point of this change:
  // it now has three steps of its own and runs five in total. Nor is a
  // view-only manager, who keeps the counters and both empty-fleet teaching
  // steps once the two add steps are dropped — three, which clears the floor.
  //
  // So this is close to unreachable, and the honest remaining cause is access
  // to `/vehicles` itself. It is worded for that rather than telling someone to
  // add a car they may not be permitted to add.
  emptyMessage:
    'There is not enough of this tab open to you to walk through. A head admin can widen your access to Vehicles, and the tour will have more to show.',
  steps: STEPS,
};
