/**
 * Auto-extension — every branch of the renewal job (spec §6 "then auto
 * extension"), fired through sandbox-auto-extend-rentals with only_rental_id =
 * the fixture, never the real job 54.
 *
 * Fixture: autoExtendWeekly(mode) — a Weekly rental at $350.00/week that
 * started 7 days ago and ends today; its booking charge ($350.00) is paid by
 * card first so each renewal's bill stands alone. The first renewal is due in
 * 1 hour; `advance auto_extend 1 day` makes it due (backdating the driving
 * columns: auto_extend_next_charge_at, end_date, …).
 *
 * A renewal bills the period rate: 1 week × $350.00 = $350.00, no tax
 * (`tax_off`, `service_fee_off`). Retry spacing is grace ÷ retries =
 * 48 h ÷ 3 = 16 h (`auto_extend_grace_48h`, `auto_extend_retries_3`).
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { autoExtendWeekly } from "./fixtures.ts";
import type { BillExpectation, Check, Scenario, Step, TenantAssumption } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };
const ASSUMES: TenantAssumption[] = ["usd", "tax_off", "service_fee_off", "auto_extend_grace_48h", "auto_extend_retries_3"];

// The booking week: 1 × $350.00, paid by card before any renewal.
const PAY_WEEK: Step = { kind: "charge_saved_card", amount: { cents: 35000, math: "1 × 350.00 = 350.00" }, note: "E2E: pay the first week" };
const RENEWAL_DUE: Step = { kind: "advance", domain: "auto_extend", days: 1 };
const FIRE: Step = { kind: "fire", job: "sandbox-auto-extend-rentals" };

const BOOKING_PAID: BillExpectation = {
  label: "Booking",
  total: { cents: 35000, math: "1 × 350.00 = 350.00" },
  paid: { cents: 35000, math: "350.00 = 350.00" },
  credited: ZERO,
  balance: { cents: 0, math: "350.00 - 350.00 - 0.00 = 0.00" },
};

const RENEWAL_PAID: BillExpectation = {
  label: "Extension #1",
  total: { cents: 35000, math: "1 × 350.00 = 350.00" },
  paid: { cents: 35000, math: "350.00 = 350.00" },
  credited: ZERO,
  balance: { cents: 0, math: "350.00 - 350.00 - 0.00 = 0.00" },
};

const RENEWAL_UNPAID: BillExpectation = {
  label: "Extension #1",
  total: { cents: 35000, math: "1 × 350.00 = 350.00" },
  paid: ZERO,
  credited: ZERO,
  balance: { cents: 35000, math: "350.00 - 0.00 - 0.00 = 350.00" },
};

const ONLY_BOOKING_TIE_OUT: Step = {
  kind: "tie_out",
  label: "no renewal was billed",
  expect: {
    outstanding: { cents: 0, math: "350.00 - 350.00 = 0.00" },
    collected: { cents: 35000, math: "350.00 = 350.00" },
    bills: [BOOKING_PAID],
  },
};

const RENEWED_TIE_OUT: Step = {
  kind: "tie_out",
  label: "renewed and paid",
  expect: {
    outstanding: { cents: 0, math: "700.00 - 700.00 = 0.00" },
    collected: { cents: 70000, math: "350.00 + 350.00 = 700.00" },
    bills: [BOOKING_PAID, RENEWAL_PAID],
  },
};

const AWAITING_TIE_OUT: Step = {
  kind: "tie_out",
  label: "renewal billed, link not paid",
  expect: {
    // 'Extension Rental' counts regardless of its due date.
    outstanding: { cents: 35000, math: "0.00 + 350.00 = 350.00" },
    // The pay-link's Pending placeholder row is not money.
    collected: { cents: 35000, math: "350.00 = 350.00" },
    bills: [BOOKING_PAID, RENEWAL_UNPAID],
  },
};

const RENEWED_BY_CARD: Check[] = [
  { label: "one renewal", observe: "extensions.count", expect: 1 },
  { label: "it is 7 days", observe: "extensions.last.days", expect: 7 },
  { label: "it reads paid", observe: "extensions.last.status", expect: "paid" },
  { label: "the return date moved 7 days", observe: "rental.end_date_moved_days", expect: 7 },
  { label: "renewal count 1", observe: "rental.auto_extend_charge_count", expect: 1 },
  { label: "no failed attempts", observe: "rental.auto_extend_failed_attempts", expect: 0 },
  { label: "renewal charges $350.00", observe: "ledger.extension_charge_cents", expect: { cents: 35000, math: "1 × 350.00 = 350.00" } },
  { label: "received $700.00 in all", observe: "payments.received_cents", expect: { cents: 70000, math: "350.00 + 350.00 = 700.00" } },
];

const DECLINED_ONCE: Check[] = [
  { label: "the unpaid renewal was rolled back", observe: "extensions.count", expect: 0 },
  { label: "no renewal charges left behind", observe: "ledger.extension_charge_cents", expect: { cents: 0, math: "0.00 = 0.00" } },
  { label: "one failed attempt", observe: "rental.auto_extend_failed_attempts", expect: 1 },
  { label: "not paused yet", observe: "rental.auto_extend_paused", expect: false },
  // Retries are spread across the grace window: 48 h ÷ 3 retries = 16 h.
  { label: "next try in 16 hours (48 h ÷ 3)", observe: "rental.auto_extend_retry_in_hours", expect: 16 },
  { label: "the return date did not move", observe: "rental.end_date_moved_days", expect: 0 },
  { label: "only the booking's $350.00 was received", observe: "payments.received_cents", expect: { cents: 35000, math: "350.00 = 350.00" } },
];

const AWAITING_LINK: Check[] = [
  { label: "one renewal, waiting for payment", observe: "extensions.count", expect: 1 },
  { label: "it is not paid", observe: "extensions.last.status", expect: "approved" },
  { label: "the rental says awaiting_payment", observe: "rental.auto_extend_status", expect: "awaiting_payment" },
  { label: "the pending-renewal latch is set", observe: "rental.auto_extend_pending", expect: true },
  { label: "one link placeholder row", observe: "payments.pending_link_count", expect: 1 },
  { label: "renewal charges $350.00 are on the ledger", observe: "ledger.extension_charge_cents", expect: { cents: 35000, math: "1 × 350.00 = 350.00" } },
  { label: "the date does not move until paid", observe: "rental.end_date_moved_days", expect: 0 },
];

export const AUTO_EXTEND: Scenario[] = [
  {
    id: "AE1",
    family: "auto_extend",
    title: "Auto-charge renews the week",
    why: "Card on file succeeds: one renewal, its own Extension charges, one payment isolated to them, the date rolls 7 days.",
    tiers: ["live"],
    fixture: autoExtendWeekly("auto_charge"),
    assumes: ASSUMES,
    steps: [PAY_WEEK, RENEWAL_DUE, FIRE, { kind: "check", label: "renewed by card", checks: RENEWED_BY_CARD }, RENEWED_TIE_OUT],
  },
  {
    id: "AE2",
    family: "auto_extend",
    title: "Auto-charge declined — retried, then paused after 3",
    why: "A card that stops working mid-rental (the insufficient-funds branch: the job treats every decline alike): each failure rolls the renewal back, retries 16 h later, and the third failure pauses auto-extension.",
    tiers: ["live"],
    fixture: autoExtendWeekly("auto_charge"),
    assumes: ASSUMES,
    steps: [
      PAY_WEEK,
      { kind: "swap_card", card: "declined" },
      RENEWAL_DUE,
      FIRE,
      { kind: "check", label: "first decline", checks: DECLINED_ONCE },
      ONLY_BOOKING_TIE_OUT,
      // The retry is 16 h out; a day later it is due again.
      RENEWAL_DUE,
      FIRE,
      { kind: "check", label: "second decline", checks: [{ label: "two failed attempts", observe: "rental.auto_extend_failed_attempts", expect: 2 }, { label: "still not paused", observe: "rental.auto_extend_paused", expect: false }] },
      RENEWAL_DUE,
      FIRE,
      {
        kind: "check",
        label: "third decline pauses",
        checks: [
          { label: "three failed attempts", observe: "rental.auto_extend_failed_attempts", expect: 3 },
          { label: "auto-extension is paused", observe: "rental.auto_extend_paused", expect: true },
          { label: "the rental says paused", observe: "rental.auto_extend_status", expect: "paused" },
          { label: "no renewal exists", observe: "extensions.count", expect: 0 },
        ],
      },
      ONLY_BOOKING_TIE_OUT,
    ],
  },
  {
    id: "AE3",
    family: "auto_extend",
    title: "Auto-charge needs authentication (SCA)",
    why: "The bank wants the customer present. The job has no SCA branch: it is handled exactly like a decline — rolled back, retried in 16 h — and no link is sent.",
    tiers: ["live"],
    fixture: autoExtendWeekly("auto_charge"),
    assumes: ASSUMES,
    suspect: "An off-session authentication_required is retried blind and, after three tries, paused — the customer is never sent a link to authenticate (the payment-plan engine sends one: S3).",
    steps: [PAY_WEEK, { kind: "swap_card", card: "auth_required" }, RENEWAL_DUE, FIRE, { kind: "check", label: "treated as a decline", checks: DECLINED_ONCE }, ONLY_BOOKING_TIE_OUT],
  },
  {
    id: "AE4",
    family: "auto_extend",
    title: "Pay-link renewal — the customer pays",
    why: "The job bills the renewal and emails a link; the date moves only once it is paid; the next run clears the pending latch.",
    tiers: ["live"],
    fixture: autoExtendWeekly("pay_link"),
    assumes: ASSUMES,
    steps: [
      PAY_WEEK,
      RENEWAL_DUE,
      FIRE,
      { kind: "check", label: "renewal billed, link sent", checks: AWAITING_LINK },
      AWAITING_TIE_OUT,
      {
        kind: "human",
        ask: "pay_latest_link",
        say: "Open the renewal payment link below and pay it with the Stripe test card 4242 4242 4242 4242 (any future expiry, any CVC, any ZIP). Then press Continue.",
      },
      // The next run sees the extension paid and clears the latch.
      FIRE,
      {
        kind: "check",
        label: "renewal paid",
        checks: [
          { label: "the renewal reads paid", observe: "extensions.last.status", expect: "paid" },
          { label: "the latch is cleared", observe: "rental.auto_extend_pending", expect: false },
          { label: "the rental is active again", observe: "rental.auto_extend_status", expect: "active" },
          { label: "the return date moved 7 days", observe: "rental.end_date_moved_days", expect: 7 },
          { label: "received $700.00 in all", observe: "payments.received_cents", expect: { cents: 70000, math: "350.00 + 350.00 = 700.00" } },
        ],
      },
      RENEWED_TIE_OUT,
    ],
  },
  {
    id: "AE5",
    family: "auto_extend",
    title: "Pay-link renewal — never paid, grace runs out",
    why: "48 h after the customer was asked, an unpaid renewal pauses auto-extension. The week was never given, and the renewal stays owed.",
    tiers: ["live"],
    fixture: autoExtendWeekly("pay_link"),
    assumes: ASSUMES,
    steps: [
      PAY_WEEK,
      RENEWAL_DUE,
      FIRE,
      { kind: "check", label: "renewal billed, link sent", checks: AWAITING_LINK },
      // 3 days > the 48 h grace; the shift also ages the extension's created_at.
      { kind: "advance", domain: "auto_extend", days: 3 },
      FIRE,
      {
        kind: "check",
        label: "grace exhausted",
        checks: [
          { label: "auto-extension is paused", observe: "rental.auto_extend_paused", expect: true },
          { label: "the rental says paused", observe: "rental.auto_extend_status", expect: "paused" },
          { label: "the renewal is still unpaid", observe: "extensions.last.status", expect: "approved" },
          { label: "the week was never given", observe: "rental.end_date_moved_days", expect: 0 },
          { label: "only the booking's $350.00 was received", observe: "payments.received_cents", expect: { cents: 35000, math: "350.00 = 350.00" } },
        ],
      },
      AWAITING_TIE_OUT,
    ],
  },
  {
    id: "AE5b",
    family: "auto_extend",
    title: "Pay-link renewal — Stripe expires the link",
    why: "The Checkout Session expires (Stripe's own expiry, forced early in TEST mode). An expired link moves no money and must not end a rental the customer still has.",
    tiers: ["live"],
    fixture: autoExtendWeekly("pay_link"),
    assumes: ASSUMES,
    suspect: "The checkout.session.expired webhook is known to cancel rentals and to leave payments rows Pending (memory: ~3,900 stale Pending rows); whether it does so for a RENEWAL link is exactly what this run shows.",
    steps: [
      PAY_WEEK,
      RENEWAL_DUE,
      FIRE,
      { kind: "check", label: "renewal billed, link sent", checks: AWAITING_LINK },
      { kind: "expire_latest_link" },
      {
        kind: "check",
        label: "after the link expired",
        checks: [
          { label: "the rental is still Active", observe: "rental.status", expect: "Active" },
          { label: "no money moved", observe: "payments.received_cents", expect: { cents: 35000, math: "350.00 = 350.00" } },
          { label: "the renewal charges are unchanged", observe: "ledger.extension_charge_cents", expect: { cents: 35000, math: "1 × 350.00 = 350.00" } },
        ],
      },
      AWAITING_TIE_OUT,
    ],
  },
  {
    id: "AE6",
    family: "auto_extend",
    title: "Pause, then resume",
    why: "A paused rental is never selected; resuming (the portal's own patch) lets the next run renew it.",
    tiers: ["live"],
    fixture: autoExtendWeekly("auto_charge"),
    assumes: ASSUMES,
    steps: [
      PAY_WEEK,
      { kind: "pause_auto_extend" },
      RENEWAL_DUE,
      FIRE,
      {
        kind: "check",
        label: "paused: nothing happens",
        checks: [
          { label: "no renewal", observe: "extensions.count", expect: 0 },
          { label: "renewal count 0", observe: "rental.auto_extend_charge_count", expect: 0 },
          { label: "still paused", observe: "rental.auto_extend_paused", expect: true },
        ],
      },
      { kind: "resume_auto_extend" },
      FIRE,
      { kind: "check", label: "resumed: renewed", checks: RENEWED_BY_CARD },
      RENEWED_TIE_OUT,
    ],
  },
  {
    id: "AE7",
    family: "auto_extend",
    title: "Prepaid credit covers the renewal",
    why: "A customer already in credit for a week is renewed from that credit: no card charge, the renewal paid, Finances unchanged in total.",
    tiers: ["live"],
    fixture: autoExtendWeekly("auto_charge"),
    assumes: ASSUMES,
    liveBlockedBy:
      "sandbox-auto-extend-rentals has no prepaid-credit path. The real auto-extend-rentals applies Credit/Partial payments and the rental's Adjustment credit before it charges (its 'Apply prepaid credit to this renewal' block and the autoext_* RPCs); the clone was cut before that and would charge the card anyway, so a live run would prove nothing about credit. Port that block into the clone, then clear this flag — tests/e2e/runner-guards.test.ts pins both sides.",
    steps: [
      PAY_WEEK,
      // One week paid in cash in advance: no open charge to take it, so it sits as credit.
      { kind: "record_payment", amount: { cents: 35000, math: "1 × 350.00 = 350.00" }, method: "Cash", note: "E2E: a week paid in advance" },
      RENEWAL_DUE,
      FIRE,
      {
        kind: "check",
        label: "renewed from credit",
        checks: [
          { label: "one renewal", observe: "extensions.count", expect: 1 },
          { label: "it reads paid", observe: "extensions.last.status", expect: "paid" },
          { label: "the card was charged once — for the booking only", observe: "stripe.succeeded_intents", expect: 1 },
          { label: "received $700.00 (card + cash)", observe: "payments.received_cents", expect: { cents: 70000, math: "350.00 + 350.00 = 700.00" } },
        ],
      },
      RENEWED_TIE_OUT,
    ],
  },
];
