/**
 * The stated fixture rates, and the fixture rentals built from them.
 *
 * EVERY expected money value in this catalogue comes from the rates below,
 * by hand, with the arithmetic written next to it. If a rate changes here,
 * every derivation that uses it must be redone by a person — the L1 suite
 * re-evaluates each `math` string, so a stale one fails loudly.
 *
 *   BOOKING DAY RATE        $100.00 / day      (Daily rental, 3 days)
 *   EXTENSION DAY RATE      $100.00 / day      (the same daily rate, 2 extra days)
 *   AUTO-EXTEND WEEK RATE   $350.00 / week     (Weekly rental, renews weekly)
 *   PAYG DAY RATE           $40.00 / day       (pay-as-you-go, accrues daily)
 *   INSTALLMENT             3 × $200.00        ($600.00 booking)
 *   PAYMENT PLAN            $600.00 split 3 ways, weekly
 *   PREPAID CREDIT          $350.00            (one week of auto-extend)
 *
 *   Every fixture starts on the visa card (or none): sandbox-fixture-setup
 *   places a real TEST deposit hold on the card it mints, and a card that
 *   declines or demands authentication off-session would fail that hold. A
 *   scenario that needs a bad card swaps it in with a `swap_card` step.
 *
 *   Tax and service fee: OFF. The tenant must say so (`tax_off`,
 *   `service_fee_off`) wherever a job prices from the tenant's settings —
 *   the runner checks before it writes anything, and refuses rather than
 *   compare against a number it would have to recompute.
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import type { FixtureSpec } from "./types.ts";

/** A plain 3-day booking, owed in full today: one Rental charge. */
export const BOOKING_3_DAYS: FixtureSpec = {
  shape: "booking",
  periodType: "Daily",
  // $100.00 per day, the stated booking day rate.
  periodRate: { cents: 10000, math: "100.00 = 100.00", why: "the stated booking day rate" },
  startOffsetDays: 0,
  lengthDays: 3,
  charges: [
    // 3 days × $100.00 = $300.00, due on the start day (today), so it counts now.
    { category: "Rental", amount: { cents: 30000, math: "3 × 100.00 = 300.00" }, dueOffsetDays: 0 },
  ],
  card: "visa",
};

/**
 * A weekly rental that started 7 days ago and ends today, with auto-extension
 * ON. The first renewal is not yet due (next charge in 1 hour), so nothing
 * happens until the runner moves the clock.
 */
export function autoExtendWeekly(chargeMode: "auto_charge" | "pay_link"): FixtureSpec {
  return {
    shape: "auto_extend",
    periodType: "Weekly",
    // $350.00 per week, the stated auto-extend week rate.
    periodRate: { cents: 35000, math: "350.00 = 350.00", why: "the stated week rate" },
    startOffsetDays: -7,
    lengthDays: 7,
    charges: [
      // 1 week × $350.00 = $350.00, due on the start day (7 days ago).
      { category: "Rental", amount: { cents: 35000, math: "1 × 350.00 = 350.00" }, dueOffsetDays: 0 },
    ],
    card: "visa",
    autoExtend: { chargeMode, unit: "Weekly", intervalCount: 1, maxPeriods: null, firstChargeInHours: 1 },
  };
}

/** A pay-as-you-go rental at $40.00/day whose first day starts in 1 hour. No upfront charge. */
export const PAYG_DAILY: FixtureSpec = {
  shape: "payg",
  periodType: "Daily",
  // $40.00 per day, the stated PAYG day rate (rental_period_type Daily → daily rate = monthly_amount).
  periodRate: { cents: 4000, math: "40.00 = 40.00", why: "the stated PAYG day rate" },
  startOffsetDays: 0,
  lengthDays: 30,
  charges: [],
  card: "visa",
  payg: { startInHours: 1, reminderEveryDays: 1 },
};

/** A $600.00 booking paid in 3 weekly installments of $200.00, the first due tomorrow. */
export const INSTALLMENT_3_WEEKLY: FixtureSpec = {
  shape: "installment",
  periodType: "Weekly",
  // 3 weeks for $600.00 → $200.00 per week.
  periodRate: { cents: 20000, math: "600.00 / 3 = 200.00" },
  startOffsetDays: 0,
  lengthDays: 21,
  charges: [
    // 3 × $200.00 = $600.00, the whole booking, due on the start day.
    { category: "Rental", amount: { cents: 60000, math: "3 × 200.00 = 600.00" }, dueOffsetDays: 0 },
  ],
  card: "visa",
  installments: {
    count: 3,
    // $600.00 / 3 = $200.00 each.
    amount: { cents: 20000, math: "600.00 / 3 = 200.00" },
    firstDueOffsetDays: 1,
    everyDays: 7,
  },
};

/**
 * A $600.00 booking on a payment plan: weekly from tomorrow, 3 payments,
 * split evenly — the live twin of the memory scenarios' base fixture
 * (docs/PAYMENT_PLANS_DESIGN.md §10.1: 60000 split 3 × 20000).
 */
export function planWeekly3(): FixtureSpec {
  return {
    shape: "payment_plan",
    periodType: "Weekly",
    periodRate: { cents: 20000, math: "600.00 / 3 = 200.00" },
    startOffsetDays: 0,
    lengthDays: 21,
    charges: [
      // 3 × $200.00 = $600.00, owed today — what the plan splits.
      { category: "Rental", amount: { cents: 60000, math: "3 × 200.00 = 600.00" }, dueOffsetDays: 0 },
    ],
    card: "visa",
    plan: {
      anchorOffsetDays: 1,
      freq: "weekly",
      interval: 1,
      count: 3,
      collectionMethod: "auto_charge",
      fallbackToLink: true,
      reminderOffsets: [],
      occurrenceAmounts: [
        // $600.00 / 3 = $200.00, three times.
        { cents: 20000, math: "600.00 / 3 = 200.00" },
        { cents: 20000, math: "600.00 / 3 = 200.00" },
        { cents: 20000, math: "600.00 / 3 = 200.00" },
      ],
    },
  };
}
