/**
 * THE end-to-end scenario catalogue — one list, in the order the spec asks
 * for it (§6: "verify simple booking first", then extension, then auto
 * extension), then the payment-plan family and cron safety.
 *
 * docs/E2E_TESTING.md explains how each tier runs it. Nothing here runs
 * anything: it is data, steps and hand-derived expectations.
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { AUTO_EXTEND } from "./auto-extend.ts";
import { CRON_SAFETY } from "./cron-safety.ts";
import { INSTALLMENTS } from "./installments.ts";
import { MANUAL_EXTENSION } from "./manual-extension.ts";
import { PAYG } from "./payg.ts";
import { PAYMENT_PLANS } from "./payment-plans.ts";
import { SIMPLE_BOOKING } from "./simple-booking.ts";
import type { Scenario } from "./types.ts";

export const CATALOGUE: readonly Scenario[] = [
  ...SIMPLE_BOOKING,
  ...MANUAL_EXTENSION,
  ...AUTO_EXTEND,
  ...PAYG,
  ...INSTALLMENTS,
  ...PAYMENT_PLANS,
  ...CRON_SAFETY,
];

export function findScenario(id: string): Scenario | null {
  return CATALOGUE.find((s) => s.id === id) ?? null;
}

/** Can the live runner execute this scenario at all? (A tier, and nothing blocking it.) */
export function isLiveRunnable(s: Scenario): boolean {
  return s.tiers.includes("live") && !s.liveBlockedBy && s.fixture !== null;
}

/** A catalogue summary for the Developer tab — no functions, just data. */
export function catalogueSummary(): {
  id: string;
  family: string;
  title: string;
  why: string;
  tiers: string[];
  liveRunnable: boolean;
  liveBlockedBy: string | null;
  suspect: string | null;
  references: string[];
  stepCount: number;
  humanSteps: number;
}[] {
  return CATALOGUE.map((s) => ({
    id: s.id,
    family: s.family,
    title: s.title,
    why: s.why,
    tiers: [...s.tiers],
    liveRunnable: isLiveRunnable(s),
    liveBlockedBy: s.liveBlockedBy ?? null,
    suspect: s.suspect ?? null,
    references: [...(s.references ?? [])],
    stepCount: s.steps.length,
    humanSteps: s.steps.filter((st) => st.kind === "human").length,
  }));
}

export type { Scenario } from "./types.ts";
