/**
 * Manual extension — the operator's Extend action (spec §6 "then extension").
 *
 * The order today (roadmap A3, "manual-extension order"): the DATES move
 * first, then the Extension* ledger rows are written against the
 * rental_extensions row that create-extension-checkout returns, and the
 * customer is sent a link. The runner reproduces the Extend dialog's own row
 * writes (AdminExtendRentalDialog: the rentals date patch, then the
 * Extension Rental charge stamped with extension_id) and calls the real
 * create-extension-checkout; the link is paid — or not — by a person, in a
 * browser, with a Stripe test card, exactly as a customer would.
 *
 * Fixture: BOOKING_3_DAYS, booking paid first so the extension's bill stands
 * on its own. Extension: 2 days × $100.00 = $200.00, no tax (`tax_off`).
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { BOOKING_3_DAYS } from "./fixtures.ts";
import type { BillExpectation, Scenario, Step } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };

/** The booking bill once it is paid in full — the same in every scenario below. */
const BOOKING_PAID: BillExpectation = {
  label: "Booking",
  total: { cents: 30000, math: "3 × 100.00 = 300.00" },
  paid: { cents: 30000, math: "300.00 = 300.00" },
  credited: ZERO,
  balance: { cents: 0, math: "300.00 - 300.00 - 0.00 = 0.00" },
};

const PAY_BOOKING: Step = { kind: "charge_saved_card", amount: { cents: 30000, math: "3 × 100.00 = 300.00" }, note: "E2E: pay the booking in full" };

// 2 extra days × $100.00 = $200.00.
const EXTEND_2_DAYS: Step = { kind: "extend_manually", days: 2, amount: { cents: 20000, math: "2 × 100.00 = 200.00" } };

const AFTER_EXTEND: Step = {
  kind: "check",
  label: "dates first, charges on the extension",
  checks: [
    { label: "the return date moved 2 days BEFORE any payment", observe: "rental.end_date_moved_days", expect: 2 },
    { label: "one extension exists", observe: "extensions.count", expect: 1 },
    { label: "it is for 2 days", observe: "extensions.last.days", expect: 2 },
    { label: "Extension charges total $200.00", observe: "ledger.extension_charge_cents", expect: { cents: 20000, math: "2 × 100.00 = 200.00" } },
  ],
};

const UNPAID_TIE_OUT: Step = {
  kind: "tie_out",
  label: "extension sent, not paid",
  expect: {
    // 'Extension Rental' is not 'Rental', so the not-yet-due rule does not
    // defer it: the whole $200.00 counts now.
    outstanding: { cents: 20000, math: "0.00 + 200.00 = 200.00" },
    collected: { cents: 30000, math: "300.00 = 300.00" },
    bills: [
      BOOKING_PAID,
      {
        label: "Extension #1",
        total: { cents: 20000, math: "2 × 100.00 = 200.00" },
        paid: ZERO,
        credited: ZERO,
        balance: { cents: 20000, math: "200.00 - 0.00 - 0.00 = 200.00" },
      },
    ],
  },
};

export const MANUAL_EXTENSION: Scenario[] = [
  {
    id: "MX1",
    family: "manual_extension",
    title: "Extend by 2 days — the customer pays the link",
    why: "Dates first, then the Extension charges on their own bill, then the link; paying it settles only the extension's charges (FIFO extension isolation) and finalizes the extension.",
    tiers: ["live"],
    fixture: BOOKING_3_DAYS,
    assumes: ["usd", "tax_off", "service_fee_off"],
    steps: [
      PAY_BOOKING,
      EXTEND_2_DAYS,
      AFTER_EXTEND,
      UNPAID_TIE_OUT,
      {
        kind: "human",
        ask: "pay_latest_link",
        say: "Open the extension payment link below and pay it with the Stripe test card 4242 4242 4242 4242 (any future expiry, any CVC, any ZIP). Then press Continue.",
      },
      {
        kind: "check",
        label: "after the link is paid",
        checks: [
          { label: "the extension reads paid", observe: "extensions.last.status", expect: "paid" },
          { label: "received $500.00 in all", observe: "payments.received_cents", expect: { cents: 50000, math: "300.00 + 200.00 = 500.00" } },
          { label: "the return date is still +2 days", observe: "rental.end_date_moved_days", expect: 2 },
          { label: "nothing left on the ledger", observe: "ledger.remaining_cents", expect: { cents: 0, math: "500.00 - 500.00 = 0.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "extension paid",
        expect: {
          outstanding: { cents: 0, math: "200.00 - 200.00 = 0.00" },
          collected: { cents: 50000, math: "300.00 + 200.00 = 500.00" },
          bills: [
            BOOKING_PAID,
            {
              label: "Extension #1",
              total: { cents: 20000, math: "2 × 100.00 = 200.00" },
              paid: { cents: 20000, math: "200.00 = 200.00" },
              credited: ZERO,
              balance: { cents: 0, math: "200.00 - 200.00 - 0.00 = 0.00" },
            },
          ],
        },
      },
    ],
  },
  {
    id: "MX2",
    family: "manual_extension",
    title: "Extend by 2 days — the link is never paid",
    why: "The customer already has the days (dates moved first); the money stays owed on the extension's own bill and Finances says so.",
    tiers: ["live"],
    fixture: BOOKING_3_DAYS,
    assumes: ["usd", "tax_off", "service_fee_off"],
    steps: [
      PAY_BOOKING,
      EXTEND_2_DAYS,
      AFTER_EXTEND,
      {
        kind: "check",
        label: "the link exists and is unpaid",
        checks: [
          { label: "the extension is not paid", observe: "extensions.last.status", expect: "approved" },
          { label: "only the booking's $300.00 was received", observe: "payments.received_cents", expect: { cents: 30000, math: "300.00 = 300.00" } },
        ],
      },
      UNPAID_TIE_OUT,
    ],
  },
];
