/**
 * Payment plans — REFERENCED, not duplicated.
 *
 * S1–S19b (and Wave 3's S20–S26) live in
 * supabase/functions/_shared/payment-plans/scenarios.ts with their
 * hand-derived expectations (docs/PAYMENT_PLANS_DESIGN.md §10.1), and run
 * twice already: against the memory store and against real Postgres (PGlite),
 * in vitest and in the /dev simulator. This file names them so the catalogue
 * is complete, and adds the LIVE twins the northwind runner can exercise
 * against Stripe TEST: the happy path and the SCA → link path. Their fixture
 * is the design's base fixture moved to "tomorrow": $600.00 owed, weekly, 3 ×
 * $200.00, auto-charge with a link fallback.
 *
 * Plan fixtures need no parking: `advance payment_plan` and `tick_plan` run in
 * the same request, so an occurrence is never left due between requests for
 * the real run-payment-plans cron (not scheduled today) to find.
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { planWeekly3 } from "./fixtures.ts";
import type { BillExpectation, Scenario } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };

/**
 * Every id in _shared/payment-plans/scenarios.ts SCENARIOS, in its order:
 * S1–S19b (slice 1), and S20–S26 (Wave 3: renewals, insurance, agreement,
 * credit, shadow comparison). tests/e2e/runner-guards.test.ts fails when the
 * engine's list and this one differ — add the new id here, never a copy.
 */
export const PAYMENT_PLAN_REFERENCES = [
  "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9", "S10",
  "S11", "S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19a", "S19b",
  "S20", "S21", "S22", "S23a", "S23b", "S24", "S25", "S26",
] as const;

/** The booking bill after k of the three $200.00 occurrences are paid. */
function bookingAfter(paidCents: number, paidMath: string, balanceCents: number, balanceMath: string): BillExpectation {
  return {
    label: "Booking",
    total: { cents: 60000, math: "3 × 200.00 = 600.00" },
    paid: { cents: paidCents, math: paidMath },
    credited: ZERO,
    balance: { cents: balanceCents, math: balanceMath },
  };
}

export const PAYMENT_PLANS: Scenario[] = [
  {
    id: "PP-REF",
    family: "payment_plan",
    title: "Payment-plan engine scenarios S1–S26 (memory and PGlite)",
    why: "Every branch of the plan engine — retries, SCA, dead card, 5xx after charge, 409, double webhook, manual, early and partial payment, skip, move, plan change, refund, month-end/DST, pause, reminders, exhausted retries, reminder-vs-retry; and the renewal set (paid-then-move, declined renewal, give-the-days-now, insurance bought or refused, extension agreement, credit covering a period, shadow comparison) — each with its own hand-derived expectations. Run by `npx vitest run --config tests/vitest.config.ts tests/payment-plans/scenarios` and in the Developer tab's Payment plan simulator.",
    tiers: ["memory", "pglite"],
    fixture: null,
    steps: [],
    assumes: [],
    references: [...PAYMENT_PLAN_REFERENCES],
  },
  {
    id: "PP-L1",
    family: "payment_plan",
    title: "Live: three weekly card payments complete the plan (S1)",
    why: "The real engine, the real Supabase store and Stripe TEST: each occurrence is charged once, with key suffix :1, and the plan completes with nothing owed.",
    tiers: ["live"],
    fixture: planWeekly3(),
    assumes: ["usd"],
    references: ["S1"],
    steps: [
      {
        kind: "tie_out",
        label: "plan created, nothing paid",
        expect: {
          // The plan schedules money; it does not change what is owed: 3 × $200.00 = $600.00.
          outstanding: { cents: 60000, math: "3 × 200.00 = 600.00" },
          collected: ZERO,
          bills: [bookingAfter(0, "0.00 = 0.00", 60000, "600.00 - 0.00 - 0.00 = 600.00")],
        },
      },
      // Anchor is tomorrow 10:00 local; two days back makes it yesterday — due.
      { kind: "advance", domain: "payment_plan", days: 2 },
      { kind: "tick_plan" },
      {
        kind: "check",
        label: "occurrence 1 charged",
        checks: [
          { label: "1 paid, 2 and 3 scheduled", observe: "plan.occurrence_statuses", expect: ["paid", "scheduled", "scheduled"] },
          { label: "one attempt, key suffix 1:1", observe: "plan.attempt_keys_suffixes", expect: ["1:1"] },
          { label: "plan payments $200.00", observe: "plan.payment_cents", expect: { cents: 20000, math: "600.00 / 3 = 200.00" } },
        ],
      },
      { kind: "advance", domain: "payment_plan", days: 7 },
      { kind: "tick_plan" },
      { kind: "advance", domain: "payment_plan", days: 7 },
      { kind: "tick_plan" },
      {
        kind: "check",
        label: "all three charged",
        checks: [
          { label: "all paid", observe: "plan.occurrence_statuses", expect: ["paid", "paid", "paid"] },
          { label: "plan completed", observe: "plan.status", expect: "completed" },
          { label: "one key per occurrence", observe: "plan.attempt_keys_suffixes", expect: ["1:1", "2:1", "3:1"] },
          { label: "3 plan payments", observe: "plan.payment_count", expect: 3 },
          { label: "plan payments $600.00", observe: "plan.payment_cents", expect: { cents: 60000, math: "3 × 200.00 = 600.00" } },
          { label: "Stripe holds 3 succeeded charges", observe: "stripe.succeeded_intents", expect: 3 },
        ],
      },
      {
        kind: "tie_out",
        label: "plan complete",
        expect: {
          // Three charges of $200.00 = $600.00 paid; $600.00 − $600.00 = $0.00 owed.
          outstanding: { cents: 0, math: "600.00 - 600.00 = 0.00" },
          collected: { cents: 60000, math: "3 × 200.00 = 600.00" },
          bills: [bookingAfter(60000, "3 × 200.00 = 600.00", 0, "600.00 - 600.00 - 0.00 = 0.00")],
        },
      },
    ],
  },
  {
    id: "PP-L3",
    family: "payment_plan",
    title: "Live: the card needs authentication, the customer pays the link (S3)",
    why: "authentication_required is never retried on the card: the occurrence needs action, attempt 2 is a link, and paying it settles the occurrence with no further card attempt.",
    tiers: ["live"],
    fixture: planWeekly3(),
    assumes: ["usd"],
    references: ["S3"],
    steps: [
      { kind: "swap_card", card: "auth_required" },
      { kind: "advance", domain: "payment_plan", days: 2 },
      { kind: "tick_plan" },
      {
        kind: "check",
        label: "needs the customer",
        checks: [
          { label: "occurrence 1 requires action", observe: "plan.occurrence_statuses", expect: ["requires_action", "scheduled", "scheduled"] },
          { label: "attempt 1 the card, attempt 2 the link", observe: "plan.attempt_keys_suffixes", expect: ["1:1", "1:2"] },
          { label: "one card attempt on occurrence 1", observe: "plan.card_attempts_for_occurrence_1", expect: 1 },
          { label: "no plan payment yet", observe: "plan.payment_count", expect: 0 },
        ],
      },
      {
        kind: "human",
        ask: "pay_latest_link",
        say: "Open the payment-plan link below ($200.00) and pay it with the Stripe test card 4242 4242 4242 4242 (any future expiry, any CVC, any ZIP). Then press Continue.",
      },
      {
        kind: "check",
        label: "paid by link",
        checks: [
          { label: "occurrence 1 paid", observe: "plan.occurrence_statuses", expect: ["paid", "scheduled", "scheduled"] },
          { label: "plan payments $200.00", observe: "plan.payment_cents", expect: { cents: 20000, math: "600.00 / 3 = 200.00" } },
          { label: "still only one card attempt on occurrence 1", observe: "plan.card_attempts_for_occurrence_1", expect: 1 },
        ],
      },
      {
        kind: "tie_out",
        label: "one of three paid",
        expect: {
          // One occurrence paid by link: $600.00 − $200.00 = $400.00 still owed.
          outstanding: { cents: 40000, math: "600.00 - 200.00 = 400.00" },
          collected: { cents: 20000, math: "600.00 / 3 = 200.00" },
          bills: [bookingAfter(20000, "600.00 / 3 = 200.00", 40000, "600.00 - 200.00 - 0.00 = 400.00")],
        },
      },
    ],
  },
];
