/**
 * Simple booking — "verify simple booking first" (spec §6): the booking is
 * owed, the card on file pays it, and a refund gives some or all of it back.
 *
 * Fixture: BOOKING_3_DAYS — one Rental charge of $300.00 (3 × $100.00), due
 * today, and a Stripe TEST visa on the customer.
 *
 * Paths exercised, each the one the portal calls:
 *   charge-saved-card (then apply-payment, the portal's "recorded" callback)
 *   process-refund
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { BOOKING_3_DAYS } from "./fixtures.ts";
import type { Scenario } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };

export const SIMPLE_BOOKING: Scenario[] = [
  {
    id: "SB1",
    family: "simple_booking",
    title: "Pay a booking in full with the card on file",
    why: "The whole booking is owed; one charge on the saved card pays it; FIFO settles the Rental charge and Finances shows it paid.",
    tiers: ["live"],
    fixture: BOOKING_3_DAYS,
    assumes: ["usd"],
    steps: [
      {
        kind: "tie_out",
        label: "before payment",
        expect: {
          // Nothing paid: the $300.00 Rental charge is due today and counts.
          outstanding: { cents: 30000, math: "300.00 - 0.00 = 300.00" },
          collected: ZERO,
          bills: [{ label: "Booking", total: { cents: 30000, math: "3 × 100.00 = 300.00" }, paid: ZERO, credited: ZERO, balance: { cents: 30000, math: "300.00 - 0.00 = 300.00" } }],
        },
      },
      // $300.00 = the whole booking (3 × $100.00).
      { kind: "charge_saved_card", amount: { cents: 30000, math: "3 × 100.00 = 300.00" }, note: "E2E: pay the booking in full" },
      {
        kind: "check",
        label: "the card payment",
        checks: [
          { label: "one payment received", observe: "payments.received_count", expect: 1 },
          { label: "it is for $300.00", observe: "payments.received_cents", expect: { cents: 30000, math: "3 × 100.00 = 300.00" } },
          { label: "FIFO applied all of it", observe: "applications.cents", expect: { cents: 30000, math: "300.00 = 300.00" } },
          { label: "nothing left on the ledger", observe: "ledger.remaining_cents", expect: { cents: 0, math: "300.00 - 300.00 = 0.00" } },
          { label: "the payment reads Applied", observe: "payments.non_pending_statuses", expect: ["Applied"] },
        ],
      },
      {
        kind: "tie_out",
        label: "after payment",
        expect: {
          outstanding: { cents: 0, math: "300.00 - 300.00 = 0.00" },
          collected: { cents: 30000, math: "300.00 - 0.00 = 300.00" },
          bills: [
            {
              label: "Booking",
              total: { cents: 30000, math: "3 × 100.00 = 300.00" },
              paid: { cents: 30000, math: "300.00 = 300.00" },
              credited: ZERO,
              balance: { cents: 0, math: "300.00 - 300.00 - 0.00 = 0.00" },
            },
          ],
        },
      },
    ],
  },
  {
    id: "SB2",
    family: "simple_booking",
    title: "Full refund of a paid booking",
    why: "Refunding everything returns the money through Stripe, writes a Refund ledger row, and marks the payment Refunded — which Finances no longer counts as collected.",
    tiers: ["live"],
    fixture: BOOKING_3_DAYS,
    assumes: ["usd"],
    steps: [
      { kind: "charge_saved_card", amount: { cents: 30000, math: "3 × 100.00 = 300.00" }, note: "E2E: pay the booking in full" },
      // Refund all $300.00 of the Rental category.
      { kind: "refund", category: "Rental", amount: { cents: 30000, math: "300.00 = 300.00" }, refundType: "full" },
      {
        kind: "check",
        label: "after the refund",
        checks: [
          { label: "the payment carries a $300.00 refund", observe: "payments.refunded_cents", expect: { cents: 30000, math: "300.00 = 300.00" } },
          { label: "the payment reads Refunded", observe: "payments.non_pending_statuses", expect: ["Refunded"] },
          // process-refund writes a negative Refund row for the amount Stripe moved.
          { label: "a -$300.00 Refund row on the ledger", observe: "ledger.refund_row_cents", expect: { cents: -30000, math: "0.00 - 300.00 = -300.00" } },
          { label: "the Rental charge stays settled (a refund does not re-open it)", observe: "ledger.remaining_cents", expect: { cents: 0, math: "0.00 = 0.00" } },
          { label: "Stripe holds one succeeded charge", observe: "stripe.succeeded_intents", expect: 1 },
        ],
      },
      {
        kind: "tie_out",
        label: "after the full refund",
        expect: {
          outstanding: { cents: 0, math: "0.00 = 0.00" },
          // Refunded is not money received (lib/payment-status), so it adds nothing.
          collected: { cents: 0, math: "300.00 - 300.00 = 0.00" },
          bills: [
            {
              label: "Booking",
              total: { cents: 30000, math: "3 × 100.00 = 300.00" },
              // The allocation row survives the refund; Paid is what was applied.
              paid: { cents: 30000, math: "300.00 = 300.00" },
              credited: ZERO,
              balance: { cents: 0, math: "300.00 - 300.00 - 0.00 = 0.00" },
            },
          ],
        },
      },
    ],
  },
  {
    id: "SB3",
    family: "simple_booking",
    title: "Partial refund of a paid booking",
    why: "Refunding part leaves the payment Partial Refund; Finances collects the net and the bill still ties out.",
    tiers: ["live"],
    fixture: BOOKING_3_DAYS,
    assumes: ["usd"],
    steps: [
      { kind: "charge_saved_card", amount: { cents: 30000, math: "3 × 100.00 = 300.00" }, note: "E2E: pay the booking in full" },
      // Refund one day: $100.00.
      { kind: "refund", category: "Rental", amount: { cents: 10000, math: "1 × 100.00 = 100.00" }, refundType: "partial" },
      {
        kind: "check",
        label: "after the partial refund",
        checks: [
          { label: "the payment carries a $100.00 refund", observe: "payments.refunded_cents", expect: { cents: 10000, math: "1 × 100.00 = 100.00" } },
          { label: "the payment reads Partial Refund", observe: "payments.non_pending_statuses", expect: ["Partial Refund"] },
          { label: "a -$100.00 Refund row on the ledger", observe: "ledger.refund_row_cents", expect: { cents: -10000, math: "0.00 - 100.00 = -100.00" } },
          { label: "net received $200.00", observe: "payments.net_received_cents", expect: { cents: 20000, math: "300.00 - 100.00 = 200.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "after the partial refund",
        expect: {
          outstanding: { cents: 0, math: "0.00 = 0.00" },
          collected: { cents: 20000, math: "300.00 - 100.00 = 200.00" },
          bills: [
            {
              label: "Booking",
              total: { cents: 30000, math: "3 × 100.00 = 300.00" },
              paid: { cents: 30000, math: "300.00 = 300.00" },
              credited: ZERO,
              balance: { cents: 0, math: "300.00 - 300.00 - 0.00 = 0.00" },
            },
          ],
        },
      },
    ],
  },
];
