/**
 * End-to-end scenario catalogue — the types every scenario is written in.
 *
 * ONE catalogue (docs/E2E_TESTING.md), three consumers:
 *   - tests/e2e/*.test.ts            L1: the catalogue's shape, the guards, the
 *                                    tie-out arithmetic — offline, no network;
 *   - supabase/functions/e2e-runner  L2: the northwind live runner (Stripe TEST
 *                                    only, fixture rentals only) — started from
 *                                    the Developer tab;
 *   - the payment-plan memory/PGlite scenarios, which this catalogue REFERENCES
 *     by id (S1…S19b) instead of copying.
 *
 * EXPECTED VALUES ARE HAND-DERIVED. Every money expectation is a `Money`: an
 * integer-cents literal written by a person, with the arithmetic that produced
 * it in `math` (and in a comment above it). Nothing here computes an expected
 * value; the L1 suite re-evaluates each `math` string only to catch a typo in
 * the hand derivation.
 *
 * Runtime-agnostic: relative `./x.ts` imports only; no Deno.*, process.*,
 * window.* — the same files run in Node (vitest) and Deno (the runner).
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

/** Which of the five things in the product (spec §2), or the cron-safety set. */
export type Family =
  | "simple_booking"
  | "manual_extension"
  | "auto_extend"
  | "payg"
  | "installment"
  | "payment_plan"
  | "cron_safety";

/**
 * Where a scenario's evidence comes from.
 *   live   — the northwind runner: real rows in the production database for a
 *            flagged fixture rental, real Stripe TEST objects, the sandbox-*
 *            clones for cron work.
 *   memory — the payment-plan engine against its in-memory store (vitest and
 *            the /dev simulator).
 *   pglite — the payment-plan engine against real Postgres in WASM (vitest).
 */
export type Tier = "live" | "memory" | "pglite";

/**
 * Stripe's documented TEST tokens that ATTACH to a customer (the keys of
 * sandbox-fixture-setup's allow-list). `declined` is pm_card_chargeCustomerFail:
 * it attaches cleanly and then fails every off-session charge — a card that
 * worked when the rental started and stopped working later.
 */
export type TestCard = "visa" | "declined" | "auth_required";

/** A hand-derived amount. `math` is "<expression> = <dollars>", e.g. "3 × 100.00 = 300.00". */
export interface Money {
  cents: number;
  math: string;
  /** Why this is the number, in plain words, when `math` alone does not say. */
  why?: string;
}

/** Tenant settings an expected value depends on — checked before anything is written. */
export type TenantAssumption =
  | "tax_off" //                tenants.tax_enabled = false (or tax_percentage = 0)
  | "service_fee_off" //        tenants.service_fee_enabled = false (or value 0)
  | "usd" //                    tenants.currency_code = 'USD'
  | "auto_extend_grace_48h" //  tenants.auto_extend_grace_hours = 48
  | "auto_extend_retries_3" //  tenants.auto_extend_max_retries = 3
  | "payg_window_1_day" //      tenants.payg_accrual_window_seconds = 86400
  | "payg_reminders_on"; //     tenants.payg_auto_reminders_enabled = true

export type ChargeCategory = "Rental" | "Tax" | "Service Fee" | "Security Deposit";

export interface FixtureCharge {
  category: ChargeCategory;
  amount: Money;
  /** due_date = the fixture's start_date + this many days. */
  dueOffsetDays: number;
}

export type FixtureShape = "booking" | "auto_extend" | "payg" | "installment" | "payment_plan";

/**
 * The rental the runner creates for one run. Dates are RELATIVE to the run's
 * day in the tenant's timezone, so a run on any date means the same thing.
 */
export interface FixtureSpec {
  shape: FixtureShape;
  periodType: "Daily" | "Weekly" | "Monthly";
  /** rentals.monthly_amount — the per-period rate every job bills from. */
  periodRate: Money;
  /** start_date = run day + this many days (negative = already running). */
  startOffsetDays: number;
  /** end_date = start_date + this many days. */
  lengthDays: number;
  /** The booking's own ledger charges (type 'Charge'), written at creation. */
  charges: FixtureCharge[];
  /** The Stripe TEST card minted for the customer (sandbox-fixture-setup), or none. */
  card: TestCard | null;
  autoExtend?: {
    chargeMode: "auto_charge" | "pay_link";
    unit: "Daily" | "Weekly" | "Monthly";
    intervalCount: number;
    maxPeriods: number | null;
    /** auto_extend_next_charge_at = now + this many hours (the first renewal is not yet due). */
    firstChargeInHours: number;
  };
  payg?: {
    /** payg_start_ts = payg_next_accrual_at = now + this many hours. */
    startInHours: number;
    /** rentals.payg_reminder_interval_days (the per-rental override). */
    reminderEveryDays: number;
  };
  installments?: {
    count: number;
    amount: Money;
    /** Installment 1's due_date = run day + this many days. */
    firstDueOffsetDays: number;
    everyDays: number;
  };
  /** A payment plan created through payment-plan-manage, as the operator would. */
  plan?: {
    /** The anchor (occurrence 1) = run day + this many days, local. */
    anchorOffsetDays: number;
    freq: "weekly";
    interval: number;
    count: number;
    collectionMethod: "auto_charge" | "checkout_link" | "manual";
    fallbackToLink: boolean;
    /** [] keeps the fixture quiet: no reminder mail to the (undeliverable) fixture address. */
    reminderOffsets: number[];
    /** Hand-derived split: occurrence amounts, in order. */
    occurrenceAmounts: Money[];
  };
}

/** The time-shift domains (sim-control's manifest names; e2e_shift_fixture's allow-list). */
export type ShiftDomain = "payg" | "auto_extend" | "installment" | "payment_plan";

/** Sandbox clones the runner may fire, always with only_rental_id = the fixture. */
export type SandboxJob =
  | "sandbox-accrue-payg-charges"
  | "sandbox-send-payg-reminders"
  | "sandbox-auto-extend-rentals"
  | "sandbox-process-installment-payment";

/**
 * A named observation the runner can compute from the rows it reads for the
 * fixture rental (observe.ts). A closed vocabulary, so a typo is a shape-test
 * failure rather than an assertion that silently compares `undefined`.
 */
export type Observable =
  | "payments.received_count"
  | "payments.received_cents"
  | "payments.net_received_cents"
  | "payments.refunded_cents"
  | "payments.pending_link_count"
  | "payments.non_pending_statuses"
  | "ledger.charge_cents"
  | "ledger.remaining_cents"
  | "ledger.extension_charge_cents"
  | "ledger.refund_row_cents"
  | "applications.cents"
  | "extensions.count"
  | "extensions.last.status"
  | "extensions.last.days"
  | "extensions.last.total_cents"
  | "rental.status"
  | "rental.end_date_moved_days"
  | "rental.auto_extend_status"
  | "rental.auto_extend_paused"
  | "rental.auto_extend_failed_attempts"
  | "rental.auto_extend_charge_count"
  | "rental.auto_extend_pending"
  | "rental.auto_extend_retry_in_hours"
  | "payg.accrual_count"
  | "payg.open_accrual_cents"
  | "payg.accrual_statuses"
  | "installments.invoice_statuses"
  | "installments.failure_counts"
  | "plan.occurrence_statuses"
  | "plan.status"
  | "plan.attempt_keys_suffixes"
  | "plan.payment_count"
  | "plan.payment_cents"
  | "plan.card_attempts_for_occurrence_1"
  // PaymentIntents on the fixture's own Stripe TEST customer — every
  // card-on-file charge. A Checkout-paid link may carry no customer, so link
  // payments are counted from payments rows, never from these two.
  | "stripe.succeeded_intents"
  | "stripe.succeeded_intent_cents";

export interface Check {
  label: string;
  observe: Observable;
  /** A Money for any `*_cents` observable (hand-derived); a plain literal otherwise. */
  expect: Money | number | string | boolean | (string | number)[];
}

/** What Finances must show for the fixture's customer (docs/FINANCES_DESIGN.md §3). */
export interface BillExpectation {
  /** "Booking", or "Extension #n" (rental_extensions.sequence_number). */
  label: string;
  total: Money;
  paid: Money;
  credited: Money;
  balance: Money;
}

export interface FinanceExpectation {
  /** The Outstanding card: what the customer owes (apps/portal/src/lib/finances/balance.ts). */
  outstanding: Money;
  /** The Collected card: Σ max(0, amount − refund) over money actually received. */
  collected: Money;
  /** Every bill on the rental, and each must tie out: Total − Paid − Credited = Balance. */
  bills: BillExpectation[];
}

/**
 * One step. Operator steps call the SAME edge function the portal calls, with
 * the caller's own session; where the portal writes rows from the browser
 * (the Extend dialog, pause/resume, Add Payment) the runner writes exactly the
 * rows that screen writes, and says so in docs/E2E_TESTING.md.
 */
export type Step =
  | { kind: "charge_saved_card"; amount: Money; note: string }
  | { kind: "record_payment"; amount: Money; method: "Cash" | "Bank Transfer"; note: string }
  | { kind: "refund"; category: ChargeCategory; amount: Money; refundType: "full" | "partial" }
  | { kind: "extend_manually"; days: number; amount: Money }
  | { kind: "pause_auto_extend" }
  | { kind: "resume_auto_extend" }
  | { kind: "swap_card"; card: TestCard }
  | { kind: "advance"; domain: ShiftDomain; days: number }
  | { kind: "fire"; job: SandboxJob; copies?: 1 | 2 }
  | { kind: "tick_plan"; copies?: 1 | 2; ageAttemptsMinutes?: number }
  | { kind: "crash_after_charge" }
  | { kind: "expire_latest_link" }
  | { kind: "human"; ask: "pay_latest_link"; say: string }
  | { kind: "replay_webhook"; event: "checkout.session.completed" }
  | { kind: "check"; label: string; checks: Check[] }
  | { kind: "tie_out"; label: string; expect: FinanceExpectation };

export interface Scenario {
  id: string;
  family: Family;
  title: string;
  /** Which branch this proves, in plain words. */
  why: string;
  tiers: Tier[];
  /** Null only for a reference-only entry (payment-plan memory/PGlite scenarios). */
  fixture: FixtureSpec | null;
  steps: Step[];
  assumes: TenantAssumption[];
  /**
   * Set when the live runner must NOT run this today, with the reason. The
   * runner reports it as "not runnable", never as a pass.
   */
  liveBlockedBy?: string;
  /** For payment-plan references: ids in supabase/functions/_shared/payment-plans/scenarios.ts. */
  references?: string[];
  /** A known or suspected defect this scenario is expected to expose. Evidence decides. */
  suspect?: string;
}
