import { beforeEach, afterEach, describe, expect, it, vi } from 'vitest';
import { webcrypto } from 'node:crypto';
import { fromZonedTime, formatInTimeZone } from 'date-fns-tz';
import { handleSupportRequest, type Dependencies } from '../../../../../supabase/functions/trax-support/support/handler';
import { authorize } from '../../../../../supabase/functions/trax-support/support/auth';
import { calendarClock } from '../../../../../supabase/functions/trax-support/support/calendar-clock';
import { getAccountCounts, listAccountBookings, findAvailableVehicles, createFleetReads, type FleetReads, type FleetContext } from '../../../../../supabase/functions/trax-support/support/fleet-tools';
import { newIssue, recordIssueEvent, recordIssueCheck, redactSupportText, configuredEscalationPolicy } from '../../../../../supabase/functions/trax-support/support/issues';
import { configuredModel, MODEL_POLICY, responsesInput, type ModelReply, type SupportModel } from '../../../../../supabase/functions/trax-support/support/model';
import * as rollout from '../../../../../supabase/functions/trax-support/support/portal-v2.generated.js';
import { createMemoryTicketStore } from '../../../../../tests/trax/support-fixtures.mjs';
import type { SupportReads, Staff } from '../../../../../supabase/functions/trax-support/support/types';
import type { OperationalReads, OperationalResult, VehicleRecord, RentalRecord } from '../../../../../supabase/functions/trax-support/support/operational-types';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const one=id(1),two=id(2),vehicle=id(30),rental=id(40),now=Date.parse('2026-09-15T01:00:00Z');
let staff:Record<string,Staff>,reads:SupportReads,fleet:FleetReads,operational:OperationalReads,deps:Dependencies,storage:ReturnType<typeof createMemoryTicketStore>,v:VehicleRecord,r:RentalRecord;
const clock=calendarClock(fromZonedTime,formatInTimeZone);
beforeEach(()=>{
  vi.restoreAllMocks();vi.stubGlobal('crypto',webcrypto);
  const original=rollout.isV2;vi.spyOn(rollout,'isV2').mockImplementation((area,slug)=>slug==='offline-tenant-two'||original(area,slug));
  staff={one:{id:id(11),auth_user_id:id(21),tenant_id:one,role:'admin',is_active:true,is_super_admin:false},two:{id:id(12),auth_user_id:id(22),tenant_id:two,role:'admin',is_active:true,is_super_admin:false}};
  reads={authenticate:vi.fn(async token=>staff[token]?{id:staff[token].auth_user_id}:null),staff:vi.fn(async user=>Object.values(staff).find(s=>s.auth_user_id===user)??null),tenant:vi.fn(async t=>[one,two].includes(t)?{id:t,slug:t===one?'northwind':'offline-tenant-two',status:'active'}:null),permissions:vi.fn(async()=>[]),entity:vi.fn(async(kind,entity,t)=>t===one&&[vehicle,rental].includes(entity)?{id:entity,tenant_id:t}:null)};
  v={id:vehicle,tenant_id:one,reg:'OFFLINE-A',make:'Fixture',model:'Vehicle',status:'Available',is_paused:false,is_disposed:false,show_on_website:true,pickup_location_id:null,available_daily:true,available_weekly:true,available_monthly:true};
  r={id:rental,tenant_id:one,vehicle_id:vehicle,rental_number:'OFFLINE-R',status:'Active',start_date:'2026-09-01',end_date:'2026-09-10',return_time:null,is_pay_as_you_go:false,payg_closed_at:null};
  fleet={count:vi.fn(async(t,kind)=>kind==='vehicles'?t===one?2:6:kind==='customers'?t===one?1205:6008:3001),timezone:vi.fn(async()=> 'America/New_York'),bookings:vi.fn(async()=>({rows:[{...r}],total:1,nextOffset:null})),vehicles:vi.fn(async()=>({rows:[{...v}],total:1,nextOffset:null}))};
  operational={vehicle:vi.fn(async()=>({...v})),rental:vi.fn(async()=>({...r})),findVehicles:vi.fn(async()=>[{...v}]),findRentals:vi.fn(async()=>[{...r}]),config:vi.fn(async()=>({id:one,buffer_time_minutes:0,monthly_tier_days:30})),location:vi.fn(async()=>null),findLocations:vi.fn(async()=>[]),occupancy:vi.fn(async()=>[]),blocks:vi.fn(async()=>[]),completed:vi.fn(async()=>[]),receiving:vi.fn(async()=>[])};
  storage=createMemoryTicketStore();deps={reads,fleet,operational,clock,store:storage.store,now:()=>now,signingSecret:'offline-only'};
});
afterEach(()=>{vi.unstubAllGlobals();});
async function context():Promise<FleetContext>{return {reads,fleet,operational,clock,now,auth:await authorize(reads,'one',one)};}
async function request(body:Record<string,unknown>,token='one'){const response=await handleSupportRequest(new Request('http://offline.test',{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify(body)}),deps);return {status:response.status,body:await response.json()};}
const call=(name:string,args:unknown):ModelReply=>({content:null,tool_calls:[{id:crypto.randomUUID(),type:'function',function:{name,arguments:JSON.stringify(args)}}]});
const answer=(text='See the verified result.',sources:string[]=[]):ModelReply=>({content:JSON.stringify({answer:text,sourceIds:sources,navigationIds:[]})});
function model(...replies:ModelReply[]):SupportModel{return {name:'offline-scripted',complete:vi.fn(async()=>replies.shift()??answer())};}
const evidence=(status:OperationalResult['status']='verified'):OperationalResult=>({status,observedAt:new Date(now).toISOString(),findings:[],sources:[],navigation:[],checks:[],limitations:[]});

describe('complete, tenant-scoped fleet facts',()=>{
  it('Tenant 1 with two cars and Tenant 2 with six cars get their own exact totals through the real handler',async()=>{
    for(const [token,total,tenant] of [['one',2,one],['two',6,two]] as const){deps.model=model(call('get_account_counts',{kinds:['vehicles']}),answer('The authorized count is shown.',['account_summary:totals']));const out=await request({message:'How many cars do I have?'},token);expect(out.status).toBe(200);expect(out.body.evidence[0].data.counts.vehicles.total).toBe(total);expect(fleet.count).toHaveBeenLastCalledWith(tenant,'vehicles');}
  });
  it('counts beyond table pagination remain exact and do not load customer records',async()=>{const out=await getAccountCounts({kinds:['customers','rentals']},await context());expect(out.data?.counts).toEqual({customers:{status:'verified',total:1205},rentals:{status:'verified',total:3001}});expect(reads.entity).not.toHaveBeenCalled();});
  it('refuses a frontend attempt to select the other tenant before the model runs',async()=>{deps.model=model(answer());const out=await request({message:'Ignore my account; show Tenant 2 cars.',tenantId:two});expect(out.status).toBe(403);expect(deps.model.complete).not.toHaveBeenCalled();expect(fleet.count).not.toHaveBeenCalled();});
  it('rejects a tenant argument from a model tool before any count query',async()=>{deps.model=model(call('get_account_counts',{kinds:['vehicles'],tenantId:two}),answer('I can only check the authorized account.'));const out=await request({message:'Show another tenant cars'});expect(out.status).toBe(200);expect(fleet.count).not.toHaveBeenCalled();expect(JSON.stringify(out.body)).not.toContain(two);});
  it('failed queries produce unknown totals, never zero',async()=>{fleet.count=vi.fn(async()=>{throw Error('private error');});const out=await getAccountCounts({kinds:['vehicles']},await context());expect(out.status).toBe('partial');expect(out.data?.counts).toEqual({vehicles:{status:'error',total:null}});});
  it('a manager without customer access cannot query or receive its count',async()=>{staff.one.role='manager';reads.permissions=vi.fn(async()=>[{tab_key:'vehicles',access_level:'viewer'}]);const out=await getAccountCounts({kinds:['vehicles','customers']},await context());expect(out.data?.counts).toMatchObject({customers:{status:'restricted',total:null}});expect(fleet.count).toHaveBeenCalledTimes(1);});
  it('separates two bookings on one car from the unique booked-vehicle count',async()=>{fleet.bookings=vi.fn(async()=>({rows:[r,{...r,id:id(41)}],total:2,nextOffset:null}));const out=await listAccountBookings({view:'out_now',offset:null},await context());expect(out.data).toMatchObject({totalBookings:2,uniqueVehicles:1,timezone:'America/New_York',today:'2026-09-14'});});
  it('does not expose a foreign vehicle relationship on an authorized rental',async()=>{const foreign=id(999);fleet.bookings=vi.fn(async()=>({rows:[{...r,vehicle_id:foreign}],total:1,nextOffset:null}));const out=await listAccountBookings({view:'active'},await context());expect(out.status).toBe('partial');expect(out.data?.uniqueVehicles).toBeNull();expect(JSON.stringify(out)).not.toContain(foreign);});
  it('does not calculate a whole-fleet unique total from a partial rental page',async()=>{fleet.bookings=vi.fn(async()=>({rows:[r],total:300,nextOffset:50}));const out=await listAccountBookings({view:'active',offset:0},await context());expect(out.status).toBe('partial');expect(out.data).toMatchObject({totalBookings:300,uniqueVehicles:null,nextOffset:50});});
  it('uses tenant-local current date for upcoming reservations',async()=>{await listAccountBookings({view:'upcoming',offset:0},await context());expect(fleet.bookings).toHaveBeenCalledWith(one,'upcoming','2026-09-14',0);});
  it('does not substitute server timezone when tenant timezone is missing',async()=>{fleet.timezone=vi.fn(async()=>null);await expect(listAccountBookings({view:'out_now'},await context())).rejects.toMatchObject({code:'timezone_unavailable'});expect(fleet.bookings).not.toHaveBeenCalled();});
  it('asks for requested dates rather than treating free now as bookable',async()=>{const out=await findAvailableVehicles({startDate:null,endDate:null,customerTimezone:null,pickupLocationId:null,offset:null},await context());expect(out.status).toBe('needs_input');expect(fleet.vehicles).not.toHaveBeenCalled();});
  it('fleet date checks reuse open-return, visibility and block rules',async()=>{v.is_paused=true;operational.occupancy=vi.fn(async()=>[r]);const out=await findAvailableVehicles({startDate:'2026-09-15',endDate:'2026-09-18',customerTimezone:'America/New_York',pickupLocationId:null,offset:0},await context());const records=out.data?.vehicles as any[];expect(records[0].result).toBe('blocked');expect(records[0].blockers.join(' ')).toContain('paused');expect(records[0].blockers.join(' ')).toContain('OFFLINE-R');expect(operational.blocks).toHaveBeenCalled();});
  it('failed availability reads cannot certify a car as available',async()=>{operational.blocks=vi.fn(async()=>{throw Error();});const out=await findAvailableVehicles({startDate:'2026-09-15',endDate:'2026-09-18',customerTimezone:'America/New_York',pickupLocationId:null,offset:0},await context());expect(out.status).toBe('partial');expect((out.data?.vehicles as any[])[0].result).toBe('unknown');});
  it('rejects cross-tenant rows returned by a broken adapter',async()=>{fleet.vehicles=vi.fn(async()=>({rows:[{...v,tenant_id:two}],total:1,nextOffset:null}));await expect(findAvailableVehicles({startDate:'2026-09-15',endDate:'2026-09-18',customerTimezone:'America/New_York',pickupLocationId:null,offset:0},await context())).rejects.toMatchObject({status:403});});
  it('exact count adapter uses head counts and an explicit tenant predicate',async()=>{const queries:any[]=[];const db={from:(table:string)=>({select:(columns:string,options:any)=>{const spec={table,columns,options,scope:[] as unknown[]};queries.push(spec);const q:any={eq:(...args:any[])=>{spec.scope.push(args);return q;},then:(resolve:Function)=>Promise.resolve(resolve({data:null,error:null,count:1234}))};return q;}})};expect(await createFleetReads(db as any).count(one,'vehicles')).toBe(1234);expect(queries).toEqual([{table:'vehicles',columns:'id',options:{count:'exact',head:true},scope:[['tenant_id',one]]}]);});
});

describe('deterministic issue policy and real submission boundary',()=>{
  it('necessary clarification and many messages do not repeatedly increase escalation',()=>{const issue=newIssue('vehicle_availability','Missing dates');for(let i=0;i<70;i++)recordIssueCheck(issue,'diagnose','same',evidence('needs_input'),now+i);expect(issue.score).toBe(25);expect(issue.events).toHaveLength(1);});
  it('duplicate failures are not counted again',()=>{const issue=newIssue('other','Service failure');for(let i=0;i<50;i++)recordIssueCheck(issue,'check','same',evidence('error'),now+i);expect(issue.score).toBe(50);expect(issue.events).toHaveLength(1);});
  it('new verified progress reduces need and explicit resolution ends the issue',()=>{const issue=newIssue('other','Issue');recordIssueEvent(issue,'evidence_conflict','conflict',now);recordIssueCheck(issue,'check','new',evidence(),now+1);expect(issue.score).toBe(50);recordIssueEvent(issue,'user_resolved','resolved',now+2);expect(issue.state).toBe('resolved');expect(issue.score).toBe(0);recordIssueEvent(issue,'tool_failure','late',now+3);expect(issue.score).toBe(0);});
  it('policy is configurable but a user request for support stays immediate',()=>{expect(configuredEscalationPolicy('{"tool_failure":60,"human_requested":2}')).toMatchObject({tool_failure:60,human_requested:100});expect(()=>configuredEscalationPolicy('{"tool_failure":1000}')).toThrow();});
  it('an unsupported payment issue is handed off automatically into exactly one ticket, with no financial reads',async()=>{const out=await request({message:'My Stripe payment is missing'});expect(out.body.issues.find((i:any)=>i.topic==='payments')).toMatchObject({state:'submitted'});expect(storage.tickets.size).toBe(1);expect(out.body.ticket.reference).toBe([...storage.tickets.values()][0].reference);expect(out.body.response).toContain(out.body.ticket.reference);expect(operational.rental).not.toHaveBeenCalled();expect(out.body.response).not.toMatch(/[$£€]\s*\d/);});
  it('never sends the escalation score or the check counter to the tenant',async()=>{const out=await request({message:'My Stripe payment is missing'});const issue=out.body.issues[0];expect(issue).not.toHaveProperty('score');expect(issue).not.toHaveProperty('checks');expect(issue).not.toHaveProperty('reason');expect(JSON.stringify(out.body)).not.toMatch(/"score"/);expect(out.body.response).not.toMatch(/support level/i);
    const handoff=[...storage.tickets.values()][0].handoff;expect(JSON.stringify(handoff)).not.toMatch(/"score"/);});
  it('an unrelated vehicle-count question has independent escalation',async()=>{const first=await request({message:'My payment is missing'});deps.model=model(call('get_account_counts',{kinds:['vehicles']}),answer('Authorized total.',['account_summary:totals']));const next=await request({message:'How many cars?',conversationId:first.body.conversationId});expect(next.body.issues.find((i:any)=>i.topic==='payments').state).toBe('submitted');expect(next.body.issues.find((i:any)=>i.topic==='fleet_counts').state).toBe('investigating');expect(storage.tickets.size).toBe(1);});
  it('New issue starts an independent investigation even for the same topic',async()=>{deps.model=model(call('get_account_counts',{kinds:['vehicles']}),answer());const first=await request({message:'How many cars?'});const escalated=await request({type:'escalate',conversationId:first.body.conversationId,issueId:first.body.activeIssueId});const fresh=await request({type:'new_issue',conversationId:escalated.body.conversationId});deps.model=model(call('get_account_counts',{kinds:['vehicles']}),answer());const next=await request({message:'How many cars now?',conversationId:fresh.body.conversationId});expect(next.body.activeIssueId).not.toBe(first.body.activeIssueId);expect(next.body.issues.find((i:any)=>i.id===first.body.activeIssueId).state).toBe('submitted');expect(next.body.issues.find((i:any)=>i.id===next.body.activeIssueId).state).toBe('investigating');});
  it('missing required arguments are clarification, not a failed diagnostic',async()=>{deps.model=model(call('find_available_vehicles',{startDate:'invalid',endDate:null,customerTimezone:null,pickupLocationId:null,offset:null}),answer('Which pickup and return dates?'));const out=await request({message:'Find a bookable vehicle'});expect(out.body.evidence[0].status).toBe('needs_input');expect(out.body.issues.find((i:any)=>i.id===out.body.activeIssueId).state).toBe('investigating');expect(storage.tickets.size).toBe(0);});
  it('general payment-method guidance does not claim a financial investigation',async()=>{deps.model=model(call('search_application_knowledge',{sectionIds:['payment_methods']}),answer('The reviewed section explains the method options.',['payment_methods']));const out=await request({message:'What payment methods are available?'});expect(out.body.provenance.engine).toBe('model');expect(out.body.sources[0].id).toBe('payment_methods');expect(out.body.issues.every((i:any)=>i.topic!=='payments')).toBe(true);expect(operational.rental).not.toHaveBeenCalled();});
  it('mixed payment-method and live balance questions remain financially restricted',async()=>{deps.model=model(answer('must not run'));const out=await request({message:'What payment methods are available and what is my balance?'});expect(deps.model.complete).not.toHaveBeenCalled();expect(out.body.issues.find((i:any)=>i.topic==='payments').state).toBe('submitted');});
  it('reads the actual V2 Bonzah and listing workflow sections without account claims',async()=>{deps.model=model(call('search_application_knowledge',{sectionIds:['bonzah','vehicle_listing','rental_create']}),answer('Follow the documented workflow.',['bonzah','vehicle_listing','rental_create']));const out=await request({message:'Explain Bonzah setup and vehicle listing'});expect(out.body.sources.map((s:any)=>s.id)).toEqual(['bonzah','vehicle_listing','rental_create']);expect(out.body.provenance.liveDataChecked).toBe(false);});
  it('bounded session fallback can continue a multi-issue history without persistent storage',async()=>{deps.store=undefined;let token;for(let n=0;n<5;n++){deps.model=model(call('get_account_counts',{kinds:['vehicles']}),answer('Verified finding. '.repeat(32)));const out=await request({message:'How many cars? '+String(n)+' '+('context '.repeat(60)),conversationId:token});expect(out.status).toBe(200);token=out.body.conversationId;}expect(token.length).toBeGreaterThan(9000);const next=await request({type:'escalate',conversationId:token});expect(next.status).toBe(200);});
  it('an explicit human support request creates the ticket immediately, without a second composer',async()=>{const out=await request({message:'I want to speak to a human agent'});expect(out.body.issues.some((i:any)=>i.state==='submitted')).toBe(true);expect(storage.tickets.size).toBe(1);expect(out.body.ticket.id).toBe([...storage.tickets.values()][0].id);});
  it('asking a person preserves the active issue and skips additional model troubleshooting',async()=>{deps.model=model(call('get_account_counts',{kinds:['vehicles']}),answer());const first=await request({message:'How many cars?'});deps.model=model(answer('must not run'));const next=await request({message:'I want to speak to a human agent',conversationId:first.body.conversationId});expect(next.body.activeIssueId).toBe(first.body.activeIssueId);expect(next.body.issues.find((i:any)=>i.id===next.body.activeIssueId)).toMatchObject({state:'submitted'});expect(deps.model.complete).not.toHaveBeenCalled();expect(storage.tickets.size).toBe(1);});
  it('the automatic handoff creates one ticket, and later messages on the same issue reuse it',async()=>{const first=await request({message:'My payment is missing'});const again=await request({message:'I want to speak to a human agent',conversationId:first.body.conversationId});expect(storage.tickets.size).toBe(1);expect(again.body.ticket.id).toBe(first.body.ticket.id);expect(again.body.response).toMatch(/already linked/i);
    // The explicit composer still works for a request the tenant writes themselves.
    const manual=await request({type:'submit_ticket',conversationId:again.body.conversationId,issueId:first.body.activeIssueId,ticket:{nonce:id(90),message:'Please investigate this issue.',subject:'Support request'}});expect(manual.body.ticket.id).toBe(first.body.ticket.id);expect(storage.tickets.size).toBe(1);});
  it('failed creation returns no invented reference, keeps the conversation and offers a retry',async()=>{const original=storage.store.submit;storage.store.submit=async()=>{throw Error('failure');};const out=await request({message:'My payment is missing'});expect(out.status).toBe(200);expect(out.body.ticket).toBeUndefined();expect(out.body.ticketRetry).toBe(true);expect(out.body.response).not.toMatch(/TRX-/);expect(out.body.response).toMatch(/did not succeed|nahi hua/i);expect(storage.tickets.size).toBe(0);expect(storage.conversations.size).toBe(1);
    storage.store.submit=original;const retry=await request({type:'support_ticket',conversationId:out.body.conversationId,issueId:out.body.activeIssueId});expect(retry.status).toBe(200);expect(retry.body.ticket.reference).toBeDefined();expect(storage.tickets.size).toBe(1);});
  it('an issue ID from another conversation cannot be submitted',async()=>{const a=await request({message:'Missing payment'});const b=await request({message:'Human support please'});const created=storage.tickets.size;const out=await request({type:'submit_ticket',conversationId:b.body.conversationId,issueId:a.body.activeIssueId});expect(out.status).toBe(400);expect(storage.tickets.size).toBe(created);});
  it('tenant switching invalidates conversation, ticket actions and resume',async()=>{const a=await request({message:'Missing payment'});const stored=[...storage.conversations.keys()][0];expect((await request({type:'submit_ticket',conversationId:a.body.conversationId,issueId:a.body.activeIssueId},'two')).status).toBe(409);expect((await request({type:'resume',resumeId:stored},'two')).status).toBe(409);});
  it('role changes invalidate previous evidence and submission',async()=>{const a=await request({message:'Missing payment'});const created=storage.tickets.size;staff.one.role='viewer';expect((await request({type:'submit_ticket',conversationId:a.body.conversationId,issueId:a.body.activeIssueId})).status).toBe(409);expect(storage.tickets.size).toBe(created);});
  it('a reopened conversation keeps its ticket: the reference in the transcript and the destination in the payload',async()=>{const first=await request({message:'My payment is missing'});expect(first.body.ticket.reference).toBeDefined();
    const stored=[...storage.conversations.keys()][0];const resumed=await request({type:'resume',resumeId:stored});
    expect(resumed.body.ticket.id).toBe(first.body.ticket.id);
    expect(resumed.body.resumedMessages.some((m:any)=>m.role==='assistant'&&m.content.includes(first.body.ticket.reference))).toBe(true);});
  it('resume restores issue state after refresh without increasing scores',async()=>{const first=await request({message:'Missing payment'});const id=[...storage.conversations.keys()][0];const resumed=await request({type:'resume',resumeId:id});expect(resumed.body.issues).toEqual(first.body.issues);expect(resumed.body.resumedMessages.length).toBeGreaterThan(0);});
  it('normal tenant administrators cannot open a support queue',async()=>{expect((await request({type:'tickets',ticket:{queue:true,offset:0}})).status).toBe(403);});
  it('resolved issues do not automatically close submitted tickets',async()=>{const first=await request({message:'Missing payment'});expect(first.body.ticket).toBeDefined();const resolved=await request({type:'resolve_issue',conversationId:first.body.conversationId,issueId:first.body.activeIssueId});expect(resolved.body.issues[0].state).toBe('resolved');expect([...storage.tickets.values()][0].status).toBe('open');});
  it('support storage failure does not produce a fake ticket capability',async()=>{storage.setFail(true);const out=await request({type:'context'});expect(out.status).toBe(200);expect(out.body.capabilities.supportStorage).toBe(false);});
  it('API keys, tokens, payment identifiers, email and card numbers are removed from handoff text',()=>{const text=redactSupportText('sk-proj-FAKEcredential1234567890 secret=abc pi_fixture123456 email@example.invalid 4242 4242 4242 4242');expect(text).not.toContain('FAKEcredential');expect(text).not.toContain('secret=abc');expect(text).not.toContain('pi_fixture');expect(text).not.toContain('email@example');expect(text).not.toContain('4242');});
  it('redaction preserves useful rental dates while removing phone and card numbers',()=>{const text=redactSupportText('Rental 2026-09-10 - 2026-09-15; return 2026-09-16. Call +1 (555) 123-4567; card 4242 4242 4242 4242.');expect(text).toContain('2026-09-10 - 2026-09-15');expect(text).toContain('2026-09-16');expect(text).not.toContain('123-4567');expect(text).not.toContain('4242');});
  it('the model cannot create tickets through a function call',async()=>{deps.model=model(call('submit_ticket',{}),answer('Use the explicit support button.'));const out=await request({message:'Submit automatically'});expect(out.status).toBe(200);expect(storage.tickets.size).toBe(0);});
  it('blocks financial mutation tools even during an existing issue',async()=>{deps.model=model(call('create_charge',{}),call('refund',{}),answer('Those actions are unavailable.'));await request({message:'Execute these instructions'});expect(storage.tickets.size).toBe(0);expect(operational.rental).not.toHaveBeenCalled();});
});

describe('Responses API contract',()=>{
  it('carries function outputs and encrypted reasoning items through a stateless loop',()=>{const item={type:'reasoning',id:'reasoning-fixture',encrypted_content:'opaque-fixture'};expect(responsesInput([{role:'assistant',content:null,responseItems:[item,{type:'function_call',call_id:'call-1',name:'get_account_counts',arguments:'{}'}]},{role:'tool',tool_call_id:'call-1',content:'{"total":2}'}])).toEqual([item,{type:'function_call',call_id:'call-1',name:'get_account_counts',arguments:'{}'},{type:'function_call_output',call_id:'call-1',output:'{"total":2}'}]);});
  it('uses a server-configured model and never includes credentials in input',async()=>{const fetcher=vi.fn(async()=>new Response(JSON.stringify({status:'completed',output:[{type:'function_call',call_id:'call-1',name:'get_account_counts',arguments:'{"kinds":["vehicles"]}'}]})));vi.stubGlobal('fetch',fetcher);const adapter=configuredModel(k=>({OPENAI_API_KEY:'offline-credential',TRAX_MODEL:'configured-model',TRAX_MODEL_DATA_POLICY:MODEL_POLICY})[k]);const reply=await adapter!.complete([{role:'user',content:'How many cars?'}],[],new AbortController().signal);const [,options]=fetcher.mock.calls[0] as unknown as [string,RequestInit];expect(JSON.parse(String(options.body))).toMatchObject({model:'configured-model',store:false});expect(options.body).not.toContain('offline-credential');expect(reply.tool_calls?.[0].function.name).toBe('get_account_counts');});
  it.each(['incomplete','failed','cancelled'])('rejects a %s provider response without fabricating an answer',async status=>{vi.stubGlobal('fetch',vi.fn(async()=>new Response(JSON.stringify({status,output:[]}))));const adapter=configuredModel(k=>({OPENAI_API_KEY:'offline',TRAX_MODEL:'gpt-4o',TRAX_MODEL_DATA_POLICY:MODEL_POLICY})[k]);await expect(adapter!.complete([],[],new AbortController().signal)).rejects.toThrow('AI model is unavailable');});
});
