/**
 * Payment plans — what a provider's answer MEANS for the plan.
 *
 * Design §7's table, in code. Every charge outcome lands in exactly one class,
 * and the class alone decides the action (retry, fallback link, pause). The
 * codes are Stripe's (decline_code first, then the error code), from research
 * E2 B3. An unknown code is `opaque`: fail, never retry, send a link — the one
 * answer that can neither double-charge nor strand the occurrence.
 *
 * `customerSafeReason` is what a person is TOLD. Lost/stolen/fraud codes are
 * never shown to anyone — not the customer (it would tip off a fraudster that
 * the card is flagged) and not the operator (they would repeat it to the
 * customer). Both see a generic decline; the raw code stays on the attempt row
 * for support.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type { ChargeOutcome } from "./providers.ts";

export type ChargeClass =
  | "succeeded"
  | "needs_customer" // SCA: the customer must act → requires_action + link
  | "needs_new_card" // the card will never work again → failed, no retry, link
  | "retry_later" // the same card may work in a few days → failed + next_attempt_at
  | "transient" // the network hiccuped → failed + next_attempt_at = +1 h
  | "opaque" // the bank said no without saying why → failed, no retry, link
  | "integration_bug" // OUR mistake → failed, pause the plan, alert; never a customer email
  | "indeterminate" // 5xx / timeout: money may have moved → replay the SAME key
  | "in_use"; // 409 idempotency_key_in_use: another request holds the key → back off

const NEEDS_CUSTOMER = new Set([
  "authentication_required",
  "authentication_not_handled",
  "payment_intent_authentication_failure",
]);

const NEEDS_NEW_CARD = new Set([
  "expired_card",
  "incorrect_number",
  "invalid_number",
  "lost_card",
  "stolen_card",
  "pickup_card",
  "restricted_card",
  "revocation_of_all_authorizations",
  "revocation_of_authorization",
  "transaction_not_allowed",
  "card_not_supported",
  "currency_not_supported",
  "pin_try_exceeded",
  "payment_method_restricted",
  // Card data that cannot become right by waiting. Not in the design table by
  // name; they take the same action as `opaque` would (fail, link), so listing
  // them here only changes the reason an operator reads.
  "incorrect_cvc",
  "invalid_cvc",
  "invalid_expiry_month",
  "invalid_expiry_year",
  // The saved card or customer no longer exists on the account (deleted card,
  // detached payment method). A new card fixes it; pausing would not.
  "resource_missing",
  // Engine-generated: the plan has no card to charge.
  "no_payment_method",
]);

const RETRY_LATER = new Set([
  "insufficient_funds",
  "card_velocity_exceeded",
  "withdrawal_count_limit_exceeded",
  "card_decline_rate_limit_exceeded",
]);

const TRANSIENT = new Set([
  "processing_error",
  "issuer_not_available",
  "reenter_transaction",
  "approve_with_id",
  "try_again_later",
  "lock_timeout",
  "rate_limit",
]);

const INTEGRATION_BUG = new Set([
  "billing_invalid_mandate",
  "missing",
  "livemode_mismatch",
  "testmode_charges_only",
  "payment_intent_unexpected_state",
  "duplicate_transaction",
  // Same key, different parameters: a replay that is not a replay. Retrying
  // with a NEW key here is exactly how a customer gets charged twice.
  "idempotency_error",
  // Our request was malformed or our account cannot charge.
  "parameter_invalid_empty",
  "parameter_invalid_integer",
  "parameter_missing",
  "parameter_unknown",
  "amount_too_small",
  "amount_too_large",
  "account_invalid",
  "api_key_expired",
  "platform_api_key_expired",
  "secret_key_required",
  // Adapter-generated: Stripe rejected the request without a code, or the
  // tenant has no provider the engine may charge through (slice 1: Square,
  // or a live Own-Stripe tenant with no connected account).
  "invalid_request_error",
  "provider_not_supported",
]);

/** Codes nobody outside support may see, for customer and operator alike. */
const SENSITIVE = new Set([
  "lost_card",
  "stolen_card",
  "pickup_card",
  "fraudulent",
  "merchant_blacklist",
  "security_violation",
  "restricted_card",
]);

function lookup(code: string | null | undefined): ChargeClass | null {
  if (!code) return null;
  const c = code.toLowerCase();
  if (NEEDS_CUSTOMER.has(c)) return "needs_customer";
  if (NEEDS_NEW_CARD.has(c)) return "needs_new_card";
  if (RETRY_LATER.has(c)) return "retry_later";
  if (TRANSIENT.has(c)) return "transient";
  if (INTEGRATION_BUG.has(c)) return "integration_bug";
  if (c === "idempotency_key_in_use") return "in_use";
  return null;
}

/**
 * Class of a declined charge. The decline_code is the bank's reason and wins;
 * the error code (often just `card_declined`) is the fallback; anything
 * unrecognised is opaque.
 */
export function classifyDecline(declineCode: string | null | undefined, errorCode: string | null | undefined): ChargeClass {
  return lookup(declineCode) ?? lookup(errorCode) ?? "opaque";
}

/** Class of any charge outcome. */
export function classifyCharge(outcome: ChargeOutcome): ChargeClass {
  switch (outcome.kind) {
    case "succeeded":
      return "succeeded";
    case "indeterminate":
      return "indeterminate";
    case "in_use":
      return "in_use";
    case "declined":
      return classifyDecline(outcome.declineCode, outcome.errorCode);
    default:
      // An outcome shape we do not know is treated as "we do not know what
      // happened" — the one class that replays instead of charging anew.
      return "indeterminate";
  }
}

/** True for a code that must never be shown outside support. */
export function isSensitiveDeclineCode(code: string | null | undefined): boolean {
  return !!code && SENSITIVE.has(code.toLowerCase());
}

const GENERIC = "Your card was declined. Please use a different card or contact your bank.";

/**
 * One plain sentence for a declined payment, safe to show a customer AND an
 * operator. Never reveals a lost/stolen/fraud flag.
 */
export function customerSafeReason(declineCode: string | null | undefined, errorCode?: string | null): string {
  if (isSensitiveDeclineCode(declineCode) || isSensitiveDeclineCode(errorCode)) return GENERIC;
  const code = (declineCode || errorCode || "").toLowerCase();
  switch (code) {
    case "insufficient_funds":
      return "Your card has insufficient funds.";
    case "expired_card":
      return "Your card has expired. Please use a different card.";
    case "incorrect_number":
    case "invalid_number":
      return "The card number is not valid. Please use a different card.";
    case "incorrect_cvc":
    case "invalid_cvc":
      return "The card's security code was not accepted.";
    case "invalid_expiry_month":
    case "invalid_expiry_year":
      return "The card's expiry date was not accepted.";
    case "authentication_required":
    case "authentication_not_handled":
    case "payment_intent_authentication_failure":
      return "Your bank needs you to confirm this payment.";
    case "card_velocity_exceeded":
    case "withdrawal_count_limit_exceeded":
    case "card_decline_rate_limit_exceeded":
      return "Your card has reached a spending limit. Please try again later or use a different card.";
    case "card_not_supported":
    case "currency_not_supported":
    case "transaction_not_allowed":
      return "Your card does not support this type of payment. Please use a different card.";
    case "processing_error":
    case "issuer_not_available":
    case "try_again_later":
    case "reenter_transaction":
      return "Your bank could not be reached. The payment will be tried again.";
    case "no_payment_method":
    case "resource_missing":
      return "There is no saved card to charge.";
    default:
      return GENERIC;
  }
}
