/**
 * Payment plans — calendar arithmetic on 'YYYY-MM-DD' strings.
 *
 * WHY NOT `Date`. A plan's due date is a day on the OPERATOR's calendar, not
 * an instant. `new Date('2026-10-02')` is UTC midnight, which prints as
 * Oct 1 anywhere west of Greenwich, and `t += 7 * 86400000` turns "every
 * Friday" into "every Thursday" at the first DST change (measured, research
 * E1). So every calculation here runs on DAY NUMBERS — whole days since
 * 1970-01-01 — and `Date.UTC` is used only as a calendar (UTC has no DST, so a
 * day number maps to exactly one Y-M-D and back).
 *
 * Instants only appear at the two edges, and both go through the IANA
 * timezone database via `Intl.DateTimeFormat` (no libraries — this file runs
 * in Deno, Next and Node):
 *   - `localDateInZone(instant, tz)` — "what day is it for the operator now?"
 *   - `dueAtUtc(date, 'HH:MM', tz)`  — "when, as an instant, is 10:00 on that day?"
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type { ISODate, Weekday } from "./types.ts";
import { PlanRuleError } from "./errors.ts";

const MS_PER_DAY = 86_400_000;
const ISO_DATE = /^(\d{4})-(\d{2})-(\d{2})$/;
// 'HH:MM', or 'HH:MM:00' as Postgres prints a `time` column.
const HH_MM = /^([01]\d|2[0-3]):([0-5]\d)(?::00)?$/;

/** Split a 'YYYY-MM-DD' string, refusing anything that is not a real calendar day. */
export function parseISODate(date: ISODate): { y: number; m: number; d: number } {
  const match = typeof date === "string" ? ISO_DATE.exec(date) : null;
  if (!match) throw new RangeError(`Not a YYYY-MM-DD date: ${JSON.stringify(date)}`);
  const y = Number(match[1]);
  const m = Number(match[2]);
  const d = Number(match[3]);
  if (m < 1 || m > 12 || d < 1 || d > daysInMonth(y, m)) {
    // '2026-02-30' parses with Date.UTC (it rolls over to March 2) — a silent
    // rollover on a payment date would move money to a day nobody chose.
    throw new RangeError(`Not a real calendar day: ${date}`);
  }
  return { y, m, d };
}

/** True when `date` is a real 'YYYY-MM-DD' day. */
export function isISODate(date: unknown): date is ISODate {
  if (typeof date !== "string") return false;
  try {
    parseISODate(date);
    return true;
  } catch {
    return false;
  }
}

/** Days in month `m` (1-12) of year `y`, leap years included. */
export function daysInMonth(y: number, m: number): number {
  // Day 0 of the NEXT month is the last day of this one.
  return new Date(Date.UTC(y, m, 0)).getUTCDate();
}

/** Whole days since 1970-01-01 (negative before). */
export function toDayNumber(date: ISODate): number {
  const { y, m, d } = parseISODate(date);
  return Math.round(Date.UTC(y, m - 1, d) / MS_PER_DAY);
}

/** Inverse of toDayNumber. */
export function fromDayNumber(dayNumber: number): ISODate {
  if (!Number.isInteger(dayNumber)) throw new RangeError(`Day number must be an integer: ${dayNumber}`);
  const dt = new Date(dayNumber * MS_PER_DAY);
  return formatYMD(dt.getUTCFullYear(), dt.getUTCMonth() + 1, dt.getUTCDate());
}

export function formatYMD(y: number, m: number, d: number): ISODate {
  return `${String(y).padStart(4, "0")}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
}

export function addDays(date: ISODate, days: number): ISODate {
  if (!Number.isInteger(days)) throw new RangeError(`addDays needs whole days: ${days}`);
  return fromDayNumber(toDayNumber(date) + days);
}

/** Calendar days from `from` to `to` (to − from). */
export function diffDays(from: ISODate, to: ISODate): number {
  return toDayNumber(to) - toDayNumber(from);
}

/** −1, 0, 1. Zero-padded ISO dates compare correctly as strings; this also validates. */
export function compareDates(a: ISODate, b: ISODate): number {
  const da = toDayNumber(a);
  const db = toDayNumber(b);
  return da < db ? -1 : da > db ? 1 : 0;
}

/** ISO weekday: Monday = 1 … Sunday = 7. */
export function isoWeekday(date: ISODate): Weekday {
  const { y, m, d } = parseISODate(date);
  const js = new Date(Date.UTC(y, m - 1, d)).getUTCDay(); // 0 = Sunday
  return (js === 0 ? 7 : js) as Weekday;
}

/** The Monday of `date`'s ISO week (WKST=MO). */
export function mondayOf(date: ISODate): ISODate {
  return addDays(date, -(isoWeekday(date) - 1));
}

/**
 * The date `k` months after (y, m), on `day` CLAMPED to that month's length
 * (−1 = the last day). Always computed from the given month, never chained
 * from a previous result: chained addMonths turns the 31st into the 28th
 * forever after one February (design D4).
 */
export function monthlyDate(y: number, m: number, k: number, day: number): ISODate {
  const index = y * 12 + (m - 1) + k;
  const y2 = Math.floor(index / 12);
  const m2 = index - y2 * 12 + 1;
  const len = daysInMonth(y2, m2);
  const d2 = day === -1 ? len : Math.min(day, len);
  return formatYMD(y2, m2, d2);
}

// ─────────────────────────────────────────────────────────────────────────────
// Instants ↔ local calendar
// ─────────────────────────────────────────────────────────────────────────────

const partFormatters = new Map<string, Intl.DateTimeFormat>();

function formatterFor(timeZone: string): Intl.DateTimeFormat {
  let f = partFormatters.get(timeZone);
  if (!f) {
    // hourCycle h23, not hour12:false: some engines print midnight as "24"
    // under hour12:false, which would read as the NEXT day.
    f = new Intl.DateTimeFormat("en-US", {
      timeZone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hourCycle: "h23",
    });
    partFormatters.set(timeZone, f);
  }
  return f;
}

/** Wall-clock parts of `epochMs` in `timeZone`. Throws RangeError on an unknown zone. */
function wallParts(epochMs: number, timeZone: string) {
  const parts = formatterFor(timeZone).formatToParts(new Date(epochMs));
  const get = (type: string) => {
    const p = parts.find((x) => x.type === type);
    if (!p) throw new RangeError(`Intl did not return '${type}' for ${timeZone}`);
    return Number(p.value);
  };
  return { y: get("year"), m: get("month"), d: get("day"), hh: get("hour") % 24, mm: get("minute"), ss: get("second") };
}

function parseInstant(instantIso: string): number {
  const ms = Date.parse(instantIso);
  if (!Number.isFinite(ms)) throw new RangeError(`Not an ISO instant: ${JSON.stringify(instantIso)}`);
  return ms;
}

/** The calendar day an instant falls on in `timeZone` (IANA). */
export function localDateInZone(instantIso: string, timeZone: string): ISODate {
  const p = wallParts(parseInstant(instantIso), timeZone);
  return formatYMD(p.y, p.m, p.d);
}

/** Offset of `timeZone` from UTC at `epochMs`, in ms (local wall − UTC). */
function zoneOffsetMs(epochMs: number, timeZone: string): number {
  const p = wallParts(epochMs, timeZone);
  const wallAsUtc = Date.UTC(p.y, p.m - 1, p.d, p.hh, p.mm, p.ss);
  // Drop the sub-second part of epochMs so the difference is whole seconds.
  return wallAsUtc - Math.floor(epochMs / 1000) * 1000;
}

/**
 * Refuse charge times in 00:00–03:59. Every DST transition in the IANA
 * database that affects our tenants happens in that window, and a wall time
 * that does not exist (or exists twice) must never decide when a card is
 * charged.
 */
export function validateChargeTime(localTime: string): { hh: number; mm: number } {
  const match = typeof localTime === "string" ? HH_MM.exec(localTime) : null;
  if (!match) {
    throw new PlanRuleError("charge_time_invalid", `Charge time must be HH:MM, got ${JSON.stringify(localTime)}`);
  }
  const hh = Number(match[1]);
  const mm = Number(match[2]);
  if (hh < 4) {
    throw new PlanRuleError("charge_time_invalid", `Charge time ${localTime} is inside the 00:00–03:59 DST window`);
  }
  return { hh, mm };
}

/**
 * The UTC instant of `localTime` on `date` in `timeZone`, as an ISO string
 * with milliseconds ('2026-11-02T15:00:00.000Z').
 *
 * Two-pass offset resolution: guess the instant using the offset at the naive
 * UTC reading, then re-read the offset at the guess. The two agree except when
 * a transition falls between them, and the second answer is the one in force
 * at the local time (charge times are ≥ 04:00, after every transition).
 */
export function dueAtUtc(date: ISODate, localTime: string, timeZone: string): string {
  const { y, m, d } = parseISODate(date);
  const { hh, mm } = validateChargeTime(localTime);
  const naive = Date.UTC(y, m - 1, d, hh, mm, 0);
  const first = naive - zoneOffsetMs(naive, timeZone);
  const second = naive - zoneOffsetMs(first, timeZone);
  return new Date(second).toISOString();
}

/** True when `timeZone` is a zone this runtime's Intl knows. */
export function isValidTimeZone(timeZone: string): boolean {
  try {
    formatterFor(timeZone);
    return true;
  } catch {
    return false;
  }
}

/** Adds whole hours to an instant (retry back-off). */
export function addHoursToInstant(instantIso: string, hours: number): string {
  return new Date(parseInstant(instantIso) + hours * 3_600_000).toISOString();
}

/** Whole seconds from `earlierIso` to `laterIso`. */
export function secondsBetween(earlierIso: string, laterIso: string): number {
  return Math.floor((parseInstant(laterIso) - parseInstant(earlierIso)) / 1000);
}

/** −1, 0, 1 over two ISO instants (not dates). */
export function compareInstants(a: string, b: string): number {
  const da = parseInstant(a);
  const db = parseInstant(b);
  return da < db ? -1 : da > db ? 1 : 0;
}
