/**
 * Payment plans — typed errors.
 *
 * A rule an operator can get wrong (every weekday unticked, "after 0
 * payments", a 02:30 charge time) is a PlanRuleError with a `code` from
 * types.ts — the form shows the code's sentence next to the field. A shape
 * error a caller should never produce (a malformed date string, fractional
 * cents) is a plain RangeError: that is a bug in the caller, not a choice the
 * operator made.
 *
 * A store refusal (an illegal state transition, a stale plan version, a
 * second live plan on a rental) is a PlanStoreError. The SQL functions RAISE in
 * the same places; the Supabase store rethrows their message as one of these.
 *
 * Its own file so dates.ts and schedule.ts can both throw it without importing
 * each other.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type { PlanRuleErrorCode } from "./types.ts";

export class PlanRuleError extends Error {
  readonly code: PlanRuleErrorCode;
  constructor(code: PlanRuleErrorCode, message?: string) {
    super(message ?? code);
    this.name = "PlanRuleError";
    this.code = code;
  }
}

export type PlanStoreErrorCode =
  | "not_found"
  | "illegal_transition"
  | "version_conflict"
  | "plan_exists" // a second active/paused plan on one rental
  | "attempt_in_flight" // an operation that must wait for a card attempt to finish
  | "invalid_input"
  | "refused"; // a documented refusal (skip on the last occurrence, …)

export class PlanStoreError extends Error {
  readonly code: PlanStoreErrorCode;
  constructor(code: PlanStoreErrorCode, message: string) {
    super(message);
    this.name = "PlanStoreError";
    this.code = code;
  }
}
