/**
 * Payment plans — the in-memory store.
 *
 * The same contract as the pp_* SQL functions in
 * supabase/migrations/20260925120100_payment_plans.sql (design §5), held in
 * plain maps so the real engine can run in vitest and in the browser simulator
 * (/dev) without a database. It is only trusted because the parity suite runs
 * the same scenarios against the PGlite store (the real SQL) and the two
 * agree — so every method below mirrors ONE SQL function, and says which.
 * Where this file and the SQL disagree, the SQL is right and this file is the
 * bug.
 *
 * The rental's money is ONE number per rental, `owedCents` — what the rental
 * still owes after every payment (negative = unapplied credit, which the SQL
 * nets out in pp_rental_owed_cents). The real ledger's FIFO allocation is out
 * of scope here; `rentalOwedCents` is `max(0, owedCents)`.
 *
 * Occurrence state machine (design §6, trigger pp_trg_occurrence_guard):
 *   scheduled → due | paid | partially_paid | skipped | superseded | cancelled
 *   due       → processing | paid | partially_paid | requires_action | failed | skipped | superseded | cancelled
 *   processing→ paid | partially_paid | failed | requires_action | due
 *   requires_action → processing | paid | partially_paid | failed | due | skipped | superseded | cancelled
 *   partially_paid  → processing | paid | failed | requires_action | due | skipped | superseded | cancelled
 *   failed    → processing | due | paid | partially_paid | requires_action | skipped | superseded | cancelled
 *   paid      → partially_paid | due            (refunds only)
 *   skipped   → due                             (operator undo)
 *   superseded, cancelled, waived: terminal
 * Attempt state machine (trigger pp_trg_attempt_guard): claimed → anything;
 * in_flight → succeeded | failed | requires_action | indeterminate | abandoned;
 * indeterminate → succeeded | failed | requires_action | abandoned;
 * requires_action → succeeded | failed | abandoned; abandoned and failed →
 * succeeded only (late money is real money); succeeded is terminal.
 * Any other transition THROWS (PlanStoreError 'illegal_transition'), as the
 * triggers raise.
 *
 * The readings the SQL header lists as "deviations from the design text",
 * mirrored here:
 *   - only an auto_charge claim moves the occurrence to 'processing'; a link or
 *     manual claim is held by its attempt row alone, and that attempt's
 *     failure or release never moves the occurrence (S3, S4, S18);
 *   - a manual claim may take a 'scheduled' occurrence (S10);
 *   - collectDue returns partially_paid rows past due_at, and 'due' rows only
 *     once due_at has passed (S10, S12);
 *   - pp_claim refuses an auto_charge on an occurrence carrying a refunded
 *     payment (D12).
 *
 * Ids are deterministic (plan-1, occ-1, att-1, pay-1, evt-1, rev-1) so
 * evidence JSON is stable across runs.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type {
  AttemptRow,
  AttemptStatus,
  ClaimResult,
  ClockedStore,
  CollectionMethod,
  ISODate,
  LedgerFixture,
  OccurrenceDraft,
  OccurrenceRow,
  OccurrenceStatus,
  PlanEvent,
  PlanLookups,
  PlanOperations,
  PlanRow,
  PlanStore,
  RecordFailureInput,
  RecordSuccessInput,
} from "./types.ts";
import { PlanStoreError } from "./errors.ts";
import { addDays, compareInstants, dueAtUtc, isISODate, localDateInZone, secondsBetween } from "./dates.ts";

export const TRANSITIONS: Readonly<Record<OccurrenceStatus, readonly OccurrenceStatus[]>> = {
  scheduled: ["due", "paid", "partially_paid", "skipped", "superseded", "cancelled"],
  due: ["processing", "paid", "partially_paid", "requires_action", "failed", "skipped", "superseded", "cancelled"],
  processing: ["paid", "partially_paid", "failed", "requires_action", "due"],
  requires_action: ["processing", "paid", "partially_paid", "failed", "due", "skipped", "superseded", "cancelled"],
  partially_paid: ["processing", "paid", "failed", "requires_action", "due", "skipped", "superseded", "cancelled"],
  failed: ["processing", "due", "paid", "partially_paid", "requires_action", "skipped", "superseded", "cancelled"],
  paid: ["partially_paid", "due"],
  skipped: ["due"],
  superseded: [],
  cancelled: [],
  waived: [],
};

export const ATTEMPT_TRANSITIONS: Readonly<Record<AttemptStatus, readonly AttemptStatus[]>> = {
  claimed: ["in_flight", "succeeded", "failed", "requires_action", "indeterminate", "abandoned"],
  in_flight: ["succeeded", "failed", "requires_action", "indeterminate", "abandoned"],
  indeterminate: ["succeeded", "failed", "requires_action", "abandoned"],
  requires_action: ["succeeded", "failed", "abandoned"],
  abandoned: ["succeeded"],
  failed: ["succeeded"],
  succeeded: [],
};

export function canTransition(from: OccurrenceStatus, to: OccurrenceStatus): boolean {
  return from === to || TRANSITIONS[from].includes(to);
}

export function canAttemptTransition(from: AttemptStatus, to: AttemptStatus): boolean {
  return from === to || ATTEMPT_TRANSITIONS[from].includes(to);
}

/** Statuses a claim may start from (pp_claim); manual also takes 'scheduled'. */
export const CLAIMABLE: readonly OccurrenceStatus[] = ["due", "failed", "requires_action", "partially_paid"];
/** A plan whose occurrences are all here is complete (pp__maybe_complete_plan). */
export const DONE: readonly OccurrenceStatus[] = ["paid", "skipped", "waived", "superseded", "cancelled"];
/** Open and not held by a card charge: what operators act on, what reminders cover. */
export const OPEN: readonly OccurrenceStatus[] = ["scheduled", "due", "failed", "requires_action", "partially_paid"];
const TERMINAL: readonly OccurrenceStatus[] = ["superseded", "cancelled", "waived"];
const OPEN_ATTEMPT: readonly AttemptStatus[] = ["claimed", "in_flight"];
const STALE_CANDIDATE: readonly AttemptStatus[] = ["claimed", "in_flight", "indeterminate"];

export interface MemoryRental {
  id: string;
  tenantId: string;
  customerId: string;
  /** What the rental still owes, in cents. Negative = unapplied credit. */
  owedCents: number;
}

export interface MemoryPayment {
  id: string;
  tenantId: string;
  rentalId: string;
  customerId: string;
  occurrenceId: string | null;
  attemptId: string | null;
  amountCents: number;
  refundCents: number;
  status: "Completed" | "Partial Refund" | "Refunded";
  method: string;
  paymentDate: ISODate;
  paymentProvider: "stripe" | "square" | null;
  providerRef: string | null;
  providerAccount: string | null;
  providerMode: "test" | "live" | null;
  platformAccount: "uk" | "uae" | null;
  checkoutSessionId: string | null;
  bookingSource: "payment_plan" | "external";
  createdAt: string;
}

interface OccState extends OccurrenceRow {
  tenantId: string;
  linkTokenHash: string | null;
  movedFrom: ISODate | null;
  paidAt: string | null;
  note: string | null;
  createdAt: string;
  updatedAt: string;
}

interface AttemptState extends AttemptRow {
  tenantId: string;
  planId: string;
  createdAt: string;
  finishedAt: string | null;
  checkoutSessionId: string | null;
}

interface PlanState extends PlanRow {
  createdAt: string;
  updatedAt: string;
  pausedAt: string | null;
  cancelledAt: string | null;
  completedAt: string | null;
  createdBy: string | null;
}

export interface MemoryEvent extends PlanEvent {
  id: string;
  tenantId: string;
  createdAt: string;
}

export interface MemoryRevision {
  id: string;
  tenantId: string;
  planId: string;
  version: number;
  changedBy: string | null;
  reason: string;
  before: PlanRow;
  after: PlanRow;
  createdAt: string;
}

/** Everything in the store, as plain JSON-safe data (the UI's plan card and the evidence file read this). */
export interface MemorySnapshot {
  now: string;
  rentals: MemoryRental[];
  plans: PlanState[];
  occurrences: OccState[];
  attempts: AttemptState[];
  payments: MemoryPayment[];
  events: MemoryEvent[];
  revisions: MemoryRevision[];
}

export type FaultableOperation =
  | "claim"
  | "markInFlight"
  | "recordSuccess"
  | "recordFailure"
  | "setLinkToken"
  | "pausePlan"
  | "recordEvent";

/** pp_replace_future's patchable keys; anything else raises. */
const PATCHABLE = new Set([
  "rule",
  "amount",
  "currency",
  "timezone",
  "chargeLocalTime",
  "collectionMethod",
  "fallbackToLink",
  "maxAttempts",
  "retryAfterDays",
  "reminderOffsets",
  "paymentProvider",
  "stripePaymentMethodId",
  "extendsRental",
]);

const clone = <T>(v: T): T => JSON.parse(JSON.stringify(v)) as T;

// Every store method is `async`, so a refusal is a REJECTED promise — exactly
// what the Supabase store gives (supabase-js resolves, the adapter throws
// inside an async function). A synchronous throw would escape a caller's
// `.catch()` in the simulator and behave differently from production.

export class MemoryPlanStore implements PlanStore, PlanOperations, PlanLookups, LedgerFixture, ClockedStore {
  private clock: string;
  private readonly providerName: "stripe" | "square" | "simulated" | null;
  private readonly rentals = new Map<string, MemoryRental>();
  private readonly plans = new Map<string, PlanState>();
  private readonly occurrences = new Map<string, OccState>();
  private readonly attempts = new Map<string, AttemptState>();
  private readonly payments = new Map<string, MemoryPayment>();
  private readonly events: MemoryEvent[] = [];
  private readonly revisions: MemoryRevision[] = [];
  private readonly faults = new Map<FaultableOperation, string[]>();
  private readonly counters = { plan: 0, occ: 0, att: 0, pay: 0, evt: 0, rev: 0 };

  constructor(opts?: {
    rentals?: { id: string; tenantId: string; customerId: string; owedCents: number }[];
    /** The store's "now" until setNow is called. */
    now?: string;
    /**
     * attempt.provider for card and link attempts. Omitted = the plan's
     * payment_provider, exactly as pp_claim / pp_record_success write it. The
     * /dev simulator passes 'simulated' so the plan card says "Simulated in the
     * Developer tab" instead of looking for a dashboard link.
     */
    providerName?: "stripe" | "square" | "simulated";
  }) {
    this.clock = opts?.now ?? "2026-01-01T00:00:00.000Z";
    this.providerName = opts?.providerName ?? null;
    for (const r of opts?.rentals ?? []) this.addRental(r);
  }

  // ── clock & harness helpers ────────────────────────────────────────────────

  /** pp_clock(): every timestamp this store writes. */
  setNow(asOf: string): void {
    if (!Number.isFinite(Date.parse(asOf))) throw new RangeError(`setNow: not an instant: ${asOf}`);
    this.clock = new Date(asOf).toISOString();
  }

  now(): string {
    return this.clock;
  }

  addRental(r: { id: string; tenantId: string; customerId: string; owedCents: number }): void {
    if (!Number.isSafeInteger(r.owedCents)) throw new RangeError("owedCents must be whole cents");
    this.rentals.set(r.id, { id: r.id, tenantId: r.tenantId, customerId: r.customerId, owedCents: r.owedCents });
  }

  /** A new charge posted to the rental outside the plan (or a credit, negative). */
  adjustRentalOwed(rentalId: string, deltaCents: number): void {
    const rental = this.requireRental(rentalId);
    if (!Number.isSafeInteger(deltaCents)) throw new RangeError("deltaCents must be whole cents");
    rental.owedCents += deltaCents;
  }

  /**
   * Make the next `times` calls of `op` throw `message` BEFORE they change
   * anything — how the evidence reaches the compensation paths (a payment row
   * that cannot be written after the card was charged).
   */
  failNext(op: FaultableOperation, message = `Injected failure in ${op}`, times = 1): void {
    const q = this.faults.get(op) ?? [];
    for (let i = 0; i < times; i++) q.push(message);
    this.faults.set(op, q);
  }

  private fault(op: FaultableOperation): void {
    const q = this.faults.get(op);
    if (q && q.length > 0) throw new Error(q.shift()!);
  }

  listPayments(filter?: { rentalId?: string; occurrenceId?: string }): MemoryPayment[] {
    return clone(
      [...this.payments.values()].filter(
        (p) => (!filter?.rentalId || p.rentalId === filter.rentalId) && (!filter?.occurrenceId || p.occurrenceId === filter.occurrenceId),
      ),
    );
  }

  /** The occurrence a link token hash belongs to (what payment-plan-pay looks up). */
  findByLinkTokenHash(tokenHash: string): OccurrenceRow | null {
    for (const o of this.occurrences.values()) if (o.linkTokenHash === tokenHash) return this.toOccRow(o);
    return null;
  }

  snapshot(): MemorySnapshot {
    return clone({
      now: this.clock,
      rentals: [...this.rentals.values()],
      plans: [...this.plans.values()],
      occurrences: [...this.occurrences.values()].sort((a, b) => (a.planId === b.planId ? a.seq - b.seq : a.planId < b.planId ? -1 : 1)),
      attempts: [...this.attempts.values()],
      payments: [...this.payments.values()],
      events: this.events,
      revisions: this.revisions,
    });
  }

  // ── internals ──────────────────────────────────────────────────────────────

  private nextId(kind: keyof MemoryPlanStore["counters"]): string {
    this.counters[kind] += 1;
    return `${kind}-${this.counters[kind]}`;
  }

  private requireRental(id: string): MemoryRental {
    const r = this.rentals.get(id);
    if (!r) throw new PlanStoreError("not_found", `Rental ${id} not found`);
    return r;
  }
  private requirePlan(id: string): PlanState {
    const p = this.plans.get(id);
    if (!p) throw new PlanStoreError("not_found", `Plan ${id} not found`);
    return p;
  }
  private requireOcc(id: string): OccState {
    const o = this.occurrences.get(id);
    if (!o) throw new PlanStoreError("not_found", `Occurrence ${id} not found`);
    return o;
  }
  private requireAttempt(id: string): AttemptState {
    const a = this.attempts.get(id);
    if (!a) throw new PlanStoreError("not_found", `Attempt ${id} not found`);
    return a;
  }

  private occsOf(planId: string): OccState[] {
    return [...this.occurrences.values()].filter((o) => o.planId === planId).sort((a, b) => a.seq - b.seq);
  }

  private attemptsOf(occurrenceId: string): AttemptState[] {
    return [...this.attempts.values()].filter((a) => a.occurrenceId === occurrenceId);
  }

  private openAttempt(occurrenceId: string): AttemptState | undefined {
    return this.attemptsOf(occurrenceId).find((a) => OPEN_ATTEMPT.includes(a.status));
  }

  /** pp_trg_occurrence_guard: legal edges only; next_attempt_at survives only on 'failed'. */
  private setStatus(occ: OccState, to: OccurrenceStatus): void {
    if (!canTransition(occ.status, to)) {
      throw new PlanStoreError("illegal_transition", `payment_plan_occurrences: illegal transition ${occ.status} -> ${to} (occurrence ${occ.id})`);
    }
    occ.status = to;
    if (to !== "failed") occ.nextAttemptAt = null;
    occ.updatedAt = this.clock;
  }

  /** pp_trg_attempt_guard. */
  private setAttemptStatus(a: AttemptState, to: AttemptStatus): void {
    if (!canAttemptTransition(a.status, to)) {
      throw new PlanStoreError("illegal_transition", `payment_plan_attempts: illegal transition ${a.status} -> ${to} (attempt ${a.id})`);
    }
    a.status = to;
  }

  /** pp__event. Returns false on a dedupe hit. */
  private pushEvent(event: PlanEvent): boolean {
    const plan = this.requirePlan(event.planId);
    if (event.dedupeKey && this.events.some((e) => e.dedupeKey === event.dedupeKey)) return false;
    this.events.push({
      planId: event.planId,
      occurrenceId: event.occurrenceId ?? null,
      kind: event.kind,
      dedupeKey: event.dedupeKey ?? null,
      channel: event.channel ?? null,
      amountCents: event.amountCents ?? null,
      detail: event.detail ? clone(event.detail) : {},
      actorId: event.actorId ?? null,
      id: this.nextId("evt"),
      tenantId: plan.tenantId,
      createdAt: this.clock,
    });
    return true;
  }

  /** Σ (amount − refund) of the payments linked to an occurrence, floor 0 (pp_settle_occurrence). */
  private paidOn(occurrenceId: string): { paid: number; count: number } {
    let paid = 0;
    let count = 0;
    for (const p of this.payments.values()) {
      if (p.occurrenceId !== occurrenceId) continue;
      paid += p.amountCents - p.refundCents;
      count += 1;
    }
    return { paid: Math.max(0, paid), count };
  }

  /** pp_settle_occurrence. */
  private settle(occ: OccState): void {
    const { paid, count } = this.paidOn(occ.id);
    let target: OccurrenceStatus = occ.status;
    if (TERMINAL.includes(occ.status) || occ.status === "skipped") target = occ.status; // history rows never move
    else if (paid >= occ.amountCents) target = "paid";
    else if (paid > 0) target = "partially_paid";
    else if (count > 0 && (occ.status === "paid" || occ.status === "partially_paid")) target = "due"; // D12: re-opened, attempt_no kept
    this.setStatus(occ, target);
    occ.amountPaidCents = paid;
    occ.paidAt = target === "paid" ? occ.paidAt ?? this.clock : target === "due" || target === "partially_paid" ? null : occ.paidAt;
    this.maybeCompletePlan(occ.planId);
  }

  /** pp__maybe_complete_plan: never reopens a completed plan. */
  private maybeCompletePlan(planId: string): void {
    const plan = this.requirePlan(planId);
    if (plan.status !== "active" && plan.status !== "paused") return;
    const occs = this.occsOf(planId);
    if (!occs.every((o) => DONE.includes(o.status))) return;
    plan.status = "completed";
    plan.completedAt = this.clock;
    plan.updatedAt = this.clock;
    this.pushEvent({ planId, kind: "plan_completed", dedupeKey: `plan_completed:${planId}:${plan.version}`, detail: {} });
  }

  private toOccRow(o: OccState): OccurrenceRow {
    return {
      id: o.id,
      planId: o.planId,
      tenantId: o.tenantId,
      rentalId: o.rentalId,
      seq: o.seq,
      planVersion: o.planVersion,
      dueDate: o.dueDate,
      dueAt: o.dueAt,
      periodStart: o.periodStart,
      periodEnd: o.periodEnd,
      amountCents: o.amountCents,
      amountPaidCents: o.amountPaidCents,
      collectionMethod: o.collectionMethod,
      status: o.status,
      attemptNo: o.attemptNo,
      nextAttemptAt: o.nextAttemptAt,
      movedFrom: o.movedFrom,
      paidAt: o.paidAt,
      note: o.note,
    };
  }

  private toAttemptRow(a: AttemptState): AttemptRow {
    const { tenantId: _t, planId: _p, ...row } = a;
    return clone(row);
  }

  /** pp__plan_to_json. */
  private toPlanRow(p: PlanState): PlanRow {
    return clone({
      id: p.id,
      tenantId: p.tenantId,
      rentalId: p.rentalId,
      customerId: p.customerId,
      status: p.status,
      rule: p.rule,
      amount: p.amount,
      currency: p.currency,
      timezone: p.timezone,
      chargeLocalTime: p.chargeLocalTime,
      collectionMethod: p.collectionMethod,
      fallbackToLink: p.fallbackToLink,
      maxAttempts: p.maxAttempts,
      retryAfterDays: p.retryAfterDays,
      reminderOffsets: p.reminderOffsets,
      paymentProvider: p.paymentProvider,
      stripePaymentMethodId: p.stripePaymentMethodId,
      extendsRental: p.extendsRental,
      version: p.version,
    });
  }

  /** pp__insert_occurrences: at least one draft; seqs follow the plan's current maximum, in draft seq order. */
  private insertOccurrences(plan: PlanState, drafts: OccurrenceDraft[]): number {
    if (!Array.isArray(drafts) || drafts.length === 0) throw new PlanStoreError("invalid_input", "payment plan: at least one occurrence is required");
    for (const d of drafts) {
      if (!isISODate(d.dueDate)) throw new PlanStoreError("invalid_input", "occurrence draft: dueDate is required");
      if (!Number.isSafeInteger(d.amountCents) || d.amountCents < 1) {
        throw new PlanStoreError("invalid_input", `occurrence draft #${d.seq}: amount must be ≥ 1 cent`);
      }
    }
    // Validate every due_at before writing, so a bad zone/time leaves nothing behind.
    const dueAts = drafts.map((d) => dueAtUtc(d.dueDate, plan.chargeLocalTime, plan.timezone));
    const base = this.occsOf(plan.id).reduce((m, o) => Math.max(m, o.seq), 0);
    const ordered = drafts.map((d, i) => ({ d, i })).sort((a, b) => (a.d.seq ?? a.i + 1) - (b.d.seq ?? b.i + 1) || a.i - b.i);
    ordered.forEach(({ d, i }, n) => {
      const id = this.nextId("occ");
      this.occurrences.set(id, {
        id,
        planId: plan.id,
        tenantId: plan.tenantId,
        rentalId: plan.rentalId,
        seq: base + n + 1,
        planVersion: plan.version,
        dueDate: d.dueDate,
        dueAt: dueAts[i],
        periodStart: d.periodStart ?? null,
        periodEnd: d.periodEnd ?? null,
        amountCents: d.amountCents,
        amountPaidCents: 0,
        collectionMethod: plan.collectionMethod,
        status: "scheduled",
        attemptNo: 0,
        nextAttemptAt: null,
        linkTokenHash: null,
        movedFrom: null,
        paidAt: null,
        note: null,
        createdAt: this.clock,
        updatedAt: this.clock,
      });
    });
    return drafts.length;
  }

  // ── PlanStore ──────────────────────────────────────────────────────────────

  /** pp_collect_due. */
  async collectDue(asOf: string, filter?: { tenantId?: string; planId?: string }): Promise<OccurrenceRow[]> {
    const out: OccState[] = [];
    for (const plan of this.plans.values()) {
      if (plan.status !== "active") continue;
      if (filter?.tenantId && plan.tenantId !== filter.tenantId) continue;
      if (filter?.planId && plan.id !== filter.planId) continue;
      for (const occ of this.occsOf(plan.id)) {
        const dueNow = compareInstants(occ.dueAt, asOf) <= 0;
        if (occ.status === "scheduled" && dueNow) this.setStatus(occ, "due");
        if ((occ.status === "due" || occ.status === "partially_paid") && dueNow) out.push(occ);
        else if (occ.status === "failed" && occ.nextAttemptAt && compareInstants(occ.nextAttemptAt, asOf) <= 0) out.push(occ);
      }
    }
    out.sort((a, b) => compareInstants(a.dueAt, b.dueAt) || a.seq - b.seq);
    return Promise.resolve(out.map((o) => this.toOccRow(o)));
  }

  /** pp_get_plan. */
  async getPlan(planId: string): Promise<PlanRow | null> {
    const p = this.plans.get(planId);
    return Promise.resolve(p ? this.toPlanRow(p) : null);
  }

  /** pp_claim. */
  async claim(occurrenceId: string, method: CollectionMethod, providerAccount: string | null): Promise<ClaimResult> {
    this.fault("claim");
    if (!["auto_charge", "checkout_link", "manual"].includes(method)) throw new PlanStoreError("invalid_input", `pp_claim: unknown method ${method}`);
    const occ = this.requireOcc(occurrenceId);
    const plan = this.requirePlan(occ.planId);

    // One holder at a time.
    if (this.openAttempt(occ.id)) return Promise.resolve({ ok: false, reason: "held_elsewhere" });
    if (!(CLAIMABLE.includes(occ.status) || (occ.status === "scheduled" && method === "manual"))) {
      return Promise.resolve({ ok: false, reason: "not_claimable" });
    }
    // Only an active plan is collected; money may still be recorded against a
    // paused or completed one, never a cancelled one.
    if (plan.status === "cancelled" || (method !== "manual" && plan.status !== "active")) {
      return Promise.resolve({ ok: false, reason: "not_claimable" });
    }
    // D12: a refunded occurrence is never auto-charged again.
    if (method === "auto_charge" && [...this.payments.values()].some((p) => p.occurrenceId === occ.id && (p.refundCents > 0 || p.status !== "Completed"))) {
      return Promise.resolve({ ok: false, reason: "not_claimable" });
    }

    // D5: never more than the rental owes.
    const owed = this.owed(occ.rentalId);
    const remaining = Math.max(0, occ.amountCents - occ.amountPaidCents);
    const amount = Math.min(remaining, owed);
    if (amount <= 0) {
      this.setStatus(occ, "skipped");
      this.pushEvent({
        planId: occ.planId,
        occurrenceId: occ.id,
        kind: "covered_by_balance",
        dedupeKey: `covered_by_balance:${occ.id}`,
        amountCents: remaining,
        detail: { remainingCents: remaining, owedCents: owed },
      });
      this.maybeCompletePlan(occ.planId);
      return Promise.resolve({ ok: false, reason: "nothing_owed" });
    }

    const attemptNo = occ.attemptNo + 1;
    const account = providerAccount || null;
    const idempotencyKey = `pp:${account ?? "platform"}:${occ.id}:${attemptNo}`;
    const id = this.nextId("att");
    this.attempts.set(id, {
      id,
      occurrenceId: occ.id,
      attemptNo,
      method,
      idempotencyKey,
      status: "claimed",
      provider: method === "manual" ? "manual" : this.providerName ?? plan.paymentProvider,
      providerAccount: account,
      providerMode: null,
      providerRef: null,
      paymentId: null,
      amountCents: amount,
      declineCode: null,
      errorCode: null,
      errorMessage: null,
      tenantId: plan.tenantId,
      planId: plan.id,
      createdAt: this.clock,
      finishedAt: null,
      checkoutSessionId: null,
    });
    occ.attemptNo = attemptNo;
    // Only a card charge puts the occurrence in 'processing'.
    if (method === "auto_charge") this.setStatus(occ, "processing");
    occ.updatedAt = this.clock;
    return Promise.resolve({ ok: true, claim: { attemptId: id, attemptNo, idempotencyKey, amountCents: amount } });
  }

  /** pp_mark_in_flight. */
  async markInFlight(attemptId: string): Promise<void> {
    this.fault("markInFlight");
    const a = this.requireAttempt(attemptId);
    if (a.status !== "claimed") {
      throw new PlanStoreError("illegal_transition", `pp_mark_in_flight: attempt ${attemptId} is not claimed (status ${a.status})`);
    }
    this.setAttemptStatus(a, "in_flight");
    return Promise.resolve();
  }

  /** pp_record_success. */
  async recordSuccess(input: RecordSuccessInput): Promise<{ paymentId: string }> {
    this.fault("recordSuccess");
    const a = this.requireAttempt(input.attemptId);
    // Idempotent: a second delivery of the same success returns the first payment.
    if (a.status === "succeeded") return Promise.resolve({ paymentId: a.paymentId! });

    if (!Number.isSafeInteger(input.amountCents) || input.amountCents <= 0) {
      throw new PlanStoreError("invalid_input", `pp_record_success: amount must be positive cents (got ${input.amountCents})`);
    }
    // D5 at the money boundary: a card charge records exactly what was claimed.
    if (a.method === "auto_charge" && input.amountCents !== a.amountCents) {
      throw new PlanStoreError("invalid_input", `pp_record_success: attempt ${a.id} claimed ${a.amountCents} cents, provider reported ${input.amountCents}`);
    }
    if (input.paymentProvider !== "stripe" && input.paymentProvider !== "square") {
      throw new PlanStoreError("invalid_input", `pp_record_success: payment_provider must be stripe or square (got ${String(input.paymentProvider)})`);
    }
    if (input.paymentProvider === "square" && input.checkoutSessionId) {
      throw new PlanStoreError("invalid_input", "pp_record_success: a Square payment has no Stripe checkout session");
    }
    if (!input.method || !input.method.trim()) throw new PlanStoreError("invalid_input", "pp_record_success: method is required");
    if (!canAttemptTransition(a.status, "succeeded")) {
      throw new PlanStoreError("illegal_transition", `payment_plan_attempts: illegal transition ${a.status} -> succeeded (attempt ${a.id})`);
    }
    const occ = this.requireOcc(a.occurrenceId);
    const plan = this.requirePlan(occ.planId);
    const rental = this.requireRental(occ.rentalId);
    const card = a.method !== "manual";

    const paymentId = this.nextId("pay");
    this.payments.set(paymentId, {
      id: paymentId,
      tenantId: plan.tenantId,
      rentalId: plan.rentalId,
      customerId: plan.customerId,
      occurrenceId: occ.id,
      attemptId: a.id,
      amountCents: input.amountCents,
      refundCents: 0,
      status: "Completed",
      method: input.method,
      paymentDate: isISODate(input.paymentDate) ? input.paymentDate : localDateInZone(this.clock, plan.timezone),
      paymentProvider: input.paymentProvider,
      providerRef: card ? input.providerRef ?? null : null,
      providerAccount: input.providerAccount ?? null,
      providerMode: input.providerMode ?? null,
      platformAccount: input.platformAccount,
      checkoutSessionId: card ? input.checkoutSessionId ?? null : null,
      bookingSource: "payment_plan",
      createdAt: this.clock,
    });
    rental.owedCents -= input.amountCents;

    this.setAttemptStatus(a, "succeeded");
    a.paymentId = paymentId;
    a.provider = a.method === "manual" ? "manual" : this.providerName ?? input.paymentProvider;
    a.providerRef = input.providerRef ?? a.providerRef;
    a.providerAccount = a.providerAccount ?? (input.providerAccount || null);
    a.providerMode = input.providerMode ?? a.providerMode;
    a.checkoutSessionId = input.checkoutSessionId ?? a.checkoutSessionId;
    a.finishedAt = this.clock;
    // Not stored by the SQL (pp_record_success has no note/actor parameter);
    // kept here only so the simulator can show them.
    if (input.note) occ.note = input.note;

    this.settle(occ);
    this.pushEvent({
      planId: plan.id,
      occurrenceId: occ.id,
      kind: a.method === "manual" ? "manual_recorded" : "charge_succeeded",
      dedupeKey: `success:${a.id}`,
      amountCents: input.amountCents,
      actorId: input.actorId ?? null,
      detail: { attemptId: a.id, attemptNo: a.attemptNo, paymentId, method: input.method, providerRef: input.providerRef ?? null },
    });
    return Promise.resolve({ paymentId });
  }

  /** pp_record_failure. */
  async recordFailure(input: RecordFailureInput): Promise<void> {
    this.fault("recordFailure");
    if (!["failed", "requires_action", "indeterminate", "abandoned"].includes(input.status)) {
      throw new PlanStoreError("invalid_input", `pp_record_failure: unknown status ${String(input.status)}`);
    }
    const a = this.requireAttempt(input.attemptId);
    if (a.status === "succeeded") throw new PlanStoreError("illegal_transition", `pp_record_failure: attempt ${a.id} already succeeded`);
    if (!canAttemptTransition(a.status, input.status)) {
      throw new PlanStoreError("illegal_transition", `payment_plan_attempts: illegal transition ${a.status} -> ${input.status} (attempt ${a.id})`);
    }
    const occ = this.requireOcc(a.occurrenceId);

    // Only a card charge put the occurrence in 'processing'; only then does
    // its outcome move the occurrence. A failed or released link / manual
    // attempt changes the attempt alone.
    let target: OccurrenceStatus | null = null;
    if (occ.status === "processing") {
      target =
        input.status === "failed"
          ? "failed"
          : input.status === "requires_action"
            ? "requires_action"
            : input.status === "indeterminate"
              ? "processing" // recovery replays the same key
              : occ.amountPaidCents > 0
                ? "partially_paid"
                : "due";
      if (!canTransition(occ.status, target)) {
        throw new PlanStoreError("illegal_transition", `payment_plan_occurrences: illegal transition ${occ.status} -> ${target} (occurrence ${occ.id})`);
      }
    }

    this.setAttemptStatus(a, input.status);
    a.providerRef = input.providerRef ?? a.providerRef;
    a.declineCode = input.declineCode ?? a.declineCode;
    a.errorCode = input.errorCode ?? a.errorCode;
    a.errorMessage = input.errorMessage ?? a.errorMessage;
    if (input.status !== "indeterminate") a.finishedAt = this.clock;

    if (target) {
      this.setStatus(occ, target);
      occ.nextAttemptAt = target === "failed" ? input.nextAttemptAt ?? null : null;
    }
    return Promise.resolve();
  }

  /** pp_settle_occurrence. */
  async settleOccurrence(occurrenceId: string): Promise<OccurrenceRow> {
    const occ = this.requireOcc(occurrenceId);
    this.settle(occ);
    return Promise.resolve(this.toOccRow(occ));
  }

  /** pp_stale_attempts: created at or before as_of − lease. */
  async staleAttempts(olderThanSeconds: number, asOf: string): Promise<AttemptRow[]> {
    const out = [...this.attempts.values()]
      .filter((a) => STALE_CANDIDATE.includes(a.status) && a.method !== "checkout_link" && secondsBetween(a.createdAt, asOf) >= olderThanSeconds)
      .sort((a, b) => compareInstants(a.createdAt, b.createdAt) || (a.id < b.id ? -1 : 1));
    return Promise.resolve(out.map((a) => this.toAttemptRow(a)));
  }

  /** pp_record_event. */
  async recordEvent(event: PlanEvent): Promise<boolean> {
    this.fault("recordEvent");
    return Promise.resolve(this.pushEvent(event));
  }

  // ── PlanLookups ────────────────────────────────────────────────────────────

  async getOccurrence(occurrenceId: string): Promise<OccurrenceRow | null> {
    const o = this.occurrences.get(occurrenceId);
    return Promise.resolve(o ? this.toOccRow(o) : null);
  }

  async getAttempt(attemptId: string): Promise<AttemptRow | null> {
    const a = this.attempts.get(attemptId);
    return Promise.resolve(a ? this.toAttemptRow(a) : null);
  }

  // ── PlanOperations ─────────────────────────────────────────────────────────

  /** pp_create_plan. */
  async createPlan(input: { plan: Omit<PlanRow, "id" | "version" | "status">; occurrences: OccurrenceDraft[]; actorId?: string | null }): Promise<string> {
    const p = input.plan;
    const rental = this.requireRental(p.rentalId);
    if (rental.tenantId !== p.tenantId) throw new PlanStoreError("invalid_input", `pp_create_plan: rental ${p.rentalId} does not belong to tenant ${p.tenantId}`);
    if (rental.customerId !== p.customerId) throw new PlanStoreError("invalid_input", `pp_create_plan: rental ${p.rentalId} does not belong to customer ${p.customerId}`);
    for (const existing of this.plans.values()) {
      if (existing.rentalId === p.rentalId && (existing.status === "active" || existing.status === "paused")) {
        throw new PlanStoreError("plan_exists", `Rental ${p.rentalId} already has a live plan (${existing.id})`);
      }
    }
    const id = this.nextId("plan");
    const plan: PlanState = {
      ...clone(p),
      currency: (p.currency || "usd").toLowerCase(),
      id,
      status: "active",
      version: 1,
      createdAt: this.clock,
      updatedAt: this.clock,
      pausedAt: null,
      cancelledAt: null,
      completedAt: null,
      createdBy: input.actorId ?? null,
    };
    this.plans.set(id, plan);
    let n: number;
    try {
      n = this.insertOccurrences(plan, input.occurrences);
    } catch (e) {
      this.plans.delete(id); // one transaction
      this.counters.plan -= 1;
      throw e;
    }
    this.pushEvent({ planId: id, kind: "plan_created", actorId: input.actorId ?? null, detail: { occurrences: n, version: 1 } });
    return Promise.resolve(id);
  }

  /** pp_replace_future. */
  async replaceFuture(input: {
    planId: string;
    expectedVersion: number;
    planPatch: Partial<Omit<PlanRow, "id" | "tenantId" | "rentalId" | "customerId" | "version">>;
    occurrences: OccurrenceDraft[];
    actorId?: string | null;
    reason: string;
  }): Promise<number> {
    if (!input.reason || !input.reason.trim()) throw new PlanStoreError("invalid_input", "pp_replace_future: a reason is required");
    const plan = this.requirePlan(input.planId);
    if (plan.version !== input.expectedVersion) {
      throw new PlanStoreError("version_conflict", `pp_replace_future: version conflict on plan ${plan.id} (expected ${input.expectedVersion}, found ${plan.version})`);
    }
    if (plan.status !== "active" && plan.status !== "paused") throw new PlanStoreError("refused", `pp_replace_future: plan ${plan.id} is ${plan.status}`);
    const occs = this.occsOf(plan.id);
    if (occs.some((o) => o.status === "processing")) {
      throw new PlanStoreError("attempt_in_flight", `pp_replace_future: plan ${plan.id} has a charge in flight; try again when it settles`);
    }
    const patch = input.planPatch ?? {};
    for (const k of Object.keys(patch)) {
      if (!PATCHABLE.has(k)) throw new PlanStoreError("invalid_input", `pp_replace_future: field "${k}" cannot be patched`);
    }
    if (!Array.isArray(input.occurrences) || input.occurrences.length === 0) {
      throw new PlanStoreError("invalid_input", "payment plan: at least one occurrence is required");
    }
    const merged: PlanState = { ...plan, ...clone(patch) } as PlanState;
    // Validate the new drafts against the MERGED plan before anything moves.
    for (const d of input.occurrences) {
      if (!isISODate(d.dueDate)) throw new PlanStoreError("invalid_input", "occurrence draft: dueDate is required");
      dueAtUtc(d.dueDate, merged.chargeLocalTime, merged.timezone);
    }

    const before = this.toPlanRow(plan);
    const open = ["scheduled", "due", "failed", "requires_action", "partially_paid"];
    for (const o of occs) {
      if (!open.includes(o.status)) continue;
      // An open link or manual claim goes with its occurrence; a late payment
      // on it is still recordable (abandoned → succeeded).
      for (const a of this.attemptsOf(o.id)) {
        if (OPEN_ATTEMPT.includes(a.status)) {
          this.setAttemptStatus(a, "abandoned");
          a.finishedAt = this.clock;
          a.errorMessage = "superseded by a plan change";
        }
      }
      this.setStatus(o, "superseded");
    }
    Object.assign(plan, clone(patch), { version: plan.version + 1, updatedAt: this.clock });
    plan.currency = (plan.currency || "usd").toLowerCase();
    this.insertOccurrences(plan, input.occurrences);

    this.revisions.push({
      id: this.nextId("rev"),
      tenantId: plan.tenantId,
      planId: plan.id,
      version: plan.version,
      changedBy: input.actorId ?? null,
      reason: input.reason,
      before,
      after: this.toPlanRow(plan),
      createdAt: this.clock,
    });
    this.pushEvent({ planId: plan.id, kind: "plan_changed", actorId: input.actorId ?? null, detail: { version: plan.version, reason: input.reason } });
    return Promise.resolve(plan.version);
  }

  /** pp_pause_plan. */
  async pausePlan(planId: string, actorId?: string | null, reason?: string): Promise<void> {
    this.fault("pausePlan");
    const plan = this.requirePlan(planId);
    if (plan.status !== "active") throw new PlanStoreError("illegal_transition", `pp_pause_plan: plan ${planId} is not active`);
    plan.status = "paused";
    plan.pausedAt = this.clock;
    plan.updatedAt = this.clock;
    this.pushEvent({ planId, kind: "plan_paused", actorId: actorId ?? null, detail: { reason: reason ?? null } });
    return Promise.resolve();
  }

  /** pp_resume_plan. */
  async resumePlan(planId: string, actorId?: string | null, reason?: string): Promise<void> {
    const plan = this.requirePlan(planId);
    if (plan.status !== "paused") throw new PlanStoreError("illegal_transition", `pp_resume_plan: plan ${planId} is not paused`);
    plan.status = "active";
    plan.pausedAt = null;
    plan.updatedAt = this.clock;
    this.pushEvent({ planId, kind: "plan_resumed", actorId: actorId ?? null, detail: { reason: reason ?? null } });
    return Promise.resolve();
  }

  /** pp_cancel_plan. */
  async cancelPlan(planId: string, actorId?: string | null, reason?: string): Promise<void> {
    const plan = this.requirePlan(planId);
    const occs = this.occsOf(planId);
    if (occs.some((o) => o.status === "processing")) {
      throw new PlanStoreError("attempt_in_flight", `pp_cancel_plan: plan ${planId} has a charge in flight; try again when it settles`);
    }
    if (plan.status !== "active" && plan.status !== "paused") throw new PlanStoreError("illegal_transition", `pp_cancel_plan: plan ${planId} is not active or paused`);
    plan.status = "cancelled";
    plan.cancelledAt = this.clock;
    plan.updatedAt = this.clock;
    for (const o of occs) {
      for (const a of this.attemptsOf(o.id)) {
        if (OPEN_ATTEMPT.includes(a.status)) {
          this.setAttemptStatus(a, "abandoned");
          a.finishedAt = this.clock;
          a.errorMessage = "plan cancelled";
        }
      }
    }
    for (const o of occs) if (OPEN.includes(o.status)) this.setStatus(o, "cancelled");
    this.pushEvent({ planId, kind: "plan_cancelled", actorId: actorId ?? null, detail: { reason: reason ?? null } });
    return Promise.resolve();
  }

  /** pp_move_occurrence. */
  async moveOccurrence(occurrenceId: string, to: ISODate, actorId?: string | null): Promise<void> {
    if (!isISODate(to)) throw new PlanStoreError("invalid_input", "pp_move_occurrence: a date is required");
    const occ = this.requireOcc(occurrenceId);
    if (!OPEN.includes(occ.status)) throw new PlanStoreError("refused", `pp_move_occurrence: occurrence ${occurrenceId} is ${occ.status}`);
    const plan = this.requirePlan(occ.planId);
    const from = occ.dueDate;
    const at = dueAtUtc(to, plan.chargeLocalTime, plan.timezone);
    occ.movedFrom = occ.movedFrom ?? from;
    occ.dueDate = to;
    occ.dueAt = at;
    // A failed occurrence moved to a date is retried on that date.
    occ.nextAttemptAt = occ.status === "failed" ? at : null;
    occ.updatedAt = this.clock;
    this.pushEvent({ planId: plan.id, occurrenceId, kind: "occurrence_moved", actorId: actorId ?? null, detail: { from, to } });
    return Promise.resolve();
  }

  /** pp_skip_occurrence. */
  async skipOccurrence(occurrenceId: string, actorId?: string | null): Promise<void> {
    const occ = this.requireOcc(occurrenceId);
    if (!OPEN.includes(occ.status)) throw new PlanStoreError("refused", `pp_skip_occurrence: occurrence ${occurrenceId} is ${occ.status}`);
    if (this.openAttempt(occ.id)) throw new PlanStoreError("attempt_in_flight", `pp_skip_occurrence: occurrence ${occurrenceId} has an open attempt`);
    const next = this.occsOf(occ.planId).find((o) => o.seq > occ.seq && OPEN.includes(o.status));
    if (!next) {
      throw new PlanStoreError("refused", `pp_skip_occurrence: occurrence ${occurrenceId} is the last open occurrence; its amount has nowhere to go`);
    }
    const remaining = Math.max(0, occ.amountCents - occ.amountPaidCents);
    next.amountCents += remaining;
    next.updatedAt = this.clock;
    this.setStatus(occ, "skipped");
    this.pushEvent({
      planId: occ.planId,
      occurrenceId,
      kind: "occurrence_skipped",
      actorId: actorId ?? null,
      amountCents: remaining,
      detail: { rolledInto: next.id, rolledIntoSeq: next.seq },
    });
    return Promise.resolve();
  }

  /** pp_set_method. */
  async setMethod(occurrenceId: string, method: CollectionMethod, actorId?: string | null): Promise<void> {
    if (!["auto_charge", "checkout_link", "manual"].includes(method)) throw new PlanStoreError("invalid_input", `pp_set_method: unknown method ${method}`);
    const occ = this.requireOcc(occurrenceId);
    if (!OPEN.includes(occ.status)) throw new PlanStoreError("refused", `pp_set_method: occurrence ${occurrenceId} is ${occ.status}`);
    const from = occ.collectionMethod;
    occ.collectionMethod = method;
    occ.updatedAt = this.clock;
    this.pushEvent({ planId: occ.planId, occurrenceId, kind: "plan_changed", actorId: actorId ?? null, detail: { occurrenceMethod: { from, to: method } } });
    return Promise.resolve();
  }

  /** pp_set_link_token. No event: link_sent is the engine's to write, after the link is sent. */
  async setLinkToken(occurrenceId: string, tokenHash: string): Promise<void> {
    this.fault("setLinkToken");
    if (!tokenHash || !tokenHash.trim()) throw new PlanStoreError("invalid_input", "pp_set_link_token: a token hash is required");
    const occ = this.requireOcc(occurrenceId);
    for (const o of this.occurrences.values()) {
      if (o.id !== occ.id && o.linkTokenHash === tokenHash) throw new PlanStoreError("invalid_input", "duplicate key value violates unique constraint on link_token_hash");
    }
    occ.linkTokenHash = tokenHash;
    occ.updatedAt = this.clock;
    return Promise.resolve();
  }

  /** pp_set_payment_method. */
  async setPaymentMethod(planId: string, paymentMethodId: string): Promise<void> {
    if (!paymentMethodId || !paymentMethodId.trim()) throw new PlanStoreError("invalid_input", "pp_set_payment_method: a payment method id is required");
    const plan = this.requirePlan(planId);
    plan.stripePaymentMethodId = paymentMethodId;
    plan.updatedAt = this.clock;
    this.pushEvent({ planId, kind: "plan_changed", detail: { paymentMethodSaved: true } });
    return Promise.resolve();
  }

  async listOccurrences(planId: string): Promise<OccurrenceRow[]> {
    return Promise.resolve(this.occsOf(planId).map((o) => this.toOccRow(o)));
  }

  async listAttempts(filter: { planId?: string; occurrenceId?: string }): Promise<AttemptRow[]> {
    const out = [...this.attempts.values()].filter(
      (a) => (!filter.planId || a.planId === filter.planId) && (!filter.occurrenceId || a.occurrenceId === filter.occurrenceId),
    );
    return Promise.resolve(out.map((a) => this.toAttemptRow(a)));
  }

  async listEvents(planId: string): Promise<(PlanEvent & { id: string; createdAt: string })[]> {
    return Promise.resolve(clone(this.events.filter((e) => e.planId === planId)).map(({ tenantId: _t, ...e }) => e));
  }

  /** pp_list_for_reminders: open, not processing, due_date within ±horizon of the plan-local today. */
  async listForReminders(asOf: string, horizonDays: number, filter?: { tenantId?: string; planId?: string }): Promise<OccurrenceRow[]> {
    const out: OccState[] = [];
    const h = Math.max(0, horizonDays);
    for (const plan of this.plans.values()) {
      if (plan.status !== "active") continue;
      if (filter?.tenantId && plan.tenantId !== filter.tenantId) continue;
      if (filter?.planId && plan.id !== filter.planId) continue;
      const today = localDateInZone(asOf, plan.timezone);
      const lo = addDays(today, -h);
      const hi = addDays(today, h);
      for (const o of this.occsOf(plan.id)) {
        if (!OPEN.includes(o.status)) continue;
        if (o.dueDate < lo || o.dueDate > hi) continue;
        out.push(o);
      }
    }
    out.sort((a, b) => compareInstants(a.dueAt, b.dueAt) || a.seq - b.seq);
    return Promise.resolve(out.map((o) => this.toOccRow(o)));
  }

  private owed(rentalId: string): number {
    return Math.max(0, this.requireRental(rentalId).owedCents);
  }

  /** pp_rental_owed_cents. */
  async rentalOwedCents(rentalId: string): Promise<number> {
    return Promise.resolve(this.owed(rentalId));
  }

  // ── LedgerFixture ──────────────────────────────────────────────────────────

  async recordExternalPayment(rentalId: string, amountCents: number, paymentDate: ISODate): Promise<string> {
    const rental = this.requireRental(rentalId);
    if (!Number.isSafeInteger(amountCents) || amountCents < 1) throw new PlanStoreError("invalid_input", "amount must be ≥ 1 cent");
    if (!isISODate(paymentDate)) throw new PlanStoreError("invalid_input", `Bad payment date ${paymentDate}`);
    const id = this.nextId("pay");
    this.payments.set(id, {
      id,
      tenantId: rental.tenantId,
      rentalId,
      customerId: rental.customerId,
      occurrenceId: null,
      attemptId: null,
      amountCents,
      refundCents: 0,
      status: "Completed",
      method: "External",
      paymentDate,
      paymentProvider: null,
      providerRef: null,
      providerAccount: null,
      providerMode: null,
      platformAccount: null,
      checkoutSessionId: null,
      bookingSource: "external",
      createdAt: this.clock,
    });
    rental.owedCents -= amountCents;
    return Promise.resolve(id);
  }

  async refundPayment(paymentId: string, amountCents: number): Promise<void> {
    const p = this.payments.get(paymentId);
    if (!p) throw new PlanStoreError("not_found", `Payment ${paymentId} not found`);
    if (!Number.isSafeInteger(amountCents) || amountCents < 1 || p.refundCents + amountCents > p.amountCents) {
      throw new PlanStoreError("invalid_input", "Refund must be ≥ 1 cent and no more than what is left of the payment");
    }
    p.refundCents += amountCents;
    p.status = p.refundCents >= p.amountCents ? "Refunded" : "Partial Refund";
    this.requireRental(p.rentalId).owedCents += amountCents;
    // D12: the linked occurrence re-opens (paid → due / partially_paid) with
    // attempt_no untouched, and pp_claim now refuses to auto-charge it.
    if (p.occurrenceId) this.settle(this.requireOcc(p.occurrenceId));
    return Promise.resolve();
  }
}
