/**
 * Payment plans — RENEWALS: open-ended plans that extend the rental (Wave 3,
 * spec §4 "the green line"; roadmap assumptions A3, A4, A5).
 *
 * One renewal period = one existing-shaped extension (a rental_extensions row
 * + Extension* ledger charges), priced exactly as auto-extend prices a period
 * (renewal-pricing.ts), posted by pp_post_renewal_period and collected by the
 * ordinary claim / charge / link / manual path. When the period is PAID the
 * live finalize_rental_extension moves the rental's end date inside
 * pp_record_success (A3). See supabase/migrations/20260926120200_open_ended_plans.sql.
 *
 * The engine's renewal stage (runRenewalStage) runs in every tick, after
 * recovery and BEFORE reminders — so a reminder already quotes a period's
 * final price, insurance included — in this order, per plan:
 *   1. RECONCILE: a posted period whose charges were settled outside the plan
 *      (credit, an operator's payment on the rental) is paid; its end date moves.
 *   2. APPEND: a renewal plan whose last period is settled gets the NEXT period
 *      (horizon: the next period only) — never two open periods ahead, so an
 *      unpaid period blocks the next one, as auto-extend's parked week does.
 *   3. POST: a period within RENEWAL_POST_LEAD_DAYS of its due date is posted.
 *      Posting ahead is what lets its insurance start on the period's first
 *      night: Bonzah cannot start a policy before tomorrow (Pacific).
 *   4. INSURE (A4): a posted period whose cover is still undecided is insured
 *      BEFORE it can be charged (pp_claim refuses it until then). Bought →
 *      the premium joins the period. Bonzah cannot cover it → NO premium and
 *      an operator alert. A transient failure retries on later ticks until the
 *      period falls due, then gives up the same way — never a premium without
 *      a policy.
 * Then the tick's normal due work charges the period.
 *
 * The operator's Extend (extendPlan) posts N periods now — "give the days now"
 * (the end date moves at once) or "when paid" (A3) — and records whether an
 * extension agreement goes out (A5; the portal sends it through /api/esign).
 *
 * Runtime-agnostic, like every file in this directory: relative sibling
 * imports only; no Deno.*, process.*, window.*.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type {
  ISODate,
  OccurrenceDraft,
  OccurrenceRow,
  PlanLookups,
  PlanOperations,
  PlanRenewal,
  PlanRow,
  PlanStore,
  PostRenewalResult,
  RenewalCoverage,
  RenewalOperations,
  RenewalPeriodUnit,
  RenewalPricingInputs,
} from "./types.ts";
import type { InsureOutcome, Notification, Notifier, RenewalInsurer } from "./providers.ts";
import { addDays, compareDates, compareInstants, diffDays, localDateInZone } from "./dates.ts";
import { hasCoverage, renewalBreakdownCents, renewalPeriod } from "./renewal-pricing.ts";
import { PlanStoreError } from "./errors.ts";

/** Post a renewal period this many days before it falls due (the −2 reminder's day). */
export const RENEWAL_POST_LEAD_DAYS = 2;
/** The most periods one Extend may add. */
export const MAX_EXTEND_PERIODS = 12;

export type RenewalStore = PlanStore & PlanOperations & PlanLookups & RenewalOperations;

export interface RenewalDeps {
  store: RenewalStore;
  notifier: Notifier;
  insurer?: RenewalInsurer | null;
}

/** Does this store carry the renewal operations? (A store without them skips the stage.) */
export function storeHasRenewals(store: unknown): store is RenewalStore {
  const s = store as Partial<RenewalOperations> | null;
  return (
    !!s &&
    typeof s.listRenewalPlans === "function" &&
    typeof s.renewalPricing === "function" &&
    typeof s.appendRenewalPeriod === "function" &&
    typeof s.postRenewalPeriod === "function" &&
    typeof s.recordRenewalInsurance === "function" &&
    typeof s.reconcileRenewals === "function"
  );
}

export type InsuranceResultKind = "insured" | "not_insurable" | "failed" | "retry_later" | "none";

export interface InsuranceResult {
  occurrenceId: string;
  outcome: InsuranceResultKind;
  premiumCents?: number;
  policyRef?: string;
  coveredFrom?: ISODate;
  coveredTo?: ISODate;
  reason?: string;
}

export interface RenewalStageResult {
  reconciled: string[];
  appended: { planId: string; occurrenceId: string; periodStart: ISODate; periodEnd: ISODate }[];
  posted: { planId: string; occurrenceId: string; extensionId: string; totalCents: number }[];
  insurance: InsuranceResult[];
  errors: { planId?: string; occurrenceId?: string; message: string }[];
}

const message = (e: unknown): string => (e instanceof Error ? e.message : String(e));

async function safeSend(notifier: Notifier, n: Notification): Promise<void> {
  try {
    await notifier.send(n);
  } catch {
    /* a notification never changes what happens to money */
  }
}

const isLive = (o: OccurrenceRow): boolean => !!o.renews && o.status !== "superseded" && o.status !== "cancelled";
const SETTLED = new Set(["paid", "skipped", "waived"]);
const UNTOUCHED = new Set(["scheduled", "due"]);

/**
 * Where the next renewal period starts: the later of the rental's end date and
 * the end of the plan's last live renewal period — so a period can never leave
 * free days or bill days twice (pp_append_renewal_period enforces the same).
 */
export function renewalChainStart(rentalEnd: ISODate | null, occurrences: OccurrenceRow[]): ISODate | null {
  let chain: ISODate | null = rentalEnd;
  for (const o of occurrences) {
    if (!isLive(o) || !o.periodEnd) continue;
    if (!chain || compareDates(o.periodEnd, chain) > 0) chain = o.periodEnd;
  }
  return chain;
}

/**
 * The draft of the renewal period starting on `start`: dated by addPeriod (as
 * auto-extend dates it), priced by renewalBreakdownCents, due on its first day
 * unless `dueDate` says otherwise (an operator's Extend is due today).
 */
export function nextRenewalDraft(
  start: ISODate,
  renewal: { periodUnit: RenewalPeriodUnit; periodCount: number },
  pricing: Pick<RenewalPricingInputs, "monthlyAmount" | "discountApplied" | "tenant">,
  dueDate?: ISODate,
): OccurrenceDraft {
  const period = renewalPeriod(start, renewal.periodUnit, renewal.periodCount);
  const bd = renewalBreakdownCents(pricing);
  return {
    seq: 1, // pp_append_renewal_period assigns the real one
    dueDate: dueDate ?? start,
    periodStart: period.periodStart,
    periodEnd: period.periodEnd,
    days: period.days,
    amountCents: bd.totalCents,
    isStub: false,
  };
}

/** Normalise a coverage to the four booleans, or null when it buys nothing. */
export function normalizeCoverage(c: RenewalCoverage | null | undefined): RenewalCoverage | null {
  if (!hasCoverage(c)) return null;
  return { cdw: !!c!.cdw, rcli: !!c!.rcli, sli: !!c!.sli, pai: !!c!.pai };
}

// ─────────────────────────────────────────────────────────────────────────────
// Posting and insuring one period
// ─────────────────────────────────────────────────────────────────────────────

interface PostOptions {
  coverage: RenewalCoverage | null;
  giveDaysNow: boolean;
  actorId: string | null;
  /** An automatic period (the renewal stage), not an operator's Extend. */
  automatic: boolean;
}

async function postPeriod(deps: RenewalDeps, plan: PlanRow, occ: OccurrenceRow, pricing: RenewalPricingInputs, opts: PostOptions): Promise<PostRenewalResult> {
  const breakdown = renewalBreakdownCents(pricing);
  const posted = await deps.store.postRenewalPeriod({
    occurrenceId: occ.id,
    breakdown,
    insuranceRequested: hasCoverage(opts.coverage),
    giveDaysNow: opts.giveDaysNow,
    actorId: opts.actorId,
  });
  // A5, automatic periods: the plan's own setting decides. The server records
  // the choice and asks the operator to send it (the portal's /api/esign is
  // the only sender of an 'extension' agreement today).
  if (posted.posted && opts.automatic && plan.renewal?.sendAgreementEachPeriod) {
    const inserted = await deps.store.recordEvent({
      planId: plan.id,
      occurrenceId: occ.id,
      kind: "agreement_choice",
      dedupeKey: `agreement_choice:auto:${occ.id}`,
      detail: { sendAgreement: true, automatic: true, extensionIds: [posted.extensionId], occurrenceIds: [occ.id] },
    });
    if (inserted) {
      await safeSend(deps.notifier, {
        kind: "alert",
        to: "operator",
        planId: plan.id,
        occurrenceId: occ.id,
        detail: {
          problem: "extension_agreement_due",
          message: `A new period (${occ.periodStart} → ${occ.periodEnd}) was added to this renewing rental, and its plan sends an extension agreement for each period — send it from the rental page`,
        },
      });
    }
  }
  return posted;
}

/**
 * A4 for one posted period whose cover is undecided. `giveUp`: a transient
 * failure is final now (the period is due, or the operator is waiting) —
 * the period is then charged without insurance, and the operator told.
 */
async function insurePeriod(
  deps: RenewalDeps,
  plan: PlanRow,
  occ: OccurrenceRow,
  coverage: RenewalCoverage | null,
  asOf: string,
  giveUp: boolean,
): Promise<InsuranceResult> {
  const base = { occurrenceId: occ.id };
  const periodText = `${occ.periodStart} → ${occ.periodEnd}`;
  const decide = async (outcome: "not_insurable" | "failed", reason: string): Promise<InsuranceResult> => {
    await deps.store.recordRenewalInsurance({ occurrenceId: occ.id, outcome, reason });
    await safeSend(deps.notifier, {
      kind: "alert",
      to: "operator",
      planId: plan.id,
      occurrenceId: occ.id,
      detail: { problem: "insurance_not_bought", message: `No insurance was bought or charged for ${periodText}: ${reason}` },
    });
    return { ...base, outcome, reason };
  };

  if (!hasCoverage(coverage)) return decide("failed", "the cover chosen for this period was not kept; buy it from the rental's insurance timeline");
  if (!deps.insurer) return decide("failed", "insurance cannot be bought from here");
  if (!occ.extensionId || !occ.periodStart || !occ.periodEnd) throw new PlanStoreError("invalid_input", `Occurrence ${occ.id} is not a posted renewal period`);

  let outcome: InsureOutcome;
  try {
    outcome = await deps.insurer.insure({
      planId: plan.id,
      occurrenceId: occ.id,
      tenantId: plan.tenantId,
      rentalId: plan.rentalId,
      customerId: plan.customerId,
      extensionId: occ.extensionId,
      periodStart: occ.periodStart,
      periodEnd: occ.periodEnd,
      coverage: coverage as RenewalCoverage,
      asOf,
    });
  } catch (e) {
    outcome = { kind: "retry_later", reason: message(e) };
  }

  switch (outcome.kind) {
    case "insured": {
      await deps.store.recordRenewalInsurance({
        occurrenceId: occ.id,
        outcome: "insured",
        policyRef: outcome.policyRef,
        premiumCents: outcome.premiumCents,
        coveredFrom: outcome.coveredFrom,
        coveredTo: outcome.coveredTo,
      });
      if (compareDates(outcome.coveredFrom, occ.periodStart) > 0) {
        const nights = diffDays(occ.periodStart, outcome.coveredFrom);
        await safeSend(deps.notifier, {
          kind: "alert",
          to: "operator",
          planId: plan.id,
          occurrenceId: occ.id,
          detail: {
            problem: "insurance_starts_late",
            message: `Insurance for ${periodText} starts ${outcome.coveredFrom}: Bonzah cannot start a policy before tomorrow (Pacific), so the first ${nights} night(s) are not insured`,
          },
        });
      }
      return { ...base, outcome: "insured", premiumCents: outcome.premiumCents, policyRef: outcome.policyRef, coveredFrom: outcome.coveredFrom, coveredTo: outcome.coveredTo };
    }
    case "not_insurable":
      return decide("not_insurable", outcome.reason);
    case "retry_later":
      if (giveUp) return decide("failed", `Bonzah did not answer in time (${outcome.reason})`);
      return { ...base, outcome: "retry_later", reason: outcome.reason };
    default:
      throw new PlanStoreError("invalid_input", `Unknown insurance outcome ${JSON.stringify(outcome)}`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// The stage
// ─────────────────────────────────────────────────────────────────────────────

async function renewPlan(deps: RenewalDeps, plan: PlanRow, asOf: string, result: RenewalStageResult): Promise<void> {
  const today = localDateInZone(asOf, plan.timezone);
  let occs = await deps.store.listOccurrences(plan.id);
  let pricing: RenewalPricingInputs | null = null;
  const pricingFor = async () => (pricing ??= await deps.store.renewalPricing(plan.rentalId));

  // 2. APPEND — a renewal plan's next period, once its last one is settled.
  if (plan.extendsRental && plan.renewal) {
    const live = occs.filter(isLive).sort((a, b) => a.seq - b.seq);
    const last = live[live.length - 1];
    if (!last || SETTLED.has(last.status)) {
      const p = await pricingFor();
      const start = renewalChainStart(p.rentalEnd, live);
      if (start) {
        const draft = nextRenewalDraft(start, plan.renewal, p);
        const r = await deps.store.appendRenewalPeriod(plan.id, draft, null);
        if (r.appended) {
          result.appended.push({ planId: plan.id, occurrenceId: r.occurrenceId, periodStart: draft.periodStart, periodEnd: draft.periodEnd });
          occs = await deps.store.listOccurrences(plan.id);
        }
      }
    }
  }

  // 3. POST — untouched, unposted periods within the lead of their due date.
  const coverage = plan.renewal ? normalizeCoverage(plan.renewal.insurance) : null;
  for (const o of occs) {
    if (!isLive(o) || o.extensionId || !UNTOUCHED.has(o.status) || o.attemptNo !== 0) continue;
    if (compareDates(addDays(o.dueDate, -RENEWAL_POST_LEAD_DAYS), today) > 0) continue;
    try {
      const posted = await postPeriod(deps, plan, o, await pricingFor(), { coverage, giveDaysNow: false, actorId: null, automatic: true });
      if (posted.posted) {
        const fresh = await deps.store.getOccurrence(o.id);
        result.posted.push({ planId: plan.id, occurrenceId: o.id, extensionId: posted.extensionId, totalCents: fresh?.amountCents ?? o.amountCents });
      }
    } catch (e) {
      result.errors.push({ planId: plan.id, occurrenceId: o.id, message: message(e) });
    }
  }

  // 4. INSURE — before anything can charge the period.
  occs = await deps.store.listOccurrences(plan.id);
  for (const o of occs) {
    if (!isLive(o) || !o.extensionId || o.insuranceStatus !== "pending" || !UNTOUCHED.has(o.status)) continue;
    try {
      const giveUp = compareInstants(o.dueAt, asOf) <= 0;
      result.insurance.push(await insurePeriod(deps, plan, o, coverage, asOf, giveUp));
    } catch (e) {
      result.errors.push({ planId: plan.id, occurrenceId: o.id, message: message(e) });
    }
  }
}

/** The renewal stage of one tick. Every plan is handled in its own try/catch. */
export async function runRenewalStage(deps: RenewalDeps, asOf: string, filter: { tenantId?: string; planId?: string } = {}): Promise<RenewalStageResult> {
  const result: RenewalStageResult = { reconciled: [], appended: [], posted: [], insurance: [], errors: [] };
  // 1. RECONCILE
  try {
    result.reconciled = await deps.store.reconcileRenewals(filter);
  } catch (e) {
    result.errors.push({ message: `reconcile: ${message(e)}` });
  }
  let plans: PlanRow[] = [];
  try {
    plans = await deps.store.listRenewalPlans(filter);
  } catch (e) {
    result.errors.push({ message: `list: ${message(e)}` });
    return result;
  }
  for (const plan of plans) {
    try {
      await renewPlan(deps, plan, asOf, result);
    } catch (e) {
      result.errors.push({ planId: plan.id, message: message(e) });
      if (e instanceof Error && e.name === "PlanRuleError") {
        // Nothing to renew for (a $0 rate): tell a person, once per plan and problem (the notifier dedupes).
        await safeSend(deps.notifier, { kind: "alert", to: "operator", planId: plan.id, detail: { problem: "renewal_cannot_be_priced", message: message(e) } });
      }
    }
  }
  return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// The operator's Extend
// ─────────────────────────────────────────────────────────────────────────────

export interface ExtendInput {
  planId: string;
  /** 1..MAX_EXTEND_PERIODS. */
  periods: number;
  /** A3: true → the rental's end date moves now; false → when each period is paid. */
  giveDaysNow: boolean;
  /** A5: the operator's answer; recorded here, sent by the portal (/api/esign 'extension'). */
  sendAgreement: boolean;
  /** Cover to buy for these periods; undefined = the plan's own (renewal plans), null = none. */
  insurance?: RenewalCoverage | null;
  /** A plan that does not renew has no period of its own: say it here (default one week). */
  periodUnit?: RenewalPeriodUnit;
  periodCount?: number;
  actorId?: string | null;
  asOf: string;
}

export interface ExtendedPeriod {
  occurrenceId: string;
  extensionId: string;
  periodStart: ISODate;
  periodEnd: ISODate;
  amountCents: number;
  insurance: InsuranceResult;
}

export interface ExtendResult {
  extensionIds: string[];
  occurrenceIds: string[];
  periods: ExtendedPeriod[];
  /** rentals.end_date after the Extend. */
  endDate: ISODate | null;
}

/**
 * Extend the rental on its live plan by N periods, now. Each period is posted
 * (an extension + its charges) and due TODAY on the plan's method — the next
 * cron run collects it, or the operator's Retry does at once. A renewal
 * plan's own next period, if it is not posted yet, is the FIRST of the N (its
 * due date is brought forward to today), so the chain never skips a period.
 * Insurance is bought now, once (the operator is waiting): if Bonzah cannot
 * cover a period, it carries no premium and the result says why.
 */
export async function extendPlan(deps: RenewalDeps, input: ExtendInput): Promise<ExtendResult> {
  if (!Number.isInteger(input.periods) || input.periods < 1 || input.periods > MAX_EXTEND_PERIODS) {
    throw new PlanStoreError("invalid_input", `Extend by 1 to ${MAX_EXTEND_PERIODS} periods`);
  }
  const clocked = deps.store as { setNow?: (asOf: string) => void };
  if (typeof clocked.setNow === "function") clocked.setNow(new Date(input.asOf).toISOString());
  const plan = await deps.store.getPlan(input.planId);
  if (!plan) throw new PlanStoreError("not_found", `Plan ${input.planId} not found`);
  if (plan.status !== "active") throw new PlanStoreError("refused", `The plan is ${plan.status}; resume it before extending`);

  const renewal: Pick<PlanRenewal, "periodUnit" | "periodCount"> = plan.renewal
    ? { periodUnit: plan.renewal.periodUnit, periodCount: plan.renewal.periodCount }
    : { periodUnit: input.periodUnit ?? "week", periodCount: input.periodCount ?? 1 };
  if (!["day", "week", "month"].includes(renewal.periodUnit) || !Number.isInteger(renewal.periodCount) || renewal.periodCount < 1 || renewal.periodCount > 52) {
    throw new PlanStoreError("invalid_input", "A period is 1–52 days, weeks or months");
  }
  const coverage = normalizeCoverage(input.insurance === undefined ? plan.renewal?.insurance ?? null : input.insurance);
  const actorId = input.actorId ?? null;
  const today = localDateInZone(input.asOf, plan.timezone);
  const pricing = await deps.store.renewalPricing(plan.rentalId);
  renewalBreakdownCents(pricing); // refuse a $0 period before writing anything

  const out: ExtendResult = { extensionIds: [], occurrenceIds: [], periods: [], endDate: null };
  const initial = await deps.store.listOccurrences(plan.id);
  const pending = initial.filter((o) => isLive(o) && !o.extensionId && UNTOUCHED.has(o.status) && o.attemptNo === 0).sort((a, b) => a.seq - b.seq);

  for (let i = 0; i < input.periods; i++) {
    let occ: OccurrenceRow | null;
    if (i < pending.length) {
      occ = pending[i];
      if (compareDates(occ.dueDate, today) > 0) await deps.store.moveOccurrence(occ.id, today, actorId);
    } else {
      const start = renewalChainStart(pricing.rentalEnd, await deps.store.listOccurrences(plan.id));
      if (!start) throw new PlanStoreError("refused", "This rental has no end date to extend from");
      const draft = nextRenewalDraft(start, renewal, pricing, today);
      const appended = await deps.store.appendRenewalPeriod(plan.id, draft, actorId);
      occ = await deps.store.getOccurrence(appended.occurrenceId);
    }
    if (!occ) throw new PlanStoreError("not_found", "The new period vanished");
    const posted = await postPeriod(deps, plan, occ, pricing, { coverage, giveDaysNow: input.giveDaysNow, actorId, automatic: false });
    let insurance: InsuranceResult = { occurrenceId: occ.id, outcome: "none" };
    let fresh = await deps.store.getOccurrence(occ.id);
    if (fresh && fresh.insuranceStatus === "pending") {
      insurance = await insurePeriod(deps, plan, fresh, coverage, input.asOf, true);
      fresh = await deps.store.getOccurrence(occ.id);
    }
    out.extensionIds.push(posted.extensionId);
    out.occurrenceIds.push(occ.id);
    out.periods.push({
      occurrenceId: occ.id,
      extensionId: posted.extensionId,
      periodStart: occ.periodStart as ISODate,
      periodEnd: occ.periodEnd as ISODate,
      amountCents: fresh?.amountCents ?? occ.amountCents,
      insurance,
    });
  }

  // A5: the operator's answer, on the record whichever way it went.
  await deps.store.recordEvent({
    planId: plan.id,
    occurrenceId: out.occurrenceIds[0],
    kind: "agreement_choice",
    dedupeKey: `agreement_choice:extend:${out.occurrenceIds[0]}`,
    actorId,
    detail: { sendAgreement: !!input.sendAgreement, automatic: false, giveDaysNow: !!input.giveDaysNow, extensionIds: out.extensionIds, occurrenceIds: out.occurrenceIds },
  });
  out.endDate = (await deps.store.renewalPricing(plan.rentalId)).rentalEnd;
  return out;
}
