/**
 * Renewal pricing — how ONE renewal period is dated and priced.
 *
 * The five functions between the VERBATIM markers are auto-extend's own period
 * math and money helpers, moved here unchanged from
 * supabase/functions/auto-extend-rentals/index.ts (commit ad357dd8) so that
 * three callers date and price a renewal with ONE piece of code:
 *   - auto-extend-rentals            (the live cron),
 *   - sandbox-auto-extend-rentals    (its Developer-tab copy),
 *   - the payment-plan engine        (renewal plans and the operator's Extend,
 *                                     renewals.ts; the shadow comparison,
 *                                     renewal-shadow.ts).
 * tests/payment-plans/engine/renewal-pricing.test.ts keeps a frozen copy of
 * the originals and proves the two agree — textually, and over a table of
 * cases. Do not "fix" them here (the Monthly overflow — Jan 31 + 1 month =
 * Mar 3 — included) without meaning to change auto-extend too: the shadow
 * comparison relies on both engines agreeing to the cent and the day.
 *
 * Money inside the verbatim helpers is DOLLARS, auto-extend's unit. The plan
 * side converts to integer cents once, in renewalBreakdownCents, from the
 * same rounded values auto-extend writes to the ledger.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type { ISODate, RenewalBreakdown, RenewalPeriodUnit, RenewalPricingInputs } from "./types.ts";
import { decimalToCents } from "./amounts.ts";
import { PlanRuleError } from "./errors.ts";

// ---- VERBATIM from auto-extend-rentals/index.ts @ ad357dd8 (only `export ` added) ----
export function addPeriod(endDate: string, unit: string, count = 1): { newEndDate: string; days: number } {
  // endDate is a YYYY-MM-DD DATE. Advance by `count` units (e.g. 2 weeks, 10 days, 3 months).
  const n = Math.max(1, Math.floor(count || 1));
  const d = new Date(`${endDate}T00:00:00Z`);
  const before = d.getTime();
  if (unit === "Daily") {
    d.setUTCDate(d.getUTCDate() + n);
  } else if (unit === "Monthly") {
    d.setUTCMonth(d.getUTCMonth() + n);
  } else {
    d.setUTCDate(d.getUTCDate() + n * 7); // Weekly
  }
  const days = Math.round((d.getTime() - before) / (24 * 60 * 60 * 1000));
  return { newEndDate: d.toISOString().split("T")[0], days };
}

// Apply per-occurrence schedule exceptions to the next renewal's grid date:
// skip past skipped dates (advancing one period each time), then relocate if moved.
export function applyExceptions(gridYmd: string, unit: string, count: number, ex: any): string {
  let g = gridYmd, guard = 0;
  const skips: string[] = Array.isArray(ex?.skips) ? ex.skips : [];
  const moves: Record<string, string> = (ex && typeof ex.moves === "object") ? ex.moves : {};
  while (skips.includes(g) && guard < 500) { g = addPeriod(g, unit, count).newEndDate; guard++; }
  return moves[g] || g;
}

export function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}

export function computeBreakdown(rentalAmount: number, tenant: any): {
  rental: number; tax: number; serviceFee: number; total: number;
} {
  const rental = round2(Number(rentalAmount) || 0);
  const taxPct = tenant?.tax_enabled ? Number(tenant?.tax_percentage || 0) : 0;
  const tax = round2(rental * (taxPct / 100));
  let serviceFee = 0;
  if (tenant?.service_fee_enabled) {
    if (tenant?.service_fee_type === "percentage") {
      serviceFee = round2(rental * (Number(tenant?.service_fee_value || 0) / 100));
    } else {
      serviceFee = round2(Number(tenant?.service_fee_value ?? tenant?.service_fee_amount ?? 0));
    }
  }
  return { rental, tax, serviceFee, total: round2(rental + tax + serviceFee) };
}

/**
 * The per-period rate actually owed: the headline rate less the agreed discount.
 * Flat currency amount, same period scope as monthly_amount (it is computed from
 * it at booking time), and the same subtraction the e-sign templates already do.
 */
export function discountedRate(r: { monthly_amount?: number | null; discount_applied?: number | null }): number {
  return Math.max(0, (Number(r?.monthly_amount) || 0) - (Number(r?.discount_applied) || 0));
}
// ---- end VERBATIM ----

/** The plan's unit → auto-extend's rentals.auto_extend_period_unit. */
export const AUTO_EXTEND_UNIT: Readonly<Record<RenewalPeriodUnit, "Daily" | "Weekly" | "Monthly">> = {
  day: "Daily",
  week: "Weekly",
  month: "Monthly",
};

/** rentals.auto_extend_period_unit / rental_period_type → the plan's unit. Anything else is a week, as in addPeriod. */
export function renewalUnitFrom(value: string | null | undefined): RenewalPeriodUnit {
  const v = String(value ?? "").toLowerCase();
  if (v === "daily" || v === "day") return "day";
  if (v === "monthly" || v === "month") return "month";
  return "week";
}

export interface RenewalPeriod {
  periodStart: ISODate; // inclusive
  periodEnd: ISODate; // exclusive — the rental's new end date once paid
  days: number;
}

/** The period that starts on `start`, dated exactly as auto-extend dates a renewal (addPeriod). */
export function renewalPeriod(start: ISODate, unit: RenewalPeriodUnit, count: number): RenewalPeriod {
  const { newEndDate, days } = addPeriod(start, AUTO_EXTEND_UNIT[unit], count);
  return { periodStart: start, periodEnd: newEndDate, days };
}

/** A dollar amount already rounded to the cent (round2's output) → integer cents, exactly (never `x * 100`). */
export function dollarsToCents(dollars: number): number {
  if (!Number.isFinite(dollars)) throw new RangeError(`Not an amount: ${dollars}`);
  return decimalToCents(dollars.toFixed(2));
}

/**
 * One renewal period's price, exactly as auto-extend prices a period that has
 * no per-occurrence override: computeBreakdown(discountedRate(rental), tenant)
 * — the discounted per-period rate, plus tax, plus the service fee. The cents
 * are the ledger rows' own values; the total is their sum (what the ledger
 * will say is owed). Insurance is NOT here: a premium joins the period only
 * once a policy has been bought (renewals.ts, A4).
 *
 * Throws PlanRuleError('amount_too_small') when the period would cost nothing
 * — auto-extend skips such a rental, a plan refuses to be set up on one.
 */
export function renewalBreakdownCents(p: Pick<RenewalPricingInputs, "monthlyAmount" | "discountApplied" | "tenant">): RenewalBreakdown {
  const bd = computeBreakdown(discountedRate({ monthly_amount: p.monthlyAmount, discount_applied: p.discountApplied }), p.tenant);
  const rentalCents = dollarsToCents(bd.rental);
  const taxCents = dollarsToCents(bd.tax);
  const serviceFeeCents = dollarsToCents(bd.serviceFee);
  const totalCents = rentalCents + taxCents + serviceFeeCents;
  if (totalCents < 1) {
    throw new PlanRuleError("amount_too_small", "This rental has no per-period price (its rate less its discount is $0), so there is nothing to renew for");
  }
  return { rentalCents, taxCents, serviceFeeCents, totalCents };
}

/** Does this coverage ask for any Bonzah product? */
export function hasCoverage(c: { cdw?: boolean; rcli?: boolean; sli?: boolean; pai?: boolean } | null | undefined): boolean {
  return !!c && (!!c.cdw || !!c.rcli || !!c.sli || !!c.pai);
}
