/**
 * The shape of the booking WRITE path.
 *
 * Kept in its own file, free of React and of the Supabase client, so the
 * contract can be read (and diffed against v1's `proceedWithPayment`) without
 * wading through the query code that implements it.
 *
 * ── WHY A RENTAL EXISTS BEFORE A PAYMENT DOES ────────────────────────────────
 * `create-booking-payment-intent` refuses a request without a `rentalId`, and
 * it computes the amount itself by summing the rental's OPEN LEDGER CHARGES —
 * rows written by the `rental_charges_trigger` AFTER INSERT trigger on
 * `rentals` and by `generate_first_charge_for_rental`. The browser cannot
 * choose what it is charged, which is the point; the price of that guarantee is
 * that the rental must be committed before a card form can be shown at all.
 */

import type { QuoteResult } from "@/lib/quote/types";
import type { BookingFormState, DeliveryOption } from "@/lib/stores/booking-store";

/* ─────────────────────────────── the request ─────────────────────────────── */

/** One leg of the journey, resolved to what `rentals` actually stores. */
export interface BookingLocationLeg {
  /** `pickup_locations.id`, or null for a fixed depot / an area delivery. */
  id: string | null;
  /** The human address written to `rentals.pickup_location` / `.return_location`. */
  address: string | null;
}

export interface CreateBookingParams {
  tenantId: string;
  vehicleId: string;
  /** The store's state, already through `validateBooking` with no errors. */
  form: BookingFormState;
  /** Resolved arrangement — never the store's raw nullable `deliveryOption`. */
  deliveryOption: DeliveryOption;
  /**
   * The live bill. Its `grandTotal` is what lands in `rentals.monthly_amount`
   * and in `invoices.total_amount`, and every line of the invoice is taken from
   * here rather than recomputed — a second derivation is a second chance to
   * disagree with the number the customer read.
   */
  quote: QuoteResult;
  /**
   * extraId -> quantity, ALREADY clamped to what is bookable. Pass the page's
   * `billableExtras`, not the raw store selection.
   */
  selectedExtras: Record<string, number>;
  pickupLocation: BookingLocationLeg;
  returnLocation: BookingLocationLeg;
}

/* ─────────────────────────────── the outcome ─────────────────────────────── */

export interface CreatedBooking {
  rentalId: string;
  /**
   * `rentals.rental_number`, read back from the insert.
   *
   * There is NO `booking_ref` column; this is generated by a trigger, so it can
   * only be read back — never predicted. Whatever the UI shows the customer must
   * be this one value.
   */
  rentalNumber: string | null;
  customerId: string;
  /** True when an existing unpaid draft was reused rather than a new row written. */
  reused: boolean;
}

export type CreateBookingFailureKind =
  /** The overlap trigger (or our own pre-check) says the car is spoken for. */
  | "vehicle-taken"
  /** The operator took the vehicle off the road since the page loaded. */
  | "vehicle-paused"
  /** A write was refused — permissions, a constraint, or the network. */
  | "write-failed";

export interface CreateBookingFailure {
  kind: CreateBookingFailureKind;
  /** Safe to render verbatim to the customer. */
  message: string;
  /** Whether offering "Try again" would be honest. */
  retryable: boolean;
  /** For the console, never for the customer. */
  detail: string | null;
}

export type CreateBookingResult =
  | { ok: true; booking: CreatedBooking }
  | { ok: false; failure: CreateBookingFailure };
