#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# staging-install-crons.sh — mirror prod's pg_cron jobs onto staging, SAFELY.
#
# WHY THIS SCRIPT EXISTS:
#   Every prod cron command hardcodes the PROD function URL *and* the PROD
#   service_role JWT, e.g.
#       net.http_post(url := 'https://<PROD_REF>.supabase.co/functions/v1/...',
#                     headers := '{"Authorization":"Bearer <PROD SERVICE JWT>"}')
#   Copying those verbatim onto staging would make STAGING CRONS FIRE AT
#   PRODUCTION every 1-5 minutes — accruing real PAYG charges, auto-extending
#   real rentals, charging real cards. This script rewrites both the ref and
#   the JWT, and refuses to install anything still pointing at prod.
#
#   Jobs targeting a FOREIGN project (e.g. daily-reminders-job -> RTECHFINAL)
#   are skipped entirely; staging must not drive another product's project.
#
# Jobs are installed INACTIVE by default. Turn on only what you're testing:
#   select cron.alter_job((select jobid from cron.job where jobname='accrue-payg-charges'), active:=true);
# Or pass --activate to enable them all.
#
# Usage: ./scripts/staging-install-crons.sh [--activate]
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
PROD_REF="hviqoaokxvlancmftwuo"
STAGING_REF="ksmreaadhbirzakkxqrq"
ACTIVATE="false"; [[ "${1:-}" == "--activate" ]] && ACTIVATE="true"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
: "${SUPABASE_ACCESS_TOKEN:?set SUPABASE_ACCESS_TOKEN}"
WORK="${WORK:-/tmp/staging-rebuild}"; mkdir -p "$WORK"

mgmt_sql(){
  curl -s -X POST "https://api.supabase.com/v1/projects/$1/database/query" \
    -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" \
    -H "Content-Type: application/json" -H "User-Agent: $UA" \
    -d "$(python3 -c "import json,sys;print(json.dumps({'query':sys.argv[1]}))" "$2")"
}

echo "▸ fetching prod cron jobs"
mgmt_sql "$PROD_REF" "select jobname, schedule, active, command from cron.job order by jobid" > "$WORK/prod_crons_full.json"

echo "▸ fetching staging service_role key"
STAGING_SR=$(curl -s "https://api.supabase.com/v1/projects/${STAGING_REF}/api-keys" \
  -H "Authorization: Bearer $SUPABASE_ACCESS_TOKEN" -H "User-Agent: $UA" \
  | python3 -c "import json,sys;print(next(k['api_key'] for k in json.load(sys.stdin) if k.get('name')=='service_role'))")
[[ -n "$STAGING_SR" ]] || { echo "could not read staging service_role key" >&2; exit 1; }

python3 - "$WORK" "$PROD_REF" "$STAGING_REF" "$STAGING_SR" "$ACTIVATE" <<'PY' > "$WORK/install_crons.sql"
import json,re,sys
work,prod,stg,sr,activate = sys.argv[1:6]
jobs=json.load(open(f"{work}/prod_crons_full.json"))
out=[]; skipped=[]
for j in jobs:
    cmd=j['command'] or ''
    refs=set(re.findall(r'https://([a-z]{20})\.supabase\.co', cmd))
    foreign = refs - {prod}
    if foreign:
        skipped.append((j['jobname'], f"targets foreign project {','.join(foreign)}")); continue
    # rewrite ref then any service_role JWT for that ref
    cmd = cmd.replace(f"https://{prod}.supabase.co", f"https://{stg}.supabase.co")
    cmd = re.sub(r'Bearer\s+eyJ[A-Za-z0-9_\-\.]+', f'Bearer {sr}', cmd)
    if prod in cmd:
        skipped.append((j['jobname'], "still references prod after rewrite")); continue
    esc = cmd.replace("'", "''")
    nm  = j['jobname'].replace("'", "''")
    sch = j['schedule'].replace("'", "''")
    out.append(f"select cron.schedule('{nm}', '{sch}', $CRONBODY${cmd}$CRONBODY$);")
    if activate != "true":
        out.append(f"select cron.alter_job((select jobid from cron.job where jobname='{nm}'), active := false);")
print("-- generated by staging-install-crons.sh")
print("\n".join(out))
sys.stderr.write(f"  installing {len(out and jobs)-len(skipped)} jobs, skipped {len(skipped)}\n")
for n,r in skipped: sys.stderr.write(f"    SKIP {n}: {r}\n")
PY

echo "▸ applying to staging (active=$ACTIVATE)"
SQL=$(cat "$WORK/install_crons.sql")
mgmt_sql "$STAGING_REF" "$SQL" | head -c 400
echo
echo "▸ result"
mgmt_sql "$STAGING_REF" "select count(*) filter (where active) as active, count(*) as total from cron.job"
