/**
 * Cron safety — the three ways a recurring job goes wrong in production:
 * two runs overlap, a run dies after the money moved, and Stripe delivers the
 * same webhook twice. Each is run live against a fixture, and each ends with
 * the same Finances tie-out the happy path would — the point is that the
 * numbers do NOT change.
 *
 *   CS1a–c  two overlapping fires  — two copies of the SAME job, concurrently,
 *                                    for the same fixture (plan tick, PAYG
 *                                    accrual, auto-extend renewal)
 *   CS2     crash after charge     — the plan engine's provider is wrapped so
 *                                    the REAL Stripe TEST charge happens and the
 *                                    engine is then told "5xx" (indeterminate);
 *                                    recovery must replay the SAME key and
 *                                    record one payment (live twin of S5)
 *   CS3     webhook delivered twice — the real checkout.session.completed event
 *                                    is fetched from Stripe and re-delivered to
 *                                    stripe-webhook-test, signed, exactly as a
 *                                    Stripe retry is (live twin of S7)
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { autoExtendWeekly, BOOKING_3_DAYS, PAYG_DAILY, planWeekly3 } from "./fixtures.ts";
import type { BillExpectation, Scenario, Step } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };

const PLAN_ONE_OF_THREE: Step = {
  kind: "tie_out",
  label: "one of three paid, once",
  expect: {
    // Occurrence 1 paid ONCE: $600.00 − $200.00 = $400.00 owed (twice would read $200.00).
    outstanding: { cents: 40000, math: "600.00 - 200.00 = 400.00" },
    collected: { cents: 20000, math: "600.00 / 3 = 200.00" },
    bills: [
      {
        label: "Booking",
        total: { cents: 60000, math: "3 × 200.00 = 600.00" },
        paid: { cents: 20000, math: "600.00 / 3 = 200.00" },
        credited: ZERO,
        balance: { cents: 40000, math: "600.00 - 200.00 - 0.00 = 400.00" },
      },
    ],
  },
};

const WEEK_PAID: BillExpectation = {
  label: "Booking",
  total: { cents: 35000, math: "1 × 350.00 = 350.00" },
  paid: { cents: 35000, math: "350.00 = 350.00" },
  credited: ZERO,
  balance: { cents: 0, math: "350.00 - 350.00 - 0.00 = 0.00" },
};

export const CRON_SAFETY: Scenario[] = [
  {
    id: "CS1a",
    family: "cron_safety",
    title: "Two plan ticks at once charge occurrence 1 once",
    why: "pp_claim is the lock: the second tick finds the occurrence claimed and does nothing. One attempt, one key, one Stripe charge, one payment.",
    tiers: ["live"],
    fixture: planWeekly3(),
    assumes: ["usd"],
    references: ["S6"],
    steps: [
      { kind: "advance", domain: "payment_plan", days: 2 },
      { kind: "tick_plan", copies: 2 },
      {
        kind: "check",
        label: "charged once",
        checks: [
          { label: "1 paid, 2 and 3 scheduled", observe: "plan.occurrence_statuses", expect: ["paid", "scheduled", "scheduled"] },
          { label: "one attempt, key suffix 1:1", observe: "plan.attempt_keys_suffixes", expect: ["1:1"] },
          { label: "one plan payment", observe: "plan.payment_count", expect: 1 },
          { label: "Stripe holds one succeeded charge", observe: "stripe.succeeded_intents", expect: 1 },
        ],
      },
      PLAN_ONE_OF_THREE,
    ],
  },
  {
    id: "CS1b",
    family: "cron_safety",
    title: "Two PAYG accrual runs at once post each day once",
    why: "The accrual insert is unique per (rental, day index): the losing run's insert is a duplicate and is skipped, so three days are still three accruals.",
    tiers: ["live"],
    fixture: PAYG_DAILY,
    assumes: ["usd", "tax_off", "service_fee_off", "payg_window_1_day"],
    steps: [
      { kind: "advance", domain: "payg", days: 3 },
      { kind: "fire", job: "sandbox-accrue-payg-charges", copies: 2 },
      {
        kind: "check",
        label: "each day once",
        checks: [
          { label: "3 accruals, not 6", observe: "payg.accrual_count", expect: 3 },
          { label: "ledger charges $120.00, not $240.00", observe: "ledger.charge_cents", expect: { cents: 12000, math: "3 × 40.00 = 120.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "three days owed, once",
        expect: {
          // 3 days × $40.00 = $120.00 (both runs together, not $240.00).
          outstanding: { cents: 12000, math: "3 × 40.00 = 120.00" },
          collected: ZERO,
          bills: [{ label: "Booking", total: { cents: 12000, math: "3 × 40.00 = 120.00" }, paid: ZERO, credited: ZERO, balance: { cents: 12000, math: "120.00 - 0.00 - 0.00 = 120.00" } }],
        },
      },
    ],
  },
  {
    id: "CS1c",
    family: "cron_safety",
    title: "Two auto-extend runs at once renew the week once",
    why: "One renewal, one card charge. A second renewal would be a second charge to the customer for the same week.",
    tiers: ["live"],
    fixture: autoExtendWeekly("auto_charge"),
    assumes: ["usd", "tax_off", "service_fee_off", "auto_extend_grace_48h", "auto_extend_retries_3"],
    suspect:
      "The renewal job selects by auto_extend_next_charge_at and claims nothing before it charges; two overlapping runs can both see the rental due. rental_extensions has no unique (rental_id, sequence_number) guard in the live dump either. Evidence decides.",
    steps: [
      { kind: "charge_saved_card", amount: { cents: 35000, math: "1 × 350.00 = 350.00" }, note: "E2E: pay the first week" },
      { kind: "advance", domain: "auto_extend", days: 1 },
      { kind: "fire", job: "sandbox-auto-extend-rentals", copies: 2 },
      {
        kind: "check",
        label: "renewed once",
        checks: [
          { label: "one renewal", observe: "extensions.count", expect: 1 },
          { label: "renewal charges $350.00, not $700.00", observe: "ledger.extension_charge_cents", expect: { cents: 35000, math: "1 × 350.00 = 350.00" } },
          { label: "Stripe holds 2 succeeded charges (booking + one renewal)", observe: "stripe.succeeded_intents", expect: 2 },
          { label: "received $700.00, not $1,050.00", observe: "payments.received_cents", expect: { cents: 70000, math: "350.00 + 350.00 = 700.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "renewed once",
        expect: {
          // Booking week + ONE renewal week = $350.00 + $350.00 = $700.00, all paid.
          outstanding: { cents: 0, math: "700.00 - 700.00 = 0.00" },
          collected: { cents: 70000, math: "350.00 + 350.00 = 700.00" },
          bills: [
            WEEK_PAID,
            { label: "Extension #1", total: { cents: 35000, math: "1 × 350.00 = 350.00" }, paid: { cents: 35000, math: "350.00 = 350.00" }, credited: ZERO, balance: { cents: 0, math: "350.00 - 350.00 - 0.00 = 0.00" } },
          ],
        },
      },
    ],
  },
  {
    id: "CS2",
    family: "cron_safety",
    title: "Crash after the charge: recovery replays the key, one payment",
    why: "Stripe took the money and the engine was told 5xx. The next tick (after the 10-minute stale window) replays the SAME idempotency key, Stripe returns the SAME PaymentIntent, and exactly one payment is recorded.",
    tiers: ["live"],
    fixture: planWeekly3(),
    assumes: ["usd"],
    references: ["S5"],
    steps: [
      { kind: "advance", domain: "payment_plan", days: 2 },
      { kind: "crash_after_charge" },
      {
        kind: "check",
        label: "money moved, nothing recorded",
        checks: [
          { label: "occurrence 1 is processing", observe: "plan.occurrence_statuses", expect: ["processing", "scheduled", "scheduled"] },
          { label: "no plan payment recorded", observe: "plan.payment_count", expect: 0 },
          { label: "yet Stripe holds one succeeded charge", observe: "stripe.succeeded_intents", expect: 1 },
        ],
      },
      // Age the in-flight attempt past STALE_ATTEMPT_SECONDS (600 s), then tick: recovery.
      { kind: "tick_plan", ageAttemptsMinutes: 11 },
      {
        kind: "check",
        label: "recovered once",
        checks: [
          { label: "occurrence 1 paid", observe: "plan.occurrence_statuses", expect: ["paid", "scheduled", "scheduled"] },
          { label: "the SAME key, never :2", observe: "plan.attempt_keys_suffixes", expect: ["1:1"] },
          { label: "one plan payment", observe: "plan.payment_count", expect: 1 },
          { label: "still one succeeded Stripe charge", observe: "stripe.succeeded_intents", expect: 1 },
        ],
      },
      PLAN_ONE_OF_THREE,
    ],
  },
  {
    id: "CS3",
    family: "cron_safety",
    title: "The extension webhook is delivered twice: one payment",
    why: "A paid extension link's checkout.session.completed arrives a second time (a Stripe retry). The second delivery must find the session already settled and change nothing.",
    tiers: ["live"],
    fixture: BOOKING_3_DAYS,
    assumes: ["usd", "tax_off", "service_fee_off"],
    references: ["S7"],
    steps: [
      { kind: "charge_saved_card", amount: { cents: 30000, math: "3 × 100.00 = 300.00" }, note: "E2E: pay the booking in full" },
      { kind: "extend_manually", days: 2, amount: { cents: 20000, math: "2 × 100.00 = 200.00" } },
      {
        kind: "human",
        ask: "pay_latest_link",
        say: "Open the extension payment link below and pay it with the Stripe test card 4242 4242 4242 4242 (any future expiry, any CVC, any ZIP). Then press Continue — the runner will re-deliver Stripe's webhook for it.",
      },
      { kind: "replay_webhook", event: "checkout.session.completed" },
      {
        kind: "check",
        label: "after the second delivery",
        checks: [
          { label: "two payments received, not three", observe: "payments.received_count", expect: 2 },
          { label: "received $500.00, not $700.00", observe: "payments.received_cents", expect: { cents: 50000, math: "300.00 + 200.00 = 500.00" } },
          { label: "the extension reads paid", observe: "extensions.last.status", expect: "paid" },
        ],
      },
      {
        kind: "tie_out",
        label: "unchanged by the replay",
        expect: {
          // Booking $300.00 + extension $200.00 = $500.00, received once each.
          outstanding: { cents: 0, math: "500.00 - 500.00 = 0.00" },
          collected: { cents: 50000, math: "300.00 + 200.00 = 500.00" },
          bills: [
            { label: "Booking", total: { cents: 30000, math: "3 × 100.00 = 300.00" }, paid: { cents: 30000, math: "300.00 = 300.00" }, credited: ZERO, balance: { cents: 0, math: "300.00 - 300.00 - 0.00 = 0.00" } },
            { label: "Extension #1", total: { cents: 20000, math: "2 × 100.00 = 200.00" }, paid: { cents: 20000, math: "200.00 = 200.00" }, credited: ZERO, balance: { cents: 0, math: "200.00 - 200.00 - 0.00 = 0.00" } },
          ],
        },
      },
    ],
  },
];
