/**
 * Installments — while the legacy mechanism exists (payment plans replace it).
 * Fired through sandbox-process-installment-payment with only_rental_id = the
 * fixture, never the real job 6; mark_overdue_installments (job 4) is a global
 * SQL function with no single-rental scope and is never fired.
 *
 * Fixture: INSTALLMENT_3_WEEKLY — a $600.00 booking (one Rental charge), and
 * an auto-collect plan of 3 × $200.00, the first due tomorrow.
 * `advance installment 1 day` makes installment 1 due today.
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { INSTALLMENT_3_WEEKLY } from "./fixtures.ts";
import type { Scenario } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };

export const INSTALLMENTS: Scenario[] = [
  {
    id: "IN1",
    family: "installment",
    title: "The first installment is charged to the card",
    why: "Installment 1 falls due; the card is charged $200.00; the installment is settled and the booking owes the other $400.00.",
    tiers: ["live"],
    fixture: INSTALLMENT_3_WEEKLY,
    assumes: ["usd"],
    suspect:
      "process-installment-payment inserts its payment with status 'Applied' (not 'Completed'), and the FIFO insert trigger only allocates 'Completed' rows — so the $600.00 Rental charge may never be reduced, and Outstanding would stay $600.00. If this tie-out fails with Paid $0.00, that is the defect, not the catalogue.",
    steps: [
      { kind: "advance", domain: "installment", days: 1 },
      { kind: "fire", job: "sandbox-process-installment-payment" },
      {
        kind: "check",
        label: "installment 1 paid",
        checks: [
          { label: "installment 1 paid, 2 and 3 open", observe: "installments.invoice_statuses", expect: ["paid", "open", "open"] },
          // One installment: $600.00 / 3 = $200.00.
          { label: "received $200.00", observe: "payments.received_cents", expect: { cents: 20000, math: "600.00 / 3 = 200.00" } },
          { label: "Stripe holds one succeeded charge of $200.00", observe: "stripe.succeeded_intent_cents", expect: { cents: 20000, math: "600.00 / 3 = 200.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "one of three paid",
        expect: {
          // $600.00 owed − $200.00 paid = $400.00 still owed.
          outstanding: { cents: 40000, math: "600.00 - 200.00 = 400.00" },
          collected: { cents: 20000, math: "600.00 / 3 = 200.00" },
          bills: [
            {
              label: "Booking",
              total: { cents: 60000, math: "3 × 200.00 = 600.00" },
              paid: { cents: 20000, math: "600.00 / 3 = 200.00" },
              credited: ZERO,
              balance: { cents: 40000, math: "600.00 - 200.00 - 0.00 = 400.00" },
            },
          ],
        },
      },
    ],
  },
  {
    id: "IN2",
    family: "installment",
    title: "The installment card declines",
    why: "The card fails off-session: the installment stays open with one failure recorded, nothing is collected, and the whole booking is still owed.",
    tiers: ["live"],
    fixture: INSTALLMENT_3_WEEKLY,
    assumes: ["usd"],
    steps: [
      { kind: "swap_card", card: "declined" },
      { kind: "advance", domain: "installment", days: 1 },
      { kind: "fire", job: "sandbox-process-installment-payment" },
      {
        kind: "check",
        label: "declined",
        checks: [
          { label: "all three still open", observe: "installments.invoice_statuses", expect: ["open", "open", "open"] },
          { label: "one failure on installment 1", observe: "installments.failure_counts", expect: [1, 0, 0] },
          { label: "nothing received", observe: "payments.received_cents", expect: { cents: 0, math: "0.00 = 0.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "nothing paid",
        expect: {
          // Nothing collected: the whole booking, 3 × $200.00 = $600.00, is owed.
          outstanding: { cents: 60000, math: "3 × 200.00 = 600.00" },
          collected: ZERO,
          bills: [
            {
              label: "Booking",
              total: { cents: 60000, math: "3 × 200.00 = 600.00" },
              paid: ZERO,
              credited: ZERO,
              balance: { cents: 60000, math: "600.00 - 0.00 - 0.00 = 600.00" },
            },
          ],
        },
      },
    ],
  },
];
