/**
 * What the runner OBSERVED, and how it is compared with what the catalogue
 * EXPECTS. Pure: rows in, numbers out. No network, no clock of its own.
 *
 * The runner (supabase/functions/e2e-runner) reads every row that hangs off
 * the fixture rental into a `Snapshot` after each checking step. `observe`
 * turns a snapshot into the value an `Observable` names; `tieOut` computes the
 * three Finances numbers — Outstanding, Collected, and each bill's
 * Total / Paid / Credited / Balance — from the SAME rules the portal's
 * Finances tab uses (apps/portal/src/lib/finances/balance.ts, bills.ts,
 * receipts.ts, stats.ts), restated here for one rental because those files
 * import the portal's `@/` aliases and cannot run in the edge runtime. The
 * rules are quoted beside each line; tests/e2e/observe.test.ts pins them on
 * hand-made rows.
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import type { Check, FinanceExpectation, Money, Observable } from "./types.ts";

// ─── Rows, as PostgREST returns them (numeric columns may be number or string) ──

type Num = number | string | null | undefined;

export interface SnapLedger {
  id: string;
  type: string | null;
  category: string | null;
  amount: Num;
  remaining_amount: Num;
  due_date: string | null;
  customer_id: string | null;
  extension_id: string | null;
}

export interface SnapPayment {
  id: string;
  amount: Num;
  refund_amount: Num;
  status: string | null;
  capture_status: string | null;
  payment_type: string | null;
  stripe_checkout_session_id: string | null;
  payment_plan_occurrence_id?: string | null;
}

export interface SnapApplication {
  payment_id: string;
  charge_entry_id: string;
  amount_applied: Num;
}

export interface SnapExtension {
  id: string;
  sequence_number: number | null;
  status: string | null;
  extension_days: number | null;
  total_amount: Num;
}

export interface SnapAccrual {
  accrual_day_index: number;
  invoice_status: string | null;
  daily_rate: Num;
  tax_amount: Num;
  service_fee_amount: Num;
}

export interface SnapInstallment {
  installment_number: number;
  invoice_status: string | null;
  failure_count: number | null;
}

export interface SnapOccurrence {
  id: string;
  seq: number;
  status: string;
}

export interface SnapAttempt {
  occurrence_id: string;
  attempt_no: number;
  method: string;
  status: string;
}

export interface SnapIntent {
  id: string;
  status: string;
  /** Minor units, as Stripe reports it. */
  amount: number;
}

export interface Snapshot {
  /** The instant the rows were read (ISO). */
  takenAt: string;
  /** The tenant-local calendar day at `takenAt` (YYYY-MM-DD). */
  today: string;
  /** The fixture's end_date when it was created, and how far the runner has shifted end_date since. */
  originalEndDate: string;
  endDateShiftDays: number;
  rental: Record<string, unknown> | null;
  ledger: SnapLedger[];
  payments: SnapPayment[];
  applications: SnapApplication[];
  extensions: SnapExtension[];
  accruals: SnapAccrual[];
  installments: SnapInstallment[];
  plan: { id: string; status: string } | null;
  occurrences: SnapOccurrence[];
  attempts: SnapAttempt[];
  /** PaymentIntents on the fixture's Stripe TEST customer; null when not read. */
  stripeIntents: SnapIntent[] | null;
}

// ─── Units and the portal's predicates ─────────────────────────────────────

/** A numeric dollar column → integer cents (balance.ts `toCents`, the one dollars→cents boundary). */
export function toCents(v: Num): number {
  const n = typeof v === "number" ? v : Number(v ?? 0);
  return Number.isFinite(n) ? Math.round(n * 100) : 0;
}

/** lib/payment-status RECEIVED_PAYMENT_STATUSES. */
const RECEIVED = ["Applied", "Credit", "Partial", "Completed", "Partial Refund"];

/** lib/payment-status `isMoneyReceived`: a received status and not an uncaptured hold. */
export function isMoneyReceived(p: SnapPayment): boolean {
  if (!p.status || !RECEIVED.includes(p.status)) return false;
  return p.capture_status !== "requires_capture";
}

const isCharge = (l: SnapLedger) => l.type === "Charge";

function daysBetween(fromDay: string, toDay: string): number {
  const a = Date.parse(`${fromDay.slice(0, 10)}T00:00:00Z`);
  const b = Date.parse(`${toDay.slice(0, 10)}T00:00:00Z`);
  return Math.round((b - a) / 86_400_000);
}

const sumCents = (xs: Num[]) => xs.reduce<number>((s, x) => s + toCents(x), 0);

// ─── Observations ─────────────────────────────────────────────────────────

export function observe(s: Snapshot, key: Observable): unknown {
  const r = s.rental ?? {};
  const charges = s.ledger.filter(isCharge);
  const received = s.payments.filter(isMoneyReceived);
  const lastExt = [...s.extensions].sort((a, b) => (a.sequence_number ?? 0) - (b.sequence_number ?? 0)).at(-1) ?? null;
  const seqOf = new Map(s.occurrences.map((o) => [o.id, o.seq]));
  switch (key) {
    case "payments.received_count":
      return received.length;
    case "payments.received_cents":
      return sumCents(received.map((p) => p.amount));
    case "payments.net_received_cents":
      return received.reduce((t, p) => t + Math.max(0, toCents(p.amount) - toCents(p.refund_amount)), 0);
    case "payments.refunded_cents":
      return sumCents(s.payments.map((p) => p.refund_amount));
    case "payments.pending_link_count":
      return s.payments.filter((p) => p.status === "Pending" && !!p.stripe_checkout_session_id).length;
    case "payments.non_pending_statuses":
      return s.payments.filter((p) => p.status !== "Pending").map((p) => String(p.status)).sort();
    case "ledger.charge_cents":
      return sumCents(charges.map((c) => c.amount));
    case "ledger.remaining_cents":
      return sumCents(charges.map((c) => c.remaining_amount));
    case "ledger.extension_charge_cents":
      return sumCents(charges.filter((c) => String(c.category ?? "").startsWith("Extension")).map((c) => c.amount));
    case "ledger.refund_row_cents":
      return sumCents(s.ledger.filter((l) => l.type === "Refund").map((l) => l.amount));
    case "applications.cents":
      return sumCents(s.applications.map((a) => a.amount_applied));
    case "extensions.count":
      return s.extensions.length;
    case "extensions.last.status":
      return lastExt?.status ?? null;
    case "extensions.last.days":
      return lastExt?.extension_days ?? null;
    case "extensions.last.total_cents":
      return lastExt ? toCents(lastExt.total_amount) : null;
    case "rental.status":
      return r.status ?? null;
    case "rental.end_date_moved_days":
      // end_date is a driving column the runner backdates; add the shift back
      // so "moved" means what the renewal did, not what the clock did.
      return typeof r.end_date === "string" ? daysBetween(s.originalEndDate, r.end_date) + s.endDateShiftDays : null;
    case "rental.auto_extend_status":
      return r.auto_extend_status ?? null;
    case "rental.auto_extend_paused":
      return r.auto_extend_paused === true;
    case "rental.auto_extend_failed_attempts":
      return Number(r.auto_extend_failed_attempts ?? 0);
    case "rental.auto_extend_charge_count":
      return Number(r.auto_extend_charge_count ?? 0);
    case "rental.auto_extend_pending":
      return r.auto_extend_pending_extension_id != null;
    case "rental.auto_extend_retry_in_hours": {
      const next = typeof r.auto_extend_next_charge_at === "string" ? Date.parse(r.auto_extend_next_charge_at) : NaN;
      return Number.isFinite(next) ? Math.round((next - Date.parse(s.takenAt)) / 3_600_000) : null;
    }
    case "payg.accrual_count":
      return s.accruals.length;
    case "payg.open_accrual_cents":
      return s.accruals
        .filter((a) => a.invoice_status === "open")
        .reduce((t, a) => t + toCents(a.daily_rate) + toCents(a.tax_amount) + toCents(a.service_fee_amount), 0);
    case "payg.accrual_statuses":
      return [...s.accruals].sort((a, b) => a.accrual_day_index - b.accrual_day_index).map((a) => String(a.invoice_status));
    case "installments.invoice_statuses":
      return [...s.installments].sort((a, b) => a.installment_number - b.installment_number).map((i) => String(i.invoice_status));
    case "installments.failure_counts":
      return [...s.installments].sort((a, b) => a.installment_number - b.installment_number).map((i) => Number(i.failure_count ?? 0));
    case "plan.occurrence_statuses":
      return [...s.occurrences].sort((a, b) => a.seq - b.seq).map((o) => o.status);
    case "plan.status":
      return s.plan?.status ?? null;
    case "plan.attempt_keys_suffixes":
      return s.attempts
        .map((a) => [seqOf.get(a.occurrence_id) ?? 0, a.attempt_no] as const)
        .sort((x, y) => x[0] - y[0] || x[1] - y[1])
        .map(([seq, n]) => `${seq}:${n}`);
    case "plan.payment_count":
      return s.payments.filter((p) => !!p.payment_plan_occurrence_id && isMoneyReceived(p)).length;
    case "plan.payment_cents":
      return sumCents(s.payments.filter((p) => !!p.payment_plan_occurrence_id && isMoneyReceived(p)).map((p) => p.amount));
    case "plan.card_attempts_for_occurrence_1": {
      const first = s.occurrences.find((o) => o.seq === 1);
      return first ? s.attempts.filter((a) => a.occurrence_id === first.id && a.method === "auto_charge").length : 0;
    }
    case "stripe.succeeded_intents":
      return s.stripeIntents === null ? null : s.stripeIntents.filter((pi) => pi.status === "succeeded").length;
    case "stripe.succeeded_intent_cents":
      return s.stripeIntents === null ? null : s.stripeIntents.filter((pi) => pi.status === "succeeded").reduce((t, pi) => t + pi.amount, 0);
  }
}

/** Does a check need Stripe read (so the runner fetches intents only when asked)? */
export function needsStripe(checks: Check[]): boolean {
  return checks.some((c) => c.observe.startsWith("stripe."));
}

// ─── Finances, for one rental ───────────────────────────────────────────────

export interface ObservedBill {
  label: string;
  totalCents: number;
  paidCents: number;
  creditedCents: number;
  balanceCents: number;
  tiesOut: boolean;
}

export interface ObservedFinance {
  outstandingCents: number;
  collectedCents: number;
  bills: ObservedBill[];
}

/**
 * Finances for the fixture's customer, who has exactly one rental.
 *
 *   Outstanding (balance.ts) = Σ remaining_amount on `Charge` rows, skipping
 *     every charge when the rental is cancelled or rejected; skipping the
 *     ledger entirely on a pay-as-you-go rental (its open `payg_accruals` are
 *     the authority — counting both double-counts); skipping a `Rental` charge
 *     whose due_date is after today (tenant-local). Plus, on a PAYG rental that
 *     is not closed: Σ open accrual day totals (rate + tax + fee).
 *   Collected (receipts.ts / filters.ts / stats.ts) = Σ max(0, amount −
 *     refund_amount) over rows with payment_type 'Payment' that are money
 *     received (`isMoneyReceived`). A Pending link row, an uncaptured hold and
 *     a fully Refunded row contribute nothing. (The card's period filter is
 *     not applied: every fixture payment is from the run itself.)
 *   Bills (bills.ts) = one per rental for its own charges ("Booking"), one per
 *     extension ("Extension #n"):
 *       Total = Σ positive charge amounts   Paid = Σ payment_applications on them
 *       Credited = Σ |negative amounts|     Balance = Σ remaining_amount
 *     and a bill ties out when Total − Paid − Credited = Balance.
 */
export function tieOut(s: Snapshot): ObservedFinance {
  const r = s.rental ?? {};
  const excluded = r.status === "Cancelled" || r.approval_status === "rejected";
  const isPayg = r.is_pay_as_you_go === true;
  const charges = s.ledger.filter(isCharge);

  let outstanding = 0;
  if (!excluded) {
    if (!isPayg) {
      for (const c of charges) {
        if (!c.customer_id) continue;
        const notYetDue = c.category === "Rental" && !!c.due_date && c.due_date.slice(0, 10) > s.today;
        if (notYetDue) continue;
        outstanding += toCents(c.remaining_amount);
      }
    } else if (r.payg_closed_at == null) {
      for (const a of s.accruals) {
        if (a.invoice_status !== "open") continue;
        outstanding += toCents(a.daily_rate) + toCents(a.tax_amount) + toCents(a.service_fee_amount);
      }
    }
  }

  // filters.ts isCollectedRow: payment_type 'Payment' (null reads as 'Payment') and money received.
  const collected = s.payments
    .filter((p) => (p.payment_type ?? "Payment") === "Payment" && isMoneyReceived(p))
    .reduce((t, p) => t + Math.max(0, toCents(p.amount) - toCents(p.refund_amount)), 0);

  const appliedByCharge = new Map<string, number>();
  for (const a of s.applications) appliedByCharge.set(a.charge_entry_id, (appliedByCharge.get(a.charge_entry_id) ?? 0) + toCents(a.amount_applied));

  const seqByExt = new Map(s.extensions.map((e) => [e.id, e.sequence_number]));
  const groups = new Map<string, SnapLedger[]>();
  for (const c of charges) {
    const key = c.extension_id ?? "";
    groups.set(key, [...(groups.get(key) ?? []), c]);
  }
  // A PAYG rental with open accruals and no ledger rows still has a booking bill.
  if (isPayg && s.accruals.some((a) => a.invoice_status === "open") && !groups.has("")) groups.set("", []);

  const bills: ObservedBill[] = [];
  for (const [ext, rows] of groups) {
    let total = 0;
    let credited = 0;
    let paid = 0;
    let balance = 0;
    for (const c of rows) {
      const amt = toCents(c.amount);
      if (amt > 0) total += amt;
      else if (amt < 0) credited += -amt;
      paid += appliedByCharge.get(c.id) ?? 0;
      balance += toCents(c.remaining_amount);
    }
    const seq = ext ? seqByExt.get(ext) : null;
    bills.push({
      label: ext ? `Extension #${seq ?? "?"}` : "Booking",
      totalCents: total,
      paidCents: paid,
      creditedCents: credited,
      balanceCents: balance,
      tiesOut: total - paid - credited === balance,
    });
  }
  bills.sort((a, b) => (a.label === "Booking" ? -1 : b.label === "Booking" ? 1 : a.label.localeCompare(b.label, "en", { numeric: true })));
  return { outstandingCents: outstanding, collectedCents: collected, bills };
}

// ─── Comparison ─────────────────────────────────────────────────────────────

export interface AssertionResult {
  label: string;
  expected: unknown;
  actual: unknown;
  pass: boolean;
  /** The hand derivation, carried into the evidence so a reader sees where the number came from. */
  math?: string;
}

export function isMoney(v: unknown): v is Money {
  return !!v && typeof v === "object" && !Array.isArray(v) && typeof (v as Money).cents === "number" && typeof (v as Money).math === "string";
}

function same(a: unknown, b: unknown): boolean {
  return JSON.stringify(a) === JSON.stringify(b);
}

export function compareCheck(c: Check, s: Snapshot): AssertionResult {
  const actual = observe(s, c.observe);
  if (isMoney(c.expect)) return { label: c.label, expected: c.expect.cents, actual, pass: actual === c.expect.cents, math: c.expect.math };
  return { label: c.label, expected: c.expect, actual, pass: same(actual, c.expect) };
}

export function compareTieOut(label: string, e: FinanceExpectation, s: Snapshot): AssertionResult[] {
  const f = tieOut(s);
  const out: AssertionResult[] = [
    { label: `${label}: Outstanding`, expected: e.outstanding.cents, actual: f.outstandingCents, pass: f.outstandingCents === e.outstanding.cents, math: e.outstanding.math },
    { label: `${label}: Collected`, expected: e.collected.cents, actual: f.collectedCents, pass: f.collectedCents === e.collected.cents, math: e.collected.math },
  ];
  const wantLabels = e.bills.map((b) => b.label);
  const gotLabels = f.bills.map((b) => b.label);
  out.push({ label: `${label}: bills on the rental`, expected: wantLabels, actual: gotLabels, pass: same(wantLabels, gotLabels) });
  for (const want of e.bills) {
    const got = f.bills.find((b) => b.label === want.label);
    const row = (field: string, exp: Money, act: number | undefined) =>
      out.push({ label: `${label}: ${want.label} ${field}`, expected: exp.cents, actual: act ?? null, pass: act === exp.cents, math: exp.math });
    row("Total", want.total, got?.totalCents);
    row("Paid", want.paid, got?.paidCents);
    row("Credited", want.credited, got?.creditedCents);
    row("Balance", want.balance, got?.balanceCents);
    out.push({ label: `${label}: ${want.label} ties out (Total − Paid − Credited = Balance)`, expected: true, actual: got?.tiesOut ?? null, pass: got?.tiesOut === true });
  }
  return out;
}
