/**
 * Pay as you go — daily accrual, the reminder with its link, and paying it.
 * Fired through sandbox-accrue-payg-charges / sandbox-send-payg-reminders with
 * only_rental_id = the fixture, never the real jobs 32 / 33.
 *
 * Fixture: PAYG_DAILY — $40.00/day, first day starts in 1 hour, reminder
 * cadence 1 day (the per-rental override). `advance payg 3 days` backdates
 * payg_start_ts / payg_next_accrual_at by 72 h, so the next run posts exactly
 * the three whole days that have "passed" (days 1–3; day 4 starts 1 h from
 * now), well under the job's 7-day-per-run cap (window 86400 s →
 * `payg_window_1_day`).
 *
 * A PAYG rental's Outstanding is its OPEN accruals, never its ledger rows —
 * both describe the same days (apps/portal/src/lib/finances/balance.ts).
 *
 * Canonical copy: tests/e2e/scenarios/. The edge-function copy
 * (supabase/functions/e2e-runner/catalogue/) is generated by
 * `node tests/e2e/sync-catalogue.mjs` — edit here, then sync.
 */

import { PAYG_DAILY } from "./fixtures.ts";
import type { Scenario, Step, TenantAssumption } from "./types.ts";

const ZERO = { cents: 0, math: "0.00 = 0.00" };
const ASSUMES: TenantAssumption[] = ["usd", "tax_off", "service_fee_off", "payg_window_1_day"];

const THREE_DAYS: Step = { kind: "advance", domain: "payg", days: 3 };
const ACCRUE: Step = { kind: "fire", job: "sandbox-accrue-payg-charges" };

const ACCRUED_3: Step = {
  kind: "check",
  label: "three days accrued",
  checks: [
    { label: "3 accruals", observe: "payg.accrual_count", expect: 3 },
    { label: "all three open", observe: "payg.accrual_statuses", expect: ["open", "open", "open"] },
    { label: "open accruals total $120.00", observe: "payg.open_accrual_cents", expect: { cents: 12000, math: "3 × 40.00 = 120.00" } },
    { label: "ledger charges total $120.00", observe: "ledger.charge_cents", expect: { cents: 12000, math: "3 × 40.00 = 120.00" } },
  ],
};

export const PAYG: Scenario[] = [
  {
    id: "PG1",
    family: "payg",
    title: "Three days accrue, once",
    why: "Each day posts one accrual and its ledger rows; running the job again the same day posts nothing.",
    tiers: ["live"],
    fixture: PAYG_DAILY,
    assumes: ASSUMES,
    steps: [
      THREE_DAYS,
      ACCRUE,
      ACCRUED_3,
      // Day 4 starts in 1 hour: a second run now must post nothing.
      ACCRUE,
      { kind: "check", label: "a second run posts nothing", checks: [{ label: "still 3 accruals", observe: "payg.accrual_count", expect: 3 }] },
      {
        kind: "tie_out",
        label: "three days owed",
        expect: {
          // PAYG: Outstanding = open accruals, 3 × $40.00 (the ledger rows are skipped).
          outstanding: { cents: 12000, math: "3 × 40.00 = 120.00" },
          collected: ZERO,
          bills: [
            {
              label: "Booking",
              total: { cents: 12000, math: "3 × 40.00 = 120.00" },
              paid: ZERO,
              credited: ZERO,
              balance: { cents: 12000, math: "120.00 - 0.00 - 0.00 = 120.00" },
            },
          ],
        },
      },
    ],
  },
  {
    id: "PG2",
    family: "payg",
    title: "Reminder with a link, and the customer pays it",
    why: "The reminder bills what the ledger says is still owed ($120.00) through a fresh link; paying it drains the three days, settles the latest accrual and supersedes the earlier two.",
    tiers: ["live"],
    fixture: PAYG_DAILY,
    assumes: [...ASSUMES, "payg_reminders_on"],
    steps: [
      THREE_DAYS,
      ACCRUE,
      ACCRUED_3,
      { kind: "fire", job: "sandbox-send-payg-reminders" },
      { kind: "check", label: "reminder sent with a link", checks: [{ label: "one link placeholder row", observe: "payments.pending_link_count", expect: 1 }] },
      {
        kind: "human",
        ask: "pay_latest_link",
        say: "Open the pay-as-you-go payment link below ($120.00) and pay it with the Stripe test card 4242 4242 4242 4242 (any future expiry, any CVC, any ZIP). Then press Continue.",
      },
      {
        kind: "check",
        label: "after the link is paid",
        checks: [
          { label: "day 3 paid, days 1–2 superseded", observe: "payg.accrual_statuses", expect: ["superseded", "superseded", "paid"] },
          { label: "nothing open", observe: "payg.open_accrual_cents", expect: { cents: 0, math: "120.00 - 120.00 = 0.00" } },
          { label: "received $120.00", observe: "payments.received_cents", expect: { cents: 12000, math: "3 × 40.00 = 120.00" } },
          { label: "the ledger is drained", observe: "ledger.remaining_cents", expect: { cents: 0, math: "120.00 - 120.00 = 0.00" } },
        ],
      },
      {
        kind: "tie_out",
        label: "paid up",
        expect: {
          outstanding: { cents: 0, math: "120.00 - 120.00 = 0.00" },
          collected: { cents: 12000, math: "3 × 40.00 = 120.00" },
          bills: [
            {
              label: "Booking",
              total: { cents: 12000, math: "3 × 40.00 = 120.00" },
              paid: { cents: 12000, math: "120.00 = 120.00" },
              credited: ZERO,
              balance: { cents: 0, math: "120.00 - 120.00 - 0.00 = 0.00" },
            },
          ],
        },
      },
    ],
  },
];
