-- Add Fleet & Pricing page to CMS

INSERT INTO cms_pages (slug, name, description, status) VALUES ('fleet', 'Fleet & Pricing Page', 'Fleet page hero, rental rates, inclusions, extras, and SEO', 'draft') ON CONFLICT (slug) DO NOTHING;

INSERT INTO cms_page_sections (page_id, section_key, content, display_order) SELECT id, 'fleet_hero', '{"headline":"Fleet & Pricing","subheading":"Browse our premium vehicles with clear daily, weekly, and monthly rates.","background_image":"","primary_cta_text":"Book Now","secondary_cta_text":"View Fleet Below"}'::jsonb, 1 FROM cms_pages WHERE slug = 'fleet' ON CONFLICT (page_id, section_key) DO NOTHING;

INSERT INTO cms_page_sections (page_id, section_key, content, display_order) SELECT id, 'rental_rates', '{"section_title":"Flexible Rental Rates","daily":{"title":"Daily","description":"Ideal for short stays and one-day hires."},"weekly":{"title":"Weekly","description":"Perfect balance of flexibility and value."},"monthly":{"title":"Monthly","description":"Exclusive long-term rates for regular clients."}}'::jsonb, 2 FROM cms_pages WHERE slug = 'fleet' ON CONFLICT (page_id, section_key) DO NOTHING;

INSERT INTO cms_page_sections (page_id, section_key, content, display_order) SELECT id, 'inclusions', '{"section_title":"Every Drive917 Rental Includes","section_subtitle":"Peace of mind and premium service come standard with every vehicle.","standard_title":"Standard Inclusions","standard_items":[{"icon":"Shield","title":"Comprehensive Insurance Coverage"},{"icon":"Phone","title":"24/7 Roadside Assistance"},{"icon":"MapPin","title":"Unlimited Mileage"},{"icon":"Fuel","title":"Full Tank of Premium Fuel"},{"icon":"User","title":"Professional Vehicle Handover"},{"icon":"Sparkles","title":"Vehicle Valeting & Cleaning"}],"premium_title":"Premium Add-ons","premium_items":[{"icon":"User","title":"Chauffeur Service (per hour)"},{"icon":"Plane","title":"Airport Meet & Greet"},{"icon":"User","title":"Additional Driver"},{"icon":"MapPin","title":"GPS Navigation System"}]}'::jsonb, 3 FROM cms_pages WHERE slug = 'fleet' ON CONFLICT (page_id, section_key) DO NOTHING;

INSERT INTO cms_page_sections (page_id, section_key, content, display_order) SELECT id, 'extras', '{"items":[{"name":"Child Safety Seat","price":15,"description":"Per day"},{"name":"Mobile WiFi Hotspot","price":10,"description":"Per day"},{"name":"Delivery & Collection","price":50,"description":"Within 25 miles"},{"name":"Extended Insurance","price":25,"description":"Per day"}],"footer_text":"All add-ons can be selected and customized during booking."}'::jsonb, 4 FROM cms_pages WHERE slug = 'fleet' ON CONFLICT (page_id, section_key) DO NOTHING;

INSERT INTO cms_page_sections (page_id, section_key, content, display_order) SELECT id, 'seo', '{"title":"Fleet & Pricing | Drive 917 - Premium Luxury Car Rentals","description":"Browse our exclusive fleet of luxury vehicles including Rolls-Royce, Bentley, and Range Rover. Transparent daily, weekly, and monthly rental rates.","keywords":"luxury car rental pricing, Rolls-Royce rental rates, premium vehicle hire"}'::jsonb, 5 FROM cms_pages WHERE slug = 'fleet' ON CONFLICT (page_id, section_key) DO NOTHING;
