// Generated by scripts/trax-knowledge.mjs from prepared documentation. Do not edit.
export const KNOWLEDGE = {
  "version": "0.4.0",
  "sourceCommit": "7cddd05e1989581fc02d54d68f4c161e7b947245",
  "verifiedAt": "2026-09-15",
  "applicationRelease": null,
  "deploymentVerified": false,
  "guides": [
    {
      "id": "rentals",
      "title": "Rentals",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "rentals",
        "rental",
        "booking",
        "bookings",
        "kiraya",
        "rental workflow"
      ],
      "navigation": [
        "rentals",
        "rental"
      ],
      "en": "Open **Rentals**, then select the rental. Review the customer, vehicle, dates and the requirements shown on that record. Approval, agreement, insurance, payment and handover are separate steps; completing one does not prove the others are finished. In V2 these are contextual stages, starting with Customer. Use the existing controls for changes you are permitted to make.",
      "ur-Latn": "**Rentals** kholein aur rental select karein. Customer, gaari, dates aur record par dikhayi gayi requirements dekhein. Approval, agreement, insurance, payment aur handover alag steps hain; aik step complete hone se baqi complete nahi hote. V2 mein ye stages hain aur pehla Customer hai. Tabdeeli sirf apni ijazat ke mutabiq existing controls se karein."
    },
    {
      "id": "rental_create",
      "title": "Rentals",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "new rental",
        "create rental",
        "creating rental",
        "new booking",
        "naya rental"
      ],
      "navigation": [
        "rental_create",
        "rentals"
      ],
      "en": "In **Rentals**, choose **New Rental**. The V2 intake asks for **Booking Mode**, **Customer**, then **Vehicle**, before opening **New Rental Agreement**. Select the real dates and complete the requirements the form shows. Fixed and pay-as-you-go bookings have different fields; do not invent an end date or a period rate. Review the agreement, insurance and verification requirements before **Create Rental**. The button can instead say **Verify or Waive to Continue**. If a payment-provider setup gate appears, review that gate in the native interface; TRAX cannot bypass it. Creating a rental can also create billing records, reminders and insurance requests. TRAX only explains these steps and does not submit the form.",
      "ur-Latn": "**Rentals** mein **New Rental** chunein. V2 mein pehle **Booking Mode**, phir **Customer** aur **Vehicle**, us ke baad **New Rental Agreement** khulta hai. Asal dates aur form ki requirements bharein. Fixed aur pay-as-you-go ke fields alag hain; end date ya rate khud se assume na karein. **Create Rental** se pehle agreement, insurance aur verification dekhein. Button **Verify or Waive to Continue** bhi dikha sakta hai. Payment-provider setup ki rukawat aaye to native screen par review karein; TRAX usay bypass nahi karta. Rental banane se billing records, reminders aur insurance requests bhi ban sakti hain. TRAX form submit nahi karta."
    },
    {
      "id": "payment_methods",
      "title": "Rentals",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "payment method",
        "payment methods"
      ],
      "navigation": [
        "rentals",
        "rental"
      ],
      "en": "For general payment-method guidance, the V2 rental has a **Payments** stage. Its existing payment dialog distinguishes collecting through the configured provider from recording money received outside the application. The manual method labels include **Cash**, **Card**, **Transfer**, **Zelle**, **Check** and **Other**. A manual Card entry is not evidence that a processor charged a card. Stripe and Square options depend on the tenant's configured provider and the dialog's eligibility checks. Use only controls your role permits. A missing or uncertain payment needs a verified investigation before another collection attempt. TRAX cannot inspect a balance, prove receipt, recommend a duplicate charge or perform a financial action in this version.",
      "ur-Latn": "Payment method ki general guidance ke liye V2 rental ka **Payments** stage dekhein. Existing dialog configured provider se collection aur bahar receive huay paisay record karna alag rakhta hai. Manual labels **Cash**, **Card**, **Transfer**, **Zelle**, **Check** aur **Other** hain. Manual Card entry se processor charge prove nahi hota. Stripe ya Square options tenant setup aur dialog checks par depend karte hain. Sirf allowed controls use karein. Agar payment missing ya uncertain ho to dobara collection se pehle verified investigation zaroori hai. TRAX is version mein balance, receipt ya financial action verify ya execute nahi karta."
    },
    {
      "id": "agreement_send",
      "title": "Rentals",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "send agreement",
        "send the agreement",
        "resend agreement",
        "updated agreement",
        "e-sign agreement",
        "agreement not signed",
        "rental agreement",
        "agreement bhejna",
        "agreement sign nahi hua"
      ],
      "navigation": [
        "rental",
        "rentals"
      ],
      "en": "Open the rental and choose **Agreement** in its stage rail; creating a rental does not send one. Select **Send the agreement**. Later sends read **Send an updated agreement** and email a fresh document built from the rental as it stands, which is how you re-issue after changing terms. The button stays disabled until the customer has a name and email address. **The terms as they stand now** shows what the next document will state. After sending, use **Open the document** or **Open the signed copy**, and **Check for a signature** to refresh the status from BoldSign. If dates or the car changed after sending, a banner offers **Send an updated agreement** / **Resend with the new terms** or **Keep the signed one** / **Keep as sent**; keeping only hides the notice in your browser. Older sends appear under **Earlier versions**. Sending needs e-sign credits, and BoldSign allows 50 sends an hour. TRAX does not send, void or sign agreements and cannot confirm a signature.",
      "ur-Latn": "Rental kholein aur stage rail mein **Agreement** chunein; rental banane se agreement khud nahi jata. **Send the agreement** dabayein. Baad mein button **Send an updated agreement** ban jata hai aur rental ki maujooda terms se naya document email karta hai; terms badalne ke baad dobara bhejne ka yehi tareeqa hai. Customer ka naam aur email na ho to button disabled rehta hai. **The terms as they stand now** batata hai ke agla document kya likhega. Bhejne ke baad **Open the document** ya **Open the signed copy** kholein, aur BoldSign se status taaza karne ke liye **Check for a signature** dabayein. Agar bhejne ke baad dates ya gaari badli ho to banner **Send an updated agreement** / **Resend with the new terms** ya **Keep the signed one** / **Keep as sent** deta hai; keep karne se notice sirf aapke browser mein chhupta hai. Purane versions **Earlier versions** mein milte hain. Bhejne ke liye e-sign credits chahiye, aur BoldSign ek ghante mein 50 sends allow karta hai. TRAX agreement bhejta, void ya sign nahi karta aur signature confirm nahi kar sakta."
    },
    {
      "id": "rental_insurance",
      "title": "Rentals",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "add cover",
        "rental insurance",
        "insurance for a rental",
        "re-quote insurance",
        "insurance dates changed",
        "bonzah cover",
        "rental ka insurance",
        "cover add karna"
      ],
      "navigation": [
        "rental",
        "rentals"
      ],
      "en": "Open the rental and choose **Insurance** in its stage rail; cover is optional. **Add cover**, or **Re-quote and replace** when a policy is active, opens **Select Insurance Coverage**; finish with **Purchase Insurance**. The premium is charged to the rental and the screen moves to **Payments**. The button is disabled, with the reason shown, when Bonzah is unavailable, the make and model is not covered, no insurable days remain, or the rental lacks a car or customer. If the dates move after purchase, a banner flags the mismatch and offers **Re-quote and replace** or **Keep the current policy** (this hides it only in your browser). If **Already insured for these dates** appears, **Issue anyway** charges your Bonzah balance again for the same period. **The customer's own policy** lists uploaded certificates. **Upload a certificate**, **Download the certificate** and **Retry this policy** are disabled on this stage; upload the customer's certificate from Insurances **AI Verifications**. TRAX does not buy or replace cover and cannot confirm a car is insured.",
      "ur-Latn": "Rental kholein aur stage rail mein **Insurance** chunein; cover lena optional hai. **Add cover** (ya policy active ho to **Re-quote and replace**) **Select Insurance Coverage** kholta hai; aakhir mein **Purchase Insurance** dabayein. Premium rental par charge ho jata hai aur screen **Payments** par chali jati hai. Agar Bonzah dastiyab na ho, make aur model covered na ho, insure karne ke din baqi na hon, ya rental mein gaari ya customer na ho to button disabled hota hai aur wajah dikhati hai. Khareedne ke baad dates badlein to banner farq batata hai aur **Re-quote and replace** ya **Keep the current policy** deta hai (yeh sirf aapke browser mein chhupata hai). **Already insured for these dates** aaye to **Issue anyway** usi muddat ke liye Bonzah balance se dobara charge karta hai. **The customer's own policy** mein upload shuda certificates hain. **Upload a certificate**, **Download the certificate** aur **Retry this policy** is stage par disabled hain; customer ka certificate Insurances ke **AI Verifications** se upload karein. TRAX cover khareedta ya replace nahi karta aur gaari insured hone ki tasdeeq nahi kar sakta."
    },
    {
      "id": "returns",
      "title": "Returns and key handover",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "return",
        "returned",
        "handover",
        "keys",
        "wapis",
        "wapas",
        "chabi",
        "chaabi",
        "chabiyan"
      ],
      "navigation": [
        "rental_return",
        "rentals"
      ],
      "en": "To record a returned car, open the rental and its **Handover** stage in V2, or the existing key-handover section in the other layout. Authorized staff confirm receipt there. This can close the rental, update the vehicle and attempt deposit-hold release and a completion notification. If the record already shows receipt or contains conflicting states, review it before repeating the action. Physical return and the system's recorded return are separate facts.",
      "ur-Latn": "Wapas aayi gaari record karne ke liye rental kholein. V2 mein **Handover** stage, aur doosre layout mein key-handover section dekhein. Authorized staff wahin receipt confirm kare. Is se rental close, vehicle update aur deposit hold release aur notification ki koshish ho sakti hai. Agar receipt pehle se recorded hai ya states mukhtalif hain, action dohrane se pehle review karein. Gaari ka wapas aana aur system mein return record hona alag baatein hain."
    },
    {
      "id": "availability",
      "title": "Vehicle availability",
      "permissions": [
        "availability"
      ],
      "keywords": [
        "availability",
        "unavailable",
        "available",
        "bookable",
        "blocked",
        "block",
        "gaari book",
        "car",
        "nahi book"
      ],
      "navigation": [
        "availability",
        "vehicle",
        "vehicles"
      ],
      "en": "A car can be missing or unbookable for several reasons: website visibility, pause or vehicle state, the selected rental duration, another rental, blocked dates or turnaround time. An overdue rental still recorded as active can also hold the vehicle. Start with the correct vehicle and the customer's actual dates and times, then review the vehicle and Availability screens. A recorded return does not rule out another blocker.",
      "ur-Latn": "Gaari nazar na aane ya book na hone ki kai wajah ho sakti hain: website visibility, pause ya vehicle state, rental duration, doosra rental, blocked dates ya turnaround time. Overdue rental jo abhi active recorded hai bhi gaari rok sakta hai. Sahi gaari aur customer ki asal dates aur times se shuru karein, phir vehicle aur Availability screens dekhein. Return recorded hone ke bawajood doosra blocker ho sakta hai."
    },
    {
      "id": "v2-availability",
      "title": "Vehicle availability",
      "permissions": [
        "availability"
      ],
      "keywords": [
        "v2 availability",
        "website unavailable",
        "checkout rejection"
      ],
      "navigation": [
        "availability",
        "vehicle",
        "vehicles"
      ],
      "en": "First distinguish missing from the V2 website, unavailable for selected dates, and checkout rejection. Use the actual vehicle and booking window; do not invent dates. The V2 fleet requires Available/Rented status, pause explicitly off, website publication not off and disposal not on. With dates it also checks the vehicle's duration flag; a selected pickup location must match or the vehicle can have no assigned location.\nFor website date availability, use the customer's browser timezone. Open rental overlap is inclusive; overdue Active/Started rentals can keep a car occupied, and an absent end remains open-ended. Vehicle and fleet-wide blocked periods and the tenant turnaround buffer are separate checks. The buffer uses pickup-day midnight, Completed rentals and the recorded return time (23:59 if absent). Another blocker may remain after a return.\nCheckout's read-only precheck differs: it can include Completed rentals and does not add the date filter's overdue rule. The final database trigger and other write-time validations have not been run by TRAX, so this result is partial and cannot promise a booking will succeed. If a receiving handover or PAYG closure is recorded but the blocking rental is still open, review the conflict rather than repeating a return action. Check Again must rerun current reads. An operator's physical-return report is not independent system evidence.",
      "ur-Latn": "Pehle samjhein: gaari V2 website par nazar nahi aa rahi, chuni hui dates par unavailable hai, ya checkout reject hota hai? Asal gaari aur booking dates lein; dates khud na banayein. Website fleet mein Available/Rented status, pause off, publication off na ho aur disposal on na ho zaroori hai. Dates hon to duration option bhi enabled ho; chuni hui pickup location vehicle ki location se match kare ya vehicle par location na lagi ho.\nDate availability ke liye customer ke browser ka timezone lein. Rental dates inclusive hain. Overdue Active/Started rental bhi gaari rok sakta hai; end date na ho to khud end na banayein. Vehicle ya poori fleet ke blocked dates aur turnaround buffer alag checks hain. Buffer pickup day ki midnight, Completed rentals aur recorded return time use karta hai; time na ho to 23:59. Return ke baad bhi doosra blocker reh sakta hai.\nCheckout ka read-only precheck alag hai: Completed rental bhi count ho sakta hai. Final database trigger aur write-time validations TRAX run nahi karta, is liye checkout result partial hai, booking success ki guarantee nahi. Receiving ya PAYG closure recorded ho lekin rental abhi open ho to conflict review karein; return dobara na chalayein. Check Again fresh records dekhta hai. Aap ka kehna ke car aur keys wapis hain operator ki report hai, independent verification nahi."
    },
    {
      "id": "customers",
      "title": "Customers",
      "permissions": [
        "customers"
      ],
      "keywords": [
        "customer",
        "customers",
        "profile",
        "renter",
        "driver",
        "customer profile"
      ],
      "navigation": [
        "customer",
        "customers"
      ],
      "en": "Open **Customers** and search for the customer before adding a duplicate. Staff with edit permission can use **Add Customer** and complete the existing form's required fields. Select a customer to review their record and rental history. Verification belongs to the existing workflow; also check requirements on the relevant rental. The Customer stage inside a rental differs from the separate customer profile. Keep identity documents in the native workflow. TRAX can open an authorized profile but does not create customers or verify identity or account state.",
      "ur-Latn": "**Customers** kholein aur customer select karke unka record aur rental history dekhein. Verification us customer ke existing workflow mein hoti hai; relevant rental ki requirements bhi dekhein. Rental ke andar Customer stage aur alag customer profile mukhtalif hain. TRAX authorized profile khol sakta hai, lekin ye guidance kisi ki identity ya account state verify nahi karti."
    },
    {
      "id": "customer_documents",
      "title": "Customers",
      "permissions": [
        "customers"
      ],
      "keywords": [
        "customer documents",
        "add document",
        "upload document",
        "upload customer document",
        "document scan flagged",
        "accept anyway",
        "document upload karna",
        "customer ke kaghzat"
      ],
      "navigation": [
        "customer",
        "customers"
      ],
      "en": "Customer files are on the customer record: open **Customers**, select the customer, then **Documents** in the section rail. Staff with customers edit permission see **Add document**, which opens **Add Document**. **Document Type** and **Document Name** are required; **Vehicle (Optional)**, **Upload File (Optional)** and **Notes** are optional. **Insurance Certificate** adds **Insurance Provider** and **Policy Number** and labels the dates **Policy Start Date** and **Policy End Date**; the start date cannot be in the future. Select **Add Document** to save. Each file shows its scan result and expiry. Use **Download**, the pencil to edit, or the bin to remove the file at once, with no confirmation. When the scanner flags a file, editors can choose **Accept anyway**. Licence photos and selfies from the verification provider stay on **Verification** and cannot be replaced here. TRAX does not upload, accept or delete documents, and identity documents should not be pasted into TRAX.",
      "ur-Latn": "Customer ki files customer record par hain: **Customers** kholein, customer chunein, phir section rail mein **Documents**. Customers edit permission wale staff ko **Add document** dikhta hai jo **Add Document** kholta hai. **Document Type** aur **Document Name** zaroori hain; **Vehicle (Optional)**, **Upload File (Optional)** aur **Notes** optional hain. **Insurance Certificate** chunne par **Insurance Provider** aur **Policy Number** aate hain aur dates **Policy Start Date** aur **Policy End Date** ban jati hain; start date aane wali tareekh nahi ho sakti. Save ke liye **Add Document** dabayein. Har file ka scan result aur expiry dikhta hai. **Download**, edit ke liye pencil, ya file hatane ke liye bin use karein; bin foran hata deta hai, koi confirmation nahi. Scanner file flag kare to editors **Accept anyway** chun sakte hain. Verification provider ki licence photos aur selfie **Verification** par rehti hain aur yahan replace nahi hotin. TRAX documents upload, accept ya delete nahi karta, aur identity documents TRAX mein paste na karein."
    },
    {
      "id": "vehicles",
      "title": "Vehicles",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "vehicle",
        "vehicles",
        "fleet",
        "gaari",
        "gari",
        "car configuration"
      ],
      "navigation": [
        "vehicle",
        "vehicles"
      ],
      "en": "Open **Vehicles** and select the vehicle. Review its configuration and booking history in the existing record. Website visibility, pause state and enabled rental durations affect customer booking, while actual availability also depends on dates and other records. Use the native edit controls only if your role permits changes.",
      "ur-Latn": "**Vehicles** kholein aur gaari select karein. Existing record mein configuration aur booking history dekhein. Website visibility, pause state aur enabled rental durations customer booking par asar dalte hain; asal availability dates aur doosre records par bhi depend karti hai. Native edit controls sirf apni role ki ijazat ke mutabiq use karein."
    },
    {
      "id": "vehicle_listing",
      "title": "Vehicles",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "publish",
        "publishing",
        "listing",
        "unpublished",
        "publish vehicle",
        "vehicle listing"
      ],
      "navigation": [
        "vehicle",
        "vehicles"
      ],
      "en": "Open **Vehicles**, choose the vehicle, then **Listing** in its V2 section rail. There is no separate **Publish** action: the booking site reads the saved vehicle configuration. Listing summarizes the public information and points to the sections that own the displayed blockers. Review **Vehicle**, **Rates & mileage**, **Extras & surcharges** and **Availability** as applicable. Website visibility, pause state and enabled durations matter, alongside dates, bookings and blocks. Editing the native configuration can affect customer booking. General guidance does not mean TRAX checked your vehicle; request a live diagnosis for a specific vehicle and booking window.",
      "ur-Latn": "**Vehicles** mein gaari chunein, phir V2 rail mein **Listing** kholein. Alag **Publish** action nahi hai: booking site saved vehicle configuration parhti hai. Listing public information aur blockers ke relevant sections dikhata hai. Zaroorat ke mutabiq **Vehicle**, **Rates & mileage**, **Extras & surcharges** aur **Availability** dekhein. Visibility, pause, duration, dates, bookings aur blocks asar dalte hain. Native configuration badalne se customer booking badal sakti hai. Ye general guidance gaari ka live check nahi; specific gaari aur dates ke liye diagnosis poochein."
    },
    {
      "id": "vehicle_create",
      "title": "Vehicles",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "add vehicle",
        "add a vehicle",
        "new vehicle",
        "create vehicle",
        "adding a vehicle",
        "nayi gaari",
        "gaari add"
      ],
      "navigation": [
        "vehicles"
      ],
      "en": "Open **Vehicles** and choose **Add Vehicle**; it is shown only to staff with vehicles edit permission. The **Add New Vehicle** form requires **License Plate Number**, **Make**, **Model**, **Year**, **Color**, **Fuel Type**, **Acquisition Date**, **Acquisition Type** and the **Daily**, **Weekly** and **Monthly** rent. A purchased vehicle also needs **Purchase Price**; a financed vehicle needs **Contract Total**. Upload at least one vehicle photo. Year cannot be later than the acquisition year, and inspection or registration due dates cannot be in the past. Mileage limits, **Pickup Location**, warranty, key and security details are optional; **Daily Booking**, **Weekly Booking** and **Monthly Booking** choose which durations the vehicle offers. Select **Add Vehicle** to save, then review the vehicle's **Listing** to see what the booking site will show. TRAX does not create vehicles.",
      "ur-Latn": "**Vehicles** kholein aur **Add Vehicle** chunein; ye sirf vehicles edit permission wale staff ko dikhta hai. **Add New Vehicle** form mein **License Plate Number**, **Make**, **Model**, **Year**, **Color**, **Fuel Type**, **Acquisition Date**, **Acquisition Type** aur **Daily**, **Weekly**, **Monthly** rent zaroori hain. Purchase gaari ke liye **Purchase Price** aur finance gaari ke liye **Contract Total** bhi zaroori hai. Kam az kam ek photo upload karein. Year acquisition year se baad ka nahi ho sakta, aur inspection ya registration due date guzri hui nahi ho sakti. Mileage, **Pickup Location**, warranty, key aur security details optional hain; **Daily Booking**, **Weekly Booking** aur **Monthly Booking** se durations chunein. Save ke liye **Add Vehicle** dabayein, phir gaari ki **Listing** dekhein ke booking site kya dikhayegi. TRAX khud gaari add nahi karta."
    },
    {
      "id": "vehicle_pause",
      "title": "Vehicles",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "pause vehicle",
        "pause a vehicle",
        "pause a car",
        "unpause",
        "resume vehicle",
        "paused vehicle",
        "blocked periods",
        "block dates for a car",
        "gaari pause",
        "gaari band karna",
        "band kaise",
        "kuch din ke liye band",
        "gaari rokna"
      ],
      "navigation": [
        "vehicle",
        "vehicles"
      ],
      "en": "Open **Vehicles**, select the car, then **Availability** in its section rail. The top of the panel says **Bookable** or **Not bookable** and lists what is in the way, such as **Paused**, **No hire length is switched on** or **Retired from the fleet**. In **Pause**, type a reason (it is kept on the record) and select **Pause**; this takes the car off the booking site without deleting anything, and rentals already under way carry on. A paused car shows **Paused** with its reason and date; select **Resume** to put it back. **Blocked periods** are dates the car is unavailable while it stays on the booking site: add one with a start date, end date and reason, and use **Unblock** to remove it. Staff without vehicles edit permission see these controls read-only. Hiding a car only from your website is a different switch in the Website section. TRAX does not pause, resume or block vehicles.",
      "ur-Latn": "**Vehicles** kholein, gaari chunein, phir section rail mein **Availability** kholein. Panel ke upar **Bookable** ya **Not bookable** likha hota hai aur rukawat ki wajah dikhti hai, jaise **Paused**, **No hire length is switched on** ya **Retired from the fleet**. **Pause** mein wajah likhein (record par mehfooz rehti hai) aur **Pause** dabayein; is se gaari booking site se hat jati hai, kuch delete nahi hota, aur jo rentals chal rahe hain woh jari rehte hain. Paused gaari par **Paused**, wajah aur date dikhti hai; wapas lane ke liye **Resume** dabayein. **Blocked periods** woh dates hain jab gaari booking site par rehte hue bhi dastiyab nahi hoti: start date, end date aur wajah ke saath period add karein, aur hatane ke liye **Unblock** use karein. Vehicles edit permission ke baghair staff ko ye controls sirf dekhne ke liye milte hain. Gaari sirf website se chhupana alag switch hai jo Website section mein hai. TRAX gaari pause, resume ya block nahi karta."
    },
    {
      "id": "messages",
      "title": "Messages",
      "permissions": [
        "messages"
      ],
      "keywords": [
        "message",
        "messages",
        "messaging",
        "conversation",
        "paigham"
      ],
      "navigation": [
        "messages"
      ],
      "en": "Open **Messages** and choose the relevant customer conversation. Use the existing messaging controls for anything you intend to send. TRAX's application guidance does not read those conversations, send messages or confirm delivery.",
      "ur-Latn": "**Messages** kholein aur relevant customer conversation select karein. Jo message bhejna ho us ke liye existing messaging controls use karein. TRAX ki application guidance conversations nahi parhti, message nahi bhejti aur delivery confirm nahi karti."
    },
    {
      "id": "reminders",
      "title": "Reminders",
      "permissions": [
        "reminders"
      ],
      "keywords": [
        "reminder",
        "reminders",
        "remind",
        "follow up",
        "yaad"
      ],
      "navigation": [
        "reminders"
      ],
      "en": "Where Reminders is enabled, open **Reminders** to review follow-ups. The default list shows pending, sent and snoozed items; filters let you review other states. Use the existing reminder form for its related record and dates. TRAX cannot create, complete or snooze reminders in this phase.",
      "ur-Latn": "Jahan Reminders enabled hai, follow-ups ke liye **Reminders** kholein. Default list pending, sent aur snoozed items dikhati hai; filters se doosri states dekhi ja sakti hain. Related record aur dates ke liye existing reminder form use karein. Is phase mein TRAX reminders create, complete ya snooze nahi karta."
    },
    {
      "id": "website",
      "title": "Website content",
      "permissions": [
        "cms"
      ],
      "keywords": [
        "website",
        "cms",
        "publish",
        "website content",
        "site content"
      ],
      "navigation": [
        "website"
      ],
      "en": "Open **Website Content** (the **Website** area in V2) and choose the page you want to review. Publishing and unpublishing affect the customer-facing site, so use the existing preview and publishing workflow with the required permissions. TRAX does not edit or publish website content.",
      "ur-Latn": "**Website Content** (V2 mein **Website** area) kholein aur page select karein. Publish aur unpublish karne se customer-facing site badalti hai; required permissions ke saath existing preview aur publishing workflow use karein. TRAX website content edit ya publish nahi karta."
    },
    {
      "id": "website_business_details",
      "title": "Website content",
      "permissions": [
        "cms"
      ],
      "keywords": [
        "contact details",
        "contact number",
        "phone number",
        "business phone",
        "business address",
        "website email",
        "website phone number",
        "google maps link",
        "rabta details"
      ],
      "navigation": [
        "website"
      ],
      "en": "Business phone, email and address for your website are edited in the Website section, not in Settings. Switch the sidebar to **Website**, then choose **Site Settings**. In **Business details**, edit **Phone**, **Phone as shown**, **Email**, **Address line 1**, **Address line 2**, **City**, **State**, **ZIP**, **Country** and **Google Maps link**. Empty fields fall back to your business record. The same screen also holds **Logo**, **Footer** and **Social links**. **Business details** has no Save button; changes are written as you type. The Contact page keeps only notes such as **Phone hours**, **Reply time** and **WhatsApp**, and takes phone, email and address from Site settings. Editing needs Website Content edit permission; without it the editor is read-only. TRAX does not edit website details.",
      "ur-Latn": "Website ke liye business phone, email aur address Settings mein nahi, Website section mein badalte hain. Sidebar ko **Website** par switch karein, phir **Site Settings** chunein. **Business details** mein **Phone**, **Phone as shown**, **Email**, **Address line 1**, **Address line 2**, **City**, **State**, **ZIP**, **Country** aur **Google Maps link** edit karein. Khali fields aap ke business record se value leti hain. Isi screen par **Logo**, **Footer** aur **Social links** bhi hain. **Business details** mein Save button nahi; likhte hi changes save hote hain. Contact page par sirf **Phone hours**, **Reply time** aur **WhatsApp** jaise notes hain; phone, email aur address Site settings se aate hain. Edit ke liye Website Content edit permission chahiye, warna editor read-only hai. TRAX website details edit nahi karta."
    },
    {
      "id": "website_vehicle_visibility",
      "title": "Website content",
      "permissions": [
        "cms"
      ],
      "keywords": [
        "show on website",
        "hide from website",
        "hide a car from my website",
        "show a car on my website",
        "website visibility",
        "not showing on website",
        "vehicles on your website",
        "website par gaari dikhana"
      ],
      "navigation": [
        "website"
      ],
      "en": "To show or hide a car on your website without taking it off the road, switch the sidebar to **Website**, open your **Fleet** page and scroll to **Vehicles on your website**. Each car shows **Visible** or **Hidden** with a switch; turning it off takes the car off your website only, and the line above the list counts how many cars are shown. A hidden car still appears everywhere in the portal and can still be rented, blocked and serviced; it is not paused or deleted. Changing the switch needs Website Content edit permission, and if the change cannot be saved an error appears. Being visible is not enough on its own: the car must also be unpaused and have at least one hire length switched on to be bookable, which you check in the car's **Availability** section. TRAX does not change website visibility.",
      "ur-Latn": "Gaari ko road se hataye baghair website par dikhane ya chhupane ke liye sidebar ko **Website** par switch karein, apna **Fleet** page kholein aur neeche **Vehicles on your website** tak jayein. Har gaari ke saath **Visible** ya **Hidden** aur ek switch hota hai; switch off karne se gaari sirf website se hat jati hai, aur list ke upar wali line batati hai ke kitni gaariyan dikh rahi hain. Chhupi hui gaari portal mein har jagah nazar aati hai aur us par rental, block aur servicing jari reh sakti hai; woh pause ya delete nahi hoti. Switch badalne ke liye Website Content edit permission chahiye, aur change save na ho to error aata hai. Sirf visible hona kaafi nahi: bookable hone ke liye gaari unpaused ho aur kam az kam ek hire length on ho, jo gaari ke **Availability** section mein dekhein. TRAX website visibility nahi badalta."
    },
    {
      "id": "settings",
      "title": "Settings",
      "permissions": [
        "settings",
        "settings.general"
      ],
      "keywords": [
        "settings",
        "configuration",
        "business details",
        "setting",
        "kahan"
      ],
      "navigation": [
        "settings_general"
      ],
      "en": "Open **Settings → General** for business configuration. Available tabs depend on your account and permissions. Managers need Settings access and the relevant sub-tab grant. Review and change values through the existing settings controls; TRAX does not save configuration.",
      "ur-Latn": "Business configuration ke liye **Settings → General** kholein. Tabs aap ke account aur permissions par depend karte hain. Manager ko Settings aur relevant sub-tab ka grant chahiye. Values existing settings controls se review aur change karein; TRAX configuration save nahi karta."
    },
    {
      "id": "templates",
      "title": "Communication templates",
      "permissions": [
        "settings",
        "settings.templates"
      ],
      "keywords": [
        "template",
        "templates",
        "email templates",
        "sms template"
      ],
      "navigation": [
        "settings_templates"
      ],
      "en": "Open **Settings** and choose **Customer messages** under **Notifications** for communication templates (older layouts label this tab **Templates**). If it is unavailable, ask an account administrator to review your settings permissions. Use the existing template workflow to edit or preview; changing a template does not itself confirm a message was sent.",
      "ur-Latn": "Communication templates ke liye **Settings** kholein aur **Notifications** ke neeche **Customer messages** chunein (purane layout mein is tab ka naam **Templates** hai). Agar ye available nahi hai to account administrator se settings permissions review karwayein. Edit ya preview ke liye existing template workflow use karein; template badalne se message bheja jana confirm nahi hota."
    },
    {
      "id": "settings_branding",
      "title": "Branding and appearance",
      "permissions": [
        "settings",
        "settings.branding"
      ],
      "keywords": [
        "branding",
        "brand colour",
        "brand color",
        "change logo",
        "company logo",
        "upload logo",
        "upload my company logo",
        "application name",
        "business name",
        "logo badalna"
      ],
      "navigation": [
        "settings_branding"
      ],
      "en": "Open **Settings** with the gear beside your organization name, or **Organization settings** in its menu, then select **Branding** under **Business**. Managers need the Settings and Branding grants; without edit rights the tab shows a view-only notice and no save buttons. In **Brand Identity**, **Application Name** is the name shown in the sidebar and browser title. **Company Logo** takes an image under 5MB and saves as soon as you select **Upload Logo**. The favicon must be under 1MB. **Default Theme Colors** holds **Primary Color**, **Secondary Color** and **Accent Color**; **Light Theme Colors** and **Dark Theme Colors** override them, and **Sync dark theme from light** keeps dark in step. Booking site buttons follow Accent; **Header & Footer Colors** set the booking site header and footer. Select **Save Changes**, or **Revert changes** to drop unsaved edits. **Reset All to Defaults** restores default branding. **Open Appearance** styles the portal itself. Phone, email and address are not on this tab; they are in **Site Settings** in the Website section. TRAX does not change branding.",
      "ur-Latn": "Organization ke naam ke saath wale gear, ya us ke menu mein **Organization settings**, se **Settings** kholein, phir **Business** ke neeche **Branding** chunein. Manager ko Settings aur Branding dono grant chahiye; edit ki ijazat na ho to view-only notice aata hai aur save buttons nahi dikhte. **Brand Identity** mein **Application Name** wo naam hai jo sidebar aur browser title mein dikhta hai. **Company Logo** 5MB se chhoti image leta hai aur **Upload Logo** dabate hi save ho jata hai. Favicon 1MB se chhota ho. **Default Theme Colors** mein **Primary Color**, **Secondary Color** aur **Accent Color** hain; **Light Theme Colors** aur **Dark Theme Colors** inhein override karte hain, aur **Sync dark theme from light** dark ko light ke mutabiq rakhta hai. Booking site ke buttons Accent follow karte hain; header aur footer **Header & Footer Colors** se. **Save Changes** dabayein, ya unsaved edits hatane ke liye **Revert changes**. **Reset All to Defaults** default branding wapas lata hai. Portal ki apni look ke liye **Open Appearance**. Phone, email aur address is tab par nahi, Website section ki **Site Settings** mein hain. TRAX branding nahi badalta."
    },
    {
      "id": "portal_appearance",
      "title": "Branding and appearance",
      "permissions": [
        "settings",
        "settings.branding"
      ],
      "keywords": [
        "portal appearance",
        "portal theme",
        "portal name",
        "favicon",
        "dark mode logo",
        "portal colour",
        "portal color",
        "portal ka rang"
      ],
      "navigation": [
        "settings_branding"
      ],
      "en": "**Appearance** styles the portal your team uses. On the updated portal, open **Settings** and select **Branding**; a portal not yet updated shows an older **Branding** tab with **Open Appearance**, laid out differently. **Portal name** is what shows at the top of the sidebar and in the browser tab, with small pictures of both beside the field that follow your typing, and a note when the name is too long for the sidebar and will be cut off. Under **Brand colour**, pick a swatch or type a colour code; the portal repaints around you straight away, and **Fix it for me** appears when text on that colour would be hard to read. **Logos** has two slots, and they are independent. **Square icon** shows in the browser tab and at the top of your sidebar: PNG, WebP, JPG, SVG or ICO, up to 10 MB, square and 128 to 4096 px a side, and **Fit into a square** is offered when an otherwise good image is not square. **Full logo** shows on your sign-in page and your booking website: PNG, WebP, JPG or SVG, up to 10 MB, 400 to 6000 px wide and 100 to 3000 px tall. Best results are a PNG with a transparent background. Each card shows your image where it will really appear, and **Upload**, **Replace** and **Remove** work on that card only. The full logo is never used as the square icon: with no square icon, the tab and the sidebar badge show your portal name's initials on a tile in your brand colour. Nothing is kept until you select **Save changes**; **Reset** puts the saved branding back. Saving updates the portal for everyone on your team. Editing needs Branding edit rights; otherwise the page is view-only. Your customers' booking site is styled separately. TRAX does not change appearance.",
      "ur-Latn": "**Appearance** aap ki team ke portal ki look set karta hai. Naye portal par **Settings** kholein aur **Branding** chunein; jo portal abhi update nahi hua, us mein purana **Branding** tab aur **Open Appearance** hota hai, jiska layout alag hai. **Portal name** wo naam hai jo sidebar ke upar aur browser tab mein dikhta hai; field ke saath dono ki chhoti tasveerein aap ke likhne ke saath badalti hain, aur naam sidebar ke liye lamba ho to note aa jata hai ke wo kat jayega. **Brand colour** mein swatch chunein ya colour code likhein; portal foran us rang mein badal jata hai, aur us rang par text parhna mushkil ho to **Fix it for me** aata hai. **Logos** mein do slot hain aur dono alag alag hain. **Square icon** browser tab aur sidebar ke upar dikhta hai: PNG, WebP, JPG, SVG ya ICO, 10 MB tak, square aur har taraf 128 se 4096 px; tasveer theek ho magar square na ho to **Fit into a square** milta hai. **Full logo** aap ke sign-in page aur booking website par dikhta hai: PNG, WebP, JPG ya SVG, 10 MB tak, 400 se 6000 px chaura aur 100 se 3000 px lamba. Behtareen nateeja transparent background wali PNG se milta hai. Har card aap ki tasveer wahin dikhata hai jahan wo asal mein aayegi, aur **Upload**, **Replace** aur **Remove** sirf usi card par chalte hain. Full logo kabhi square icon ki jagah nahi lagta: square icon na ho to tab aur sidebar badge mein aap ke portal name ke initials aap ke brand rang ki tile par dikhte hain. **Save changes** dabaye baghair kuch save nahi hota; **Reset** save shuda branding wapas laata hai. Save karne se poori team ke liye portal badal jata hai. Edit ke liye Branding edit ki ijazat chahiye, warna page view-only hai. Customers ki booking site alag se style hoti hai. TRAX appearance nahi badalta."
    },
    {
      "id": "pending_bookings",
      "title": "Pending bookings",
      "permissions": [
        "pending_bookings"
      ],
      "keywords": [
        "pending bookings",
        "approve booking",
        "approve a booking",
        "reject booking",
        "booking request",
        "booking requests",
        "release hold",
        "booking approve kaise karein",
        "booking reject karni hai"
      ],
      "navigation": [],
      "en": "Open **Pending Bookings**; it appears under **Bookings** in the sidebar only when the account payment mode is manual. It lists website bookings whose card payment is on hold, with **Customer**, **Vehicle**, **Dates**, **Amount**, **Verification** and **Expiry** (time left on the hold). **Approve** and **Reject** appear only for staff with pending bookings edit permission. In **Approve Booking**, **Approve & Capture Payment** charges the held payment and sets the rental Active and the vehicle Rented; it is refused if another pending or active rental overlaps that vehicle's dates. In **Reject Booking**, **Rejection Reason (optional)** is saved with the payment, and **Reject & Release Hold** releases the hold, cancels the rental and its unpaid charges and sets the vehicle Available. If the hold cannot be released, nothing is changed. Use **Refresh** to reload. Bookings paid through the website checkout that captures immediately do not appear here. TRAX does not approve, reject, capture or release bookings or payments.",
      "ur-Latn": "**Pending Bookings** kholein; ye sidebar mein **Bookings** ke neeche sirf tab nazar aata hai jab account ka payment mode manual ho. Is list mein woh website bookings hain jin ki card payment hold par hai, saath **Customer**, **Vehicle**, **Dates**, **Amount**, **Verification** aur **Expiry** (hold ka baqi waqt). **Approve** aur **Reject** sirf pending bookings edit permission wale staff ko dikhte hain. **Approve Booking** mein **Approve & Capture Payment** held payment charge karta hai aur rental Active aur gaari Rented kar deta hai; agar usi gaari ki dates par koi aur pending ya active rental overlap ho to approval nahi hota. **Reject Booking** mein **Rejection Reason (optional)** payment ke saath save hota hai, aur **Reject & Release Hold** hold chhor deta hai, rental aur us ke unpaid charges cancel karta hai aur gaari Available kar deta hai. Agar hold release na ho sake to kuch change nahi hota. List dobara load karne ke liye **Refresh** dabayein. Jo website bookings checkout par foran charge ho jati hain woh yahan nahi aatin. TRAX bookings ya payments approve, reject, capture ya release nahi karta."
    },
    {
      "id": "blocked_customers",
      "title": "Blocked customers",
      "permissions": [
        "blocked_customers"
      ],
      "keywords": [
        "blocked customers",
        "block customer",
        "block a customer",
        "unblock customer",
        "add to blocklist",
        "blocklist",
        "blocked identity",
        "remove from blocklist",
        "customer block kaise karein",
        "unblock karna hai"
      ],
      "navigation": [
        "customers",
        "customer"
      ],
      "en": "Open **Customers** and select **Blocked** to see **Blocked Customers**; the button needs blocked customers view permission. Blocked people are left out of the main customer list. The **Blocked Customers** tab offers **View** and **Unblock**; unblocking lets the person make new rentals again and deactivates blocklist entries for their licence and ID numbers. The **Blocked Identities** tab lists blocklisted numbers with **Remove**. Staff with blocked customers edit permission can choose **Add to Blocklist**: **Identity Type**, **Identity Number** and **Reason** are required, **Customer Name** and **Notes (optional)** are not. New customers or identity verifications with that identity will be blocked, and a licence or ID card entry also blocks existing customers with the same number. To block one person, open their record, go to **Account** and turn on **Block this customer with us** (customers edit permission); this also blocklists their licence and ID numbers. TRAX does not block, unblock or verify anyone.",
      "ur-Latn": "**Customers** kholein aur **Blocked** dabayein to **Blocked Customers** khulega; is button ke liye blocked customers ki view permission chahiye. Blocked log main customer list mein nahi dikhte. **Blocked Customers** tab mein **View** aur **Unblock** hain; unblock karne se woh dobara naye rentals le sakte hain aur un ke licence aur ID numbers ki blocklist entries inactive ho jati hain. **Blocked Identities** tab mein blocklisted numbers aur **Remove** hai. Blocked customers edit permission wale staff **Add to Blocklist** chun sakte hain: **Identity Type**, **Identity Number** aur **Reason** zaroori hain, **Customer Name** aur **Notes (optional)** zaroori nahi. Is identity wale naye customers ya identity verifications block honge, aur licence ya ID card entry usi number wale mojooda customers ko bhi block kar deti hai. Kisi ek shakhs ko block karne ke liye us ka record kholein, **Account** mein jayein aur **Block this customer with us** on karein (customers edit permission); is se un ke licence aur ID numbers bhi blocklist ho jate hain. TRAX kisi ko block, unblock ya verify nahi karta."
    },
    {
      "id": "payments_record",
      "title": "Payments",
      "permissions": [
        "payments"
      ],
      "keywords": [
        "record payment",
        "record a payment",
        "take a payment",
        "manual payment",
        "cash payment",
        "bank transfer received",
        "rental payments stage",
        "payment darj",
        "raqam record"
      ],
      "navigation": [
        "rental",
        "rentals"
      ],
      "en": "To record money received for a rental, open the rental and choose **Payments** in its stage rail. The stage shows **Outstanding**, the **Charges** list and the **Payments** list; manual entries read **Recorded by hand** with no provider record. Select **Take a payment** (it reads **Nothing owed** when nothing is outstanding). In the **Take a payment** window, tick categories under **Apply to**, check **Amount**, then press the confirm button that states the amount and number of charges. The **Record Payment** dialog opens with that amount fixed. Choose **Method** (**Cash**, **Card**, **Transfer**, **Zelle**, **Check** or **Other**), set **Date**, add an optional **Reference**, then select **Record Payment**. If the same amount was recorded on this rental in the last 14 days, you are asked to confirm a possible duplicate. The payment is applied to the chosen charges; if applying fails, nothing is saved. The provider buttons in that dialog create a payment link rather than recording money already received. Use these controls only if your role allows it. TRAX does not record, charge or verify payments.",
      "ur-Latn": "Rental par aayi raqam darj karne ke liye rental kholein aur stage rail mein **Payments** chunein. Is stage mein **Outstanding**, **Charges** list aur **Payments** list dikhti hai; haath se darj entries par **Recorded by hand** likha hota hai aur provider record nahi hota. **Take a payment** dabayein (kuch baqi na ho to button par **Nothing owed** likha hota hai). **Take a payment** window mein **Apply to** ke neeche categories tick karein, **Amount** check karein, phir woh confirm button dabayein jis par amount aur charges ki tadaad likhi hoti hai. Phir **Record Payment** dialog usi amount ke saath khulta hai. **Method** (**Cash**, **Card**, **Transfer**, **Zelle**, **Check** ya **Other**) chunein, **Date** set karein, optional **Reference** likhein, aur **Record Payment** dabayein. Agar pichle 14 din mein isi rental par yehi amount record hui ho to duplicate ki confirmation maangi jati hai. Payment chuni hui charges par apply hoti hai; apply na ho sakay to kuch save nahi hota. Dialog ke provider buttons payment link banate hain, mili hui raqam record nahi karte. Ye controls sirf apni role ki ijazat ke mutabiq use karein. TRAX payment record, charge ya verify nahi karta."
    },
    {
      "id": "payments_review",
      "title": "Payments",
      "permissions": [
        "payments"
      ],
      "keywords": [
        "approve payment",
        "reject payment",
        "reverse payment",
        "pending review",
        "remove payment link",
        "payments list",
        "payment approve karna"
      ],
      "navigation": [],
      "en": "Open **Payments** from the sidebar to see payments across all rentals. The list opens on **This Month**; use **Period** (**7 Days**, **This Month**, **All Time**), the calendar button, **Method**, **Status** and the customer or vehicle search. Select a rental badge to open that rental, then choose **Payments** in its stage rail. Staff with payments edit permission see **Record Payment**, where **Customer** and **Vehicle** are required and the vehicle list shows that customer's active rentals. A **Pending Review** payment shows **Approve Payment** and **Reject Payment**; approving marks it approved and applies it to charges. Rejecting needs **Reason for Rejection**, and the dialog warns that **Reject & close rental** also ends the rental, frees the vehicle, writes off outstanding charges and emails the customer. To drop an unpaid duplicate link without touching the rental, use **Remove payment link** in the row menu. **Reverse Payment** appears only for eligible manual payments, needs **Reason for Reversal**, returns allocated charges to outstanding and cannot be undone. TRAX does not approve, reject, reverse or investigate payments.",
      "ur-Latn": "Sidebar se **Payments** kholein. List **This Month** par khulti hai; **Period** (**7 Days**, **This Month**, **All Time**), calendar button, **Method**, **Status** aur customer ya vehicle search use karein. Rental badge dabakar woh rental kholein, phir stage rail mein **Payments** chunein. Payments edit permission wale staff ko **Record Payment** dikhta hai; is mein **Customer** aur **Vehicle** zaroori hain aur vehicle list mein us customer ke active rentals aate hain. **Pending Review** payment par **Approve Payment** aur **Reject Payment** hote hain; approve karne se payment charges par apply hoti hai. Reject ke liye **Reason for Rejection** zaroori hai, aur dialog khabardar karta hai ke **Reject & close rental** poora rental band karta hai, gaari free karta hai, baqi charges write off karta hai aur customer ko email bhejta hai. Rental chheray baghair unpaid duplicate link hatana ho to row menu se **Remove payment link** use karein. **Reverse Payment** sirf eligible manual payments par aata hai, **Reason for Reversal** maangta hai, charges dobara outstanding karta hai aur undo nahi hota. TRAX payment approve, reject, reverse ya investigate nahi karta."
    },
    {
      "id": "invoices",
      "title": "Invoices",
      "permissions": [
        "invoices"
      ],
      "keywords": [
        "create invoice",
        "create an invoice",
        "send invoice",
        "delete invoice",
        "invoice email",
        "invoice pdf",
        "payment requests",
        "export invoices",
        "invoice bhejna",
        "invoice kahan"
      ],
      "navigation": [],
      "en": "Open **Invoices** from the sidebar. It has two tabs. **Invoices** lists rental invoices; they appear when rentals are created, and this page has no create button. Search by invoice number, customer or vehicle, filter by **Status**, set an **Invoice Date** range with **From** and **To**, and use **Clear Filters** to reset. The download icon exports the filtered list as a CSV file. Each row's menu offers **Send Email** and **Delete** to staff with invoices edit permission. **Send Email** opens **Send Invoice Email** with a preview, **Print / Save PDF** and **Send Email**; sending is disabled if the customer has no email address. **Delete** opens **Delete Invoice**; confirming with **Delete Invoice** removes the record permanently. The **Payment Requests** tab lists payment links and charges sent to customers with **Sent**, **Customer**, **For**, **Amount** and **Status**, and can be searched by customer or type. TRAX does not create, send or delete invoices and cannot confirm whether an invoice has been paid.",
      "ur-Latn": "Sidebar se **Invoices** kholein. Is mein do tabs hain. **Invoices** tab mein rental invoices hoti hain; ye rental banne par khud aati hain, is page par invoice banane ka koi button nahi. Invoice number, customer ya vehicle se search karein, **Status** se filter karein, **From** aur **To** se **Invoice Date** range lagayein, aur **Clear Filters** se reset karein. Download icon filtered list ko CSV file mein export karta hai. Har row ke menu mein invoices edit permission wale staff ko **Send Email** aur **Delete** milte hain. **Send Email** se **Send Invoice Email** khulta hai jis mein preview, **Print / Save PDF** aur **Send Email** hain; customer ki email na ho to bhejna disabled rehta hai. **Delete** se **Delete Invoice** khulta hai; **Delete Invoice** dabane se record hamesha ke liye delete ho jata hai. **Payment Requests** tab mein customers ko bheje gaye payment links aur charges **Sent**, **Customer**, **For**, **Amount** aur **Status** ke saath dikhte hain, aur customer ya type se search ho sakta hai. TRAX invoice banata, bhejta ya delete nahi karta, aur ye confirm nahi kar sakta ke invoice pay hui ya nahi."
    },
    {
      "id": "fines_record",
      "title": "Fines",
      "permissions": [
        "fines"
      ],
      "keywords": [
        "add fine",
        "add a fine",
        "record a fine",
        "new traffic fine",
        "parking ticket",
        "speeding ticket",
        "fine evidence",
        "challan add",
        "jurmana darj"
      ],
      "navigation": [],
      "en": "Open **Fines** and choose **Add Fine**; it is shown only to staff with fines edit permission. You can also use **Add a charge** in a rental's **Payments** stage, which preselects that customer and rental, or **Add a fine** in the customer record's **Fines** section. The **Add New Fine** dialog requires **Fine Type** (**Parking Citation**, **Speeding Violation**, or **Other** with a custom name), **Customer**, **Rental**, **Issue Date**, **Due Date** and **Amount**. Choosing the rental sets the vehicle and pre-fills **Reference Number** with the plate; replace it with the ticket reference if you have one. **Issue Date** cannot be in the future; **Due Date** defaults to 28 days later and cannot be earlier. **Notes** and **Evidence Files** (up to 10 files, 20MB each) are optional. **Create Fine** stays disabled until the form is valid. The fine is saved as **Open** and a Fine charge is added to that rental. TRAX does not create, charge, waive or collect fines.",
      "ur-Latn": "**Fines** kholein aur **Add Fine** chunein; ye sirf fines edit permission wale staff ko dikhta hai. Rental ke **Payments** stage mein **Add a charge** se bhi fine add ho sakta hai (customer aur rental pehle se select hote hain), ya customer record ke **Fines** section mein **Add a fine** se. **Add New Fine** dialog mein **Fine Type** (**Parking Citation**, **Speeding Violation**, ya **Other** ke saath custom naam), **Customer**, **Rental**, **Issue Date**, **Due Date** aur **Amount** zaroori hain. Rental chunne par vehicle khud set ho jati hai aur **Reference Number** mein plate aa jati hai; challan ka reference ho to woh likh dein. **Issue Date** future ki nahi ho sakti; **Due Date** khud 28 din baad set hoti hai aur issue date se pehle nahi ho sakti. **Notes** aur **Evidence Files** (10 files tak, har file 20MB tak) optional hain. Form theek bharne tak **Create Fine** disabled rehta hai. Fine **Open** status mein save hota hai aur us rental par Fine charge lag jata hai. TRAX khud fine add, charge, waive ya collect nahi karta."
    },
    {
      "id": "fines",
      "title": "Fines",
      "permissions": [
        "fines"
      ],
      "keywords": [
        "waive fine",
        "fine payment",
        "overdue fines",
        "fines list",
        "toll statement",
        "fine status",
        "challan waive",
        "jurmana maaf"
      ],
      "navigation": [],
      "en": "Open **Fines** from the sidebar to reach **Fines Management**. Search by reference, vehicle or customer, or filter by **Status**, **Issue Date** and **Due Date**; an open fine past its due date shows **Overdue**. Select the eye icon under **View** to open **Fine Details**, which has **Overview** and **Documents** tabs. For an **Open** fine, the row menu offers **Record Payment** and **Waive Fine** to staff with fines edit permission, and the detail page shows the same two buttons. **Record Payment** opens the payment dialog with the fine amount already set, and the fine status updates after the payment is recorded. **Waive Fine** acts immediately with no confirmation step: the fine becomes **Waived** and its charge is removed. With edit permission you can tick rows and use **Charge Selected**, **Waive Selected** or **Email Statement + Pay Link**; each asks for confirmation, and the email option needs unpaid fines for one customer and one rental with an email on file. TRAX does not look up, pay, charge or waive fines.",
      "ur-Latn": "Sidebar se **Fines** kholein, **Fines Management** screen aa jayegi. Reference, vehicle ya customer se search karein, ya **Status**, **Issue Date** aur **Due Date** se filter karein; due date guzarne wala open fine **Overdue** dikhata hai. **View** column mein aankh wale icon se **Fine Details** khulta hai, jis mein **Overview** aur **Documents** tabs hain. **Open** fine ke row menu mein fines edit permission wale staff ko **Record Payment** aur **Waive Fine** milte hain; detail page par bhi yehi do buttons hain. **Record Payment** payment dialog kholta hai jis mein fine ki amount pehle se set hoti hai, aur payment record hone ke baad fine ka status update ho jata hai. **Waive Fine** foran chal jata hai, koi confirmation nahi maangta: fine **Waived** ho jata hai aur us ka charge hat jata hai. Edit permission ho to rows tick karke **Charge Selected**, **Waive Selected** ya **Email Statement + Pay Link** use karein; har aik confirmation maangta hai, aur email option ke liye aik hi customer aur aik hi rental ke unpaid fines aur customer ki email zaroori hai. TRAX khud fines dhoondta, pay, charge ya waive nahi karta."
    },
    {
      "id": "expenses",
      "title": "Expenses",
      "permissions": [
        "expenses"
      ],
      "keywords": [
        "expenses",
        "add expense",
        "expense tracker",
        "vehicle expense",
        "business expense",
        "kharcha",
        "kharchay add"
      ],
      "navigation": [],
      "en": "Expense tracking is not offered in this portal. **Expenses** is not listed in the sidebar, and opening the Expenses page directly shows a not-found page, whatever your role. The sidebar's finance entries are **Payments**, **Invoices** and **Fines**; managers see only the ones they have been granted. TRAX cannot add, edit or delete expenses, and it cannot make the Expenses tracker available.",
      "ur-Latn": "Is portal mein expense tracking available nahi hai. Sidebar mein **Expenses** nahi hai, aur Expenses page seedha kholne par not-found page aata hai, chahe aap ki role koi bhi ho. Sidebar mein finance ke liye **Payments**, **Invoices** aur **Fines** hain; managers ko sirf woh dikhte hain jin ki unhein ijazat mili ho. TRAX expenses add, edit ya delete nahi karta, aur Expenses tracker ko available bhi nahi kar sakta."
    },
    {
      "id": "insurances",
      "title": "Insurance",
      "permissions": [
        "insurances"
      ],
      "keywords": [
        "insurance policies",
        "bonzah policy",
        "generate insurance",
        "verify insurance",
        "customer own insurance",
        "upload insurance",
        "insurance kaise add karein",
        "bima policy"
      ],
      "navigation": [],
      "en": "To add cover to one rental, use that rental's **Insurance** stage. The Insurances page is not in the sidebar. Its **Policies** tab lists Bonzah policies and uploaded insurance documents with **Policy Status** and **Payment**; search by document or customer name, or toggle **Bonzah Only**. **Generate Insurance** opens **Generate Bonzah Insurance**: pick a rental, choose coverage, then **Purchase Insurance**, which creates the policy and adds an insurance charge to the rental; collect payment afterwards. It is disabled under a **New insurance policies are turned off** banner when Bonzah cannot sell; existing policies stay viewable. On Bonzah rows, **Add Payment** shows while the charge is **Unpaid** or **Partial**, **PDF** downloads the policy and **View Rental** opens the rental. For a customer's own policy, open **AI Verifications**, select **Verify Insurance**, add PDF, JPG, PNG, WebP or HEIC files, then upload and verify; use **Attach** to link it to an active or pending rental. Managers need the Insurances grant. TRAX does not buy, verify or attach cover, take payments, or confirm a vehicle is insured.",
      "ur-Latn": "Kisi aik rental par cover lagana ho to us rental ka **Insurance** stage use karein. Insurances page sidebar mein nahi hai. Is ke **Policies** tab mein Bonzah policies aur upload shuda insurance documents **Policy Status** aur **Payment** ke saath nazar aate hain; document ya customer ke naam se search karein, ya **Bonzah Only** lagayein. **Generate Insurance** se **Generate Bonzah Insurance** khulta hai: rental chunein, coverage select karein, phir **Purchase Insurance** dabayein; is se policy banti hai aur rental par insurance charge lag jata hai, payment baad mein lein. Jab Bonzah bech nahi sakta to **New insurance policies are turned off** banner aata hai aur button disabled hota hai; purani policies dekhi ja sakti hain. Bonzah rows par **Add Payment** tab dikhta hai jab charge **Unpaid** ya **Partial** ho, **PDF** policy download karta hai aur **View Rental** rental kholta hai. Customer ki apni policy ke liye **AI Verifications** kholein, **Verify Insurance** chunein, PDF, JPG, PNG, WebP ya HEIC files add karke upload aur verify karein; phir **Attach** se active ya pending rental se jorein. Managers ko Insurances grant chahiye. TRAX insurance khareedta, verify ya attach nahi karta, payment nahi leta, aur gaari insured hone ki tasdeeq nahi karta."
    },
    {
      "id": "agreements",
      "title": "Agreements",
      "permissions": [
        "agreements"
      ],
      "keywords": [
        "agreements list",
        "all agreements",
        "void agreement",
        "cancel agreement",
        "generate agreement",
        "pending signature",
        "export agreements",
        "agreement cancel karna",
        "agreements kahan hain"
      ],
      "navigation": [],
      "en": "To send or resend one rental's agreement, use that rental's **Agreement** stage. The full Agreements list is not in the sidebar; open it from **All agreements** on the **BoldSign** card in Integrations, or from an Agreements search result. Rows show **Status** as **Signed** or **Pending signature**. **Generate Agreement** opens a rental picker, then **Configure Agreement**: choose an **Agreement Type** (PAYG, installment and extension options unlock only when the rental has them; extensions also need an **Extension Period**) and select **Generate & Send**. On a pending row, **Sign** opens the signing page in a dialog, the send icon resends the signing notification, and the ban icon asks **Void Agreement?**; **Yes, Void Agreement** revokes the BoldSign envelope so the customer can no longer sign. The eye and download icons view or download the document. **Export PDFs** downloads a ZIP of summary records, not signed copies. Managers need the Agreements grant to open the page. TRAX does not generate, sign, resend or void agreements.",
      "ur-Latn": "Kisi aik rental ka agreement bhejna ya dobara bhejna ho to us rental ka **Agreement** stage use karein. Poori Agreements list sidebar mein nahi hai; Integrations mein **BoldSign** card par **All agreements** se, ya Agreements search result se kholein. Rows mein **Status** **Signed** ya **Pending signature** dikhta hai. **Generate Agreement** rental picker kholta hai, phir **Configure Agreement** mein **Agreement Type** chunein (PAYG, installment aur extension options sirf tab khulte hain jab rental mein woh hon; extension ke liye **Extension Period** bhi chahiye) aur **Generate & Send** dabayein. Pending row par **Sign** signing page dialog mein kholta hai, send icon signing notification dobara bhejta hai, aur ban icon **Void Agreement?** poochta hai; **Yes, Void Agreement** BoldSign envelope revoke kar deta hai aur customer sign nahi kar sakta. Eye aur download icons document dekhne ya download karne ke liye hain. **Export PDFs** summary records ki ZIP deta hai, signed copies nahi. Page kholne ke liye managers ko Agreements grant chahiye. TRAX agreement generate, sign, resend ya void nahi karta."
    },
    {
      "id": "audit_logs",
      "title": "Audit logs",
      "permissions": [
        "audit_logs"
      ],
      "keywords": [
        "audit log",
        "audit logs",
        "activity log",
        "who changed",
        "change history",
        "export audit csv",
        "kis ne badla"
      ],
      "navigation": [
        "audit_logs"
      ],
      "en": "Select your organization name at the top of the sidebar and choose **Audit Logs**. Managers see it only with the **Audit Logs** grant, which is view only. Each row shows **Date & Time**, **Action**, **Entity**, **Details** and **Performed By**; hover over the details to see everything recorded, and **System** means no staff member is linked. Filter by entity type, action, **Performed by** and a **From date** to **To date** range; **Clear** removes the filters. Entries show 25 per page with **Previous** and **Next**, and at most the 500 most recent matching entries are loaded. **Export CSV** downloads those loaded entries. The **Performed by** list offers only active staff. Actions ending in **View** or **Warn** record that a form or warning was shown, not that a change was saved. Entries cannot be edited or deleted on this page. TRAX cannot read or search audit entries.",
      "ur-Latn": "Sidebar ke upar organization ka naam select karein aur **Audit Logs** chunein. Manager ko ye sirf **Audit Logs** grant ke saath dikhta hai, jo view only hai. Har row mein **Date & Time**, **Action**, **Entity**, **Details** aur **Performed By** hai; poori recorded detail ke liye details par hover karein, aur **System** ka matlab hai koi staff member linked nahi. Entity type, action, **Performed by** aur **From date** se **To date** tak filter karein; **Clear** filters hata deta hai. Ek page par 25 entries aati hain, **Previous** aur **Next** se page badlein, aur zyada se zyada 500 taaza matching entries load hoti hain. **Export CSV** yehi loaded entries download karta hai. **Performed by** list mein sirf active staff hain. **View** ya **Warn** par khatam hone wale actions sirf form ya warning dikhne ka record hain, change save hone ka nahi. Is page par entries edit ya delete nahi hotin. TRAX audit entries parh ya search nahi sakta."
    },
    {
      "id": "dashboard",
      "title": "Dashboard",
      "permissions": [],
      "keywords": [
        "dashboard",
        "home dashboard",
        "dashboard cards",
        "home screen",
        "attention required now",
        "coming and going",
        "on your desk",
        "setup guide",
        "dashboard par kya hai"
      ],
      "navigation": [
        "rental_create",
        "availability"
      ],
      "en": "Open **Dashboard** for today at a glance. **New Rental**, beside the first section title, needs rentals edit permission. **On your desk** starts with a card for the new features Drive247 has announced to your company, when there are any: a picture, a heading and one line, several cards taking turns. Select the card (**See how it works**) to open a short slides dialog with **Back**, **Next** and **Got it**; on the last slide an optional button opens the page where the feature lives. With no feature announced there is no card, and the other two cards take the full width. A feature dialog can also open by itself on the dashboard; there **Don't show again** stops it opening by itself, and the card stays. Next come **Sit down with these once** feature guides and **Reminders**, where **Add a note** saves a note with an optional time. **Today** shows **Attention required now**, **Coming and going** (pickups and returns dated today for pending or active rentals, in your business timezone), **Money today** and **Everything else on today**. Vehicles not returned covers rentals up to 30 days past their end date, excluding pay-as-you-go and auto-extend; older ones count as rentals never closed off. In **How it's going**, **Who and what earns**, **Revenue and bookings** and most **Other stats** are sample figures, not your data. Card rows and footer links do not open pages yet. Managers see only items for areas they are granted. TRAX does not read or calculate these figures.",
      "ur-Latn": "**Dashboard** par aaj ka haal ek nazar mein milta hai. Pehle section title ke saath **New Rental** button hai; is ke liye rentals edit permission chahiye. **On your desk** mein pehle un naye features ka card hota hai jo Drive247 ne aap ki company ke liye announce kiye hon (agar koi ho): tasveer, heading aur ek line, zyada features hon to cards baari baari aate hain. Card (**See how it works**) par click karne se slides wala chhota dialog khulta hai jis mein **Back**, **Next** aur **Got it** hain; aakhri slide par ek optional button feature ke page par le jata hai. Koi feature announce na ho to card nahi hota aur baqi do cards poori width le lete hain. Feature dialog dashboard par khud bhi khul sakta hai; wahan **Don't show again** se woh khud nahi khulega, card phir bhi rehta hai. Us ke baad **Sit down with these once** guides aur **Reminders** hain; **Add a note** se note time ke saath bhi save hota hai. **Today** mein **Attention required now**, **Coming and going** (pending ya active rentals ke aaj ke pickups aur returns, business timezone ke mutabiq), **Money today** aur **Everything else on today** hain. Vehicles not returned mein woh rentals hain jin ki end date 30 din ke andar guzri ho (pay-as-you-go aur auto-extend nahi); purani rentals never closed off mein ginti hain. **How it's going** mein **Who and what earns**, **Revenue and bookings** aur zyada tar **Other stats** sample figures hain, aap ka data nahi. Card rows aur footer links abhi page nahi kholte. Managers ko sirf granted areas ke items dikhte hain. TRAX ye figures parhta ya calculate nahi karta."
    },
    {
      "id": "bonzah",
      "title": "Integrations",
      "permissions": [
        "settings.integrations"
      ],
      "keywords": [
        "bonzah",
        "bonzah insurance",
        "insurance setup"
      ],
      "navigation": [
        "integrations"
      ],
      "en": "Open **Integrations → Bonzah** in V2. The setup panel shows **Apply**, **Review**, **Activate** and **Sell**. Apply with the details requested there, then follow the panel's actual review status. Approval, saved credentials, live activation and enabling cover are distinct steps; an application alone does not make insurance available. **Test connection** belongs to the native integration panel. Keep credentials there, not in chat. Rental insurance options depend on eligibility, rental type and the tenant's setup; pay-as-you-go does not use the same selection flow. TRAX can explain this workflow but has not checked your provider connection, policy or coverage and cannot activate insurance.",
      "ur-Latn": "V2 mein **Integrations → Bonzah** kholein. Panel **Apply**, **Review**, **Activate** aur **Sell** stages dikhata hai. Required details se apply karein aur panel ka asal review status follow karein. Approval, credentials save karna, live activation aur cover enable karna alag steps hain. Sirf application se insurance available nahi hota. **Test connection** native panel mein hai. Credentials wahin rakhein, chat mein nahi. Rental type, eligibility aur tenant setup insurance options badalte hain; pay-as-you-go ka flow alag hai. TRAX connection, policy ya coverage verify ya activate nahi karta."
    },
    {
      "id": "billing_subscription",
      "title": "Subscription",
      "permissions": [
        "settings.subscription"
      ],
      "keywords": [
        "subscription",
        "billing",
        "update billing card",
        "cancel subscription",
        "cancel my subscription",
        "plan details",
        "drive247 plan",
        "subscription cancel karna"
      ],
      "navigation": [],
      "en": "**Billing** is what your business pays Drive247, not payments from renters. Open **Billing** in the sidebar or **Billing & subscription** in the organization menu; every staff role can open it. **Plan Details** shows your plan, status, amount, current period and next payment or access end date. Under **Billing Methods**, select **Add payment method** or **Manage payment methods**, then **Add or replace card**; card details are entered on Stripe's secure page, where choosing a primary card or removing one is also handled. **Credits** covers credit bought from Drive247, and **Invoices & Receipts** lists past invoices. If a payment failed, **Payment required** offers **Update payment method** and, when available, **Pay your pending invoice**. Without an active plan the page shows **Choose your plan**. To cancel, select **Contact support** under **Need to cancel?**, optionally add a reason and select **Send request**; nothing is cancelled and billing continues until the team contacts you. TRAX cannot see billing amounts, change plans or cards, or cancel a subscription.",
      "ur-Latn": "**Billing** wo hai jo aap ka business Drive247 ko pay karta hai, renters ki payments nahi. Sidebar mein **Billing** ya organization menu mein **Billing & subscription** kholein; har staff role isay khol sakta hai. **Plan Details** mein plan, status, amount, current period aur agli payment ya access khatam hone ki date hai. **Billing Methods** mein **Add payment method** ya **Manage payment methods**, phir **Add or replace card** chunein; card details Stripe ke secure page par bharte hain, aur primary card chunna ya card hatana bhi wahin hota hai. **Credits** Drive247 se khareeda gaya credit hai, aur **Invoices & Receipts** mein purani invoices hain. Payment fail ho to **Payment required** par **Update payment method** aur, agar mojood ho, **Pay your pending invoice** milta hai. Active plan na ho to **Choose your plan** dikhta hai. Cancel ke liye **Need to cancel?** ke neeche **Contact support**, chahein to wajah likhein, phir **Send request**; kuch cancel nahi hota aur team ke rabta karne tak billing jari rehti hai. TRAX billing amount nahi dekhta, plan ya card nahi badalta aur subscription cancel nahi karta."
    },
    {
      "id": "staff_add",
      "title": "Staff administration",
      "permissions": [
        "settings"
      ],
      "keywords": [
        "add staff",
        "add a staff member",
        "add user",
        "new staff member",
        "invite staff",
        "create user account",
        "manage users",
        "add team member",
        "manage team",
        "naya staff",
        "staff add karna"
      ],
      "navigation": [],
      "en": "Only a head admin can add staff. Open **Settings** with the gear beside your organization name, or **Organization settings** in its menu, then select **Team** under **Business** (only head admins see it). On **Manage Users**, select **Add User**. In **Add New User**, enter **Full Name**, **Email Address** and **Role**: **Admin** (full access except user management), **Manager** (custom tab access), **Operations** (day-to-day operations) or **Viewer** (read-only). Head Admin cannot be assigned here. A Manager needs at least one tab ticked under **Tab Permissions**. Select **Create User**. The account gets a temporary password and a welcome email with login details is sent. **User Created Successfully** shows the **Temporary Password** only once; copy it before selecting **I've Saved the Credentials**, because it cannot be retrieved later. If the welcome email fails, the notice says so and you must give the password to the person yourself. The new user is asked to change the password after signing in and shows a **Temp Password** badge. An email already used on this account is rejected. TRAX cannot create staff accounts, see passwords or send the welcome email.",
      "ur-Latn": "Staff sirf head admin add kar sakta hai. Organization ke naam ke saath wale gear, ya us ke menu mein **Organization settings**, se **Settings** kholein, phir **Business** ke neeche **Team** chunein (ye sirf head admin ko dikhta hai). **Manage Users** par **Add User** dabayein. **Add New User** mein **Full Name**, **Email Address** aur **Role** bharein: **Admin** (user management ke ilawa full access), **Manager** (custom tab access), **Operations** (rozana ka kaam) ya **Viewer** (sirf dekh sakta hai). Head Admin yahan assign nahi hota. Manager ke liye **Tab Permissions** mein kam az kam ek tab tick karna zaroori hai. **Create User** dabayein. Account temporary password ke saath banta hai aur login details wali welcome email jati hai. **User Created Successfully** mein **Temporary Password** sirf ek dafa dikhta hai; **I've Saved the Credentials** dabane se pehle copy kar lein, baad mein wapas nahi milega. Welcome email na ja sake to notice bata dega; phir password khud dein. Naye user ko sign in ke baad password badalne ka kaha jata hai aur **Temp Password** badge dikhta hai. Is account par pehle se maujood email qubool nahi hoti. TRAX staff account nahi banata, password nahi dekhta aur welcome email nahi bhejta."
    },
    {
      "id": "staff_roles",
      "title": "Staff administration",
      "permissions": [
        "settings"
      ],
      "keywords": [
        "change role",
        "user role",
        "manager permissions",
        "manager access",
        "tab permissions",
        "staff permissions",
        "viewer role",
        "role badalna",
        "staff ki ijazat"
      ],
      "navigation": [],
      "en": "Only a head admin can change roles and manager permissions. Open **Settings**, select **Team** under **Business**, then open the three-dot **Actions** menu on the person's row. **Change Role** opens **Change User Role**: choose a **New Role** and select **Update Role**. **Admin** has full access except user management, **Manager** gets only the tabs you grant, **Operations** covers day-to-day work and **Viewer** is read-only. Head Admin rows have no **Change Role** option, and nobody can change their own role. For a Manager, tick tabs under **Tab Permissions** and switch each between **View** and **Edit**; new ticks start as View, and tabs marked **View only** cannot be edited. Settings sub-tabs such as **General**, **Branding** and **Templates** appear only after **Settings** is ticked, and a manager needs both. At least one tab is required. For an existing manager use **Edit Permissions**, then **Save Permissions**. Managers never see **Team** and can never open **Manage Users**. TRAX cannot change roles or permissions.",
      "ur-Latn": "Roles aur manager permissions sirf head admin badal sakta hai. **Settings** kholein, **Business** ke neeche **Team** chunein, phir us shakhs ki row ka teen-dot **Actions** menu kholein. **Change Role** se **Change User Role** khulta hai: **New Role** chunein aur **Update Role** dabayein. **Admin** ko user management ke ilawa full access hai, **Manager** ko sirf diye gaye tabs, **Operations** rozana ka kaam karta hai aur **Viewer** sirf dekh sakta hai. Head Admin row mein **Change Role** nahi hota, aur koi apna role khud nahi badal sakta. Manager ke liye **Tab Permissions** mein tabs tick karein aur har ek ko **View** ya **Edit** par rakhein; naya tick View se shuru hota hai, aur **View only** tabs edit nahi ho sakte. **General**, **Branding** ya **Templates** jaise Settings sub-tabs tabhi dikhte hain jab **Settings** tick ho, aur manager ko dono chahiye. Kam az kam ek tab zaroori hai. Maujooda manager ke liye **Edit Permissions**, phir **Save Permissions**. Manager ko **Team** nahi dikhta aur woh **Manage Users** kabhi nahi khol sakta. TRAX roles ya permissions nahi badalta."
    },
    {
      "id": "staff_deactivate",
      "title": "Staff administration",
      "permissions": [
        "settings"
      ],
      "keywords": [
        "deactivate user",
        "deactivate staff",
        "remove staff access",
        "reactivate user",
        "reset staff password",
        "inactive user",
        "staff band karna"
      ],
      "navigation": [],
      "en": "Only a head admin can deactivate staff. Open **Settings**, select **Team** under **Business**, open the three-dot **Actions** menu on the person's row and choose **Deactivate**. It applies immediately, with no confirmation step, and the status changes to **Inactive**. An inactive account cannot sign in, and the person's existing sessions are signed out. You cannot deactivate yourself. The person stays in the list; choose **Activate** on the same row to restore access. To issue a new password instead, choose **Reset Password**, use **Generate** or type one under **New Password**, copy it, then select **Reset Password**. A **Can't sign in** badge means the row has no login account. Activation and deactivation are recorded in **Audit Logs**. TRAX cannot deactivate, activate or reset passwords for staff.",
      "ur-Latn": "Staff ko sirf head admin deactivate kar sakta hai. **Settings** kholein, **Business** ke neeche **Team** chunein, us shakhs ki row ka teen-dot **Actions** menu kholein aur **Deactivate** chunein. Ye foran lagu hota hai, koi confirmation nahi aati, aur status **Inactive** ho jata hai. Inactive account sign in nahi kar sakta aur us ke maujooda sessions sign out ho jate hain. Aap khud ko deactivate nahi kar sakte. Shakhs list mein rehta hai; access wapas dene ke liye usi row par **Activate** chunein. Naya password dene ke liye **Reset Password** chunein, **Generate** dabayein ya **New Password** mein khud likhein, copy karein, phir **Reset Password** dabayein. **Can't sign in** badge ka matlab hai us row ka login account nahi hai. Activate aur deactivate **Audit Logs** mein record hote hain. TRAX staff ko deactivate, activate ya password reset nahi karta."
    },
    {
      "id": "plates",
      "title": "Plates",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "license plate",
        "licence plate",
        "add plate",
        "number plate",
        "plate status",
        "plate document",
        "export plates",
        "number plate add karna"
      ],
      "navigation": [],
      "en": "**Plates Management** is not in the sidebar; reach it from search. Select **Add Plate** to open **Add New Plate**. **Plate Number** and **Status** (**Ordered**, **Received**, **Assigned** or **Expired**) are required; the number is saved in capitals without spaces and must be unique. **Vehicle** becomes required when status is **Assigned**, and **Order Date** cannot be in the future for **Received** or **Assigned** plates. **Supplier**, cost, **Retention Document Reference**, **Notes** and a document chosen with **Choose File** (PDF, image or Word file, max 10MB) are optional. Select **Add Plate** to save; linking a vehicle also records the change in that vehicle's history. Filter by status or by **Has Document** / **No Document**, use the search box, and **Export CSV** to download the filtered list. Click a plate number to copy it. In a row's menu, **Edit** reopens the form (save with **Update Plate**) and **View History** shows the plate's timeline. TRAX does not create, edit or delete plates.",
      "ur-Latn": "**Plates Management** sidebar mein nahi hai; search se kholein. **Add Plate** dabayein, **Add New Plate** khulega. **Plate Number** aur **Status** (**Ordered**, **Received**, **Assigned** ya **Expired**) zaroori hain; number capital letters mein baghair spaces save hota hai aur unique hona chahiye. Status **Assigned** ho to **Vehicle** zaroori hai, aur **Received** ya **Assigned** plate ki **Order Date** aane wali tareekh nahi ho sakti. **Supplier**, cost, **Retention Document Reference**, **Notes** aur **Choose File** se document (PDF, image ya Word file, zyada se zyada 10MB) optional hain. Save ke liye **Add Plate** dabayein; gaari link karne par us gaari ki history mein bhi entry banti hai. Status ya **Has Document** / **No Document** se filter karein, search box use karein, aur filtered list ke liye **Export CSV** dabayein. Plate number par click karne se copy ho jata hai. Row menu mein **Edit** form dobara kholta hai (**Update Plate** se save) aur **View History** plate ki timeline dikhata hai. TRAX plates banata, edit ya delete nahi karta."
    },
    {
      "id": "plate_assign",
      "title": "Plates",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "assign plate",
        "unassign plate",
        "replace plate",
        "mark plate expired",
        "delete plate",
        "plate history",
        "plate gaari par lagana",
        "plate hatana"
      ],
      "navigation": [],
      "en": "In **Plates Management**, open a plate's row menu. **Assign** appears when the plate has no vehicle and opens **Assign Plate to Vehicle**; **Select Vehicle** is required and lists vehicles with Available status. If that vehicle already has a plate, **Plate Replacement Required** warns that its current plate will be set to **Received**; confirm with **Replace & Assign**, otherwise **Assign Plate**. **Assignment Note (Optional)** is added to the vehicle's history. Assigning sets the plate to **Assigned**. **Unassign** removes the vehicle and sets the plate to **Received**. **Mark Expired** appears on any plate that is not already expired. **Delete** is disabled for assigned plates, so unassign first; on an unassigned plate it deletes straight away with no confirmation. **View History** shows the plate's timeline. TRAX does not assign, unassign, expire or delete plates.",
      "ur-Latn": "**Plates Management** mein plate ka row menu kholein. Jab plate ke saath koi gaari na ho to **Assign** dikhta hai aur **Assign Plate to Vehicle** kholta hai; **Select Vehicle** zaroori hai aur is mein Available status wali gaariyan aati hain. Agar us gaari par pehle se plate lagi ho to **Plate Replacement Required** batata hai ke purani plate **Received** ho jayegi; **Replace & Assign** se confirm karein, warna **Assign Plate** dabayein. **Assignment Note (Optional)** gaari ki history mein likha jata hai. Assign karne se plate **Assigned** ho jati hai. **Unassign** gaari hata kar plate ko **Received** kar deta hai. **Mark Expired** har us plate par dikhta hai jo pehle se expired na ho. Assigned plate par **Delete** disabled hai, pehle unassign karein; unassigned plate par yeh foran, baghair confirmation, delete kar deta hai. **View History** plate ki timeline dikhata hai. TRAX plates assign, unassign, expire ya delete nahi karta."
    },
    {
      "id": "credits",
      "title": "Credits",
      "permissions": [
        "settings.subscription"
      ],
      "keywords": [
        "buy credits",
        "credit top up",
        "top up credits",
        "auto refill",
        "auto-refill",
        "e-sign credits",
        "credits kaise add",
        "auto refill kaise"
      ],
      "navigation": [],
      "en": "Credits are platform credit your business buys from Drive247 to pay for e-signatures, verifications and messages; they are not renter payments. Open **Billing** in the sidebar and scroll to **Credits**. **Live credits** shows what remains. Set **Amount to buy** with the minus and plus buttons or by typing (at least 5 credits), then select the buy button to open Stripe checkout; afterwards you return to the same screen. Expand the usage and settings panel for **Transaction History**, the **Usage History** chart with service and period filters, and **Auto-Refill Settings**: turn on **Enable Auto-Refill**, set **When balance drops below** and **Top up amount**, then select **Save Settings**. Auto-refill charges your saved payment method. If Billing shows **Choose your plan** or **Payment required**, the Credits section is not on that screen. TRAX does not buy credits, change auto-refill or check your credit balance.",
      "ur-Latn": "Credits woh platform credit hain jo aapka business Drive247 se khareedta hai; in se e-signatures, verifications aur messages ki payment hoti hai, ye renters ki payments nahi. Sidebar se **Billing** kholein aur neeche **Credits** tak jayein. **Live credits** baqi credits dikhata hai. **Amount to buy** minus/plus buttons ya type karke set karein (kam az kam 5 credits), phir buy button dabayein; Stripe checkout khulega aur payment ke baad aap isi screen par wapas aayenge. Usage aur settings wala panel kholein: wahan **Transaction History**, service aur period filters wala **Usage History** chart, aur **Auto-Refill Settings** hain. **Enable Auto-Refill** on karein, **When balance drops below** aur **Top up amount** set karein, phir **Save Settings** dabayein. Auto-refill aapka saved payment method charge karta hai. Agar Billing par **Choose your plan** ya **Payment required** dikhe to wahan Credits section nahi hota. TRAX credits nahi khareedta, auto-refill nahi badalta aur credit balance check nahi karta."
    },
    {
      "id": "human_support",
      "title": "Human support conversations",
      "permissions": [],
      "keywords": [
        "support",
        "human",
        "ticket",
        "communicate",
        "reply",
        "support se baat",
        "my tickets"
      ],
      "navigation": [],
      "en": "In V2, choose **Support** in your profile menu, or Open Support in the TRAX header, to open the portal's Support section. TRAX closes and keeps your AI conversation. Support lists your own tickets: open one to read its messages and reply, or choose New request to start one. You can attach up to three screenshots or PDFs (10 MB each) to a message, and support can send files back the same way. When TRAX cannot resolve an issue it creates the support ticket itself and gives you its reference and an Open support ticket button, which brings you to that conversation here. Opening Support or the New ticket composer submits nothing; your own first Send creates that ticket. After a confirmed submission, follow the ticket reference and reply in the same conversation. A reply to a resolved ticket reopens that issue. Use New request for a separate problem. Human support messaging does not depend on the AI model. If support storage is unavailable, the interface reports that limitation; it must not claim your message was sent. Do not include credentials, card details or identity documents. Messages do not change bookings or payments.",
      "ur-Latn": "V2 mein apne profile menu ka **Support** ya TRAX header ka Open Support chunein; portal ka Support section khul jata hai aur TRAX band ho kar apni AI conversation mehfooz rakhta hai. Support mein aap ke apne tickets hote hain: kisi ko khol kar messages parhein aur reply karein, ya New request se naya masla likhein. Har message ke saath teen tak screenshots ya PDF (har ek 10 MB tak) bhej sakte hain, aur support bhi isi tarah files bhej sakta hai. Jo issue TRAX hal nahi kar pata, us ka support ticket TRAX khud bana deta hai aur asli reference ke saath Open support ticket button deta hai jo isi section mein wohi conversation kholta hai. Sirf Support ya New ticket composer kholne se ticket nahi banta; aap ka pehla Send banata hai. Confirmed submission ke baad ticket reference aur isi conversation mein support ke replies milte hain. Resolved ticket par reply se wohi issue dobara open hota hai; alag maslay ke liye New request use karein. Human support chat AI model ke baghair kaam karti hai, lekin support storage configured hona zaroori hai. Credentials, card details ya identity documents share na karein. Chat messages bookings ya payments change nahi karte."
    }
  ],
  "navigation": [
    {
      "id": "rentals",
      "label": "Open Rentals",
      "href": "/rentals",
      "permission": "rentals",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "rental",
      "label": "Open rental",
      "href": "/rentals/{id}",
      "permission": "rentals",
      "entity": "rental",
      "source": "apps/portal/src/components/rentals-v2/rental-detail/stages.ts"
    },
    {
      "id": "rental_return",
      "label": "Open return workflow",
      "href": "/rentals/{id}",
      "permission": "rentals",
      "entity": "rental",
      "editPermission": "rentals",
      "v2Stage": "handover",
      "source": "apps/portal/src/components/rentals-v2/rental-detail/stages.ts"
    },
    {
      "id": "vehicles",
      "label": "Open Vehicles",
      "href": "/vehicles",
      "permission": "vehicles",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "vehicle",
      "label": "Open vehicle",
      "href": "/vehicles/{id}",
      "permission": "vehicles",
      "entity": "vehicle",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "customers",
      "label": "Open Customers",
      "href": "/customers",
      "permission": "customers",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "customer",
      "label": "Open customer",
      "href": "/customers/{id}",
      "permission": "customers",
      "entity": "customer",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "availability",
      "label": "Open Availability",
      "href": "/blocked-dates",
      "permission": "availability",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "messages",
      "label": "Open Messages",
      "href": "/messages",
      "permission": "messages",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "reminders",
      "label": "Open Reminders",
      "href": "/reminders",
      "permission": "reminders",
      "hiddenArea": "reminders",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "website",
      "label": "Open Website Content",
      "href": "/cms",
      "permission": "cms",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "settings_general",
      "label": "Open General settings",
      "href": "/settings?tab=general",
      "permission": "settings.general",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "settings_templates",
      "label": "Open Templates",
      "href": "/settings?tab=templates",
      "permission": "settings.templates",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "rental_create",
      "label": "Open New Rental",
      "href": "/rentals/new",
      "permission": "rentals",
      "editPermission": "rentals",
      "v2Area": "rentals",
      "source": "apps/portal/src/components/rentals-v2/rental-create-v2.tsx"
    },
    {
      "id": "integrations",
      "label": "Open Integrations",
      "href": "/integrations",
      "permission": "settings.integrations",
      "v2Area": "appearance",
      "source": "apps/portal/src/app/(dashboard)/integrations/page.tsx"
    },
    {
      "id": "settings_branding",
      "label": "Open Branding settings",
      "href": "/settings?tab=branding",
      "permission": "settings.branding",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "audit_logs",
      "label": "Open Audit Logs",
      "href": "/audit-logs",
      "permission": "audit_logs",
      "source": "apps/portal/src/lib/permissions.ts"
    }
  ]
} as const;
