// Generated by scripts/trax-knowledge.mjs from prepared documentation. Do not edit.
export const KNOWLEDGE = {
  "version": "0.1.0",
  "sourceCommit": "13f9ea8679fbc6e35940b7d5824efa77b9da4b2d",
  "verifiedAt": "2026-09-12",
  "applicationRelease": null,
  "deploymentVerified": false,
  "guides": [
    {
      "id": "rentals",
      "title": "Rentals",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "rentals",
        "rental",
        "booking",
        "bookings",
        "kiraya",
        "rental workflow"
      ],
      "navigation": [
        "rentals",
        "rental"
      ],
      "en": "Open **Rentals**, then select the rental. Review the customer, vehicle, dates and the requirements shown on that record. Approval, agreement, insurance, payment and handover are separate steps; completing one does not prove the others are finished. In V2 these are contextual stages, starting with Customer. Use the existing controls for changes you are permitted to make.",
      "ur-Latn": "**Rentals** kholein aur rental select karein. Customer, gaari, dates aur record par dikhayi gayi requirements dekhein. Approval, agreement, insurance, payment aur handover alag steps hain; aik step complete hone se baqi complete nahi hote. V2 mein ye stages hain aur pehla Customer hai. Tabdeeli sirf apni ijazat ke mutabiq existing controls se karein."
    },
    {
      "id": "returns",
      "title": "Returns and key handover",
      "permissions": [
        "rentals"
      ],
      "keywords": [
        "return",
        "returned",
        "handover",
        "keys",
        "wapis",
        "wapas",
        "chabi",
        "chaabi",
        "chabiyan"
      ],
      "navigation": [
        "rental_return",
        "rentals"
      ],
      "en": "To record a returned car, open the rental and its **Handover** stage in V2, or the existing key-handover section in the other layout. Authorized staff confirm receipt there. This can close the rental, update the vehicle and attempt deposit-hold release and a completion notification. If the record already shows receipt or contains conflicting states, review it before repeating the action. Physical return and the system's recorded return are separate facts.",
      "ur-Latn": "Wapas aayi gaari record karne ke liye rental kholein. V2 mein **Handover** stage, aur doosre layout mein key-handover section dekhein. Authorized staff wahin receipt confirm kare. Is se rental close, vehicle update aur deposit hold release aur notification ki koshish ho sakti hai. Agar receipt pehle se recorded hai ya states mukhtalif hain, action dohrane se pehle review karein. Gaari ka wapas aana aur system mein return record hona alag baatein hain."
    },
    {
      "id": "availability",
      "title": "Vehicle availability",
      "permissions": [
        "availability"
      ],
      "keywords": [
        "availability",
        "unavailable",
        "available",
        "bookable",
        "blocked",
        "block",
        "gaari book",
        "car",
        "nahi book"
      ],
      "navigation": [
        "availability",
        "vehicle",
        "vehicles"
      ],
      "en": "A car can be missing or unbookable for several reasons: website visibility, pause or vehicle state, the selected rental duration, another rental, blocked dates or turnaround time. An overdue rental still recorded as active can also hold the vehicle. Start with the correct vehicle and the customer's actual dates and times, then review the vehicle and Availability screens. A recorded return does not rule out another blocker.",
      "ur-Latn": "Gaari nazar na aane ya book na hone ki kai wajah ho sakti hain: website visibility, pause ya vehicle state, rental duration, doosra rental, blocked dates ya turnaround time. Overdue rental jo abhi active recorded hai bhi gaari rok sakta hai. Sahi gaari aur customer ki asal dates aur times se shuru karein, phir vehicle aur Availability screens dekhein. Return recorded hone ke bawajood doosra blocker ho sakta hai."
    },
    {
      "id": "customers",
      "title": "Customers",
      "permissions": [
        "customers"
      ],
      "keywords": [
        "customer",
        "customers",
        "profile",
        "renter",
        "driver",
        "customer profile"
      ],
      "navigation": [
        "customer",
        "customers"
      ],
      "en": "Open **Customers** and select the customer to review their record and associated rental history. Verification information belongs to that customer's existing workflow; check the requirements shown on the relevant rental as well. The Customer stage inside a rental is different from the separate customer profile. TRAX can open an authorized profile, but this guidance does not verify anyone's identity or account state.",
      "ur-Latn": "**Customers** kholein aur customer select karke unka record aur rental history dekhein. Verification us customer ke existing workflow mein hoti hai; relevant rental ki requirements bhi dekhein. Rental ke andar Customer stage aur alag customer profile mukhtalif hain. TRAX authorized profile khol sakta hai, lekin ye guidance kisi ki identity ya account state verify nahi karti."
    },
    {
      "id": "vehicles",
      "title": "Vehicles",
      "permissions": [
        "vehicles"
      ],
      "keywords": [
        "vehicle",
        "vehicles",
        "fleet",
        "gaari",
        "gari",
        "car configuration"
      ],
      "navigation": [
        "vehicle",
        "vehicles"
      ],
      "en": "Open **Vehicles** and select the vehicle. Review its configuration and booking history in the existing record. Website visibility, pause state and enabled rental durations affect customer booking, while actual availability also depends on dates and other records. Use the native edit controls only if your role permits changes.",
      "ur-Latn": "**Vehicles** kholein aur gaari select karein. Existing record mein configuration aur booking history dekhein. Website visibility, pause state aur enabled rental durations customer booking par asar dalte hain; asal availability dates aur doosre records par bhi depend karti hai. Native edit controls sirf apni role ki ijazat ke mutabiq use karein."
    },
    {
      "id": "messages",
      "title": "Messages",
      "permissions": [
        "messages"
      ],
      "keywords": [
        "message",
        "messages",
        "messaging",
        "conversation",
        "paigham"
      ],
      "navigation": [
        "messages"
      ],
      "en": "Open **Messages** and choose the relevant customer conversation. Use the existing messaging controls for anything you intend to send. TRAX's application guidance does not read those conversations, send messages or confirm delivery.",
      "ur-Latn": "**Messages** kholein aur relevant customer conversation select karein. Jo message bhejna ho us ke liye existing messaging controls use karein. TRAX ki application guidance conversations nahi parhti, message nahi bhejti aur delivery confirm nahi karti."
    },
    {
      "id": "reminders",
      "title": "Reminders",
      "permissions": [
        "reminders"
      ],
      "keywords": [
        "reminder",
        "reminders",
        "remind",
        "follow up",
        "yaad"
      ],
      "navigation": [
        "reminders"
      ],
      "en": "Where Reminders is enabled, open **Reminders** to review follow-ups. The default list shows pending, sent and snoozed items; filters let you review other states. Use the existing reminder form for its related record and dates. TRAX cannot create, complete or snooze reminders in this phase.",
      "ur-Latn": "Jahan Reminders enabled hai, follow-ups ke liye **Reminders** kholein. Default list pending, sent aur snoozed items dikhati hai; filters se doosri states dekhi ja sakti hain. Related record aur dates ke liye existing reminder form use karein. Is phase mein TRAX reminders create, complete ya snooze nahi karta."
    },
    {
      "id": "website",
      "title": "Website content",
      "permissions": [
        "cms"
      ],
      "keywords": [
        "website",
        "cms",
        "publish",
        "website content",
        "site content"
      ],
      "navigation": [
        "website"
      ],
      "en": "Open **Website Content** (the **Website** area in V2) and choose the page you want to review. Publishing and unpublishing affect the customer-facing site, so use the existing preview and publishing workflow with the required permissions. TRAX does not edit or publish website content.",
      "ur-Latn": "**Website Content** (V2 mein **Website** area) kholein aur page select karein. Publish aur unpublish karne se customer-facing site badalti hai; required permissions ke saath existing preview aur publishing workflow use karein. TRAX website content edit ya publish nahi karta."
    },
    {
      "id": "settings",
      "title": "Settings",
      "permissions": [
        "settings",
        "settings.general"
      ],
      "keywords": [
        "settings",
        "configuration",
        "business details",
        "setting",
        "kahan"
      ],
      "navigation": [
        "settings_general"
      ],
      "en": "Open **Settings → General** for business configuration. Available tabs depend on your account and permissions. Managers need Settings access and the relevant sub-tab grant. Review and change values through the existing settings controls; TRAX does not save configuration.",
      "ur-Latn": "Business configuration ke liye **Settings → General** kholein. Tabs aap ke account aur permissions par depend karte hain. Manager ko Settings aur relevant sub-tab ka grant chahiye. Values existing settings controls se review aur change karein; TRAX configuration save nahi karta."
    },
    {
      "id": "templates",
      "title": "Communication templates",
      "permissions": [
        "settings",
        "settings.templates"
      ],
      "keywords": [
        "template",
        "templates",
        "email templates",
        "sms template"
      ],
      "navigation": [
        "settings_templates"
      ],
      "en": "Look in **Settings → Templates** for communication templates. If that tab is unavailable, ask an account administrator to review your settings permissions. Use the existing template workflow to edit or preview; changing a template does not itself confirm a message was sent.",
      "ur-Latn": "Communication templates ke liye **Settings → Templates** dekhein. Agar tab available nahi hai to account administrator se settings permissions review karwayein. Edit ya preview ke liye existing template workflow use karein; template badalne se message bheja jana confirm nahi hota."
    }
  ],
  "navigation": [
    {
      "id": "rentals",
      "label": "Open Rentals",
      "href": "/rentals",
      "permission": "rentals",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "rental",
      "label": "Open rental",
      "href": "/rentals/{id}",
      "permission": "rentals",
      "entity": "rental",
      "source": "apps/portal/src/components/rentals-v2/rental-detail/stages.ts"
    },
    {
      "id": "rental_return",
      "label": "Open return workflow",
      "href": "/rentals/{id}",
      "permission": "rentals",
      "entity": "rental",
      "editPermission": "rentals",
      "v2Stage": "handover",
      "source": "apps/portal/src/components/rentals-v2/rental-detail/stages.ts"
    },
    {
      "id": "vehicles",
      "label": "Open Vehicles",
      "href": "/vehicles",
      "permission": "vehicles",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "vehicle",
      "label": "Open vehicle",
      "href": "/vehicles/{id}",
      "permission": "vehicles",
      "entity": "vehicle",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "customers",
      "label": "Open Customers",
      "href": "/customers",
      "permission": "customers",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "customer",
      "label": "Open customer",
      "href": "/customers/{id}",
      "permission": "customers",
      "entity": "customer",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "availability",
      "label": "Open Availability",
      "href": "/blocked-dates",
      "permission": "availability",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "messages",
      "label": "Open Messages",
      "href": "/messages",
      "permission": "messages",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "reminders",
      "label": "Open Reminders",
      "href": "/reminders",
      "permission": "reminders",
      "hiddenArea": "reminders",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "website",
      "label": "Open Website Content",
      "href": "/cms",
      "permission": "cms",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "settings_general",
      "label": "Open General settings",
      "href": "/settings?tab=general",
      "permission": "settings.general",
      "source": "apps/portal/src/lib/permissions.ts"
    },
    {
      "id": "settings_templates",
      "label": "Open Templates",
      "href": "/settings?tab=templates",
      "permission": "settings.templates",
      "source": "apps/portal/src/lib/permissions.ts"
    }
  ]
} as const;
