import type { ModelTool } from './model.ts';
const str={type:'string'},nullable={type:['string','null']};
function tool(name:string,description:string,properties:Record<string,unknown>):ModelTool {
  return {type:'function',function:{name,description,strict:true,parameters:{type:'object',additionalProperties:false,required:Object.keys(properties),properties}}};
}
export const MODEL_TOOLS:ModelTool[]=[
  tool('get_rental_payment_evidence','Payments linked to one resolved rental, each checked against its exactly linked Stripe transaction in the backend-verified account and environment. Returns payment cards (Drive247 and Stripe status, verified amount, account and mode), per-currency totals and permitted Open in Stripe or View receipt actions. Read-only; requires a finance grant.',{rentalId:str,offset:{type:['integer','null']}}),
  tool('investigate_rental_payment','Fresh investigation of one payment from the rental, for example when the user cannot find it in Stripe or asks which account received it: verified account and environment, charge and capture state, differences and evidence-based explanations. Read-only.',{rentalId:str,paymentId:str}),
  tool('resolve_payment_dashboard_action','Fresh, verified Open in Stripe or View receipt action for one payment from the rental, or the reason no dashboard link is available. Read-only; never creates links, logins or payments.',{rentalId:str,paymentId:str}),
  tool('get_stripe_account_summary','Fresh available/pending funds for the authorized tenant’s exclusive connected account. Separate currencies. Not a rental balance. Requires an explicit account-finance grant.',{}),
  tool('select_support_issue','Select the current issue before investigation. Reuse a matching issue for follow-ups; unrelated questions must use a separate topic/record. No score can be supplied.',{topic:{type:'string',enum:['vehicle_availability','fleet_counts','bookings','payments','workflow','other']},recordKind:{type:['string','null'],enum:['vehicle','rental','customer',null]},recordId:nullable}),
  tool('request_support_handoff','Ask the backend to assess whether safe options are exhausted or the user explicitly requested a person. This only offers Contact Support. It never creates a ticket.',{reason:{type:'string',enum:['human_requested','guidance_missing','diagnostics_exhausted']}}),
  tool('get_account_counts','Exact total vehicles, customers and rentals for the authenticated tenant, independently permission checked. Includes historical records; not an availability calculation.',{kinds:{type:'array',items:{type:'string',enum:['vehicles','customers','rentals']}}}),
  tool('list_account_bookings','List active/out-on-hire recorded states or upcoming reservations using the current tenant timezone. Booking totals are separate from unique vehicles. Follow nextOffset when partial; do not infer bookability.',{view:{type:'string',enum:['active','upcoming','out_now']},offset:{type:['integer','null']}}),
  tool('find_available_vehicles','Check a bounded page of vehicles with the authoritative V2 date rules. Requires actual dates and customer timezone. Partial pages are never a complete fleet availability total.',{startDate:nullable,endDate:nullable,customerTimezone:nullable,pickupLocationId:nullable,offset:{type:['integer','null']}}),
  tool('search_application_knowledge','Retrieve up to three reviewed sections by their exact IDs from the authorized catalog. These are guidance, not live facts.',{sectionIds:{type:'array',items:str}}),
  tool('resolve_navigation_target','Resolve an authorized destination from the navigation catalog; for record destinations use only an ID returned by a tool or validated page context.',{target:str,entityId:nullable}),
  tool('resolve_authorized_entity','Resolve an exact vehicle UUID/registration, rental UUID/number, or the exact pickup location name shown in the website selector. A short vehicle make or model can return ambiguous matches. Ask the user to choose; never guess.',{kind:{type:'string',enum:['vehicle','rental','pickup_location']},query:str}),
  tool('get_rental_support_context','Read one authorized rental and its receiving handovers. Does not close or repair it. No customer or finance fields.',{rentalId:str}),
  tool('diagnose_vehicle_availability','Fresh V2 website/checkout read-only diagnostic for ONE vehicle. First clarify actual failed operation. For date_availability obtain actual dates and customer browser timezone. No invented date window. Checkout is partial precheck only, not write-time validation.',{vehicleId:str,operation:{type:'string',enum:['website_visibility','date_availability','booking_rejection']},startDate:nullable,endDate:nullable,customerTimezone:nullable,pickupLocationId:nullable}),
];
