/**
 * Payment plans — HOW MUCH, in integer cents.
 *
 * Every mode works on whole cents and never on dollars, so the occurrences of
 * a plan always sum to exactly the total the operator saw in the preview:
 *
 *   split_total   total ÷ n, rounded DOWN; the remainder cents go on the LAST
 *                 occurrence ($1,000 over 6 → 5 × $166.66 + $166.70).
 *   split_by_days total × days_i ÷ Σdays, rounded DOWN; the remainder on the
 *                 LAST ("pay for the time each payment covers").
 *   fixed         the same amount every time, stub included.
 *   per_period    days covered × daily rate.
 *
 * Rounding DOWN with the remainder last (rather than rounding each share)
 * means no occurrence ever asks for a cent more than its share, and the last
 * one — the one nearest the return date — absorbs the difference. Any
 * occurrence below 1 cent is a PlanRuleError('amount_too_small'): a $0.00
 * payment cannot be charged, and silently dropping it would change the count
 * the operator agreed to.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type { AmountSpec } from "./types.ts";
import { PlanRuleError } from "./errors.ts";

function requireCents(value: unknown, what: string): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value)) {
    // Fractional cents are a caller bug (the boundary converts dollars to
    // cents once), not an operator choice — so not a PlanRuleError.
    throw new RangeError(`${what} must be a whole number of cents, got ${JSON.stringify(value)}`);
  }
  return value;
}

/**
 * floor(a × b ÷ c) exactly, for non-negative safe integers. A float division
 * can round k − ε up to k; the two corrections put it back.
 */
export function mulDivFloor(a: number, b: number, c: number): number {
  if (c <= 0) throw new RangeError("mulDivFloor: divisor must be positive");
  const product = a * b;
  if (!Number.isSafeInteger(product)) throw new RangeError("mulDivFloor: amount × days exceeds safe integer range");
  let q = Math.floor(product / c);
  while (q * c > product) q--;
  while ((q + 1) * c <= product) q++;
  return q;
}

/** Equal shares, remainder cents on the last. */
export function splitEvenly(totalCents: number, n: number): number[] {
  requireCents(totalCents, "Total");
  if (!Number.isInteger(n) || n < 1) throw new RangeError(`splitEvenly: n must be ≥ 1, got ${n}`);
  const base = Math.floor(totalCents / n);
  const out = new Array<number>(n).fill(base);
  out[n - 1] = totalCents - base * (n - 1);
  return out;
}

/** Shares proportional to days, rounded down, remainder cents on the last. */
export function splitByDays(totalCents: number, days: number[]): number[] {
  requireCents(totalCents, "Total");
  if (days.length === 0) throw new RangeError("splitByDays: no periods");
  if (days.some((d) => !Number.isInteger(d) || d < 1)) throw new RangeError("splitByDays: every period needs ≥ 1 day");
  const totalDays = days.reduce((s, d) => s + d, 0);
  const out = days.map((d) => mulDivFloor(totalCents, d, totalDays));
  const allButLast = out.slice(0, -1).reduce((s, x) => s + x, 0);
  out[out.length - 1] = totalCents - allButLast;
  return out;
}

/**
 * The amount of each occurrence, given the days each one covers (from
 * schedule.ts computePeriods). Throws amount_too_small if any is < 1 cent.
 */
export function computeAmounts(spec: AmountSpec, days: number[]): number[] {
  if (!spec || typeof spec !== "object") throw new RangeError("An amount spec is required");
  const n = days.length;
  if (n === 0) throw new RangeError("computeAmounts: no occurrences");
  let out: number[];
  switch (spec.mode) {
    case "split_total":
      requireCents(spec.totalCents, "Total");
      out = splitEvenly(spec.totalCents, n);
      break;
    case "split_by_days":
      requireCents(spec.totalCents, "Total");
      out = splitByDays(spec.totalCents, days);
      break;
    case "fixed":
      requireCents(spec.amountCents, "Amount");
      out = new Array<number>(n).fill(spec.amountCents);
      break;
    case "per_period": {
      requireCents(spec.dailyRateCents, "Daily rate");
      out = days.map((d) => d * spec.dailyRateCents);
      break;
    }
    default:
      throw new RangeError(`Unknown amount mode ${JSON.stringify((spec as { mode?: unknown }).mode)}`);
  }
  const small = out.findIndex((c) => c < 1);
  if (small !== -1) {
    throw new PlanRuleError(
      "amount_too_small",
      `Payment #${small + 1} would be ${out[small]} cents — every payment must be at least 1 cent`,
    );
  }
  return out;
}

/** Σ of a list of cents. */
export function sumCents(values: number[]): number {
  return values.reduce((s, v) => s + v, 0);
}

/** Integer cents → a Postgres numeric(12,2) value, exact (no float formatting surprises). */
export function centsToDecimal(cents: number): string {
  requireCents(cents, "Amount");
  const sign = cents < 0 ? "-" : "";
  const abs = Math.abs(cents);
  return `${sign}${Math.floor(abs / 100)}.${String(abs % 100).padStart(2, "0")}`;
}

/**
 * A Postgres numeric money value (number or string, as PostgREST returns it)
 * → integer cents. Parsed from the digits, never `x * 100`, which turns 0.29
 * into 28.999999999999996.
 */
export function decimalToCents(value: number | string | null | undefined): number {
  if (value === null || value === undefined || value === "") return 0;
  const s = typeof value === "number" ? value.toFixed(2) : String(value).trim();
  const m = /^(-)?(\d+)(?:\.(\d+))?$/.exec(s);
  if (!m) throw new RangeError(`Not a decimal amount: ${JSON.stringify(value)}`);
  const frac = (m[3] ?? "").padEnd(2, "0");
  if (frac.length > 2 && /[1-9]/.test(frac.slice(2))) {
    throw new RangeError(`Amount has fractions of a cent: ${JSON.stringify(value)}`);
  }
  const cents = Number(m[2]) * 100 + Number(frac.slice(0, 2));
  return m[1] ? -cents : cents;
}
