/**
 * Payment plans — the engine (design §7).
 *
 * Pure orchestration over injected seams: a store (the SQL functions, or the
 * memory store), a payment provider (Stripe, or the simulation), a notifier and
 * a link minter. The SAME code runs in the cron (run-payment-plans), in vitest
 * and in the browser simulator — "one engine, one simulation" (spec §4.3).
 *
 * A tick, in this order:
 *   1. RECOVERY. Attempts left claimed / in_flight / indeterminate by a worker
 *      that died or a provider that answered 5xx. `claimed` never reached the
 *      provider → abandoned. In flight for < 23 h → replay the SAME idempotency
 *      key with the same parameters (Stripe returns what really happened).
 *      Older, or on a plan that is no longer active → look the charge up by
 *      metadata; found → record it, not found → abandoned. NEVER a new key
 *      without a lookup: a new key is a new charge.
 *   2. REMINDERS BEFORE DUE WORK — offsets ≤ 0 only ("due Friday", "charging
 *      today"). For each open occurrence and each such offset where due_date +
 *      offset is the plan-local today: record the event with dedupe key
 *      reminder:{occ}:{offset} and send only if that insert won — so two ticks
 *      in one day send one email.
 *   3. DUE WORK (collectDue), per collection method: auto_charge → claim,
 *      mark in flight (write-ahead), charge with the key, classify; checkout
 *      link → claim, mint the stable URL, email it; manual → an
 *      occurrence_due event and an operator notification. Nothing charged.
 *   1b. RENEWALS (Wave 3, renewals.ts) — open-ended plans that extend the
 *      rental: reconcile periods settled outside the plan, append a renewal
 *      plan's next period once its last is settled, post periods about to
 *      fall due (an extension + its Extension* charges) and buy their
 *      insurance BEFORE anything can charge them. Before the reminders, so a
 *      reminder quotes the period's final price.
 *   4. REMINDERS AFTER DUE WORK — offsets > 0 only ("still unpaid"), and only
 *      for occurrences the due work left open. A card retry lands on a later
 *      day than the due date (retry_after_days), so "+2 days, still unpaid"
 *      and the retry often fall on the same tick; sent first, the customer was
 *      told they were overdue minutes before being charged successfully (S19).
 *      For the same reason an occurrence whose card retry is still to come
 *      later TODAY is held until that retry's tick — the cron ticks from local
 *      midnight, hours before a 10:00 retry. Same dedupe keys as step 2.
 *
 * Every occurrence is processed in its own try/catch: one bad row is reported
 * in TickResult.errors and the tick carries on.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type {
  AmountMode,
  AmountSpec,
  AttemptRow,
  ClaimOk,
  ClaimResult,
  CollectionMethod,
  Freq,
  ISODate,
  OccurrenceDraft,
  OccurrenceRow,
  PlanLookups,
  PlanOperations,
  PlanRow,
  PlanStore,
  RenewalBreakdown,
  RenewalCoverage,
  RenewalPeriodUnit,
  RenewalPricingInputs,
  ScheduleEnd,
  ScheduleOverride,
  ScheduleRule,
  Weekday,
} from "./types.ts";
import { DEFAULT_CHARGE_LOCAL_TIME } from "./types.ts";
import type { ChargeOutcome, ChargeRequest, LinkMinter, Notification, Notifier, PaymentProvider, RenewalInsurer } from "./providers.ts";
import { nextRenewalDraft, normalizeCoverage, runRenewalStage, storeHasRenewals, type RenewalStageResult } from "./renewals.ts";
import { renewalBreakdownCents } from "./renewal-pricing.ts";
import { classifyCharge, customerSafeReason, type ChargeClass } from "./classify.ts";
import { addDays, addHoursToInstant, compareInstants, dueAtUtc, isISODate, isoWeekday, isValidTimeZone, localDateInZone, parseISODate, secondsBetween, validateChargeTime } from "./dates.ts";
import { buildSchedule } from "./schedule.ts";
import { PlanRuleError, PlanStoreError } from "./errors.ts";

// ─────────────────────────────────────────────────────────────────────────────
// Public types
// ─────────────────────────────────────────────────────────────────────────────

export type EngineStore = PlanStore & PlanOperations & PlanLookups;

export interface EngineDeps {
  store: EngineStore;
  provider: PaymentProvider;
  notifier: Notifier;
  links: LinkMinter;
  /**
   * Buys a renewal period's Bonzah policy before it is charged (A4). Optional:
   * without one, a period that asks for cover is charged WITHOUT it — no
   * premium — and the operator is alerted. Additive (Wave 3).
   */
  insurer?: RenewalInsurer | null;
}

/** An attempt older than this with no answer is recovered (design §7.1: 600 s). */
export const STALE_ATTEMPT_SECONDS = 600;
/** Replay the same key only inside this window; Stripe keeps keys 24 h. */
export const REPLAY_WINDOW_SECONDS = 23 * 3600;
/** A transient decline (network, issuer down) is retried after this long. */
export const TRANSIENT_RETRY_HOURS = 1;
/** Reminders look this many days either side of the plan-local today. */
export const REMINDER_HORIZON_DAYS = 30;

/** What a manual record may say the money was. payments.method values. */
export const MANUAL_METHODS = ["Cash", "Bank Transfer", "Zelle", "Check", "Card (external)", "Other"] as const;
export type ManualMethod = (typeof MANUAL_METHODS)[number];

export type OccurrenceAction =
  | "charged"
  | "failed"
  | "retry_scheduled"
  | "requires_action"
  | "link_sent"
  | "due_manual"
  | "covered_by_balance"
  | "held_elsewhere"
  | "not_claimable"
  | "not_eligible"
  | "indeterminate"
  | "in_use"
  | "paused_integration"
  | "noop";

export interface OccurrenceActionResult {
  occurrenceId: string;
  planId: string;
  action: OccurrenceAction;
  attemptId?: string;
  attemptNo?: number;
  idempotencyKey?: string;
  amountCents?: number;
  paymentId?: string;
  providerRef?: string | null;
  chargeClass?: ChargeClass;
  /** Safe to show a customer or an operator (never a fraud flag). */
  reason?: string;
  nextAttemptAt?: string | null;
  url?: string;
  /** A fallback link that went out after this attempt. */
  fallback?: OccurrenceActionResult;
}

export interface RecoveryResult {
  attemptId: string;
  occurrenceId: string;
  path: "abandoned_unsent" | "replayed" | "looked_up" | "skipped";
  outcome: string;
  paymentId?: string;
}

export interface TickResult {
  asOf: string;
  recovered: RecoveryResult[];
  reminders: { occurrenceId: string; planId: string; offset: number; sent: boolean }[];
  actions: OccurrenceActionResult[];
  errors: { occurrenceId?: string; attemptId?: string; stage: "recovery" | "renewals" | "reminders" | "due"; message: string }[];
  /** What the renewal stage did (only when the store carries renewals). Additive (Wave 3). */
  renewals?: RenewalStageResult;
}

// ─────────────────────────────────────────────────────────────────────────────
// Small helpers
// ─────────────────────────────────────────────────────────────────────────────

/** pp:{account or 'platform'}:{occurrence}:{attempt_no} — design §4. The store builds it at claim; this is the same rule for display and checks. */
export function idempotencyKey(account: string | null, occurrenceId: string, attemptNo: number): string {
  return `pp:${account ?? "platform"}:${occurrenceId}:${attemptNo}`;
}

function setClock(store: unknown, asOf: string): void {
  const s = store as { setNow?: (asOf: string) => void };
  if (typeof s?.setNow === "function") s.setNow(asOf);
}

const message = (e: unknown): string => (e instanceof Error ? e.message : String(e));

/**
 * Narrow a ClaimResult. A type predicate rather than `if (!c.ok)`, because the
 * portal compiles these files with strictNullChecks off, where TypeScript does
 * not narrow a union on a boolean-literal discriminant.
 */
export function isClaimOk(c: ClaimResult): c is { ok: true; claim: ClaimOk } {
  return c.ok === true;
}

function remainingOf(occ: OccurrenceRow): number {
  return Math.max(0, occ.amountCents - occ.amountPaidCents);
}

/** Never let a notification failure break a money path; report it instead. */
async function safeSend(deps: { notifier: Notifier }, n: Notification): Promise<string | null> {
  try {
    await deps.notifier.send(n);
    return null;
  } catch (e) {
    return message(e);
  }
}

async function requirePlan(store: EngineStore | (PlanStore & PlanLookups), planId: string): Promise<PlanRow> {
  const plan = await store.getPlan(planId);
  if (!plan) throw new PlanStoreError("not_found", `Plan ${planId} not found`);
  return plan;
}

async function requireOccurrence(store: PlanLookups, occurrenceId: string): Promise<OccurrenceRow> {
  const occ = await store.getOccurrence(occurrenceId);
  if (!occ) throw new PlanStoreError("not_found", `Occurrence ${occurrenceId} not found`);
  return occ;
}

const OPEN_ATTEMPT = new Set(["claimed", "in_flight"]);

/**
 * Auto-collection eligibility (design §6 / D12), as the engine applies it.
 *
 *   failed         — only when next_attempt_at has arrived.
 *   due / partially_paid — only when no CARD or LINK attempt has ever been made
 *                    on it, other than ones `abandoned` before reaching anyone.
 *
 * This is D12's "attempt_no = 0" with two refinements the scenarios require:
 * a MANUAL record does not count (S10: 5000 recorded by hand the day before,
 * the card is still charged the 15000 remainder on the due date), and an
 * attempt recovery abandoned because it was never sent does not count (the
 * occurrence is still owed and nothing ever asked the card). A refunded card
 * or link payment DOES count — its succeeded attempt stays on the row — so a
 * refunded occurrence is never charged again automatically (S14).
 */
export function isAutoEligible(occ: OccurrenceRow, attempts: AttemptRow[], asOf: string): boolean {
  if (occ.status === "failed") return !!occ.nextAttemptAt && compareInstants(occ.nextAttemptAt, asOf) <= 0;
  if (occ.status !== "due" && occ.status !== "partially_paid") return false;
  if (compareInstants(occ.dueAt, asOf) > 0) return false;
  if (occ.attemptNo === 0) return true;
  return attempts.every((a) => a.method === "manual" || a.status === "abandoned");
}

async function eligible(store: EngineStore, occ: OccurrenceRow, asOf: string): Promise<boolean> {
  if (occ.status === "failed" || occ.attemptNo === 0) return isAutoEligible(occ, [], asOf);
  return isAutoEligible(occ, await store.listAttempts({ occurrenceId: occ.id }), asOf);
}

function chargeRequest(plan: PlanRow, occ: OccurrenceRow, attempt: { id: string; amountCents: number; idempotencyKey: string }, account: string | null): ChargeRequest {
  return {
    amountCents: attempt.amountCents,
    currency: plan.currency.toLowerCase(),
    idempotencyKey: attempt.idempotencyKey,
    account,
    customerRef: plan.customerId,
    paymentMethodRef: plan.stripePaymentMethodId,
    metadata: {
      type: "payment_plan",
      occurrence_id: occ.id,
      attempt_id: attempt.id,
      plan_id: plan.id,
      tenant_id: plan.tenantId,
      rental_id: plan.rentalId,
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Charging
// ─────────────────────────────────────────────────────────────────────────────

interface AttemptCtx {
  plan: PlanRow;
  occ: OccurrenceRow;
  attemptId: string;
  attemptNo: number;
  amountCents: number;
  idempotencyKey: string;
}

/** Record a card success; if the record cannot be written, give the money back (design §7 compensation). */
async function recordCardSuccess(deps: EngineDeps, ctx: AttemptCtx, providerRef: string, amountCents: number, asOf: string): Promise<OccurrenceActionResult> {
  const { plan, occ } = ctx;
  const base: OccurrenceActionResult = {
    occurrenceId: occ.id,
    planId: plan.id,
    action: "charged",
    attemptId: ctx.attemptId,
    attemptNo: ctx.attemptNo,
    idempotencyKey: ctx.idempotencyKey,
    amountCents,
    providerRef,
    chargeClass: "succeeded",
  };
  try {
    const { paymentId } = await deps.store.recordSuccess({
      attemptId: ctx.attemptId,
      amountCents,
      providerRef,
      providerAccount: deps.provider.account,
      providerMode: deps.provider.mode,
      paymentProvider: plan.paymentProvider,
      platformAccount: deps.provider.platformAccount ?? "uk",
      paymentDate: localDateInZone(asOf, plan.timezone),
      method: "Card",
    });
    return { ...base, paymentId };
  } catch (recordErr) {
    // The card WAS charged and the payment row could not be written. Leaving
    // it would be money taken with nothing on the ledger; retrying could take
    // it twice. So: refund it (keyed, so a repeat of this path cannot refund
    // twice), then say so. Precedent: auto-extend-rentals' rollback, which
    // pauses rather than retrying whenever the refund itself fails.
    const why = message(recordErr);
    let refund: { ok: boolean; message?: string };
    try {
      refund = await deps.provider.refund(providerRef, amountCents, `pp-refund:${ctx.attemptId}`);
    } catch (e) {
      refund = { ok: false, message: message(e) };
    }
    if (refund.ok) {
      try {
        await deps.store.recordFailure({
          attemptId: ctx.attemptId,
          status: "failed",
          providerRef,
          errorCode: "record_failed_refunded",
          errorMessage: `Charged, but the payment could not be recorded (${why}); refunded in full.`,
          nextAttemptAt: null,
        });
        await deps.store.recordEvent({
          planId: plan.id,
          occurrenceId: occ.id,
          kind: "charge_failed",
          amountCents,
          detail: { attemptId: ctx.attemptId, compensated: "refunded", providerRef, error: why },
        });
      } catch (e2) {
        // The store is still failing. The attempt stays in flight; recovery
        // will replay the key, see the charge, look it up NET of the refund,
        // find nothing, and fail it — no phantom payment. Pause if we can.
        await pauseAndAlert(deps, plan, occ, "refunded_unrecorded", `Charge ${providerRef} was refunded after the payment could not be recorded, and the failure could not be written either: ${message(e2)}`);
      }
      await safeSend(deps, {
        kind: "alert",
        to: "operator",
        planId: plan.id,
        occurrenceId: occ.id,
        amountCents,
        detail: { problem: "charge_refunded_after_record_failure", providerRef, attemptId: ctx.attemptId, error: why },
      });
      return { ...base, action: "failed", paymentId: undefined, reason: "The payment could not be recorded and was refunded." };
    }
    // Refund failed: money is out and unrecorded. Mark indeterminate (recovery
    // records it once the store is healthy — the money is real), PAUSE the
    // plan so nothing else is charged, and alert a human.
    try {
      await deps.store.recordFailure({
        attemptId: ctx.attemptId,
        status: "indeterminate",
        providerRef,
        errorCode: "record_failed_refund_failed",
        errorMessage: `Charged, the payment could not be recorded (${why}), and the refund failed (${refund.message ?? "unknown"}).`,
      });
    } catch {
      /* the attempt is still in flight either way; recovery sees it */
    }
    await pauseAndAlert(deps, plan, occ, "refund_failed", `Charge ${providerRef} could not be recorded (${why}) and its refund failed (${refund.message ?? "unknown"}). Money is captured and unrecorded.`);
    return { ...base, action: "indeterminate", paymentId: undefined, reason: "Charged but not recorded; refund failed — plan paused for review." };
  }
}

async function pauseAndAlert(deps: Pick<EngineDeps, "store" | "notifier">, plan: PlanRow, occ: OccurrenceRow | null, problem: string, detailText: string): Promise<void> {
  let paused = false;
  try {
    const fresh = await deps.store.getPlan(plan.id);
    if (fresh?.status === "active") {
      await deps.store.pausePlan(plan.id, null, `${problem}: ${detailText}`.slice(0, 500));
      paused = true;
    }
  } catch {
    paused = false;
  }
  await safeSend(deps, {
    kind: "alert",
    to: "operator",
    planId: plan.id,
    occurrenceId: occ?.id,
    detail: { problem, message: detailText, planPaused: paused },
  });
}

/** Turn a provider answer into state. Shared by the first call and by recovery's replay. */
async function applyOutcome(deps: EngineDeps, ctx: AttemptCtx, outcome: ChargeOutcome, asOf: string): Promise<OccurrenceActionResult> {
  const { plan, occ } = ctx;
  const cls = classifyCharge(outcome);
  const base: OccurrenceActionResult = {
    occurrenceId: occ.id,
    planId: plan.id,
    action: "failed",
    attemptId: ctx.attemptId,
    attemptNo: ctx.attemptNo,
    idempotencyKey: ctx.idempotencyKey,
    amountCents: ctx.amountCents,
    chargeClass: cls,
  };

  if (outcome.kind === "succeeded") return recordCardSuccess(deps, ctx, outcome.providerRef, ctx.amountCents, asOf);

  if (outcome.kind === "indeterminate") {
    // Money may or may not have moved. Keep the claim (occurrence stays
    // processing) and let recovery replay THIS key — never a new one.
    await deps.store.recordFailure({ attemptId: ctx.attemptId, status: "indeterminate", errorMessage: outcome.message ?? "No definitive answer from the provider" });
    return { ...base, action: "indeterminate" };
  }

  if (outcome.kind === "in_use") {
    // 409: another request holds this key right now. Leave the attempt in
    // flight; recovery picks it up after the lease.
    return { ...base, action: "in_use" };
  }

  // Declined.
  const reason = customerSafeReason(outcome.declineCode, outcome.errorCode);
  const failure = {
    attemptId: ctx.attemptId,
    providerRef: outcome.providerRef,
    declineCode: outcome.declineCode,
    errorCode: outcome.errorCode,
    errorMessage: outcome.message ?? null,
  };
  const operatorNote = (extra: Record<string, unknown>) =>
    safeSend(deps, {
      kind: "failed",
      to: "operator",
      planId: plan.id,
      occurrenceId: occ.id,
      amountCents: ctx.amountCents,
      dueDate: occ.dueDate,
      detail: { attemptId: ctx.attemptId, attemptNo: ctx.attemptNo, chargeClass: cls, reason, ...extra },
    });

  if (cls === "integration_bug") {
    await deps.store.recordFailure({ ...failure, status: "failed", nextAttemptAt: null });
    await deps.store.recordEvent({ planId: plan.id, occurrenceId: occ.id, kind: "charge_failed", amountCents: ctx.amountCents, detail: { attemptId: ctx.attemptId, chargeClass: cls, errorCode: outcome.errorCode, declineCode: outcome.declineCode } });
    // Our mistake, not the customer's: never email them; stop the plan until a human looks.
    await pauseAndAlert(deps, plan, occ, "integration_bug", `Charge refused with ${outcome.errorCode ?? outcome.declineCode ?? "an unknown code"}: ${outcome.message ?? ""}`.trim());
    return { ...base, action: "paused_integration", reason, providerRef: outcome.providerRef };
  }

  if (cls === "needs_customer") {
    await deps.store.recordFailure({ ...failure, status: "requires_action" });
    await deps.store.recordEvent({ planId: plan.id, occurrenceId: occ.id, kind: "requires_action", amountCents: ctx.amountCents, detail: { attemptId: ctx.attemptId, declineCode: outcome.declineCode, errorCode: outcome.errorCode } });
    await operatorNote({});
    const result: OccurrenceActionResult = { ...base, action: "requires_action", reason, providerRef: outcome.providerRef };
    return withFallback(deps, result, plan, occ.id, asOf, reason);
  }

  const retryable = cls === "retry_later" || cls === "transient";
  const canRetry = retryable && ctx.attemptNo < plan.maxAttempts;
  let nextAttemptAt: string | null = null;
  if (canRetry) {
    nextAttemptAt =
      cls === "retry_later"
        ? // The local calendar decides: "in 2 days at 10:00" is 10:00 local on
          // that day, not +48 h (which drifts an hour across a DST change).
          dueAtUtc(addDays(localDateInZone(asOf, plan.timezone), plan.retryAfterDays), plan.chargeLocalTime, plan.timezone)
        : addHoursToInstant(asOf, TRANSIENT_RETRY_HOURS);
  }
  await deps.store.recordFailure({ ...failure, status: "failed", nextAttemptAt });
  await deps.store.recordEvent({
    planId: plan.id,
    occurrenceId: occ.id,
    kind: "charge_failed",
    amountCents: ctx.amountCents,
    detail: { attemptId: ctx.attemptId, chargeClass: cls, declineCode: outcome.declineCode, errorCode: outcome.errorCode, nextAttemptAt },
  });
  await operatorNote({ nextAttemptAt });
  if (canRetry) return { ...base, action: "retry_scheduled", reason, nextAttemptAt, providerRef: outcome.providerRef };
  return withFallback(deps, { ...base, action: "failed", reason, nextAttemptAt: null, providerRef: outcome.providerRef }, plan, occ.id, asOf, reason);
}

/** D7: when the card needs the customer or is dead, send them a link — or, with fallback off, tell them. */
async function withFallback(deps: EngineDeps, result: OccurrenceActionResult, plan: PlanRow, occurrenceId: string, asOf: string, reason: string): Promise<OccurrenceActionResult> {
  const occ = await requireOccurrence(deps.store, occurrenceId);
  if (plan.fallbackToLink) {
    const fallback = await sendLink(deps, plan, occ, asOf, { fallbackReason: reason });
    return { ...result, fallback };
  }
  await safeSend(deps, {
    kind: "failed",
    to: "customer",
    planId: plan.id,
    occurrenceId: occ.id,
    amountCents: remainingOf(occ),
    dueDate: occ.dueDate,
    detail: { reason },
  });
  return result;
}

/** Claim → mark in flight → charge with the claim's key → apply the outcome. */
async function chargeOccurrence(deps: EngineDeps, plan: PlanRow, occ: OccurrenceRow, asOf: string): Promise<OccurrenceActionResult> {
  const claimed = await deps.store.claim(occ.id, "auto_charge", deps.provider.account);
  if (!isClaimOk(claimed)) {
    return { occurrenceId: occ.id, planId: plan.id, action: claimed.reason === "nothing_owed" ? "covered_by_balance" : claimed.reason };
  }
  const c: ClaimOk = claimed.claim;
  // Write-ahead: the attempt says "in flight" BEFORE the provider is called, so
  // a worker that dies mid-call leaves a row recovery will replay, never a
  // `claimed` row it would abandon while money moved.
  await deps.store.markInFlight(c.attemptId);
  await deps.store.recordEvent({
    planId: plan.id,
    occurrenceId: occ.id,
    kind: "charge_attempted",
    dedupeKey: `charge_attempted:${c.attemptId}`,
    amountCents: c.amountCents,
    detail: { attemptId: c.attemptId, attemptNo: c.attemptNo, idempotencyKey: c.idempotencyKey },
  });
  const ctx: AttemptCtx = { plan, occ, attemptId: c.attemptId, attemptNo: c.attemptNo, amountCents: c.amountCents, idempotencyKey: c.idempotencyKey };
  let outcome: ChargeOutcome;
  try {
    outcome = await deps.provider.charge(chargeRequest(plan, occ, { id: c.attemptId, amountCents: c.amountCents, idempotencyKey: c.idempotencyKey }, deps.provider.account));
  } catch (e) {
    // A thrown provider call is an unknown outcome, exactly like a 5xx.
    outcome = { kind: "indeterminate", message: message(e) };
  }
  return applyOutcome(deps, ctx, outcome, asOf);
}

// ─────────────────────────────────────────────────────────────────────────────
// Links
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Claim a checkout_link attempt, mint the stable /pay/plan/<token> URL, store
 * its hash, email it. The attempt stays in flight until the webhook records
 * the payment (onLinkPaid) or an operator releases it.
 */
async function sendLink(deps: EngineDeps, plan: PlanRow, occ: OccurrenceRow, asOf: string, opts: { fallbackReason?: string } = {}): Promise<OccurrenceActionResult> {
  if (opts.fallbackReason !== undefined) {
    await deps.store.recordEvent({ planId: plan.id, occurrenceId: occ.id, kind: "fallback_to_link", detail: { reason: opts.fallbackReason } });
  }
  const claimed = await deps.store.claim(occ.id, "checkout_link", deps.provider.account);
  if (!isClaimOk(claimed)) {
    return { occurrenceId: occ.id, planId: plan.id, action: claimed.reason === "nothing_owed" ? "covered_by_balance" : claimed.reason };
  }
  const c = claimed.claim;
  await deps.store.markInFlight(c.attemptId);
  let url: string;
  try {
    const minted = await deps.links.mint(occ.id);
    await deps.store.setLinkToken(occ.id, minted.tokenHash);
    url = minted.url;
  } catch (e) {
    // No usable link exists: release the claim so the occurrence is not held
    // by an attempt nobody can pay.
    try {
      await deps.store.recordFailure({ attemptId: c.attemptId, status: "abandoned", errorMessage: `Link could not be created: ${message(e)}` });
    } catch {
      /* reported below */
    }
    throw e;
  }
  const sendError = await safeSend(deps, {
    kind: "link",
    to: "customer",
    planId: plan.id,
    occurrenceId: occ.id,
    url,
    amountCents: c.amountCents,
    dueDate: occ.dueDate,
    detail: { attemptId: c.attemptId, ...(opts.fallbackReason ? { reason: opts.fallbackReason } : {}) },
  });
  // The store does not write link_sent (pp_set_link_token has no event): the
  // engine writes it once the link has actually gone out. Never the URL — it
  // carries the token, which is a bearer credential for this payment.
  await deps.store.recordEvent({
    planId: plan.id,
    occurrenceId: occ.id,
    kind: "link_sent",
    channel: "email",
    amountCents: c.amountCents,
    detail: { attemptId: c.attemptId, ...(sendError ? { deliveryError: sendError } : {}) },
  });
  return { occurrenceId: occ.id, planId: plan.id, action: "link_sent", attemptId: c.attemptId, attemptNo: c.attemptNo, idempotencyKey: c.idempotencyKey, amountCents: c.amountCents, url };
}

async function openAttempts(store: EngineStore, occurrenceId: string): Promise<AttemptRow[]> {
  return (await store.listAttempts({ occurrenceId })).filter((a) => OPEN_ATTEMPT.has(a.status));
}

/**
 * Release (abandon) any outstanding LINK attempt on an occurrence, so an
 * operator action — a manual record, a card retry, a skip, a plan change — can
 * proceed. Refuses (PlanStoreError 'attempt_in_flight') when a CARD charge is
 * in flight: that one must finish or be recovered, never be abandoned.
 * Returns how many links were released.
 */
export async function releaseOpenLinks(store: EngineStore, occurrenceId: string, reason: string): Promise<number> {
  const open = await openAttempts(store, occurrenceId);
  if (open.some((a) => a.method !== "checkout_link")) {
    throw new PlanStoreError("attempt_in_flight", "A card payment is in progress on this occurrence; wait for it to finish");
  }
  for (const a of open) await store.recordFailure({ attemptId: a.id, status: "abandoned", errorMessage: reason });
  return open.length;
}

/** releaseOpenLinks over every occurrence of a plan (before an update or a cancel). */
export async function releasePlanLinks(store: EngineStore, planId: string, reason: string): Promise<number> {
  let n = 0;
  for (const occ of await store.listOccurrences(planId)) n += await releaseOpenLinks(store, occ.id, reason);
  return n;
}

// ─────────────────────────────────────────────────────────────────────────────
// Recovery
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The provider holds a charge for this attempt, but not for the amount that
 * was claimed (someone refunded part of it at Stripe). pp_record_success
 * records a card attempt at exactly its claimed amount, so neither "record it"
 * nor "fail it" is true. Leave the attempt where it is, pause the plan, and
 * hand it to a person.
 */
async function partialRefundFound(
  deps: EngineDeps,
  plan: PlanRow,
  occ: OccurrenceRow,
  att: AttemptRow,
  found: { providerRef: string; amountCents: number },
  path: "replayed" | "looked_up",
): Promise<RecoveryResult> {
  if (att.status !== "indeterminate") {
    await deps.store.recordFailure({ attemptId: att.id, status: "indeterminate", providerRef: found.providerRef, errorCode: "amount_mismatch", errorMessage: `Provider holds ${found.amountCents} cents net; ${att.amountCents} were claimed` });
  }
  await pauseAndAlert(deps, plan, occ, "recovery_amount_mismatch", `Attempt ${att.id}: charge ${found.providerRef} holds ${found.amountCents} cents net of refunds, but ${att.amountCents} were claimed. Reconcile by hand.`);
  return { attemptId: att.id, occurrenceId: occ.id, path, outcome: "amount_mismatch" };
}

async function recoverAttempt(deps: EngineDeps, att: AttemptRow, asOf: string, filter: { tenantId?: string; planId?: string }): Promise<RecoveryResult | null> {
  const occ = await requireOccurrence(deps.store, att.occurrenceId);
  if (filter.tenantId && occ.tenantId !== filter.tenantId) return null;
  if (filter.planId && occ.planId !== filter.planId) return null;
  const plan = await requirePlan(deps.store, occ.planId);
  const base = { attemptId: att.id, occurrenceId: occ.id };

  if (att.method === "manual" || att.status === "claimed") {
    // Never reached a provider (claimed = markInFlight never ran; manual has
    // no provider). Nothing can have moved.
    await deps.store.recordFailure({ attemptId: att.id, status: "abandoned", errorMessage: "Claimed but never sent; released by recovery" });
    return { ...base, path: "abandoned_unsent", outcome: "abandoned" };
  }

  if ((att.providerAccount ?? null) !== (deps.provider.account ?? null)) {
    // Replaying on a different account would be a different charge.
    throw new Error(`Attempt ${att.id} ran on ${att.providerAccount ?? "the platform"}, not ${deps.provider.account ?? "the platform"}; not recovered here`);
  }

  const ctx: AttemptCtx = { plan, occ, attemptId: att.id, attemptNo: att.attemptNo, amountCents: att.amountCents, idempotencyKey: att.idempotencyKey };
  const age = att.createdAt ? secondsBetween(att.createdAt, asOf) : Number.POSITIVE_INFINITY;

  if (plan.status === "active" && age < REPLAY_WINDOW_SECONDS) {
    let outcome: ChargeOutcome;
    try {
      outcome = await deps.provider.charge(chargeRequest(plan, occ, { id: att.id, amountCents: att.amountCents, idempotencyKey: att.idempotencyKey }, att.providerAccount));
    } catch (e) {
      outcome = { kind: "indeterminate", message: message(e) };
    }
    if (outcome.kind === "succeeded") {
      // A replay returns Stripe's CACHED first answer, which does not know
      // about a refund made since (the compensation path refunds). Confirm the
      // money is still there before writing a payment for it.
      const found = await deps.provider.findByAttempt(att.id);
      if (!found) {
        await deps.store.recordFailure({ attemptId: att.id, status: "failed", providerRef: outcome.providerRef, errorCode: "charge_refunded_or_missing", errorMessage: "Replay reported success but no un-refunded charge exists", nextAttemptAt: null });
        await pauseAndAlert(deps, plan, occ, "recovery_mismatch", `Attempt ${att.id}: the provider replayed a success (${outcome.providerRef}) but no un-refunded charge was found.`);
        return { ...base, path: "replayed", outcome: "refunded_or_missing" };
      }
      if (found.amountCents !== att.amountCents) {
        return partialRefundFound(deps, plan, occ, att, found, "replayed");
      }
      const r = await recordCardSuccess(deps, ctx, found.providerRef, att.amountCents, asOf);
      return { ...base, path: "replayed", outcome: r.action, paymentId: r.paymentId };
    }
    if (outcome.kind === "indeterminate") {
      if (att.status !== "indeterminate") {
        await deps.store.recordFailure({ attemptId: att.id, status: "indeterminate", errorMessage: outcome.message ?? "No definitive answer on replay" });
      }
      return { ...base, path: "replayed", outcome: "indeterminate" };
    }
    const r = await applyOutcome(deps, ctx, outcome, asOf);
    return { ...base, path: "replayed", outcome: r.action, paymentId: r.paymentId };
  }

  // Too old to replay safely (Stripe forgets keys after 24 h, and a forgotten
  // key is a NEW charge), or the plan is no longer active: look it up.
  const found = await deps.provider.findByAttempt(att.id);
  if (found && found.amountCents !== att.amountCents) {
    return partialRefundFound(deps, plan, occ, att, found, "looked_up");
  }
  if (found) {
    try {
      const { paymentId } = await deps.store.recordSuccess({
        attemptId: att.id,
        amountCents: att.amountCents,
        providerRef: found.providerRef,
        providerAccount: att.providerAccount,
        providerMode: deps.provider.mode,
        paymentProvider: plan.paymentProvider,
        platformAccount: deps.provider.platformAccount ?? "uk",
        paymentDate: localDateInZone(asOf, plan.timezone),
        method: "Card",
      });
      return { ...base, path: "looked_up", outcome: "charged", paymentId };
    } catch (e) {
      // The money is real; the attempt stays in flight and the next tick
      // tries again. Say so loudly — no refund here, the customer owes it.
      await safeSend(deps, { kind: "alert", to: "operator", planId: plan.id, occurrenceId: occ.id, detail: { problem: "recovered_charge_unrecorded", attemptId: att.id, providerRef: found.providerRef, error: message(e) } });
      throw e;
    }
  }
  await deps.store.recordFailure({ attemptId: att.id, status: "abandoned", errorMessage: "No charge found at the provider for this attempt" });
  return { ...base, path: "looked_up", outcome: "abandoned" };
}

// ─────────────────────────────────────────────────────────────────────────────
// Reminders & due work
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @param linkUrlThisTick the payment URL the due work of THIS tick already
 *   emailed for this occurrence (a link, or a card's fallback link). Reused so
 *   the reminder does not mint a fresh token — which would kill the link in
 *   the email the customer received a moment earlier.
 */
async function sendReminder(deps: EngineDeps, plan: PlanRow, occ: OccurrenceRow, offset: number, linkUrlThisTick?: string): Promise<boolean> {
  const inserted = await deps.store.recordEvent({
    planId: plan.id,
    occurrenceId: occ.id,
    kind: "reminder",
    dedupeKey: `reminder:${occ.id}:${offset}`,
    channel: "email",
    amountCents: remainingOf(occ),
    detail: { offset, dueDate: occ.dueDate, method: occ.collectionMethod },
  });
  if (!inserted) return false;
  // A link that is already out gets a FRESH token in the reminder (only the
  // hash is stored, so the old URL cannot be re-sent). The newest email's
  // link always works; payment-plan-pay tells an old one to use it.
  let url: string | undefined;
  const openLink = (await openAttempts(deps.store, occ.id)).find((a) => a.method === "checkout_link");
  if (openLink && linkUrlThisTick) {
    url = linkUrlThisTick;
  } else if (openLink) {
    const minted = await deps.links.mint(occ.id);
    await deps.store.setLinkToken(occ.id, minted.tokenHash);
    url = minted.url;
  }
  await safeSend(deps, {
    kind: "reminder",
    to: "customer",
    planId: plan.id,
    occurrenceId: occ.id,
    url,
    amountCents: remainingOf(occ),
    dueDate: occ.dueDate,
    detail: { offset, method: occ.collectionMethod },
  });
  return true;
}

async function processDue(deps: EngineDeps, plan: PlanRow, occ: OccurrenceRow, asOf: string): Promise<OccurrenceActionResult> {
  if (plan.status !== "active") return { occurrenceId: occ.id, planId: plan.id, action: "noop" };
  switch (occ.collectionMethod) {
    case "manual": {
      const inserted = await deps.store.recordEvent({
        planId: plan.id,
        occurrenceId: occ.id,
        kind: "occurrence_due",
        dedupeKey: `occurrence_due:${occ.id}`,
        amountCents: remainingOf(occ),
        detail: { dueDate: occ.dueDate },
      });
      if (inserted) {
        await safeSend(deps, { kind: "due_manual", to: "operator", planId: plan.id, occurrenceId: occ.id, amountCents: remainingOf(occ), dueDate: occ.dueDate });
        return { occurrenceId: occ.id, planId: plan.id, action: "due_manual", amountCents: remainingOf(occ) };
      }
      return { occurrenceId: occ.id, planId: plan.id, action: "noop" };
    }
    case "auto_charge":
      if (!(await eligible(deps.store, occ, asOf))) return { occurrenceId: occ.id, planId: plan.id, action: "not_eligible" };
      return chargeOccurrence(deps, plan, occ, asOf);
    case "checkout_link":
      if (!(await eligible(deps.store, occ, asOf))) return { occurrenceId: occ.id, planId: plan.id, action: "not_eligible" };
      return sendLink(deps, plan, occ, asOf);
    default:
      throw new PlanStoreError("invalid_input", `Unknown collection method ${String(occ.collectionMethod)}`);
  }
}

/** One pass of the engine. See the file header for the order and why. */
export async function runTick(deps: EngineDeps, opts: { asOf: string; tenantId?: string; planId?: string }): Promise<TickResult> {
  const asOf = new Date(opts.asOf).toISOString();
  setClock(deps.store, asOf);
  const filter = { tenantId: opts.tenantId, planId: opts.planId };
  const result: TickResult = { asOf, recovered: [], reminders: [], actions: [], errors: [] };
  const plans = new Map<string, PlanRow>();
  const planOf = async (id: string) => {
    let p = plans.get(id);
    if (!p) {
      p = await requirePlan(deps.store, id);
      plans.set(id, p);
    }
    return p;
  };

  // 1. Recovery first: an in-flight charge must be resolved before anything
  //    else touches its occurrence.
  let stale: AttemptRow[] = [];
  try {
    stale = await deps.store.staleAttempts(STALE_ATTEMPT_SECONDS, asOf);
  } catch (e) {
    result.errors.push({ stage: "recovery", message: message(e) });
  }
  for (const att of stale) {
    try {
      const r = await recoverAttempt(deps, att, asOf, filter);
      if (r) result.recovered.push(r);
    } catch (e) {
      result.errors.push({ stage: "recovery", attemptId: att.id, occurrenceId: att.occurrenceId, message: message(e) });
    }
  }

  // 1b. Renewals: reconcile, append, post, insure — before any reminder quotes
  //     a period's price and before the due work can charge one.
  if (storeHasRenewals(deps.store)) {
    const stage = await runRenewalStage({ store: deps.store, notifier: deps.notifier, insurer: deps.insurer ?? null }, asOf, filter);
    result.renewals = stage;
    for (const e of stage.errors) result.errors.push({ stage: "renewals", occurrenceId: e.occurrenceId, message: e.planId ? `plan ${e.planId}: ${e.message}` : e.message });
  }

  // One reminder pass. `which` picks the offsets: ≤ 0 before the due work,
  // > 0 after it. Each pass lists what is open AT THAT MOMENT, so the second
  // one never reminds about an occurrence the due work has just settled.
  const remind = async (which: "before_due" | "after_due", planOfPass: (id: string) => Promise<PlanRow>, linkUrls: Map<string, string>) => {
    let forReminders: OccurrenceRow[] = [];
    try {
      forReminders = await deps.store.listForReminders(asOf, REMINDER_HORIZON_DAYS, filter);
    } catch (e) {
      result.errors.push({ stage: "reminders", message: message(e) });
    }
    for (const occ of forReminders) {
      try {
        if (occ.status === "processing") continue; // a card charge is running right now
        const plan = await planOfPass(occ.planId);
        if (plan.status !== "active") continue;
        const today = localDateInZone(asOf, plan.timezone);
        // A card retry still to come TODAY decides whether "still unpaid" is
        // true. The cron ticks all day, so without this the first tick after
        // local midnight would send it hours before a 10:00 retry succeeds.
        // The retry's own tick (later today) sends it if the retry fails.
        const retryLaterToday =
          which === "after_due" &&
          occ.status === "failed" &&
          !!occ.nextAttemptAt &&
          compareInstants(occ.nextAttemptAt, asOf) > 0 &&
          localDateInZone(occ.nextAttemptAt, plan.timezone) === today;
        for (const offset of plan.reminderOffsets ?? []) {
          if (which === "before_due" ? offset > 0 : offset <= 0) continue;
          if (retryLaterToday) continue;
          if (addDays(occ.dueDate, offset) !== today) continue;
          const sent = await sendReminder(deps, plan, occ, offset, linkUrls.get(occ.id));
          result.reminders.push({ occurrenceId: occ.id, planId: plan.id, offset, sent });
        }
      } catch (e) {
        result.errors.push({ stage: "reminders", occurrenceId: occ.id, message: message(e) });
      }
    }
  };

  // 2. Reminders that come before the money: "due in two days", "charging today".
  await remind("before_due", planOf, new Map());

  // 3. Due work.
  let due: OccurrenceRow[] = [];
  try {
    due = await deps.store.collectDue(asOf, filter);
  } catch (e) {
    result.errors.push({ stage: "due", message: message(e) });
  }
  for (const occ of due) {
    try {
      // Re-read: recovery or a reminder earlier in this tick may have moved it.
      const fresh = await requireOccurrence(deps.store, occ.id);
      const plan = await requirePlan(deps.store, fresh.planId); // fresh: a pause earlier in the tick must stop this
      result.actions.push(await processDue(deps, plan, fresh, asOf));
    } catch (e) {
      result.errors.push({ stage: "due", occurrenceId: occ.id, message: message(e) });
    }
  }

  // 4. Reminders that say "still unpaid" — only now, after this tick's retry
  //    has had its chance, and only for what it left open. A plan the due
  //    work touched is re-read: it may have paused it (an integration bug),
  //    and a paused plan sends no reminders.
  for (const occ of due) plans.delete(occ.planId);
  const linkUrls = new Map<string, string>();
  for (const a of result.actions) {
    const url = a.url ?? a.fallback?.url;
    if (url) linkUrls.set(a.occurrenceId, url);
  }
  await remind("after_due", planOf, linkUrls);
  return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// Operator actions
// ─────────────────────────────────────────────────────────────────────────────

const OPERATOR_COLLECTABLE = new Set(["due", "failed", "requires_action", "partially_paid"]);

/**
 * The operator's "Retry" (design §8 occurrence_retry): collect THIS occurrence
 * now, by its method, through the same path the cron takes — but without the
 * automatic-eligibility gate, because a person decided. This is the only way a
 * refunded occurrence (D12) is ever charged again.
 */
export async function collectOccurrenceNow(deps: EngineDeps, occurrenceId: string, asOf: string): Promise<OccurrenceActionResult> {
  setClock(deps.store, asOf);
  const occ = await requireOccurrence(deps.store, occurrenceId);
  const plan = await requirePlan(deps.store, occ.planId);
  if (plan.status !== "active") throw new PlanStoreError("refused", `The plan is ${plan.status}; resume it before collecting`);
  if (!OPERATOR_COLLECTABLE.has(occ.status)) {
    throw new PlanStoreError("refused", occ.status === "scheduled" ? "This payment is not due yet — move its date to collect it now" : `A ${occ.status} payment cannot be collected`);
  }
  switch (occ.collectionMethod) {
    case "manual":
      throw new PlanStoreError("refused", "This payment is collected by hand — record the payment instead");
    case "checkout_link":
      return sendOccurrenceLink(deps, occurrenceId, asOf);
    case "auto_charge": {
      await releaseOpenLinks(deps.store, occ.id, "Operator retried the card");
      const fresh = await requireOccurrence(deps.store, occ.id);
      return chargeOccurrence(deps, plan, fresh, asOf);
    }
    default:
      throw new PlanStoreError("invalid_input", `Unknown collection method ${String(occ.collectionMethod)}`);
  }
}

/**
 * The operator's "Send link" (design §8 occurrence_send_link). When a link is
 * already out, re-sends it with a fresh token (the old URL stops working);
 * otherwise claims a new link attempt.
 */
export async function sendOccurrenceLink(deps: EngineDeps, occurrenceId: string, asOf: string): Promise<OccurrenceActionResult> {
  setClock(deps.store, asOf);
  const occ = await requireOccurrence(deps.store, occurrenceId);
  const plan = await requirePlan(deps.store, occ.planId);
  // pp_claim only collects on an active plan; a re-send follows the same rule.
  if (plan.status !== "active") throw new PlanStoreError("refused", `The plan is ${plan.status}; resume it before sending a link`);
  if (!OPERATOR_COLLECTABLE.has(occ.status)) {
    throw new PlanStoreError("refused", occ.status === "scheduled" ? "This payment is not due yet — move its date to send a link now" : `A ${occ.status} payment cannot be sent a link`);
  }
  const open = await openAttempts(deps.store, occ.id);
  if (open.some((a) => a.method !== "checkout_link")) {
    throw new PlanStoreError("attempt_in_flight", "A card payment is in progress on this occurrence; wait for it to finish");
  }
  const existing = open.find((a) => a.method === "checkout_link");
  if (existing) {
    const minted = await deps.links.mint(occ.id);
    await deps.store.setLinkToken(occ.id, minted.tokenHash);
    const sendError = await safeSend(deps, { kind: "link", to: "customer", planId: plan.id, occurrenceId: occ.id, url: minted.url, amountCents: remainingOf(occ), dueDate: occ.dueDate, detail: { attemptId: existing.id, resent: true } });
    await deps.store.recordEvent({
      planId: plan.id,
      occurrenceId: occ.id,
      kind: "link_sent",
      channel: "email",
      amountCents: remainingOf(occ),
      detail: { attemptId: existing.id, resent: true, ...(sendError ? { deliveryError: sendError } : {}) },
    });
    return { occurrenceId: occ.id, planId: plan.id, action: "link_sent", attemptId: existing.id, attemptNo: existing.attemptNo, idempotencyKey: existing.idempotencyKey, amountCents: existing.amountCents, url: minted.url };
  }
  return sendLink(deps, plan, occ, asOf);
}

export interface LinkPaidInput {
  attemptId: string;
  providerRef: string;
  amountCents: number;
  paidAt: string;
  checkoutSessionId?: string | null;
  /** pm_… saved by the Checkout (setup_future_usage); becomes the plan's card. */
  paymentMethodRef?: string | null;
  providerMode?: "test" | "live" | null;
  platformAccount?: "uk" | "uae";
}

export type LinkPaidResult =
  | { status: "recorded"; paymentId: string; occurrenceStatusBefore: string }
  | { status: "already_recorded"; paymentId: string | null }
  | { status: "duplicate_payment"; paymentId: string | null };

/**
 * What the webhook does when a plan's Checkout completes (design §8). The
 * store call is idempotent on the attempt, so a double delivery writes one
 * payment (S7). A DIFFERENT payment for an attempt that already succeeded —
 * the customer paid two sessions — is not silently dropped: it is reported to
 * the operator, who decides whether to refund it.
 */
export async function onLinkPaid(deps: Pick<EngineDeps, "store" | "notifier">, input: LinkPaidInput): Promise<LinkPaidResult> {
  setClock(deps.store, input.paidAt);
  const att = await deps.store.getAttempt(input.attemptId);
  if (!att) throw new PlanStoreError("not_found", `Attempt ${input.attemptId} not found`);
  const occ = await requireOccurrence(deps.store, att.occurrenceId);
  const plan = await requirePlan(deps.store, occ.planId);

  if (att.status === "succeeded") {
    if (!input.providerRef || !att.providerRef || att.providerRef === input.providerRef) {
      return { status: "already_recorded", paymentId: att.paymentId };
    }
    await safeSend(deps, {
      kind: "alert",
      to: "operator",
      planId: plan.id,
      occurrenceId: occ.id,
      amountCents: input.amountCents,
      detail: { problem: "duplicate_link_payment", attemptId: att.id, recordedRef: att.providerRef, extraRef: input.providerRef, checkoutSessionId: input.checkoutSessionId ?? null },
    });
    return { status: "duplicate_payment", paymentId: att.paymentId };
  }

  const before = occ.status;
  const { paymentId } = await deps.store.recordSuccess({
    attemptId: att.id,
    amountCents: input.amountCents,
    providerRef: input.providerRef,
    providerAccount: att.providerAccount,
    providerMode: input.providerMode ?? att.providerMode ?? null,
    paymentProvider: plan.paymentProvider,
    platformAccount: input.platformAccount ?? "uk",
    paymentDate: localDateInZone(input.paidAt, plan.timezone),
    method: "Card",
    checkoutSessionId: input.checkoutSessionId ?? null,
  });
  if (input.paymentMethodRef && input.paymentMethodRef !== plan.stripePaymentMethodId) {
    await deps.store.setPaymentMethod(plan.id, input.paymentMethodRef);
  }
  if (before === "paid" || before === "skipped" || before === "superseded" || before === "cancelled" || before === "waived") {
    // Paid through a link after the occurrence was already settled or closed
    // (released link, operator recorded cash meanwhile). The money is real and
    // is now on the rental; a person should decide about a refund.
    await safeSend(deps, {
      kind: "alert",
      to: "operator",
      planId: plan.id,
      occurrenceId: occ.id,
      amountCents: input.amountCents,
      detail: { problem: "link_paid_after_settled", occurrenceStatus: before, paymentId, providerRef: input.providerRef },
    });
  }
  return { status: "recorded", paymentId, occurrenceStatusBefore: before };
}

export interface ManualPaymentInput {
  occurrenceId: string;
  amountCents: number;
  method: ManualMethod | string;
  paymentDate: ISODate;
  note?: string | null;
  actorId?: string | null;
  /** The instant of the action, for a simulated clock. */
  asOf?: string;
}

/**
 * The operator states money they already received (design §8
 * occurrence_record_payment). Nothing is charged. An outstanding link is
 * released first so the customer cannot pay the same thing twice through it.
 */
export async function recordManualPayment(deps: Pick<EngineDeps, "store" | "notifier">, input: ManualPaymentInput): Promise<{ paymentId: string; attemptId: string; releasedLinks: number }> {
  if (input.asOf) setClock(deps.store, input.asOf);
  if (!Number.isSafeInteger(input.amountCents) || input.amountCents < 1) throw new PlanStoreError("invalid_input", "The amount must be at least 1 cent");
  if (!(MANUAL_METHODS as readonly string[]).includes(input.method)) {
    throw new PlanStoreError("invalid_input", `Method must be one of: ${MANUAL_METHODS.join(", ")}`);
  }
  if (!isISODate(input.paymentDate)) throw new PlanStoreError("invalid_input", `Bad payment date ${input.paymentDate}`);
  const occ = await requireOccurrence(deps.store, input.occurrenceId);
  const plan = await requirePlan(deps.store, occ.planId);
  if (!["scheduled", "due", "failed", "requires_action", "partially_paid"].includes(occ.status)) {
    throw new PlanStoreError("refused", `A ${occ.status} payment cannot take a manual record`);
  }
  const releasedLinks = await releaseOpenLinks(deps.store, occ.id, "Operator recorded a payment by hand");
  const claimed = await deps.store.claim(occ.id, "manual", null);
  if (!isClaimOk(claimed)) {
    throw new PlanStoreError(
      "refused",
      claimed.reason === "nothing_owed"
        ? "The rental owes nothing, so this payment is already covered (it has been marked covered by balance). Record the money as a payment on the rental instead."
        : claimed.reason === "held_elsewhere"
          ? "A card payment is in progress on this payment; wait for it to finish"
          : "This payment cannot take a manual record in its current state",
    );
  }
  try {
    const { paymentId } = await deps.store.recordSuccess({
      attemptId: claimed.claim.attemptId,
      amountCents: input.amountCents,
      providerRef: null,
      providerAccount: null,
      providerMode: null,
      paymentProvider: plan.paymentProvider,
      platformAccount: "uk",
      paymentDate: input.paymentDate,
      method: input.method,
      note: input.note ?? null,
      actorId: input.actorId ?? null,
    });
    return { paymentId, attemptId: claimed.claim.attemptId, releasedLinks };
  } catch (e) {
    try {
      await deps.store.recordFailure({ attemptId: claimed.claim.attemptId, status: "abandoned", errorMessage: `Manual record failed: ${message(e)}` });
    } catch {
      /* recovery abandons a stale manual claim anyway */
    }
    throw e;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// The form → a plan row + its schedule (preview / create / update)
// ─────────────────────────────────────────────────────────────────────────────

/** What the operator fills in (design §9 "the one form"). No charged amount comes from here for split modes. */
export interface PlanForm {
  freq: Freq;
  interval: number;
  byWeekday?: Weekday[];
  byMonthDay?: number;
  dates?: ISODate[];
  anchor: ISODate;
  firstOccurrence: "on_anchor" | "on_rhythm";
  end: { kind: "rental_end" } | { kind: "count"; count: number } | { kind: "until"; until: ISODate } | { kind: "open"; through: ISODate };
  amountMode: AmountMode;
  /** fixed only. */
  fixedAmountCents?: number | null;
  /** per_period only. */
  dailyRateCents?: number | null;
  collectionMethod: CollectionMethod;
  fallbackToLink?: boolean;
  maxAttempts?: number;
  retryAfterDays?: number;
  reminderOffsets?: number[];
  chargeLocalTime?: string;
  overrides?: ScheduleOverride[];
  /**
   * Additive (Wave 3): "keeps renewing until stopped". With renewal set the
   * plan RENEWS THE RENTAL one period at a time: end.kind must be 'open', the
   * anchor is the rental's end date (whatever the form says), the rhythm is
   * the period, and every amount is priced by the server exactly as
   * auto-extend prices a period (ctx.renewalPricing) — freq, interval,
   * weekdays, anchor and the amount fields of the form are not used.
   */
  renewal?: {
    extendsRental: true;
    periodUnit: RenewalPeriodUnit;
    periodCount: number;
    insurance?: RenewalCoverage | null;
    sendAgreementEachPeriod: boolean;
  };
}

/** What only the server knows (or the simulator's store). */
export interface PlanContext {
  tenantId: string;
  rentalId: string;
  customerId: string;
  /** rentals.end_date; required for end kind 'rental_end'. */
  rentalEnd: ISODate | null;
  timezone: string;
  currency: string;
  paymentProvider: "stripe" | "square";
  /** pp_rental_owed_cents — the total a split plan collects. */
  owedCents: number;
  stripePaymentMethodId?: string | null;
  /** Additive (Wave 3): the rental's rate and the tenant's tax/fee settings — required for a renewal form. */
  renewalPricing?: Pick<RenewalPricingInputs, "monthlyAmount" | "discountApplied" | "tenant"> | null;
}

export interface PlanDraft {
  plan: Omit<PlanRow, "id" | "version" | "status">;
  occurrences: OccurrenceDraft[];
  summary: {
    count: number;
    totalCents: number;
    owedCents: number;
    /** The plan's total differs from what the rental owes — the form warns. */
    differsFromOwed: boolean;
    firstDueDate: ISODate;
    lastDueDate: ISODate;
    /** due_at of each occurrence, in order (the preview shows the local time). */
    dueAts: string[];
    /** Additive (Wave 3): a renewing plan's first period and what one period costs. */
    renewal?: {
      periodStart: ISODate;
      periodEnd: ISODate;
      days: number;
      breakdown: RenewalBreakdown;
      insurance: RenewalCoverage | null;
    };
  };
}

/**
 * Turn the form into the plan row and its occurrences. Used by preview (no
 * writes), create and update, on the server AND in the simulator, so the
 * preview can never show a schedule the server would not store.
 *
 * The SERVER derives the money: split_total / split_by_days always collect
 * `ctx.owedCents` (pp_rental_owed_cents), never a total from the browser.
 * fixed / per_period amounts are the operator's price; the claim still caps
 * every collection at what the rental owes (D5).
 */
export function planFormToRowAndSchedule(form: PlanForm, ctx: PlanContext): PlanDraft {
  if (!form || typeof form !== "object") throw new RangeError("A plan form is required");
  if (!isValidTimeZone(ctx.timezone)) throw new RangeError(`Unknown timezone ${ctx.timezone}`);
  const chargeLocalTime = form.chargeLocalTime ?? DEFAULT_CHARGE_LOCAL_TIME;
  validateChargeTime(chargeLocalTime);
  if (form.renewal) return renewalFormToRowAndSchedule(form, ctx, chargeLocalTime);

  let end: ScheduleEnd;
  switch (form.end?.kind) {
    case "rental_end":
      if (!ctx.rentalEnd) throw new PlanRuleError("no_occurrences", "This rental has no end date — choose a number of payments or an end date");
      end = { kind: "rental_end", rentalEnd: ctx.rentalEnd };
      break;
    case "count":
      end = { kind: "count", count: form.end.count };
      break;
    case "until":
      end = { kind: "until", until: form.end.until };
      break;
    case "open":
      end = { kind: "open", through: form.end.through };
      break;
    default:
      throw new RangeError("The form needs an end");
  }

  const rule: ScheduleRule = {
    freq: form.freq,
    interval: form.interval,
    anchor: form.anchor,
    firstOccurrence: form.firstOccurrence,
    end,
    ...(form.freq === "weekly" ? { byWeekday: form.byWeekday } : {}),
    ...(form.freq === "monthly" ? { byMonthDay: form.byMonthDay } : {}),
    ...(form.freq === "dates" ? { dates: form.dates } : {}),
  };

  let amount: AmountSpec;
  switch (form.amountMode) {
    case "split_total":
      amount = { mode: "split_total", totalCents: ctx.owedCents };
      break;
    case "split_by_days":
      amount = { mode: "split_by_days", totalCents: ctx.owedCents };
      break;
    case "fixed":
      amount = { mode: "fixed", amountCents: form.fixedAmountCents as number };
      break;
    case "per_period":
      amount = { mode: "per_period", dailyRateCents: form.dailyRateCents as number };
      break;
    default:
      throw new RangeError(`Unknown amount mode ${JSON.stringify(form.amountMode)}`);
  }

  const collection = collectionSettings(form);

  const occurrences = buildSchedule(rule, amount, form.overrides);
  const totalCents = occurrences.reduce((s, o) => s + o.amountCents, 0);
  const plan: Omit<PlanRow, "id" | "version" | "status"> = {
    tenantId: ctx.tenantId,
    rentalId: ctx.rentalId,
    customerId: ctx.customerId,
    rule,
    amount,
    currency: (ctx.currency || "usd").toLowerCase(),
    timezone: ctx.timezone,
    chargeLocalTime,
    ...collection,
    paymentProvider: ctx.paymentProvider,
    stripePaymentMethodId: ctx.stripePaymentMethodId ?? null,
    extendsRental: false,
  };
  return {
    plan,
    occurrences,
    summary: {
      count: occurrences.length,
      totalCents,
      owedCents: ctx.owedCents,
      differsFromOwed: totalCents !== ctx.owedCents,
      firstDueDate: occurrences[0].dueDate,
      lastDueDate: occurrences[occurrences.length - 1].dueDate,
      dueAts: occurrences.map((o) => dueAtUtc(o.dueDate, chargeLocalTime, ctx.timezone)),
    },
  };
}

/** The collection half of the form (method, retries, reminders), checked. Shared by every plan shape. */
function collectionSettings(form: PlanForm): Pick<PlanRow, "collectionMethod" | "fallbackToLink" | "maxAttempts" | "retryAfterDays" | "reminderOffsets"> {
  const maxAttempts = form.maxAttempts ?? 3;
  const retryAfterDays = form.retryAfterDays ?? 2;
  if (!Number.isInteger(maxAttempts) || maxAttempts < 1 || maxAttempts > 10) throw new RangeError("maxAttempts must be 1–10");
  if (!Number.isInteger(retryAfterDays) || retryAfterDays < 1 || retryAfterDays > 14) throw new RangeError("retryAfterDays must be 1–14");
  const offsets = [...new Set(form.reminderOffsets ?? [-2, 0, 2])].sort((a, b) => a - b);
  if (offsets.some((o) => !Number.isInteger(o) || Math.abs(o) > REMINDER_HORIZON_DAYS)) {
    throw new RangeError(`Reminder offsets must be whole days within ±${REMINDER_HORIZON_DAYS}`);
  }
  if (!["auto_charge", "checkout_link", "manual"].includes(form.collectionMethod)) {
    throw new RangeError(`Unknown collection method ${JSON.stringify(form.collectionMethod)}`);
  }
  return { collectionMethod: form.collectionMethod, fallbackToLink: form.fallbackToLink ?? true, maxAttempts, retryAfterDays, reminderOffsets: offsets };
}

/**
 * A renewing plan (Wave 3): the rental's end date is the anchor, one period is
 * the rhythm, and the plan is created with its FIRST period only — the engine
 * appends each next one when the last is settled (renewals.ts). The price is
 * auto-extend's (renewalBreakdownCents); insurance is bought per period later.
 */
function renewalFormToRowAndSchedule(form: PlanForm, ctx: PlanContext, chargeLocalTime: string): PlanDraft {
  const ren = form.renewal!;
  if (ren.extendsRental !== true) throw new RangeError("renewal.extendsRental must be true");
  if (!["day", "week", "month"].includes(ren.periodUnit)) throw new RangeError(`Unknown renewal period unit ${JSON.stringify(ren.periodUnit)}`);
  if (!Number.isInteger(ren.periodCount) || ren.periodCount < 1 || ren.periodCount > MAX_RENEWAL_PERIOD_COUNT) {
    throw new PlanRuleError("interval_invalid", `A renewal period is 1 to ${MAX_RENEWAL_PERIOD_COUNT} ${ren.periodUnit}s`);
  }
  if (form.end?.kind !== "open") throw new RangeError("A renewing plan is open-ended: end.kind must be 'open'");
  if (!ctx.rentalEnd) throw new PlanRuleError("no_occurrences", "This rental has no end date — a renewing plan starts on it");
  if (!ctx.renewalPricing) throw new RangeError("A renewing plan needs the rental's rate (ctx.renewalPricing)");
  const anchor = ctx.rentalEnd;
  parseISODate(anchor);

  const freq: Freq = ren.periodUnit === "day" ? "daily" : ren.periodUnit === "week" ? "weekly" : "monthly";
  const rule: ScheduleRule = {
    freq,
    interval: ren.periodCount,
    anchor,
    firstOccurrence: "on_anchor",
    end: { kind: "open", through: anchor },
    ...(freq === "weekly" ? { byWeekday: [isoWeekday(anchor)] } : {}),
    ...(freq === "monthly" ? { byMonthDay: parseISODate(anchor).d } : {}),
  };
  const breakdown = renewalBreakdownCents(ctx.renewalPricing);
  const first = nextRenewalDraft(anchor, ren, ctx.renewalPricing);
  const insurance = normalizeCoverage(ren.insurance ?? null);
  const plan: Omit<PlanRow, "id" | "version" | "status"> = {
    tenantId: ctx.tenantId,
    rentalId: ctx.rentalId,
    customerId: ctx.customerId,
    rule,
    amount: { mode: "fixed", amountCents: breakdown.totalCents },
    currency: (ctx.currency || "usd").toLowerCase(),
    timezone: ctx.timezone,
    chargeLocalTime,
    ...collectionSettings(form),
    paymentProvider: ctx.paymentProvider,
    stripePaymentMethodId: ctx.stripePaymentMethodId ?? null,
    extendsRental: true,
    renewal: { periodUnit: ren.periodUnit, periodCount: ren.periodCount, insurance, sendAgreementEachPeriod: !!ren.sendAgreementEachPeriod },
  };
  return {
    plan,
    occurrences: [first],
    summary: {
      count: 1,
      totalCents: breakdown.totalCents,
      owedCents: ctx.owedCents,
      // A renewing plan does not collect the balance; it prices each new period.
      differsFromOwed: false,
      firstDueDate: first.dueDate,
      lastDueDate: first.dueDate,
      dueAts: [dueAtUtc(first.dueDate, chargeLocalTime, ctx.timezone)],
      renewal: { periodStart: first.periodStart, periodEnd: first.periodEnd, days: first.days, breakdown, insurance },
    },
  };
}

/** payment_plans.renewal_period_count is 1..52. */
export const MAX_RENEWAL_PERIOD_COUNT = 52;
