/**
 * Payment plans — the SHADOW COMPARISON for rentals still on auto-extend
 * (Wave 3; roadmap "Shadow comparison for existing auto-extend rentals").
 *
 * Before any auto-extend rental is moved onto a renewal plan, this computes —
 * with NO writes — what the old job (auto-extend-rentals) would charge for the
 * next periods next to what the plan engine would charge for the same periods,
 * and says in words wherever they differ. Both sides use the same extracted
 * helpers (renewal-pricing.ts), so a difference is a real difference in rules,
 * never two copies of the arithmetic drifting apart.
 *
 * The OLD side follows auto-extend-rentals line by line: period k runs from
 * E_k to addPeriod(E_k); its price is the per-occurrence override for E_k
 * (priceOverride is tax-inclusive, backed out at the tenant's tax rate) or
 * computeBreakdown(discountedRate(rental)); plus that override's extras and
 * insurance premium; minus the customer's unapplied credit (applied by FIFO
 * after any open non-extension charge). It charges at the renewal grid date
 * (applyExceptions) 00:00 UTC less the lead hours; period 0 uses the rental's
 * real pointer (auto_extend_next_charge_at).
 * The NEW side is the renewal plan: the same period, priced with no
 * per-period override, insurance bought before the charge, the rental's own
 * credit, charged at the plan's local charge time on the period's first day.
 *
 * `matches` compares money and dates only (period, amount, rental/tax/fee/
 * insurance). The instant of the charge always differs by design and is
 * reported in `notes`, never as a mismatch.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type { ISODate, RenewalPricingInputs } from "./types.ts";
import { addPeriod, applyExceptions, computeBreakdown, discountedRate, dollarsToCents, round2 } from "./renewal-pricing.ts";
import { dueAtUtc, localDateInZone, parseISODate } from "./dates.ts";

/** The auto-extend columns of one rental (rentals.auto_extend_*), as read. */
export interface AutoExtendSnapshot {
  rentalId: string;
  enabled: boolean;
  /** rentals.status — the old job only runs 'Active' rentals. */
  status: string | null;
  endDate: ISODate | null;
  monthlyAmount: number | null;
  discountApplied: number | null;
  /** 'Daily' | 'Weekly' | 'Monthly' (anything else is Weekly, as in addPeriod). */
  periodUnit: string | null;
  intervalCount: number | null;
  exceptions: unknown;
  // deno-lint-ignore no-explicit-any
  overrides: Record<string, any> | null;
  nextChargeAt: string | null;
  leadHours: number | null;
  chargeCount: number | null;
  maxPeriods: number | null;
  pendingExtensionId: string | null;
  paused: boolean;
  chargeMode: string | null;
}

export interface ShadowInputs {
  rental: AutoExtendSnapshot;
  tenant: RenewalPricingInputs["tenant"] & {
    timezone: string;
    /** AUTOEXT_ADJ_CREDIT_TENANTS includes this tenant: the old job also spends negative Adjustment rows. */
    adjustmentCreditEnabled?: boolean;
  };
  /** Unapplied credit the OLD job spends: every Credit/Partial payment of the CUSTOMER, in cents. */
  customerCreditCents: number;
  /** Unapplied credit the PLAN spends: the RENTAL's own Credit/Partial payments, in cents. */
  rentalCreditCents: number;
  /** Open non-extension charges on the rental, in cents — FIFO pays these before any extension. */
  openBaseChargesCents: number;
  /**
   * Premium in cents for each period start whose override buys insurance
   * (bonzah-calculate-premium, read-only); null = could not be priced.
   */
  premiums?: Record<ISODate, number | null>;
  /** How many periods to compare (1–12, default 4). */
  periods?: number;
  /** The plan's charge time (default 10:00). */
  chargeLocalTime?: string;
}

export interface ShadowBreakdown {
  rentalCents: number;
  taxCents: number;
  serviceFeeCents: number;
  extrasCents: number;
  insuranceCents: number;
  creditAppliedCents: number;
  /** What is charged: rental + tax + fee + extras + insurance − credit. */
  totalCents: number;
}

export interface ShadowRow {
  /** 'YYYY-MM-DD → YYYY-MM-DD' (end exclusive: the new end date). */
  period: string;
  oldEngine: { dueAt: string | null; chargeDate: ISODate | null; amountCents: number; breakdown: ShadowBreakdown };
  newEngine: { dueAt: string; amountCents: number; breakdown: ShadowBreakdown };
  matches: boolean;
  notes: string[];
}

export interface ShadowResult {
  rows: ShadowRow[];
  /** About the rental as a whole (paused, a parked week, auto-extend off …). */
  notes: string[];
}

export const SHADOW_DEFAULT_PERIODS = 4;
export const SHADOW_MAX_PERIODS = 12;

const EMPTY: ShadowBreakdown = { rentalCents: 0, taxCents: 0, serviceFeeCents: 0, extrasCents: 0, insuranceCents: 0, creditAppliedCents: 0, totalCents: 0 };

function money(cents: number): string {
  const sign = cents < 0 ? "-" : "";
  const abs = Math.abs(cents);
  return `${sign}$${Math.floor(abs / 100)}.${String(abs % 100).padStart(2, "0")}`;
}

/** 'YYYY-MM-DD' at 00:00 UTC, less `hours`, as an ISO instant (auto-extend's next_charge_at). */
function gridInstant(gridYmd: ISODate, hours: number): string {
  const d = new Date(`${gridYmd}T00:00:00Z`);
  d.setUTCHours(d.getUTCHours() - (Number(hours) || 0));
  return d.toISOString();
}

export function shadowCompare(input: ShadowInputs): ShadowResult {
  const r = input.rental;
  const tz = input.tenant.timezone;
  const unit = r.periodUnit || "Weekly";
  const count = r.intervalCount || 1;
  const lead = Number(r.leadHours) || 0;
  const n = Math.min(SHADOW_MAX_PERIODS, Math.max(1, Math.floor(input.periods ?? SHADOW_DEFAULT_PERIODS)));
  const chargeTime = input.chargeLocalTime ?? "10:00";
  const notes: string[] = [];

  if (!r.enabled) notes.push("Auto-extend is off for this rental: the old job charges nothing. The rows show what it would charge if it were on.");
  if (r.status !== "Active") notes.push(`The rental is '${r.status ?? "unknown"}', not 'Active': the old job skips it.`);
  if (r.paused) notes.push("Auto-extend is paused: the old job charges nothing until someone resumes it (a plan would be paused the same way).");
  if (r.pendingExtensionId) {
    notes.push(`A renewal is already parked unpaid (extension ${r.pendingExtensionId}): the old job creates no new period until it is paid, and pauses after the grace window. Settle or move that period before the rental moves to a plan.`);
  }
  if (input.tenant.adjustmentCreditEnabled) {
    notes.push("This tenant's old job also spends negative 'Adjustment' credit rows; the plan spends credit payments only. Any such adjustment credit is not in these numbers.");
  }
  if (input.customerCreditCents !== input.rentalCreditCents) {
    notes.push(`Credit scope differs: the old job spends all of the customer's unapplied credit (${money(input.customerCreditCents)}), the plan only this rental's (${money(input.rentalCreditCents)}).`);
  }
  if (!r.endDate) {
    notes.push("The rental has no end date: neither engine can renew it.");
    return { rows: [], notes };
  }

  let oldCredit = Math.max(0, input.customerCreditCents - input.openBaseChargesCents);
  let newCredit = Math.max(0, input.rentalCreditCents - input.openBaseChargesCents);
  const pricing = { monthlyAmount: r.monthlyAmount, discountApplied: r.discountApplied, tenant: input.tenant };
  const rows: ShadowRow[] = [];
  let start: ISODate = r.endDate;

  for (let k = 0; k < n; k++) {
    const { newEndDate: end } = addPeriod(start, unit, count);
    const rowNotes: string[] = [];
    // deno-lint-ignore no-explicit-any
    const occ: any = (r.overrides && r.overrides[start]) || {};

    // ── OLD: auto-extend-rentals, per period ─────────────────────────────────
    let bd: { rental: number; tax: number; serviceFee: number; total: number };
    if (occ.priceOverride != null && Number(occ.priceOverride) >= 0) {
      const taxPct = input.tenant?.tax_enabled ? Number(input.tenant?.tax_percentage || 0) : 0;
      const incl = round2(Number(occ.priceOverride));
      const rental = taxPct > 0 ? round2(incl / (1 + taxPct / 100)) : incl;
      bd = { rental, tax: round2(incl - rental), serviceFee: 0, total: incl };
      rowNotes.push(`The old job uses this period's price override (${money(dollarsToCents(incl))} including tax); a plan has no per-period price, so it charges the rental's rate.`);
    } else {
      bd = computeBreakdown(discountedRate({ monthly_amount: r.monthlyAmount, discount_applied: r.discountApplied }), input.tenant);
    }
    const extras: number = Array.isArray(occ.extras)
      ? round2(
          occ.extras
            // deno-lint-ignore no-explicit-any
            .filter((e: any) => e && Number(e.amount) > 0)
            // deno-lint-ignore no-explicit-any
            .reduce((s: number, e: any) => s + round2(Number(e.amount)), 0),
        )
      : 0;
    if (extras > 0) rowNotes.push(`The old job adds ${money(dollarsToCents(extras))} of extras for this period ('Extension Add-on'); a plan period carries none — record them as a charge on the rental.`);
    const cov = occ.buyInsurance && occ.insuranceCoverage ? occ.insuranceCoverage : null;
    const buysCover = !!cov && (cov.cdw || cov.rcli || cov.sli || cov.pai);
    let premiumCents = 0;
    if (buysCover) {
      const p = input.premiums?.[start];
      if (p === null || p === undefined) {
        rowNotes.push("This period's override buys insurance, but its premium could not be priced here, so neither side includes it.");
      } else {
        premiumCents = p;
        rowNotes.push(`The old job charges a ${money(p)} insurance premium and buys NO policy (it only prices one); the plan buys the policy (quote → confirm) before charging, and charges nothing if Bonzah cannot cover the period.`);
      }
    }
    const oldGross = dollarsToCents(round2(bd.total + extras + premiumCents / 100));
    const stopped = !!r.maxPeriods && (Number(r.chargeCount) || 0) + k >= r.maxPeriods;
    const grid = applyExceptions(start, unit, count, r.exceptions);
    const computedDue = gridInstant(grid, lead);
    let oldDueAt: string | null = k === 0 && r.nextChargeAt ? new Date(r.nextChargeAt).toISOString() : computedDue;
    if (k === 0 && r.nextChargeAt && oldDueAt !== computedDue) {
      rowNotes.push(`The old job's pointer (auto_extend_next_charge_at) is ${oldDueAt}, not the ${computedDue} its schedule gives: it charges at the pointer.`);
    }
    if (grid !== start) {
      rowNotes.push(`A schedule exception moves the old job's charge for this period from ${start} to ${grid}; the plan charges on the period's first day (use Move on that payment to match).`);
    }
    let oldBreakdown: ShadowBreakdown;
    if (stopped) {
      oldBreakdown = { ...EMPTY };
      oldDueAt = null;
      rowNotes.push(`auto_extend_max_periods (${r.maxPeriods}) is reached: the old job stops here. A plan renews until it is cancelled.`);
    } else if (oldGross <= 0) {
      oldBreakdown = { ...EMPTY };
      rowNotes.push("The old job skips a period that costs nothing.");
    } else {
      const applied = Math.min(oldCredit, oldGross);
      oldCredit -= applied;
      if (applied >= oldGross) rowNotes.push("The old job covers this period entirely from credit: no charge, no link.");
      oldBreakdown = {
        rentalCents: dollarsToCents(bd.rental),
        taxCents: dollarsToCents(bd.tax),
        serviceFeeCents: dollarsToCents(bd.serviceFee),
        extrasCents: dollarsToCents(extras),
        insuranceCents: premiumCents,
        creditAppliedCents: applied,
        totalCents: oldGross - applied,
      };
    }

    // ── NEW: the renewal plan, same period ───────────────────────────────────
    const nb = computeBreakdown(discountedRate({ monthly_amount: pricing.monthlyAmount, discount_applied: pricing.discountApplied }), pricing.tenant);
    const newGross = dollarsToCents(nb.rental) + dollarsToCents(nb.tax) + dollarsToCents(nb.serviceFee) + premiumCents;
    const newApplied = Math.min(newCredit, Math.max(0, newGross));
    newCredit -= newApplied;
    const newBreakdown: ShadowBreakdown = {
      rentalCents: dollarsToCents(nb.rental),
      taxCents: dollarsToCents(nb.tax),
      serviceFeeCents: dollarsToCents(nb.serviceFee),
      extrasCents: 0,
      insuranceCents: premiumCents,
      creditAppliedCents: newApplied,
      totalCents: Math.max(0, newGross - newApplied),
    };
    const newDueAt = dueAtUtc(start, chargeTime, tz);

    if (unit === "Monthly" && parseISODate(start).d > 28) {
      rowNotes.push(`Month end: auto-extend's addPeriod rolls ${start} + ${count} month(s) over to ${end} (a short month overflows). Both engines use the same helper, so they agree — check the date is what you want.`);
    }
    if (oldDueAt && oldDueAt !== newDueAt) {
      rowNotes.push(
        `When: the old job charges at ${oldDueAt} (00:00 UTC on the renewal date${lead ? ` less ${lead} lead hour(s)` : ""} — ${localDateInZone(oldDueAt, tz)} in ${tz}); the plan charges at ${chargeTime} ${tz} on ${start} (${newDueAt}).`,
      );
    }

    const matches =
      !stopped &&
      oldBreakdown.totalCents === newBreakdown.totalCents &&
      oldBreakdown.rentalCents === newBreakdown.rentalCents &&
      oldBreakdown.taxCents === newBreakdown.taxCents &&
      oldBreakdown.serviceFeeCents === newBreakdown.serviceFeeCents &&
      oldBreakdown.extrasCents === 0 &&
      oldBreakdown.insuranceCents === newBreakdown.insuranceCents &&
      oldBreakdown.creditAppliedCents === newBreakdown.creditAppliedCents;
    if (!matches && !stopped) {
      rowNotes.push(`Mismatch: the old job would charge ${money(oldBreakdown.totalCents)}, the plan ${money(newBreakdown.totalCents)}.`);
    }

    rows.push({
      period: `${start} → ${end}`,
      oldEngine: { dueAt: oldDueAt, chargeDate: stopped ? null : grid, amountCents: oldBreakdown.totalCents, breakdown: oldBreakdown },
      newEngine: { dueAt: newDueAt, amountCents: newBreakdown.totalCents, breakdown: newBreakdown },
      matches,
      notes: rowNotes,
    });
    start = end;
  }
  return { rows, notes };
}
