/**
 * Payment plans — the §10.1 scenarios (docs/PAYMENT_PLANS_DESIGN.md), as data
 * and scripts, each with named assertions whose EXPECTED values are the design
 * table's literals (hand-derived, not produced by the engine).
 *
 * One scenario list, three runners:
 *   - vitest, against the memory store     (tests/payment-plans/scenarios/)
 *   - vitest, against real Postgres (PGlite, the pp_* SQL functions and the
 *     live FIFO trigger)                    (same test file)
 *   - the browser, in the /dev simulator    (the UI agent's component)
 * "However you test it, I can test it the same way." The memory store is only
 * trusted because the first two agree.
 *
 * Runtime-agnostic, like every file in this directory: relative sibling
 * imports only; no Deno.*, process.*, window.*.
 *
 * Canonical copy: supabase/functions/_shared/payment-plans/. The portal copy is
 * generated by scripts/sync-payment-plans.mjs — edit here, then sync.
 */

import type {
  AmountSpec,
  AttemptRow,
  CollectionMethod,
  LedgerFixture,
  OccurrenceRow,
  PlanEvent,
  PlanLookups,
  PlanOperations,
  PlanRow,
  PlanStore,
  ScheduleRule,
} from "./types.ts";
import { MemoryPlanStore } from "./memory-store.ts";
import { RecordingNotifier, SimulatedLinkMinter, SimulatedProvider, type ChargeRequest } from "./providers.ts";
import { onLinkPaid, recordManualPayment, runTick, type EngineDeps, type TickResult } from "./engine.ts";
import { buildSchedule } from "./schedule.ts";

// ─────────────────────────────────────────────────────────────────────────────
// The pinned API
// ─────────────────────────────────────────────────────────────────────────────

export interface Assertion {
  label: string;
  expected: unknown;
  actual: unknown;
  pass: boolean;
}

export interface ScenarioRun {
  id: string;
  title: string;
  assertions: Assertion[];
  pass: boolean;
  /** ticks, events, attempts, keys, payments, provider calls — see ScenarioEvidence. */
  evidence: unknown;
}

export interface ScenarioRental {
  rentalId: string;
  tenantId: string;
  customerId: string;
}

/** A payments row on the rental, as the scenarios read it (both stores). */
export interface ScenarioPayment {
  id: string;
  occurrenceId: string | null;
  amountCents: number;
  refundCents: number;
  method: string;
  providerRef: string | null;
}

export type ScenarioStore = PlanStore & PlanOperations & PlanLookups & LedgerFixture;

export interface ScenarioContext {
  store: ScenarioStore;
  provider: SimulatedProvider;
  notifier: RecordingNotifier;
  links: SimulatedLinkMinter;
  /** One engine pass (runTick) at this instant; resolves to its TickResult. */
  tick(asOf: string): Promise<unknown>;
  // ── Additive to the pinned API: what a script needs from a context. The UI
  // never builds a context itself (createMemoryContext does), so these are
  // free to require.
  /** 'memory' | 'pglite' — for evidence. */
  kind: string;
  /** A rental owing `owedCents` (one charge) for the scenario to plan against. */
  seedRental(owedCents: number): Promise<ScenarioRental>;
  /** Move the store's clock (an operator action at an instant, no engine pass). */
  at(asOf: string): Promise<void>;
  /** The rental's payments rows. */
  payments(rentalId: string): Promise<ScenarioPayment[]>;
  /** payment_plan_revisions rows for a plan. */
  revisionCount(planId: string): Promise<number>;
}

export interface Scenario {
  id: string;
  title: string;
  why: string;
  run(ctx: ScenarioContext): Promise<ScenarioRun>;
}

export interface ScenarioEvidence {
  context: string;
  error: string | null;
  ticks: TickResult[];
  notes: Record<string, unknown>;
  plan: PlanRow | null;
  occurrences: OccurrenceRow[];
  attempts: AttemptRow[];
  keys: string[];
  events: (PlanEvent & { id: string; createdAt: string })[];
  payments: ScenarioPayment[];
  providerCalls: { key: string; amountCents: number; occurrenceId: string | null; attemptId: string | null }[];
  charges: { idempotencyKey: string; providerRef: string; amountCents: number; occurrenceId: string; refundedCents: number }[];
  refunds: { providerRef: string; amountCents: number }[];
  notifications: unknown[];
  links: unknown[];
}

// ─────────────────────────────────────────────────────────────────────────────
// Contexts and the runner
// ─────────────────────────────────────────────────────────────────────────────

export function engineDeps(ctx: ScenarioContext): EngineDeps {
  return { store: ctx.store, provider: ctx.provider, notifier: ctx.notifier, links: ctx.links };
}

/** MemoryPlanStore + SimulatedProvider('acct_sim') + recorders. Writes nothing anywhere. */
export function createMemoryContext(): ScenarioContext {
  const store = new MemoryPlanStore({ now: "2026-09-01T00:00:00.000Z" });
  const provider = new SimulatedProvider({ account: "acct_sim", mode: "test", fallback: "succeed" });
  const notifier = new RecordingNotifier();
  const links = new SimulatedLinkMinter();
  let n = 0;
  const ctx: ScenarioContext = {
    kind: "memory",
    store,
    provider,
    notifier,
    links,
    tick: (asOf) => runTick(engineDeps(ctx), { asOf }),
    at: (asOf) => {
      store.setNow(asOf);
      return Promise.resolve();
    },
    seedRental: (owedCents) => {
      n += 1;
      const r = { id: `rental-${n}`, tenantId: "tenant-1", customerId: `customer-${n}`, owedCents };
      store.addRental(r);
      return Promise.resolve({ rentalId: r.id, tenantId: r.tenantId, customerId: r.customerId });
    },
    payments: (rentalId) =>
      Promise.resolve(
        store.listPayments({ rentalId }).map((p) => ({
          id: p.id,
          occurrenceId: p.occurrenceId,
          amountCents: p.amountCents,
          refundCents: p.refundCents,
          method: p.method,
          providerRef: p.providerRef,
        })),
      ),
    revisionCount: (planId) => Promise.resolve(store.snapshot().revisions.filter((r) => r.planId === planId).length),
  };
  return ctx;
}

/** Run one scenario on a fresh context (memory unless another factory is given). */
export async function runScenario(s: Scenario, makeCtx?: () => ScenarioContext | Promise<ScenarioContext>): Promise<ScenarioRun> {
  const ctx = await (makeCtx ?? createMemoryContext)();
  return s.run(ctx);
}

// ─────────────────────────────────────────────────────────────────────────────
// Script helpers
// ─────────────────────────────────────────────────────────────────────────────

function deepEqual(a: unknown, b: unknown): boolean {
  if (Object.is(a, b)) return true;
  if (typeof a !== "object" || typeof b !== "object" || a === null || b === null) return false;
  if (Array.isArray(a) !== Array.isArray(b)) return false;
  if (Array.isArray(a)) {
    const bb = b as unknown[];
    return a.length === bb.length && a.every((x, i) => deepEqual(x, bb[i]));
  }
  const ao = a as Record<string, unknown>;
  const bo = b as Record<string, unknown>;
  const ka = Object.keys(ao).filter((k) => ao[k] !== undefined).sort();
  const kb = Object.keys(bo).filter((k) => bo[k] !== undefined).sort();
  return ka.length === kb.length && ka.every((k, i) => k === kb[i] && deepEqual(ao[k], bo[k]));
}

const jsonSafe = (v: unknown): unknown => (v === undefined ? null : JSON.parse(JSON.stringify(v)));

interface Rec {
  check(label: string, expected: unknown, actual: unknown): void;
  tick(asOf: string): Promise<TickResult>;
  note(key: string, value: unknown): void;
  planId: string | null;
  rentalId: string | null;
}

function define(id: string, title: string, why: string, body: (ctx: ScenarioContext, r: Rec) => Promise<void>): Scenario {
  return {
    id,
    title,
    why,
    async run(ctx: ScenarioContext): Promise<ScenarioRun> {
      const assertions: Assertion[] = [];
      const ticks: TickResult[] = [];
      const notes: Record<string, unknown> = {};
      const r: Rec = {
        planId: null,
        rentalId: null,
        check(label, expected, actual) {
          assertions.push({ label, expected: jsonSafe(expected), actual: jsonSafe(actual), pass: deepEqual(jsonSafe(expected), jsonSafe(actual)) });
        },
        async tick(asOf) {
          const t = (await ctx.tick(asOf)) as TickResult;
          ticks.push(t);
          return t;
        },
        note(key, value) {
          notes[key] = jsonSafe(value);
        },
      };
      let error: string | null = null;
      try {
        await body(ctx, r);
      } catch (e) {
        error = e instanceof Error ? `${e.name}: ${e.message}` : String(e);
        assertions.push({ label: "the script ran to the end without throwing", expected: null, actual: error, pass: false });
      }
      const tickErrors = ticks.flatMap((t) => t.errors.map((e) => ({ asOf: t.asOf, ...e })));
      assertions.push({ label: "no engine tick reported an error", expected: [], actual: jsonSafe(tickErrors), pass: tickErrors.length === 0 });
      const evidence = await collectEvidence(ctx, r, ticks, notes, error);
      return { id, title, assertions, pass: assertions.every((a) => a.pass), evidence };
    },
  };
}

async function collectEvidence(ctx: ScenarioContext, r: Rec, ticks: TickResult[], notes: Record<string, unknown>, error: string | null): Promise<ScenarioEvidence> {
  const ev: ScenarioEvidence = {
    context: ctx.kind,
    error,
    ticks: jsonSafe(ticks) as TickResult[],
    notes,
    plan: null,
    occurrences: [],
    attempts: [],
    keys: [],
    events: [],
    payments: [],
    providerCalls: ctx.provider.calls.map((c: ChargeRequest) => ({
      key: c.idempotencyKey,
      amountCents: c.amountCents,
      occurrenceId: c.metadata?.occurrence_id ?? null,
      attemptId: c.metadata?.attempt_id ?? null,
    })),
    charges: ctx.provider.allCharges(),
    refunds: [...ctx.provider.refunds],
    notifications: jsonSafe(ctx.notifier.sent) as unknown[],
    links: jsonSafe(ctx.links.minted) as unknown[],
  };
  try {
    if (r.planId) {
      ev.plan = await ctx.store.getPlan(r.planId);
      ev.occurrences = await ctx.store.listOccurrences(r.planId);
      ev.attempts = await ctx.store.listAttempts({ planId: r.planId });
      ev.keys = ev.attempts.map((a) => a.idempotencyKey);
      ev.events = await ctx.store.listEvents(r.planId);
    }
    if (r.rentalId) ev.payments = await ctx.payments(r.rentalId);
  } catch (e) {
    ev.error = `${ev.error ?? ""} evidence: ${e instanceof Error ? e.message : String(e)}`.trim();
  }
  return jsonSafe(ev) as ScenarioEvidence;
}

// ─── The base fixture (§10.1) ─────────────────────────────────────────────

const TZ = "America/New_York";
/** Before any scenario time; plans are created "now". */
const SETUP_AT = "2026-09-25T12:00:00.000Z";

export const BASE_RULE: ScheduleRule = {
  freq: "weekly",
  interval: 1,
  byWeekday: [5],
  anchor: "2026-10-02",
  firstOccurrence: "on_anchor",
  end: { kind: "count", count: 3 },
};
export const BASE_AMOUNT: AmountSpec = { mode: "split_total", totalCents: 60000 };
/** 10:00 America/New_York in EDT = 14:00Z. */
export const BASE_DUE_AT = ["2026-10-02T14:00:00.000Z", "2026-10-09T14:00:00.000Z", "2026-10-16T14:00:00.000Z"] as const;

interface Setup {
  planId: string;
  rental: ScenarioRental;
  occ: OccurrenceRow[];
  ids: string[];
}

async function setup(
  ctx: ScenarioContext,
  r: Rec,
  opts: { owedCents?: number; rule?: ScheduleRule; amount?: AmountSpec; method?: CollectionMethod; checkBase?: boolean } = {},
): Promise<Setup> {
  await ctx.at(SETUP_AT);
  const rental = await ctx.seedRental(opts.owedCents ?? 60000);
  const rule = opts.rule ?? BASE_RULE;
  const amount = opts.amount ?? BASE_AMOUNT;
  const plan: Omit<PlanRow, "id" | "version" | "status"> = {
    tenantId: rental.tenantId,
    rentalId: rental.rentalId,
    customerId: rental.customerId,
    rule,
    amount,
    currency: "usd",
    timezone: TZ,
    chargeLocalTime: "10:00",
    collectionMethod: opts.method ?? "auto_charge",
    fallbackToLink: true,
    maxAttempts: 3,
    retryAfterDays: 2,
    reminderOffsets: [-2, 0, 2],
    paymentProvider: "stripe",
    stripePaymentMethodId: "pm_sim_card",
    extendsRental: false,
  };
  const planId = await ctx.store.createPlan({ plan, occurrences: buildSchedule(rule, amount) });
  r.planId = planId;
  r.rentalId = rental.rentalId;
  const occ = await ctx.store.listOccurrences(planId);
  if (opts.checkBase !== false) {
    r.check(
      "base plan: 10-02, 10-09, 10-16 × 20000, due 10:00 New York = 14:00Z",
      [
        ["2026-10-02", BASE_DUE_AT[0], 20000],
        ["2026-10-09", BASE_DUE_AT[1], 20000],
        ["2026-10-16", BASE_DUE_AT[2], 20000],
      ],
      occ.map((o) => [o.dueDate, o.dueAt, o.amountCents]),
    );
  }
  return { planId, rental, occ, ids: occ.map((o) => o.id) };
}

const occOf = async (ctx: ScenarioContext, id: string) => {
  const o = await ctx.store.getOccurrence(id);
  if (!o) throw new Error(`occurrence ${id} vanished`);
  return o;
};
const statusOf = async (ctx: ScenarioContext, id: string) => (await occOf(ctx, id)).status;
const cardCalls = (ctx: ScenarioContext, occId: string) => ctx.provider.calls.filter((c) => c.metadata?.occurrence_id === occId);
const attemptsOf = (ctx: ScenarioContext, occId: string) => ctx.store.listAttempts({ occurrenceId: occId });
const paymentsOf = async (ctx: ScenarioContext, rentalId: string, occId: string) => (await ctx.payments(rentalId)).filter((p) => p.occurrenceId === occId);
const eventsOf = async (ctx: ScenarioContext, planId: string, occId: string | null, kind: string) =>
  (await ctx.store.listEvents(planId)).filter((e) => e.kind === kind && (occId === null || e.occurrenceId === occId));
const planStatus = async (ctx: ScenarioContext, planId: string) => (await ctx.store.getPlan(planId))?.status ?? null;
const sorted = (xs: number[]) => [...xs].sort((a, b) => a - b);

// ─────────────────────────────────────────────────────────────────────────────
// S1–S18
// ─────────────────────────────────────────────────────────────────────────────

const S1 = define("S1", "Happy path", "The card works every time: three charges, one key each, the plan completes and the rental owes nothing.", async (ctx, r) => {
  const { planId, rental, ids } = await setup(ctx, r);
  for (const t of BASE_DUE_AT) await r.tick(t);
  const atts = await ctx.store.listAttempts({ planId });
  r.check("3 attempts", 3, atts.length);
  r.check("all attempts succeeded", ["succeeded", "succeeded", "succeeded"], atts.map((a) => a.status));
  r.check("keys pp:acct_sim:{occ}:1", ids.map((id) => `pp:acct_sim:${id}:1`), ids.map((id) => atts.find((a) => a.occurrenceId === id)?.idempotencyKey ?? null));
  r.check("3 payments × 20000", [20000, 20000, 20000], sorted((await ctx.payments(rental.rentalId)).map((p) => p.amountCents)));
  r.check("all occurrences paid", ["paid", "paid", "paid"], (await ctx.store.listOccurrences(planId)).map((o) => o.status));
  r.check("plan completed", "completed", await planStatus(ctx, planId));
  r.check("owed 0", 0, await ctx.store.rentalOwedCents(rental.rentalId));
});

const S2 = define("S2", "Retry after insufficient funds", "A soft decline is retried at 10:00 local two days later — on the same occurrence, with a new key, and paid once.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  ctx.provider.queue(ids[0], [{ decline: "insufficient_funds" }, "succeed"]);
  await r.tick(BASE_DUE_AT[0]);
  const o1 = await occOf(ctx, ids[0]);
  r.check("10-02T14:00Z: occ1 failed", "failed", o1.status);
  r.check("next_attempt_at 10-04T14:00Z", "2026-10-04T14:00:00.000Z", o1.nextAttemptAt);
  const before = cardCalls(ctx, ids[0]).length;
  await r.tick("2026-10-03T14:00:00.000Z");
  r.check("tick 10-03 → no provider call", 0, cardCalls(ctx, ids[0]).length - before);
  await r.tick("2026-10-04T14:00:00.000Z");
  const a2 = (await attemptsOf(ctx, ids[0])).find((a) => a.attemptNo === 2);
  r.check("attempt 2 key …:2", `pp:acct_sim:${ids[0]}:2`, a2?.idempotencyKey ?? null);
  r.check("attempt 2 succeeded", "succeeded", a2?.status ?? null);
  r.check("occ1 has exactly 1 payment of 20000", [20000], (await paymentsOf(ctx, rental.rentalId, ids[0])).map((p) => p.amountCents));
});

const S3 = define("S3", "SCA → link", "authentication_required needs the customer: the card is not retried, a link goes out, and paying it settles the occurrence.", async (ctx, r) => {
  const { planId, rental, ids } = await setup(ctx, r);
  ctx.provider.queue(ids[0], [{ decline: "authentication_required" }]);
  await r.tick(BASE_DUE_AT[0]);
  r.check("occ1 requires_action", "requires_action", await statusOf(ctx, ids[0]));
  const a2 = (await attemptsOf(ctx, ids[0])).find((a) => a.attemptNo === 2);
  r.check("attempt 2 is a checkout_link, in_flight", ["checkout_link", "in_flight"], [a2?.method ?? null, a2?.status ?? null]);
  const kinds = (await ctx.store.listEvents(planId)).filter((e) => e.occurrenceId === ids[0]).map((e) => e.kind);
  r.check("event fallback_to_link recorded", true, kinds.includes("fallback_to_link"));
  r.check("event link_sent recorded", true, kinds.includes("link_sent"));
  if (a2) {
    await onLinkPaid(engineDeps(ctx), { attemptId: a2.id, providerRef: "pi_link_s3", amountCents: 20000, paidAt: "2026-10-03T16:00:00.000Z", checkoutSessionId: "cs_s3" });
  }
  r.check("link paid → occ1 paid", "paid", await statusOf(ctx, ids[0]));
  r.check("occ1: 1 payment", 1, (await paymentsOf(ctx, rental.rentalId, ids[0])).length);
  await r.tick(BASE_DUE_AT[1]);
  await r.tick(BASE_DUE_AT[2]);
  r.check("0 further card calls for occ1 (only the one that asked for SCA)", 1, cardCalls(ctx, ids[0]).length);
});

const S4 = define("S4", "Dead card", "expired_card is never retried: the occurrence fails with no retry time, a link goes out, and the operator's cash record settles it.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  ctx.provider.queue(ids[0], [{ decline: "expired_card" }]);
  await r.tick(BASE_DUE_AT[0]);
  const o1 = await occOf(ctx, ids[0]);
  r.check("occ1 failed", "failed", o1.status);
  r.check("next_attempt_at null", null, o1.nextAttemptAt);
  const link = (await attemptsOf(ctx, ids[0])).find((a) => a.method === "checkout_link");
  r.check("link sent: a checkout_link attempt in flight", "in_flight", link?.status ?? null);
  r.check("link sent: a link email to the customer", true, ctx.notifier.sent.some((n) => n.kind === "link" && n.to === "customer" && n.occurrenceId === ids[0]));
  await recordManualPayment(engineDeps(ctx), { occurrenceId: ids[0], amountCents: 20000, method: "Cash", paymentDate: "2026-10-03", asOf: "2026-10-03T15:00:00.000Z" });
  r.check("operator records 20000 Cash → occ1 paid", "paid", await statusOf(ctx, ids[0]));
  r.check("occ1 payments: one 20000 Cash", [[20000, "Cash"]], (await paymentsOf(ctx, rental.rentalId, ids[0])).map((p) => [p.amountCents, p.method]));
  await r.tick(BASE_DUE_AT[1]);
  r.check("the dead card is never charged again", 1, cardCalls(ctx, ids[0]).length);
});

const S5 = define("S5", "5xx after the charge", "The provider took the money and answered 5xx. Recovery replays the SAME key, finds the charge, and records it once — never a second charge.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  ctx.provider.queue(ids[0], ["indeterminate_after_charge"]);
  await r.tick(BASE_DUE_AT[0]);
  r.check("occ1 processing", "processing", await statusOf(ctx, ids[0]));
  await r.tick("2026-10-02T14:15:00.000Z");
  r.check("recovery replays key …:1 (every call for occ1 used it)", [`pp:acct_sim:${ids[0]}:1`, `pp:acct_sim:${ids[0]}:1`], cardCalls(ctx, ids[0]).map((c) => c.idempotencyKey));
  r.check("occ1 paid", "paid", await statusOf(ctx, ids[0]));
  await r.tick(BASE_DUE_AT[1]);
  await r.tick(BASE_DUE_AT[2]);
  const charges = ctx.provider.chargesFor(ids[0]);
  r.check("provider holds 1 charge for occ1", 1, charges.length);
  const pays = await paymentsOf(ctx, rental.rentalId, ids[0]);
  r.check("1 payment row for occ1", 1, pays.length);
  r.check("the payment carries the same provider ref", charges[0]?.providerRef ?? "(no charge)", pays[0]?.providerRef ?? null);
});

const S6 = define("S6", "409 in use", "A 409 means another request holds the key: leave the attempt in flight, and let recovery finish it with the same key.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  ctx.provider.queue(ids[0], ["in_use"]);
  await r.tick(BASE_DUE_AT[0]);
  const a1 = (await attemptsOf(ctx, ids[0])).find((a) => a.attemptNo === 1);
  r.check("attempt stays in_flight", "in_flight", a1?.status ?? null);
  await r.tick("2026-10-02T14:15:00.000Z");
  const a1b = (await attemptsOf(ctx, ids[0])).find((a) => a.attemptNo === 1);
  r.check("next tick recovery → succeeded", "succeeded", a1b?.status ?? null);
  r.check("1 payment", 1, (await paymentsOf(ctx, rental.rentalId, ids[0])).length);
  r.check("1 charge at the provider", 1, ctx.provider.chargesFor(ids[0]).length);
});

const S7 = define("S7", "Double webhook", "Stripe delivers checkout.session.completed twice: one payment row.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r, { method: "checkout_link" });
  await r.tick(BASE_DUE_AT[0]);
  const link = (await attemptsOf(ctx, ids[0])).find((a) => a.method === "checkout_link");
  r.check("a link went out", "in_flight", link?.status ?? null);
  const input = { attemptId: link?.id ?? "(none)", providerRef: "pi_link_s7", amountCents: 20000, paidAt: "2026-10-02T18:00:00.000Z", checkoutSessionId: "cs_s7" };
  const first = await onLinkPaid(engineDeps(ctx), input);
  const second = await onLinkPaid(engineDeps(ctx), input);
  r.note("webhookResults", [first, second]);
  r.check("second delivery is recognised", "already_recorded", second.status);
  r.check("1 payment row", 1, (await paymentsOf(ctx, rental.rentalId, ids[0])).length);
  r.check("occ1 paid", "paid", await statusOf(ctx, ids[0]));
  r.check("no card was charged", 0, ctx.provider.calls.length);
});

const S8 = define("S8", "Manual collection", "A manual plan never charges: at the due time the operator is told, and their record settles it.", async (ctx, r) => {
  const { planId, rental, ids } = await setup(ctx, r, { method: "manual" });
  await r.tick(BASE_DUE_AT[0]);
  r.check("10-02T14:00Z: occ1 due", "due", await statusOf(ctx, ids[0]));
  r.check("one occurrence_due event", 1, (await eventsOf(ctx, planId, ids[0], "occurrence_due")).length);
  r.check("0 provider calls", 0, ctx.provider.calls.length);
  await recordManualPayment(engineDeps(ctx), { occurrenceId: ids[0], amountCents: 20000, method: "Bank Transfer", paymentDate: "2026-10-02", asOf: "2026-10-02T18:00:00.000Z" });
  r.check("operator records 20000 → paid", "paid", await statusOf(ctx, ids[0]));
  r.check("payments: 20000", [20000], (await paymentsOf(ctx, rental.rentalId, ids[0])).map((p) => p.amountCents));
});

const S9 = define("S9", "Early payment outside the plan", "D5: the customer pays the rest off directly; the plan never charges what is no longer owed.", async (ctx, r) => {
  const { planId, rental, ids } = await setup(ctx, r);
  await r.tick(BASE_DUE_AT[0]);
  r.check("occ1 paid", "paid", await statusOf(ctx, ids[0]));
  await ctx.at("2026-10-05T15:00:00.000Z");
  await ctx.store.recordExternalPayment(rental.rentalId, 40000, "2026-10-05");
  await r.tick(BASE_DUE_AT[1]);
  await r.tick(BASE_DUE_AT[2]);
  r.check("occ2 and occ3 skipped", ["skipped", "skipped"], [await statusOf(ctx, ids[1]), await statusOf(ctx, ids[2])]);
  r.check("one covered_by_balance event each", [1, 1], [(await eventsOf(ctx, planId, ids[1], "covered_by_balance")).length, (await eventsOf(ctx, planId, ids[2], "covered_by_balance")).length]);
  r.check("0 provider calls for them", [0, 0], [cardCalls(ctx, ids[1]).length, cardCalls(ctx, ids[2]).length]);
  r.check("plan completed", "completed", await planStatus(ctx, planId));
  r.check("owed 0", 0, await ctx.store.rentalOwedCents(rental.rentalId));
});

const S10 = define("S10", "Partial pre-payment", "5000 recorded by hand the day before: the card is charged only the 15000 still owed on the due date.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  await recordManualPayment(engineDeps(ctx), { occurrenceId: ids[0], amountCents: 5000, method: "Cash", paymentDate: "2026-10-01", asOf: "2026-10-01T15:00:00.000Z" });
  const o1 = await occOf(ctx, ids[0]);
  r.check("occ1 partially_paid (5000)", ["partially_paid", 5000], [o1.status, o1.amountPaidCents]);
  await r.tick(BASE_DUE_AT[0]);
  r.check("10-02 charge amount 15000", [15000], cardCalls(ctx, ids[0]).map((c) => c.amountCents));
  r.check("occ1 paid", "paid", await statusOf(ctx, ids[0]));
  r.check("occ1 payments 5000 + 15000", [5000, 15000], sorted((await paymentsOf(ctx, rental.rentalId, ids[0])).map((p) => p.amountCents)));
});

const S11 = define("S11", "Skip", "The operator skips occ2: nothing is taken on 10-09 and its 20000 rolls into occ3.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  await r.tick(BASE_DUE_AT[0]);
  await ctx.at("2026-10-05T15:00:00.000Z");
  await ctx.store.skipOccurrence(ids[1]);
  r.check("occ2 skipped", "skipped", await statusOf(ctx, ids[1]));
  r.check("occ3 amount 40000", 40000, (await occOf(ctx, ids[2])).amountCents);
  await r.tick(BASE_DUE_AT[1]);
  r.check("nothing charged for occ2", 0, cardCalls(ctx, ids[1]).length);
  await r.tick(BASE_DUE_AT[2]);
  r.check("charged 40000 on 10-16", [40000], cardCalls(ctx, ids[2]).map((c) => c.amountCents));
  r.check("total collected 60000", 60000, (await ctx.payments(rental.rentalId)).reduce((s, p) => s + p.amountCents - p.refundCents, 0));
});

const S12 = define("S12", "Move", "The operator moves occ2 from Fri 10-09 to Mon 10-12: it is charged at 10:00 New York on the new date, not before.", async (ctx, r) => {
  const { ids } = await setup(ctx, r);
  await r.tick(BASE_DUE_AT[0]);
  await ctx.at("2026-10-05T15:00:00.000Z");
  await ctx.store.moveOccurrence(ids[1], "2026-10-12");
  await r.tick(BASE_DUE_AT[1]);
  r.check("no charge for occ2 at 10-09T14:00Z", 0, cardCalls(ctx, ids[1]).length);
  r.check("occ2 due_at 10-12T14:00Z", "2026-10-12T14:00:00.000Z", (await occOf(ctx, ids[1])).dueAt);
  await r.tick("2026-10-12T13:59:00.000Z");
  r.check("not a minute early", 0, cardCalls(ctx, ids[1]).length);
  await r.tick("2026-10-12T14:00:00.000Z");
  r.check("charged at 10-12T14:00Z", 1, cardCalls(ctx, ids[1]).length);
  r.check("occ2 paid", "paid", await statusOf(ctx, ids[1]));
});

const S13 = define("S13", "Plan change", "After occ1 is paid the plan becomes every 2 weeks from 10-16: the open occurrences are superseded, new ones appended, both charged.", async (ctx, r) => {
  const { planId, ids } = await setup(ctx, r);
  await r.tick(BASE_DUE_AT[0]);
  r.check("occ1 paid", "paid", await statusOf(ctx, ids[0]));
  await ctx.at("2026-10-05T15:00:00.000Z");
  const rule2: ScheduleRule = { freq: "weekly", interval: 2, byWeekday: [5], anchor: "2026-10-16", firstOccurrence: "on_anchor", end: { kind: "count", count: 2 } };
  const amount2: AmountSpec = { mode: "split_total", totalCents: 40000 };
  const version = await ctx.store.replaceFuture({ planId, expectedVersion: 1, planPatch: { rule: rule2, amount: amount2 }, occurrences: buildSchedule(rule2, amount2), reason: "Every 2 weeks from 10-16" });
  r.check("version 2", 2, version);
  const all = await ctx.store.listOccurrences(planId);
  r.check("occ2, occ3 superseded", ["superseded", "superseded"], [all.find((o) => o.id === ids[1])?.status, all.find((o) => o.id === ids[2])?.status]);
  const fresh = all.filter((o) => !ids.includes(o.id));
  r.check("new seq 4 (10-16) and 5 (10-30) × 20000", [[4, "2026-10-16", 20000, 2], [5, "2026-10-30", 20000, 2]], fresh.map((o) => [o.seq, o.dueDate, o.amountCents, o.planVersion]));
  r.check("one revision row", 1, await ctx.revisionCount(planId));
  r.check("plan version 2", 2, (await ctx.store.getPlan(planId))?.version ?? null);
  await r.tick(BASE_DUE_AT[1]);
  await r.tick(BASE_DUE_AT[2]);
  await r.tick("2026-10-30T14:00:00.000Z");
  r.check("both charged", ["paid", "paid"], await Promise.all(fresh.map((o) => statusOf(ctx, o.id))));
  r.check("the superseded occurrences were never charged", [0, 0], [cardCalls(ctx, ids[1]).length, cardCalls(ctx, ids[2]).length]);
});

const S14 = define("S14", "Refund (D12)", "occ1 is paid, then refunded in full: it re-opens, but no tick ever charges it again — only an operator can.", async (ctx, r) => {
  const { rental, ids } = await setup(ctx, r);
  await r.tick(BASE_DUE_AT[0]);
  const pay = (await paymentsOf(ctx, rental.rentalId, ids[0]))[0];
  r.check("occ1 paid with one payment", ["paid", 20000], [await statusOf(ctx, ids[0]), pay?.amountCents ?? null]);
  await ctx.at("2026-10-03T15:00:00.000Z");
  if (pay) await ctx.store.refundPayment(pay.id, 20000);
  const o1 = await occOf(ctx, ids[0]);
  r.check("occ1 back to due, attempt_no 1", ["due", 1], [o1.status, o1.attemptNo]);
  for (const t of ["2026-10-04T14:00:00.000Z", BASE_DUE_AT[1], BASE_DUE_AT[2], "2026-10-23T14:00:00.000Z"]) await r.tick(t);
  r.check("no provider call on any later tick for occ1", 1, cardCalls(ctx, ids[0]).length);
  r.check("occ1 still due", "due", await statusOf(ctx, ids[0]));
});

const S15 = define("S15", "Month-end across DST", "Monthly on the 31st from 2027-01-31: Feb clamps to the 28th, March returns to the 31st, and 10:00 New York is 15:00Z in winter, 14:00Z after 03-14.", async (ctx, r) => {
  const rule: ScheduleRule = { freq: "monthly", interval: 1, byMonthDay: 31, anchor: "2027-01-31", firstOccurrence: "on_anchor", end: { kind: "count", count: 3 } };
  const { ids, occ } = await setup(ctx, r, { owedCents: 90000, rule, amount: { mode: "split_total", totalCents: 90000 }, checkBase: false });
  const expectedAt = ["2027-01-31T15:00:00.000Z", "2027-02-28T15:00:00.000Z", "2027-03-31T14:00:00.000Z"];
  r.check("due at 01-31 15:00Z, 02-28 15:00Z, 03-31 14:00Z", expectedAt, occ.map((o) => o.dueAt));
  const early: number[] = [];
  const onTime: number[][] = [];
  for (let i = 0; i < 3; i++) {
    const minuteBefore = new Date(Date.parse(expectedAt[i]) - 60_000).toISOString();
    await r.tick(minuteBefore);
    early.push(cardCalls(ctx, ids[i]).length);
    await r.tick(expectedAt[i]);
    onTime.push(cardCalls(ctx, ids[i]).map((c) => c.amountCents));
  }
  r.check("nothing charged a minute before each instant", [0, 0, 0], early);
  r.check("charged at each instant × 30000", [[30000], [30000], [30000]], onTime);
});

const S16 = define("S16", "Pause", "Paused 10-05, resumed 10-12: nothing is taken while paused; occ2 is charged at the first tick after resume.", async (ctx, r) => {
  const { planId, ids } = await setup(ctx, r);
  await r.tick(BASE_DUE_AT[0]);
  await ctx.at("2026-10-05T15:00:00.000Z");
  await ctx.store.pausePlan(planId, null, "customer away");
  await r.tick(BASE_DUE_AT[1]);
  r.check("no charge at 10-09", 0, cardCalls(ctx, ids[1]).length);
  await ctx.at("2026-10-12T15:00:00.000Z");
  await ctx.store.resumePlan(planId);
  await r.tick("2026-10-12T15:00:00.000Z");
  r.check("occ2 charged at the first tick after resume", 1, cardCalls(ctx, ids[1]).length);
  r.check("occ2 paid", "paid", await statusOf(ctx, ids[1]));
});

const S17 = define("S17", "Reminders, once each", "Two ticks a day from 09-30 to 10-06: each reminder for occ1 (−2, 0, +2) is sent exactly once.", async (ctx, r) => {
  const { planId, ids } = await setup(ctx, r, { method: "manual" });
  for (const day of ["2026-09-30", "2026-10-01", "2026-10-02", "2026-10-03", "2026-10-04", "2026-10-05", "2026-10-06"]) {
    await r.tick(`${day}T14:00:00.000Z`);
    await r.tick(`${day}T20:00:00.000Z`);
  }
  const rem = (await eventsOf(ctx, planId, null, "reminder")).map((e) => [e.occurrenceId, e.dedupeKey, e.createdAt]);
  r.check(
    "reminder events: occ1 on 09-30 (−2), 10-02 (0), 10-04 (+2) — once each",
    [
      [ids[0], `reminder:${ids[0]}:-2`, "2026-09-30T14:00:00.000Z"],
      [ids[0], `reminder:${ids[0]}:0`, "2026-10-02T14:00:00.000Z"],
      [ids[0], `reminder:${ids[0]}:2`, "2026-10-04T14:00:00.000Z"],
    ],
    rem,
  );
  r.check("3 reminder emails for occ1", 3, ctx.notifier.sent.filter((n) => n.kind === "reminder" && n.occurrenceId === ids[0]).length);
});

const S18 = define("S18", "Retries exhausted", "insufficient_funds every time: attempts on 10-02, 10-04 and 10-06 at 10:00 local, then no more card retries and a link instead.", async (ctx, r) => {
  const { planId, ids } = await setup(ctx, r);
  ctx.provider.queue(ids[0], [{ decline: "insufficient_funds" }, { decline: "insufficient_funds" }, { decline: "insufficient_funds" }, { decline: "insufficient_funds" }]);
  const counts: number[] = [];
  const nexts: (string | null)[] = [];
  for (const t of ["2026-10-02T14:00:00.000Z", "2026-10-04T14:00:00.000Z", "2026-10-06T14:00:00.000Z"]) {
    await r.tick(t);
    counts.push(cardCalls(ctx, ids[0]).length);
    nexts.push((await occOf(ctx, ids[0])).nextAttemptAt);
  }
  r.check("attempts 1, 2, 3 at 10-02, 10-04, 10-06 14:00Z", [1, 2, 3], counts);
  r.check("keys …:1, …:2, …:3", [1, 2, 3].map((n) => `pp:acct_sim:${ids[0]}:${n}`), cardCalls(ctx, ids[0]).map((c) => c.idempotencyKey));
  r.check("retry times 10-04, 10-06, then none", ["2026-10-04T14:00:00.000Z", "2026-10-06T14:00:00.000Z", null], nexts);
  const o1 = await occOf(ctx, ids[0]);
  r.check("then occ1 failed, next_attempt_at null", ["failed", null], [o1.status, o1.nextAttemptAt]);
  const link = (await attemptsOf(ctx, ids[0])).find((a) => a.method === "checkout_link");
  r.check("fallback link sent (attempt 4, in flight)", [4, "in_flight"], [link?.attemptNo ?? null, link?.status ?? null]);
  r.check("fallback_to_link event", 1, (await eventsOf(ctx, planId, ids[0], "fallback_to_link")).length);
  await r.tick("2026-10-08T14:00:00.000Z");
  r.check("no 4th card attempt", 3, cardCalls(ctx, ids[0]).length);
});

export const SCENARIOS: Scenario[] = [S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, S11, S12, S13, S14, S15, S16, S17, S18];
